#ifndef __ARCH_ARM_MACH_OMAP2_PRCM44XX_H
#define __ARCH_ARM_MACH_OMAP2_PRCM44XX_H
#define OMAP4430_INVALID_PRCM_PARTITION		0
#define OMAP4430_PRM_PARTITION			1
#define OMAP4430_CM1_PARTITION			2
#define OMAP4430_CM2_PARTITION			3
#define OMAP4430_SCRM_PARTITION			4
#define OMAP4430_PRCM_MPU_PARTITION		5
#define OMAP54XX_PRM_PARTITION			1
#define OMAP54XX_CM_CORE_AON_PARTITION		2
#define OMAP54XX_CM_CORE_PARTITION		3
#define OMAP54XX_SCRM_PARTITION			4
#define OMAP54XX_PRCM_MPU_PARTITION		5
#define DRA7XX_PRM_PARTITION                   1
#define DRA7XX_CM_CORE_AON_PARTITION           2
#define DRA7XX_CM_CORE_PARTITION               3
#define DRA7XX_MPU_PRCM_PARTITION              5
#define OMAP4_MAX_PRCM_PARTITIONS		6
#endif
