#ifndef	_SYS_SYSEVENT_EVENTDEFS_H
#define	_SYS_SYSEVENT_EVENTDEFS_H
#ifdef	__cplusplus
extern "C" {
#endif
#define	EC_NONE		"EC_none"
#define	EC_PRIV		"EC_priv"
#define	EC_PLATFORM	"EC_platform"	 
#define	EC_DR		"EC_dr"	 
#define	EC_ENV		"EC_env"	 
#define	EC_DOMAIN	"EC_domain"	 
#define	EC_AP_DRIVER	"EC_ap_driver"	 
#define	EC_IPMP		"EC_ipmp"	 
#define	EC_DEV_ADD	"EC_dev_add"	 
#define	EC_DEV_REMOVE	"EC_dev_remove"	 
#define	EC_DEV_BRANCH	"EC_dev_branch"	 
#define	EC_DEV_STATUS	"EC_dev_status"	 
#define	EC_FM		"EC_fm"		 
#define	EC_ZFS		"EC_zfs"	 
#define	EC_DATALINK	"EC_datalink"	 
#define	EC_VRRP		"EC_vrrp"	 
#define	ESC_DISK	"disk"		 
#define	ESC_NETWORK	"network"	 
#define	ESC_PRINTER	"printer"	 
#define	ESC_LOFI	"lofi"		 
#define	ESC_DEV_BRANCH_ADD	"dev_branch_add"
#define	ESC_DEV_BRANCH_REMOVE	"dev_branch_remove"
#define	ESC_DEV_DLE		"dev_dle"
#define	ESC_DEV_EJECT_REQUEST	"dev_eject_request"
#define	ESC_FM_ERROR		"error"
#define	ESC_FM_ERROR_REPLAY	"error_replay"
#define	ESC_ZFS_RESILVER_START		"resilver_start"
#define	ESC_ZFS_RESILVER_FINISH		"resilver_finish"
#define	ESC_ZFS_VDEV_REMOVE		"vdev_remove"
#define	ESC_ZFS_VDEV_REMOVE_AUX		"vdev_remove_aux"
#define	ESC_ZFS_VDEV_REMOVE_DEV		"vdev_remove_dev"
#define	ESC_ZFS_POOL_CREATE		"pool_create"
#define	ESC_ZFS_POOL_DESTROY		"pool_destroy"
#define	ESC_ZFS_POOL_IMPORT		"pool_import"
#define	ESC_ZFS_POOL_EXPORT		"pool_export"
#define	ESC_ZFS_VDEV_ADD		"vdev_add"
#define	ESC_ZFS_VDEV_ATTACH		"vdev_attach"
#define	ESC_ZFS_VDEV_CLEAR		"vdev_clear"
#define	ESC_ZFS_VDEV_CHECK		"vdev_check"
#define	ESC_ZFS_VDEV_ONLINE		"vdev_online"
#define	ESC_ZFS_CONFIG_SYNC		"config_sync"
#define	ESC_ZFS_SCRUB_START		"scrub_start"
#define	ESC_ZFS_SCRUB_FINISH		"scrub_finish"
#define	ESC_ZFS_SCRUB_ABORT		"scrub_abort"
#define	ESC_ZFS_SCRUB_RESUME		"scrub_resume"
#define	ESC_ZFS_SCRUB_PAUSED		"scrub_paused"
#define	ESC_ZFS_VDEV_SPARE		"vdev_spare"
#define	ESC_ZFS_VDEV_AUTOEXPAND		"vdev_autoexpand"
#define	ESC_ZFS_BOOTFS_VDEV_ATTACH	"bootfs_vdev_attach"
#define	ESC_ZFS_POOL_REGUID		"pool_reguid"
#define	ESC_ZFS_HISTORY_EVENT		"history_event"
#define	ESC_ZFS_TRIM_START		"trim_start"
#define	ESC_ZFS_TRIM_FINISH		"trim_finish"
#define	ESC_ZFS_TRIM_CANCEL		"trim_cancel"
#define	ESC_ZFS_TRIM_RESUME		"trim_resume"
#define	ESC_ZFS_TRIM_SUSPEND		"trim_suspend"
#define	ESC_ZFS_ERRORSCRUB_START	"errorscrub_start"
#define	ESC_ZFS_ERRORSCRUB_FINISH	"errorscrub_finish"
#define	ESC_ZFS_ERRORSCRUB_ABORT	"errorscrub_abort"
#define	ESC_ZFS_ERRORSCRUB_RESUME	"errorscrub_resume"
#define	ESC_ZFS_ERRORSCRUB_PAUSED	"errorscrub_paused"
#define	ESC_DATALINK_PHYS_ADD	"datalink_phys_add"	 
#ifdef	__cplusplus
}
#endif
#endif  
