{
  "module_name": "Makefile",
  "hash_id": "3eb1c73bee6518e155f2343a902ac0c7b3d927bc461356ea383d35a835bba777",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/zydas/zd1211rw/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_ZD1211RW) += zd1211rw.o\n\nzd1211rw-objs := zd_chip.o zd_mac.o \\\n\t\tzd_rf_al2230.o zd_rf_rf2959.o \\\n\t\tzd_rf_al7230b.o zd_rf_uw2453.o \\\n\t\tzd_rf.o zd_usb.o\n\nccflags-$(CONFIG_ZD1211RW_DEBUG) := -DDEBUG\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}