{
  "module_name": "Kbuild",
  "hash_id": "416a87a09f4737b571cf2b7c4614fa416e411a7c15486183abb6b6bf13f5a39d",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/nouveau/nvkm/subdev/fault/Kbuild",
  "human_readable_source": "# SPDX-License-Identifier: MIT\nnvkm-y += nvkm/subdev/fault/base.o\nnvkm-y += nvkm/subdev/fault/user.o\nnvkm-y += nvkm/subdev/fault/gp100.o\nnvkm-y += nvkm/subdev/fault/gp10b.o\nnvkm-y += nvkm/subdev/fault/gv100.o\nnvkm-y += nvkm/subdev/fault/tu102.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}