{
  "module_name": "Makefile",
  "hash_id": "ccdf08bd6e11f6cbb13ee53eb26ca84f785a7a5255820e0bc8f23b4dd75f04a1",
  "original_prompt": "Ingested from linux-6.6.14/kernel/debug/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the linux kernel debugger\n#\n\nobj-$(CONFIG_KGDB) += debug_core.o gdbstub.o\nobj-$(CONFIG_KGDB_KDB) += kdb/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}