{
  "module_name": "Makefile",
  "hash_id": "eaa3517bef017e86bd960572a9d87397b40ebfcee5a8d1b5e56a5a3f032facde",
  "original_prompt": "Ingested from linux-6.6.14/drivers/peci/controller/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n\nobj-$(CONFIG_PECI_ASPEED)\t+= peci-aspeed.o\nobj-$(CONFIG_PECI_NPCM)\t\t+= peci-npcm.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}