


#ifndef	__STMMAC_PTP_H__
#define	__STMMAC_PTP_H__

#define PTP_XGMAC_OFFSET	0xd00
#define	PTP_GMAC4_OFFSET	0xb00
#define	PTP_GMAC3_X_OFFSET	0x700


#define	PTP_TCR		0x00	
#define	PTP_SSIR	0x04	
#define	PTP_STSR	0x08	
#define	PTP_STNSR	0x0c	
#define	PTP_STSUR	0x10	
#define	PTP_STNSUR	0x14	
#define	PTP_TAR		0x18	
#define	PTP_ACR		0x40	
#define	PTP_ATNR	0x48	
#define	PTP_ATSR	0x4c	
#define	PTP_TS_INGR_CORR_NS	0x58	
#define	PTP_TS_EGR_CORR_NS	0x5C	
#define	PTP_TS_INGR_CORR_SNS	0x60	
#define	PTP_TS_EGR_CORR_SNS	0x64	
#define	PTP_TS_INGR_LAT	0x68	
#define	PTP_TS_EGR_LAT	0x6c	

#define	PTP_STNSUR_ADDSUB_SHIFT	31
#define	PTP_DIGITAL_ROLLOVER_MODE	0x3B9ACA00	
#define	PTP_BINARY_ROLLOVER_MODE	0x80000000	


#define	PTP_TCR_TSENA		BIT(0)	
#define	PTP_TCR_TSCFUPDT	BIT(1)	
#define	PTP_TCR_TSINIT		BIT(2)	
#define	PTP_TCR_TSUPDT		BIT(3)	
#define	PTP_TCR_TSTRIG		BIT(4)	
#define	PTP_TCR_TSADDREG	BIT(5)	
#define	PTP_TCR_TSENALL		BIT(8)	
#define	PTP_TCR_TSCTRLSSR	BIT(9)	

#define	PTP_TCR_TSVER2ENA	BIT(10)

#define	PTP_TCR_TSIPENA		BIT(11)

#define	PTP_TCR_TSIPV6ENA	BIT(12)

#define	PTP_TCR_TSIPV4ENA	BIT(13)

#define	PTP_TCR_TSEVNTENA	BIT(14)

#define	PTP_TCR_TSMSTRENA	BIT(15)

#define	PTP_TCR_SNAPTYPSEL_1	BIT(16)

#define	PTP_TCR_TSENMACADDR	BIT(18)


#define	PTP_SSIR_SSINC_MAX		0xff
#define	GMAC4_PTP_SSIR_SSINC_SHIFT	16


#define	PTP_ACR_ATSFC		BIT(0)	
#define	PTP_ACR_ATSEN0		BIT(4)	
#define	PTP_ACR_ATSEN1		BIT(5)	
#define	PTP_ACR_ATSEN2		BIT(6)	
#define	PTP_ACR_ATSEN3		BIT(7)	
#define	PTP_ACR_ATSEN_SHIFT	5	
#define	PTP_ACR_MASK		GENMASK(7, 4)	
#define	PMC_ART_VALUE0		0x01	
#define	PMC_ART_VALUE1		0x02	
#define	PMC_ART_VALUE2		0x03	
#define	PMC_ART_VALUE3		0x04	
#define	GMAC4_ART_TIME_SHIFT	16	

enum aux_snapshot {
	AUX_SNAPSHOT0 = 0x10,
	AUX_SNAPSHOT1 = 0x20,
	AUX_SNAPSHOT2 = 0x40,
	AUX_SNAPSHOT3 = 0x80,
};

#endif	
