{
  "module_name": "Makefile",
  "hash_id": "040cda8cd7538f36589a7903b52d8e390d8c763dc64adc1d9f80b1a283b0166b",
  "original_prompt": "Ingested from linux-6.6.14/drivers/staging/iio/addac/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for industrial I/O ADDAC drivers\n#\n\nobj-$(CONFIG_ADT7316) += adt7316.o\nobj-$(CONFIG_ADT7316_SPI) += adt7316-spi.o\nobj-$(CONFIG_ADT7316_I2C) += adt7316-i2c.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}