#ifndef __HDLCD_REGS_H__
#define __HDLCD_REGS_H__
#define HDLCD_REG_VERSION		0x0000	 
#define HDLCD_REG_INT_RAWSTAT		0x0010	 
#define HDLCD_REG_INT_CLEAR		0x0014	 
#define HDLCD_REG_INT_MASK		0x0018	 
#define HDLCD_REG_INT_STATUS		0x001c	 
#define HDLCD_REG_FB_BASE		0x0100	 
#define HDLCD_REG_FB_LINE_LENGTH	0x0104	 
#define HDLCD_REG_FB_LINE_COUNT		0x0108	 
#define HDLCD_REG_FB_LINE_PITCH		0x010c	 
#define HDLCD_REG_BUS_OPTIONS		0x0110	 
#define HDLCD_REG_V_SYNC		0x0200	 
#define HDLCD_REG_V_BACK_PORCH		0x0204	 
#define HDLCD_REG_V_DATA		0x0208	 
#define HDLCD_REG_V_FRONT_PORCH		0x020c	 
#define HDLCD_REG_H_SYNC		0x0210	 
#define HDLCD_REG_H_BACK_PORCH		0x0214	 
#define HDLCD_REG_H_DATA		0x0218	 
#define HDLCD_REG_H_FRONT_PORCH		0x021c	 
#define HDLCD_REG_POLARITIES		0x0220	 
#define HDLCD_REG_COMMAND		0x0230	 
#define HDLCD_REG_PIXEL_FORMAT		0x0240	 
#define HDLCD_REG_RED_SELECT		0x0244	 
#define HDLCD_REG_GREEN_SELECT		0x0248	 
#define HDLCD_REG_BLUE_SELECT		0x024c	 
#define HDLCD_PRODUCT_ID		0x1CDC0000
#define HDLCD_PRODUCT_MASK		0xFFFF0000
#define HDLCD_VERSION_MAJOR_MASK	0x0000FF00
#define HDLCD_VERSION_MINOR_MASK	0x000000FF
#define HDLCD_INTERRUPT_DMA_END		(1 << 0)
#define HDLCD_INTERRUPT_BUS_ERROR	(1 << 1)
#define HDLCD_INTERRUPT_VSYNC		(1 << 2)
#define HDLCD_INTERRUPT_UNDERRUN	(1 << 3)
#define HDLCD_DEBUG_INT_MASK		(HDLCD_INTERRUPT_DMA_END |  \
					HDLCD_INTERRUPT_BUS_ERROR | \
					HDLCD_INTERRUPT_UNDERRUN)
#define HDLCD_POLARITY_VSYNC		(1 << 0)
#define HDLCD_POLARITY_HSYNC		(1 << 1)
#define HDLCD_POLARITY_DATAEN		(1 << 2)
#define HDLCD_POLARITY_DATA		(1 << 3)
#define HDLCD_POLARITY_PIXELCLK		(1 << 4)
#define HDLCD_COMMAND_DISABLE		(0 << 0)
#define HDLCD_COMMAND_ENABLE		(1 << 0)
#define HDLCD_PIXEL_FMT_LITTLE_ENDIAN	(0 << 31)
#define HDLCD_PIXEL_FMT_BIG_ENDIAN	(1 << 31)
#define HDLCD_BYTES_PER_PIXEL_MASK	(3 << 3)
#define HDLCD_BUS_BURST_MASK		0x01f
#define HDLCD_BUS_MAX_OUTSTAND		0xf00
#define HDLCD_BUS_BURST_NONE		(0 << 0)
#define HDLCD_BUS_BURST_1		(1 << 0)
#define HDLCD_BUS_BURST_2		(1 << 1)
#define HDLCD_BUS_BURST_4		(1 << 2)
#define HDLCD_BUS_BURST_8		(1 << 3)
#define HDLCD_BUS_BURST_16		(1 << 4)
#define HDLCD_MAX_XRES			4096
#define HDLCD_MAX_YRES			4096
#define NR_PALETTE			256
#endif  
