{
  "module_name": "Makefile",
  "hash_id": "9a3815f8466840a966afd6d4090f04831a6ed168b72092dc23ed8ae831313341",
  "original_prompt": "Ingested from linux-6.6.14/drivers/infiniband/ulp/srpt/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_INFINIBAND_SRPT)\t+= ib_srpt.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}