{
  "module_name": "Makefile",
  "hash_id": "f9485beaafd0fd20ba2c52b359ebd8ec3e60b0a482cb102308d632d446f28928",
  "original_prompt": "Ingested from linux-6.6.14/fs/ext2/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the linux ext2-filesystem routines.\n#\n\nobj-$(CONFIG_EXT2_FS) += ext2.o\n\next2-y := balloc.o dir.o file.o ialloc.o inode.o \\\n\t  ioctl.o namei.o super.o symlink.o trace.o\n\n# For tracepoints to include our trace.h from tracepoint infrastructure\nCFLAGS_trace.o := -I$(src)\n\next2-$(CONFIG_EXT2_FS_XATTR)\t += xattr.o xattr_user.o xattr_trusted.o\next2-$(CONFIG_EXT2_FS_POSIX_ACL) += acl.o\next2-$(CONFIG_EXT2_FS_SECURITY)\t += xattr_security.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}