{
  "module_name": "Makefile",
  "hash_id": "de4adbcee85dadc9611ec522626851d111d92ecb7b12faa2de7e09acd76b18a1",
  "original_prompt": "Ingested from linux-6.6.14/net/802/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the Linux 802.x protocol layers.\n#\n\n# Check the p8022 selections against net/core/Makefile.\nobj-$(CONFIG_LLC)\t+= p8022.o psnap.o\nobj-$(CONFIG_NET_FC)\t+=                 fc.o\nobj-$(CONFIG_FDDI)\t+=                 fddi.o\nobj-$(CONFIG_HIPPI)\t+=                 hippi.o\nobj-$(CONFIG_ATALK)\t+= p8022.o psnap.o\nobj-$(CONFIG_STP)\t+= stp.o\nobj-$(CONFIG_GARP)\t+= garp.o\nobj-$(CONFIG_MRP)\t+= mrp.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}