




#ifndef HW_ATL_LLH_INTERNAL_H
#define HW_ATL_LLH_INTERNAL_H


#define HW_ATL_TS_RESET_ADR 0x00003100
#define HW_ATL_TS_RESET_MSK 0x00000004
#define HW_ATL_TS_RESET_SHIFT 2
#define HW_ATL_TS_RESET_WIDTH 1


#define HW_ATL_TS_POWER_DOWN_ADR 0x00003100
#define HW_ATL_TS_POWER_DOWN_MSK 0x00000001
#define HW_ATL_TS_POWER_DOWN_SHIFT 0
#define HW_ATL_TS_POWER_DOWN_WIDTH 1


#define HW_ATL_TS_READY_ADR 0x00003120
#define HW_ATL_TS_READY_MSK 0x80000000
#define HW_ATL_TS_READY_SHIFT 31
#define HW_ATL_TS_READY_WIDTH 1


#define HW_ATL_TS_READY_LATCH_HIGH_ADR 0x00003120
#define HW_ATL_TS_READY_LATCH_HIGH_MSK 0x40000000
#define HW_ATL_TS_READY_LATCH_HIGH_SHIFT 30
#define HW_ATL_TS_READY_LATCH_HIGH_WIDTH 1


#define HW_ATL_TS_DATA_OUT_ADR 0x00003120
#define HW_ATL_TS_DATA_OUT_MSK 0x00000FFF
#define HW_ATL_TS_DATA_OUT_SHIFT 0
#define HW_ATL_TS_DATA_OUT_WIDTH 12


#define HW_ATL_GLB_CPU_SEM_ADR(semaphore)  (0x000003a0u + (semaphore) * 0x4)

#define HW_ATL_STATS_RX_DMA_GOOD_OCTET_COUNTERLSW 0x00006808

#define HW_ATL_STATS_RX_DMA_GOOD_PKT_COUNTERLSW 0x00006800

#define HW_ATL_STATS_TX_DMA_GOOD_OCTET_COUNTERLSW 0x00008808

#define HW_ATL_STATS_TX_DMA_GOOD_PKT_COUNTERLSW 0x00008800


#define HW_ATL_STATS_RX_DMA_GOOD_OCTET_COUNTERMSW 0x0000680c

#define HW_ATL_STATS_RX_DMA_GOOD_PKT_COUNTERMSW 0x00006804

#define HW_ATL_STATS_TX_DMA_GOOD_OCTET_COUNTERMSW 0x0000880c

#define HW_ATL_STATS_TX_DMA_GOOD_PKT_COUNTERMSW 0x00008804


#define HW_ATL_MAC_MSM_RX_ERRS_CNT_ADR 0x00000120u


#define HW_ATL_MAC_MSM_RX_UCST_FRM_CNT_ADR 0x000000e0u


#define HW_ATL_MAC_MSM_RX_MCST_FRM_CNT_ADR 0x000000e8u


#define HW_ATL_MAC_MSM_RX_BCST_FRM_CNT_ADR 0x000000f0u


#define HW_ATL_MAC_MSM_RX_BCST_OCTETS_COUNTER1_ADR 0x000001b0u


#define HW_ATL_MAC_MSM_RX_BCST_OCTETS_COUNTER2_ADR 0x000001b4u


#define HW_ATL_MAC_MSM_RX_UCST_OCTETS_COUNTER0_ADR 0x000001b8u


#define HW_ATL_MAC_MSM_TX_UCST_FRM_CNT_ADR 0x00000108u


#define HW_ATL_MAC_MSM_TX_MCST_FRM_CNT_ADR 0x00000110u


#define HW_ATL_GLB_MIF_ID_ADR 0x0000001cu


#define HW_ATL_ITR_IAMRLSW_ADR 0x00002090

#define HW_ATL_RPB_RX_DMA_DROP_PKT_CNT_ADR 0x00006818


#define HW_ATL_ITR_IMCRLSW_ADR 0x00002070

#define HW_ATL_ITR_IMSRLSW_ADR 0x00002060

#define HW_ATL_ITR_REG_RES_DSBL_ADR 0x00002300

#define HW_ATL_ITR_REG_RES_DSBL_MSK 0x20000000

#define HW_ATL_ITR_REG_RES_DSBL_SHIFT 29

#define HW_ATL_ITR_ISCRLSW_ADR 0x00002050

#define HW_ATL_ITR_ISRLSW_ADR 0x00002000

#define HW_ATL_ITR_RES_ADR 0x00002300

#define HW_ATL_ITR_RES_MSK 0x80000000

#define HW_ATL_ITR_RES_SHIFT 31


#define HW_ATL_ITR_RSC_EN_ADR 0x00002200


#define HW_ATL_ITR_RSC_DELAY_ADR 0x00002204

#define HW_ATL_ITR_RSC_DELAY_MSK 0x0000000f

#define HW_ATL_ITR_RSC_DELAY_WIDTH 4

#define HW_ATL_ITR_RSC_DELAY_SHIFT 0


#define HW_ATL_RDM_DCADCPUID_ADR(dca) (0x00006100 + (dca) * 0x4)

#define HW_ATL_RDM_DCADCPUID_MSK 0x000000ff

#define HW_ATL_RDM_DCADCPUID_SHIFT 0

#define HW_ATL_RDM_DCA_EN_ADR 0x00006180




#define HW_ATL_RDM_DCA_EN_ADR 0x00006180

#define HW_ATL_RDM_DCA_EN_MSK 0x80000000

#define HW_ATL_RDM_DCA_EN_MSKN 0x7fffffff

#define HW_ATL_RDM_DCA_EN_SHIFT 31

#define HW_ATL_RDM_DCA_EN_WIDTH 1

#define HW_ATL_RDM_DCA_EN_DEFAULT 0x1




#define HW_ATL_RDM_DCA_MODE_ADR 0x00006180

#define HW_ATL_RDM_DCA_MODE_MSK 0x0000000f

#define HW_ATL_RDM_DCA_MODE_MSKN 0xfffffff0

#define HW_ATL_RDM_DCA_MODE_SHIFT 0

#define HW_ATL_RDM_DCA_MODE_WIDTH 4

#define HW_ATL_RDM_DCA_MODE_DEFAULT 0x0




#define HW_ATL_RDM_DESCDDATA_SIZE_ADR(descriptor) \
	(0x00005b18 + (descriptor) * 0x20)

#define HW_ATL_RDM_DESCDDATA_SIZE_MSK 0x0000001f

#define HW_ATL_RDM_DESCDDATA_SIZE_MSKN 0xffffffe0

#define HW_ATL_RDM_DESCDDATA_SIZE_SHIFT 0

#define HW_ATL_RDM_DESCDDATA_SIZE_WIDTH 5

#define HW_ATL_RDM_DESCDDATA_SIZE_DEFAULT 0x0




#define HW_ATL_RDM_DCADDESC_EN_ADR(dca) (0x00006100 + (dca) * 0x4)

#define HW_ATL_RDM_DCADDESC_EN_MSK 0x80000000

#define HW_ATL_RDM_DCADDESC_EN_MSKN 0x7fffffff

#define HW_ATL_RDM_DCADDESC_EN_SHIFT 31

#define HW_ATL_RDM_DCADDESC_EN_WIDTH 1

#define HW_ATL_RDM_DCADDESC_EN_DEFAULT 0x0




#define HW_ATL_RDM_DESCDEN_ADR(descriptor) (0x00005b08 + (descriptor) * 0x20)

#define HW_ATL_RDM_DESCDEN_MSK 0x80000000

#define HW_ATL_RDM_DESCDEN_MSKN 0x7fffffff

#define HW_ATL_RDM_DESCDEN_SHIFT 31

#define HW_ATL_RDM_DESCDEN_WIDTH 1

#define HW_ATL_RDM_DESCDEN_DEFAULT 0x0




#define HW_ATL_RDM_DESCDHDR_SIZE_ADR(descriptor) \
	(0x00005b18 + (descriptor) * 0x20)

#define HW_ATL_RDM_DESCDHDR_SIZE_MSK 0x00001f00

#define HW_ATL_RDM_DESCDHDR_SIZE_MSKN 0xffffe0ff

#define HW_ATL_RDM_DESCDHDR_SIZE_SHIFT 8

#define HW_ATL_RDM_DESCDHDR_SIZE_WIDTH 5

#define HW_ATL_RDM_DESCDHDR_SIZE_DEFAULT 0x0




#define HW_ATL_RDM_DESCDHDR_SPLIT_ADR(descriptor) \
	(0x00005b08 + (descriptor) * 0x20)

#define HW_ATL_RDM_DESCDHDR_SPLIT_MSK 0x10000000

#define HW_ATL_RDM_DESCDHDR_SPLIT_MSKN 0xefffffff

#define HW_ATL_RDM_DESCDHDR_SPLIT_SHIFT 28

#define HW_ATL_RDM_DESCDHDR_SPLIT_WIDTH 1

#define HW_ATL_RDM_DESCDHDR_SPLIT_DEFAULT 0x0




#define HW_ATL_RDM_DESCDHD_ADR(descriptor) (0x00005b0c + (descriptor) * 0x20)

#define HW_ATL_RDM_DESCDHD_MSK 0x00001fff

#define HW_ATL_RDM_DESCDHD_MSKN 0xffffe000

#define HW_ATL_RDM_DESCDHD_SHIFT 0

#define HW_ATL_RDM_DESCDHD_WIDTH 13




#define HW_ATL_RDM_DESCDLEN_ADR(descriptor) (0x00005b08 + (descriptor) * 0x20)

#define HW_ATL_RDM_DESCDLEN_MSK 0x00001ff8

#define HW_ATL_RDM_DESCDLEN_MSKN 0xffffe007

#define HW_ATL_RDM_DESCDLEN_SHIFT 3

#define HW_ATL_RDM_DESCDLEN_WIDTH 10

#define HW_ATL_RDM_DESCDLEN_DEFAULT 0x0




#define HW_ATL_RDM_DESCDRESET_ADR(descriptor) (0x00005b08 + (descriptor) * 0x20)

#define HW_ATL_RDM_DESCDRESET_MSK 0x02000000

#define HW_ATL_RDM_DESCDRESET_MSKN 0xfdffffff

#define HW_ATL_RDM_DESCDRESET_SHIFT 25

#define HW_ATL_RDM_DESCDRESET_WIDTH 1

#define HW_ATL_RDM_DESCDRESET_DEFAULT 0x0




#define HW_ATL_RDM_RX_DMA_DESC_CACHE_INIT_ADR 0x00005a00

#define HW_ATL_RDM_RX_DMA_DESC_CACHE_INIT_MSK 0xffffffff

#define HW_ATL_RDM_RX_DMA_DESC_CACHE_INIT_MSKN 0x00000000

#define HW_ATL_RDM_RX_DMA_DESC_CACHE_INIT_SHIFT 0

#define HW_ATL_RDM_RX_DMA_DESC_CACHE_INIT_WIDTH 32

#define HW_ATL_RDM_RX_DMA_DESC_CACHE_INIT_DEFAULT 0x0




#define RDM_RX_DMA_DESC_CACHE_INIT_DONE_ADR 0x00005a10

#define RDM_RX_DMA_DESC_CACHE_INIT_DONE_MSK 0x00000001U

#define RDM_RX_DMA_DESC_CACHE_INIT_DONE_MSKN 0xfffffffe

#define RDM_RX_DMA_DESC_CACHE_INIT_DONE_SHIFT 0U

#define RDM_RX_DMA_DESC_CACHE_INIT_DONE_WIDTH 1

#define RDM_RX_DMA_DESC_CACHE_INIT_DONE_DEFAULT 0x0





#define HW_ATL_RDM_INT_DESC_WRB_EN_ADR 0x00005a30

#define HW_ATL_RDM_INT_DESC_WRB_EN_MSK 0x00000004

#define HW_ATL_RDM_INT_DESC_WRB_EN_MSKN 0xfffffffb

#define HW_ATL_RDM_INT_DESC_WRB_EN_SHIFT 2

#define HW_ATL_RDM_INT_DESC_WRB_EN_WIDTH 1

#define HW_ATL_RDM_INT_DESC_WRB_EN_DEFAULT 0x0




#define HW_ATL_RDM_DCADHDR_EN_ADR(dca) (0x00006100 + (dca) * 0x4)

#define HW_ATL_RDM_DCADHDR_EN_MSK 0x40000000

#define HW_ATL_RDM_DCADHDR_EN_MSKN 0xbfffffff

#define HW_ATL_RDM_DCADHDR_EN_SHIFT 30

#define HW_ATL_RDM_DCADHDR_EN_WIDTH 1

#define HW_ATL_RDM_DCADHDR_EN_DEFAULT 0x0




#define HW_ATL_RDM_DCADPAY_EN_ADR(dca) (0x00006100 + (dca) * 0x4)

#define HW_ATL_RDM_DCADPAY_EN_MSK 0x20000000

#define HW_ATL_RDM_DCADPAY_EN_MSKN 0xdfffffff

#define HW_ATL_RDM_DCADPAY_EN_SHIFT 29

#define HW_ATL_RDM_DCADPAY_EN_WIDTH 1

#define HW_ATL_RDM_DCADPAY_EN_DEFAULT 0x0




#define HW_ATL_RDM_INT_RIM_EN_ADR 0x00005A30

#define HW_ATL_RDM_INT_RIM_EN_MSK 0x00000008

#define HW_ATL_RDM_INT_RIM_EN_MSKN 0xFFFFFFF7

#define HW_ATL_RDM_INT_RIM_EN_SHIFT 3

#define HW_ATL_RDM_INT_RIM_EN_WIDTH 1

#define HW_ATL_RDM_INT_RIM_EN_DEFAULT 0x0


#define HW_ATL_GEN_INTR_MAP_ADR(regidx) (0x00002180u + (regidx) * 0x4)



#define HW_ATL_GEN_INTR_STAT_ADR 0x000021A4U


#define HW_ATL_INTR_GLB_CTL_ADR 0x00002300u


#define HW_ATL_INTR_THR_ADR(throttle) (0x00002800u + (throttle) * 0x4)


#define HW_ATL_RX_DMA_DESC_BASE_ADDRLSW_ADR(descriptor) \
(0x00005b00u + (descriptor) * 0x20)


#define HW_ATL_RX_DMA_DESC_BASE_ADDRMSW_ADR(descriptor) \
(0x00005b04u + (descriptor) * 0x20)


#define HW_ATL_RX_DMA_DESC_STAT_ADR(descriptor) \
	(0x00005b14u + (descriptor) * 0x20)


#define HW_ATL_RX_DMA_DESC_TAIL_PTR_ADR(descriptor) \
	(0x00005b10u + (descriptor) * 0x20)


#define HW_ATL_RX_INTR_MODERATION_CTL_ADR(rim) (0x00005A40u + (rim) * 0x4)


#define HW_ATL_RX_FLR_MCST_FLR_MSK_ADR 0x00005270u


#define HW_ATL_RX_FLR_MCST_FLR_ADR(filter) (0x00005250u + (filter) * 0x4)


#define HW_ATL_RX_FLR_RSS_CONTROL1_ADR 0x000054C0u


#define HW_ATL_RX_FLR_CONTROL2_ADR 0x00005104u




#define HW_ATL_TDM_TX_DMA_DEBUG_CTL_ADR 0x00008920

#define HW_ATL_TDM_TX_DMA_DEBUG_CTL_MSK 0xffffffff

#define HW_ATL_TDM_TX_DMA_DEBUG_CTL_MSKN 0x00000000

#define HW_ATL_TDM_TX_DMA_DEBUG_CTL_SHIFT 0

#define HW_ATL_TDM_TX_DMA_DEBUG_CTL_WIDTH 32

#define HW_ATL_TDM_TX_DMA_DEBUG_CTL_DEFAULT 0x0


#define HW_ATL_TX_DMA_DESC_BASE_ADDRLSW_ADR(descriptor) \
	(0x00007c00u + (descriptor) * 0x40)


#define HW_ATL_TX_DMA_DESC_TAIL_PTR_ADR(descriptor) \
	(0x00007c10u + (descriptor) * 0x40)




#define HW_ATL_RPB_DMA_SYS_LBK_ADR 0x00005000

#define HW_ATL_RPB_DMA_SYS_LBK_MSK 0x00000040

#define HW_ATL_RPB_DMA_SYS_LBK_MSKN 0xffffffbf

#define HW_ATL_RPB_DMA_SYS_LBK_SHIFT 6

#define HW_ATL_RPB_DMA_SYS_LBK_WIDTH 1

#define HW_ATL_RPB_DMA_SYS_LBK_DEFAULT 0x0




#define HW_ATL_RPB_DMA_NET_LBK_ADR 0x00005000

#define HW_ATL_RPB_DMA_NET_LBK_MSK 0x00000010

#define HW_ATL_RPB_DMA_NET_LBK_MSKN 0xffffffef

#define HW_ATL_RPB_DMA_NET_LBK_SHIFT 4

#define HW_ATL_RPB_DMA_NET_LBK_WIDTH 1

#define HW_ATL_RPB_DMA_NET_LBK_DEFAULT 0x0




#define HW_ATL_RPB_RPF_RX_TC_MODE_ADR 0x00005700

#define HW_ATL_RPB_RPF_RX_TC_MODE_MSK 0x00000100

#define HW_ATL_RPB_RPF_RX_TC_MODE_MSKN 0xfffffeff

#define HW_ATL_RPB_RPF_RX_TC_MODE_SHIFT 8

#define HW_ATL_RPB_RPF_RX_TC_MODE_WIDTH 1

#define HW_ATL_RPB_RPF_RX_TC_MODE_DEFAULT 0x0




#define HW_ATL_RPB_RX_BUF_EN_ADR 0x00005700

#define HW_ATL_RPB_RX_BUF_EN_MSK 0x00000001

#define HW_ATL_RPB_RX_BUF_EN_MSKN 0xfffffffe

#define HW_ATL_RPB_RX_BUF_EN_SHIFT 0

#define HW_ATL_RPB_RX_BUF_EN_WIDTH 1

#define HW_ATL_RPB_RX_BUF_EN_DEFAULT 0x0




#define HW_ATL_RPB_RXBHI_THRESH_ADR(buffer) (0x00005714 + (buffer) * 0x10)

#define HW_ATL_RPB_RXBHI_THRESH_MSK 0x3fff0000

#define HW_ATL_RPB_RXBHI_THRESH_MSKN 0xc000ffff

#define HW_ATL_RPB_RXBHI_THRESH_SHIFT 16

#define HW_ATL_RPB_RXBHI_THRESH_WIDTH 14

#define HW_ATL_RPB_RXBHI_THRESH_DEFAULT 0x0




#define HW_ATL_RPB_RXBLO_THRESH_ADR(buffer) (0x00005714 + (buffer) * 0x10)

#define HW_ATL_RPB_RXBLO_THRESH_MSK 0x00003fff

#define HW_ATL_RPB_RXBLO_THRESH_MSKN 0xffffc000

#define HW_ATL_RPB_RXBLO_THRESH_SHIFT 0

#define HW_ATL_RPB_RXBLO_THRESH_WIDTH 14

#define HW_ATL_RPB_RXBLO_THRESH_DEFAULT 0x0




#define HW_ATL_RPB_RX_FC_MODE_ADR 0x00005700

#define HW_ATL_RPB_RX_FC_MODE_MSK 0x00000030

#define HW_ATL_RPB_RX_FC_MODE_MSKN 0xffffffcf

#define HW_ATL_RPB_RX_FC_MODE_SHIFT 4

#define HW_ATL_RPB_RX_FC_MODE_WIDTH 2

#define HW_ATL_RPB_RX_FC_MODE_DEFAULT 0x0




#define HW_ATL_RPB_RXBBUF_SIZE_ADR(buffer) (0x00005710 + (buffer) * 0x10)

#define HW_ATL_RPB_RXBBUF_SIZE_MSK 0x000001ff

#define HW_ATL_RPB_RXBBUF_SIZE_MSKN 0xfffffe00

#define HW_ATL_RPB_RXBBUF_SIZE_SHIFT 0

#define HW_ATL_RPB_RXBBUF_SIZE_WIDTH 9

#define HW_ATL_RPB_RXBBUF_SIZE_DEFAULT 0x0




#define HW_ATL_RPB_RXBXOFF_EN_ADR(buffer) (0x00005714 + (buffer) * 0x10)

#define HW_ATL_RPB_RXBXOFF_EN_MSK 0x80000000

#define HW_ATL_RPB_RXBXOFF_EN_MSKN 0x7fffffff

#define HW_ATL_RPB_RXBXOFF_EN_SHIFT 31

#define HW_ATL_RPB_RXBXOFF_EN_WIDTH 1

#define HW_ATL_RPB_RXBXOFF_EN_DEFAULT 0x0




#define HW_ATL_RPFL2BC_THRESH_ADR 0x00005100

#define HW_ATL_RPFL2BC_THRESH_MSK 0xffff0000

#define HW_ATL_RPFL2BC_THRESH_MSKN 0x0000ffff

#define HW_ATL_RPFL2BC_THRESH_SHIFT 16

#define HW_ATL_RPFL2BC_THRESH_WIDTH 16

#define HW_ATL_RPFL2BC_THRESH_DEFAULT 0x0




#define HW_ATL_RPFL2BC_EN_ADR 0x00005100

#define HW_ATL_RPFL2BC_EN_MSK 0x00000001

#define HW_ATL_RPFL2BC_EN_MSKN 0xfffffffe

#define HW_ATL_RPFL2BC_EN_SHIFT 0

#define HW_ATL_RPFL2BC_EN_WIDTH 1

#define HW_ATL_RPFL2BC_EN_DEFAULT 0x0




#define HW_ATL_RPFL2BC_ACT_ADR 0x00005100

#define HW_ATL_RPFL2BC_ACT_MSK 0x00007000

#define HW_ATL_RPFL2BC_ACT_MSKN 0xffff8fff

#define HW_ATL_RPFL2BC_ACT_SHIFT 12

#define HW_ATL_RPFL2BC_ACT_WIDTH 3

#define HW_ATL_RPFL2BC_ACT_DEFAULT 0x0




#define HW_ATL_RPFL2MC_ENF_ADR(filter) (0x00005250 + (filter) * 0x4)

#define HW_ATL_RPFL2MC_ENF_MSK 0x80000000

#define HW_ATL_RPFL2MC_ENF_MSKN 0x7fffffff

#define HW_ATL_RPFL2MC_ENF_SHIFT 31

#define HW_ATL_RPFL2MC_ENF_WIDTH 1

#define HW_ATL_RPFL2MC_ENF_DEFAULT 0x0




#define HW_ATL_RPFL2PROMIS_MODE_ADR 0x00005100

#define HW_ATL_RPFL2PROMIS_MODE_MSK 0x00000008

#define HW_ATL_RPFL2PROMIS_MODE_MSKN 0xfffffff7

#define HW_ATL_RPFL2PROMIS_MODE_SHIFT 3

#define HW_ATL_RPFL2PROMIS_MODE_WIDTH 1

#define HW_ATL_RPFL2PROMIS_MODE_DEFAULT 0x0




#define HW_ATL_RPFL2UC_ACTF_ADR(filter) (0x00005114 + (filter) * 0x8)

#define HW_ATL_RPFL2UC_ACTF_MSK 0x00070000

#define HW_ATL_RPFL2UC_ACTF_MSKN 0xfff8ffff

#define HW_ATL_RPFL2UC_ACTF_SHIFT 16

#define HW_ATL_RPFL2UC_ACTF_WIDTH 3

#define HW_ATL_RPFL2UC_ACTF_DEFAULT 0x0




#define HW_ATL_RPFL2UC_ENF_ADR(filter) (0x00005114 + (filter) * 0x8)

#define HW_ATL_RPFL2UC_ENF_MSK 0x80000000

#define HW_ATL_RPFL2UC_ENF_MSKN 0x7fffffff

#define HW_ATL_RPFL2UC_ENF_SHIFT 31

#define HW_ATL_RPFL2UC_ENF_WIDTH 1

#define HW_ATL_RPFL2UC_ENF_DEFAULT 0x0


#define HW_ATL_RPFL2UC_DAFLSW_ADR(filter) (0x00005110 + (filter) * 0x8)

#define HW_ATL_RPFL2UC_DAFMSW_ADR(filter) (0x00005114 + (filter) * 0x8)

#define HW_ATL_RPFL2UC_DAFMSW_MSK 0x0000ffff

#define HW_ATL_RPFL2UC_DAFMSW_SHIFT 0




#define HW_ATL_RPFL2MC_ACCEPT_ALL_ADR 0x00005270

#define HW_ATL_RPFL2MC_ACCEPT_ALL_MSK 0x00004000

#define HW_ATL_RPFL2MC_ACCEPT_ALL_MSKN 0xFFFFBFFF

#define HW_ATL_RPFL2MC_ACCEPT_ALL_SHIFT 14

#define HW_ATL_RPFL2MC_ACCEPT_ALL_WIDTH 1

#define HW_ATL_RPFL2MC_ACCEPT_ALL_DEFAULT 0x0


#define HW_ATL_RPF_RPB_RX_TC_UPT_WIDTH 3

#define HW_ATL_RPF_RPB_RX_TC_UPT_DEFAULT 0x0




#define HW_ATL_RPF_RSS_KEY_ADDR_ADR 0x000054d0

#define HW_ATL_RPF_RSS_KEY_ADDR_MSK 0x0000001f

#define HW_ATL_RPF_RSS_KEY_ADDR_MSKN 0xffffffe0

#define HW_ATL_RPF_RSS_KEY_ADDR_SHIFT 0

#define HW_ATL_RPF_RSS_KEY_ADDR_WIDTH 5

#define HW_ATL_RPF_RSS_KEY_ADDR_DEFAULT 0x0




#define HW_ATL_RPF_RSS_KEY_WR_DATA_ADR 0x000054d4

#define HW_ATL_RPF_RSS_KEY_WR_DATA_MSK 0xffffffff

#define HW_ATL_RPF_RSS_KEY_WR_DATA_MSKN 0x00000000

#define HW_ATL_RPF_RSS_KEY_WR_DATA_SHIFT 0

#define HW_ATL_RPF_RSS_KEY_WR_DATA_WIDTH 32

#define HW_ATL_RPF_RSS_KEY_WR_DATA_DEFAULT 0x0




#define HW_ATL_RPF_RSS_KEY_WR_ENI_ADR 0x000054d0

#define HW_ATL_RPF_RSS_KEY_WR_ENI_MSK 0x00000020

#define HW_ATL_RPF_RSS_KEY_WR_ENI_MSKN 0xffffffdf

#define HW_ATL_RPF_RSS_KEY_WR_ENI_SHIFT 5

#define HW_ATL_RPF_RSS_KEY_WR_ENI_WIDTH 1

#define HW_ATL_RPF_RSS_KEY_WR_ENI_DEFAULT 0x0




#define HW_ATL_RPF_RSS_REDIR_ADDR_ADR 0x000054e0

#define HW_ATL_RPF_RSS_REDIR_ADDR_MSK 0x0000000f

#define HW_ATL_RPF_RSS_REDIR_ADDR_MSKN 0xfffffff0

#define HW_ATL_RPF_RSS_REDIR_ADDR_SHIFT 0

#define HW_ATL_RPF_RSS_REDIR_ADDR_WIDTH 4

#define HW_ATL_RPF_RSS_REDIR_ADDR_DEFAULT 0x0




#define HW_ATL_RPF_RSS_REDIR_WR_DATA_ADR 0x000054e4

#define HW_ATL_RPF_RSS_REDIR_WR_DATA_MSK 0x0000ffff

#define HW_ATL_RPF_RSS_REDIR_WR_DATA_MSKN 0xffff0000

#define HW_ATL_RPF_RSS_REDIR_WR_DATA_SHIFT 0

#define HW_ATL_RPF_RSS_REDIR_WR_DATA_WIDTH 16

#define HW_ATL_RPF_RSS_REDIR_WR_DATA_DEFAULT 0x0




#define HW_ATL_RPF_RSS_REDIR_WR_ENI_ADR 0x000054e0

#define HW_ATL_RPF_RSS_REDIR_WR_ENI_MSK 0x00000010

#define HW_ATL_RPF_RSS_REDIR_WR_ENI_MSKN 0xffffffef

#define HW_ATL_RPF_RSS_REDIR_WR_ENI_SHIFT 4

#define HW_ATL_RPF_RSS_REDIR_WR_ENI_WIDTH 1

#define HW_ATL_RPF_RSS_REDIR_WR_ENI_DEFAULT 0x0




#define HW_ATL_RPF_TPO_RPF_SYS_LBK_ADR 0x00005000

#define HW_ATL_RPF_TPO_RPF_SYS_LBK_MSK 0x00000100

#define HW_ATL_RPF_TPO_RPF_SYS_LBK_MSKN 0xfffffeff

#define HW_ATL_RPF_TPO_RPF_SYS_LBK_SHIFT 8

#define HW_ATL_RPF_TPO_RPF_SYS_LBK_WIDTH 1

#define HW_ATL_RPF_TPO_RPF_SYS_LBK_DEFAULT 0x0




#define HW_ATL_RPF_VL_INNER_TPID_ADR 0x00005284

#define HW_ATL_RPF_VL_INNER_TPID_MSK 0x0000ffff

#define HW_ATL_RPF_VL_INNER_TPID_MSKN 0xffff0000

#define HW_ATL_RPF_VL_INNER_TPID_SHIFT 0

#define HW_ATL_RPF_VL_INNER_TPID_WIDTH 16

#define HW_ATL_RPF_VL_INNER_TPID_DEFAULT 0x8100




#define HW_ATL_RPF_VL_OUTER_TPID_ADR 0x00005284

#define HW_ATL_RPF_VL_OUTER_TPID_MSK 0xffff0000

#define HW_ATL_RPF_VL_OUTER_TPID_MSKN 0x0000ffff

#define HW_ATL_RPF_VL_OUTER_TPID_SHIFT 16

#define HW_ATL_RPF_VL_OUTER_TPID_WIDTH 16

#define HW_ATL_RPF_VL_OUTER_TPID_DEFAULT 0x88a8




#define HW_ATL_RPF_VL_PROMIS_MODE_ADR 0x00005280

#define HW_ATL_RPF_VL_PROMIS_MODE_MSK 0x00000002

#define HW_ATL_RPF_VL_PROMIS_MODE_MSKN 0xfffffffd

#define HW_ATL_RPF_VL_PROMIS_MODE_SHIFT 1

#define HW_ATL_RPF_VL_PROMIS_MODE_WIDTH 1

#define HW_ATL_RPF_VL_PROMIS_MODE_DEFAULT 0x0




#define HW_ATL_RPF_VL_ACCEPT_UNTAGGED_MODE_ADR 0x00005280

#define HW_ATL_RPF_VL_ACCEPT_UNTAGGED_MODE_MSK 0x00000004

#define HW_ATL_RPF_VL_ACCEPT_UNTAGGED_MODE_MSKN 0xFFFFFFFB

#define HW_ATL_RPF_VL_ACCEPT_UNTAGGED_MODE_SHIFT 2

#define HW_ATL_RPF_VL_ACCEPT_UNTAGGED_MODE_WIDTH 1

#define HW_ATL_RPF_VL_ACCEPT_UNTAGGED_MODE_DEFAULT 0x0




#define HW_ATL_RPF_VL_UNTAGGED_ACT_ADR 0x00005280

#define HW_ATL_RPF_VL_UNTAGGED_ACT_MSK 0x00000038

#define HW_ATL_RPF_VL_UNTAGGED_ACT_MSKN 0xFFFFFFC7

#define HW_ATL_RPF_VL_UNTAGGED_ACT_SHIFT 3

#define HW_ATL_RPF_VL_UNTAGGED_ACT_WIDTH 3

#define HW_ATL_RPF_VL_UNTAGGED_ACT_DEFAULT 0x0




#define HW_ATL_RPF_VL_EN_F_ADR(filter) (0x00005290 + (filter) * 0x4)

#define HW_ATL_RPF_VL_EN_F_MSK 0x80000000

#define HW_ATL_RPF_VL_EN_F_MSKN 0x7FFFFFFF

#define HW_ATL_RPF_VL_EN_F_SHIFT 31

#define HW_ATL_RPF_VL_EN_F_WIDTH 1

#define HW_ATL_RPF_VL_EN_F_DEFAULT 0x0




#define HW_ATL_RPF_VL_ACT_F_ADR(filter) (0x00005290 + (filter) * 0x4)

#define HW_ATL_RPF_VL_ACT_F_MSK 0x00070000

#define HW_ATL_RPF_VL_ACT_F_MSKN 0xFFF8FFFF

#define HW_ATL_RPF_VL_ACT_F_SHIFT 16

#define HW_ATL_RPF_VL_ACT_F_WIDTH 3

#define HW_ATL_RPF_VL_ACT_F_DEFAULT 0x0




#define HW_ATL_RPF_VL_ID_F_ADR(filter) (0x00005290 + (filter) * 0x4)

#define HW_ATL_RPF_VL_ID_F_MSK 0x00000FFF

#define HW_ATL_RPF_VL_ID_F_MSKN 0xFFFFF000

#define HW_ATL_RPF_VL_ID_F_SHIFT 0

#define HW_ATL_RPF_VL_ID_F_WIDTH 12

#define HW_ATL_RPF_VL_ID_F_DEFAULT 0x0




#define HW_ATL_RPF_VL_RXQ_EN_F_ADR(filter) (0x00005290 + (filter) * 0x4)

#define HW_ATL_RPF_VL_RXQ_EN_F_MSK 0x10000000

#define HW_ATL_RPF_VL_RXQ_EN_F_MSKN 0xEFFFFFFF

#define HW_ATL_RPF_VL_RXQ_EN_F_SHIFT 28

#define HW_ATL_RPF_VL_RXQ_EN_F_WIDTH 1

#define HW_ATL_RPF_VL_RXQ_EN_F_DEFAULT 0x0




#define HW_ATL_RPF_VL_RXQ_F_ADR(filter) (0x00005290 + (filter) * 0x4)

#define HW_ATL_RPF_VL_RXQ_F_MSK 0x01F00000

#define HW_ATL_RPF_VL_RXQ_F_MSKN 0xFE0FFFFF

#define HW_ATL_RPF_VL_RXQ_F_SHIFT 20

#define HW_ATL_RPF_VL_RXQ_F_WIDTH 5

#define HW_ATL_RPF_VL_RXQ_F_DEFAULT 0x0




#define HW_ATL_RPF_ET_ENF_ADR(filter) (0x00005300 + (filter) * 0x4)

#define HW_ATL_RPF_ET_ENF_MSK 0x80000000

#define HW_ATL_RPF_ET_ENF_MSKN 0x7fffffff

#define HW_ATL_RPF_ET_ENF_SHIFT 31

#define HW_ATL_RPF_ET_ENF_WIDTH 1

#define HW_ATL_RPF_ET_ENF_DEFAULT 0x0




#define HW_ATL_RPF_ET_UPFEN_ADR(filter) (0x00005300 + (filter) * 0x4)

#define HW_ATL_RPF_ET_UPFEN_MSK 0x40000000

#define HW_ATL_RPF_ET_UPFEN_MSKN 0xbfffffff

#define HW_ATL_RPF_ET_UPFEN_SHIFT 30

#define HW_ATL_RPF_ET_UPFEN_WIDTH 1

#define HW_ATL_RPF_ET_UPFEN_DEFAULT 0x0




#define HW_ATL_RPF_ET_RXQFEN_ADR(filter) (0x00005300 + (filter) * 0x4)

#define HW_ATL_RPF_ET_RXQFEN_MSK 0x20000000

#define HW_ATL_RPF_ET_RXQFEN_MSKN 0xdfffffff

#define HW_ATL_RPF_ET_RXQFEN_SHIFT 29

#define HW_ATL_RPF_ET_RXQFEN_WIDTH 1

#define HW_ATL_RPF_ET_RXQFEN_DEFAULT 0x0




#define HW_ATL_RPF_ET_UPF_ADR(filter) (0x00005300 + (filter) * 0x4)

#define HW_ATL_RPF_ET_UPF_MSK 0x1c000000

#define HW_ATL_RPF_ET_UPF_MSKN 0xe3ffffff

#define HW_ATL_RPF_ET_UPF_SHIFT 26

#define HW_ATL_RPF_ET_UPF_WIDTH 3

#define HW_ATL_RPF_ET_UPF_DEFAULT 0x0




#define HW_ATL_RPF_ET_RXQF_ADR(filter) (0x00005300 + (filter) * 0x4)

#define HW_ATL_RPF_ET_RXQF_MSK 0x01f00000

#define HW_ATL_RPF_ET_RXQF_MSKN 0xfe0fffff

#define HW_ATL_RPF_ET_RXQF_SHIFT 20

#define HW_ATL_RPF_ET_RXQF_WIDTH 5

#define HW_ATL_RPF_ET_RXQF_DEFAULT 0x0




#define HW_ATL_RPF_ET_MNG_RXQF_ADR(filter) (0x00005300 + (filter) * 0x4)

#define HW_ATL_RPF_ET_MNG_RXQF_MSK 0x00080000

#define HW_ATL_RPF_ET_MNG_RXQF_MSKN 0xfff7ffff

#define HW_ATL_RPF_ET_MNG_RXQF_SHIFT 19

#define HW_ATL_RPF_ET_MNG_RXQF_WIDTH 1

#define HW_ATL_RPF_ET_MNG_RXQF_DEFAULT 0x0




#define HW_ATL_RPF_ET_ACTF_ADR(filter) (0x00005300 + (filter) * 0x4)

#define HW_ATL_RPF_ET_ACTF_MSK 0x00070000

#define HW_ATL_RPF_ET_ACTF_MSKN 0xfff8ffff

#define HW_ATL_RPF_ET_ACTF_SHIFT 16

#define HW_ATL_RPF_ET_ACTF_WIDTH 3

#define HW_ATL_RPF_ET_ACTF_DEFAULT 0x0




#define HW_ATL_RPF_ET_VALF_ADR(filter) (0x00005300 + (filter) * 0x4)

#define HW_ATL_RPF_ET_VALF_MSK 0x0000ffff

#define HW_ATL_RPF_ET_VALF_MSKN 0xffff0000

#define HW_ATL_RPF_ET_VALF_SHIFT 0

#define HW_ATL_RPF_ET_VALF_WIDTH 16

#define HW_ATL_RPF_ET_VALF_DEFAULT 0x0



#define HW_ATL_RPF_L3_REG_CTRL_ADR(filter) (0x00005380 + (filter) * 0x4)




#define HW_ATL_RPF_L3_SRCA_ADR(filter) (0x000053B0 + (filter) * 0x4)

#define HW_ATL_RPF_L3_SRCA_MSK 0xFFFFFFFFu

#define HW_ATL_RPF_L3_SRCA_MSKN 0xFFFFFFFFu

#define HW_ATL_RPF_L3_SRCA_SHIFT 0

#define HW_ATL_RPF_L3_SRCA_WIDTH 32

#define HW_ATL_RPF_L3_SRCA_DEFAULT 0x0



 
#define HW_ATL_RPF_L3_DSTA_ADR(filter) (0x000053D0 + (filter) * 0x4)

#define HW_ATL_RPF_L3_DSTA_MSK 0xFFFFFFFFu

#define HW_ATL_RPF_L3_DSTA_MSKN 0xFFFFFFFFu

#define HW_ATL_RPF_L3_DSTA_SHIFT 0

#define HW_ATL_RPF_L3_DSTA_WIDTH 32

#define HW_ATL_RPF_L3_DSTA_DEFAULT 0x0




#define HW_ATL_RPF_L4_SPD_ADR(srcport) (0x00005400u + (srcport) * 0x4)

#define HW_ATL_RPF_L4_SPD_MSK 0x0000FFFFu

#define HW_ATL_RPF_L4_SPD_MSKN 0xFFFF0000u

#define HW_ATL_RPF_L4_SPD_SHIFT 0

#define HW_ATL_RPF_L4_SPD_WIDTH 16

#define HW_ATL_RPF_L4_SPD_DEFAULT 0x0




#define HW_ATL_RPF_L4_DPD_ADR(destport) (0x00005420u + (destport) * 0x4)

#define HW_ATL_RPF_L4_DPD_MSK 0x0000FFFFu

#define HW_ATL_RPF_L4_DPD_MSKN 0xFFFF0000u

#define HW_ATL_RPF_L4_DPD_SHIFT 0

#define HW_ATL_RPF_L4_DPD_WIDTH 16

#define HW_ATL_RPF_L4_DPD_DEFAULT 0x0




#define HW_ATL_RPO_IPV4CHK_EN_ADR 0x00005580

#define HW_ATL_RPO_IPV4CHK_EN_MSK 0x00000002

#define HW_ATL_RPO_IPV4CHK_EN_MSKN 0xfffffffd

#define HW_ATL_RPO_IPV4CHK_EN_SHIFT 1

#define HW_ATL_RPO_IPV4CHK_EN_WIDTH 1

#define HW_ATL_RPO_IPV4CHK_EN_DEFAULT 0x0




#define HW_ATL_RPO_DESCDVL_STRIP_ADR(descriptor) \
	(0x00005b08 + (descriptor) * 0x20)

#define HW_ATL_RPO_DESCDVL_STRIP_MSK 0x20000000

#define HW_ATL_RPO_DESCDVL_STRIP_MSKN 0xdfffffff

#define HW_ATL_RPO_DESCDVL_STRIP_SHIFT 29

#define HW_ATL_RPO_DESCDVL_STRIP_WIDTH 1

#define HW_ATL_RPO_DESCDVL_STRIP_DEFAULT 0x0




#define HW_ATL_RPOL4CHK_EN_ADR 0x00005580

#define HW_ATL_RPOL4CHK_EN_MSK 0x00000001

#define HW_ATL_RPOL4CHK_EN_MSKN 0xfffffffe

#define HW_ATL_RPOL4CHK_EN_SHIFT 0

#define HW_ATL_RPOL4CHK_EN_WIDTH 1

#define HW_ATL_RPOL4CHK_EN_DEFAULT 0x0




#define HW_ATL_RPO_OUTER_VL_INS_MODE_ADR 0x00005580

#define HW_ATL_RPO_OUTER_VL_INS_MODE_MSK 0x00000004

#define HW_ATL_RPO_OUTER_VL_INS_MODE_MSKN 0xFFFFFFFB

#define HW_ATL_RPO_OUTER_VL_INS_MODE_SHIFT 2

#define HW_ATL_RPO_OUTER_VL_INS_MODE_WIDTH 1

#define HW_ATL_RPO_OUTER_VL_INS_MODE_DEFAULT 0x0




#define HW_ATL_RX_REG_RES_DSBL_ADR 0x00005000

#define HW_ATL_RX_REG_RES_DSBL_MSK 0x20000000

#define HW_ATL_RX_REG_RES_DSBL_MSKN 0xdfffffff

#define HW_ATL_RX_REG_RES_DSBL_SHIFT 29

#define HW_ATL_RX_REG_RES_DSBL_WIDTH 1

#define HW_ATL_RX_REG_RES_DSBL_DEFAULT 0x1




#define HW_ATL_TDM_DCADCPUID_ADR(dca) (0x00008400 + (dca) * 0x4)

#define HW_ATL_TDM_DCADCPUID_MSK 0x000000ff

#define HW_ATL_TDM_DCADCPUID_MSKN 0xffffff00

#define HW_ATL_TDM_DCADCPUID_SHIFT 0

#define HW_ATL_TDM_DCADCPUID_WIDTH 8

#define HW_ATL_TDM_DCADCPUID_DEFAULT 0x0




#define HW_ATL_TDM_LSO_EN_ADR 0x00007810

#define HW_ATL_TDM_LSO_EN_MSK 0xffffffff

#define HW_ATL_TDM_LSO_EN_MSKN 0x00000000

#define HW_ATL_TDM_LSO_EN_SHIFT 0

#define HW_ATL_TDM_LSO_EN_WIDTH 32

#define HW_ATL_TDM_LSO_EN_DEFAULT 0x0




#define HW_ATL_TDM_DCA_EN_ADR 0x00008480

#define HW_ATL_TDM_DCA_EN_MSK 0x80000000

#define HW_ATL_TDM_DCA_EN_MSKN 0x7fffffff

#define HW_ATL_TDM_DCA_EN_SHIFT 31

#define HW_ATL_TDM_DCA_EN_WIDTH 1

#define HW_ATL_TDM_DCA_EN_DEFAULT 0x1




#define HW_ATL_TDM_DCA_MODE_ADR 0x00008480

#define HW_ATL_TDM_DCA_MODE_MSK 0x0000000f

#define HW_ATL_TDM_DCA_MODE_MSKN 0xfffffff0

#define HW_ATL_TDM_DCA_MODE_SHIFT 0

#define HW_ATL_TDM_DCA_MODE_WIDTH 4

#define HW_ATL_TDM_DCA_MODE_DEFAULT 0x0




#define HW_ATL_TDM_DCADDESC_EN_ADR(dca) (0x00008400 + (dca) * 0x4)

#define HW_ATL_TDM_DCADDESC_EN_MSK 0x80000000

#define HW_ATL_TDM_DCADDESC_EN_MSKN 0x7fffffff

#define HW_ATL_TDM_DCADDESC_EN_SHIFT 31

#define HW_ATL_TDM_DCADDESC_EN_WIDTH 1

#define HW_ATL_TDM_DCADDESC_EN_DEFAULT 0x0




#define HW_ATL_TDM_DESCDEN_ADR(descriptor) (0x00007c08 + (descriptor) * 0x40)

#define HW_ATL_TDM_DESCDEN_MSK 0x80000000

#define HW_ATL_TDM_DESCDEN_MSKN 0x7fffffff

#define HW_ATL_TDM_DESCDEN_SHIFT 31

#define HW_ATL_TDM_DESCDEN_WIDTH 1

#define HW_ATL_TDM_DESCDEN_DEFAULT 0x0




#define HW_ATL_TDM_DESCDHD_ADR(descriptor) (0x00007c0c + (descriptor) * 0x40)

#define HW_ATL_TDM_DESCDHD_MSK 0x00001fff

#define HW_ATL_TDM_DESCDHD_MSKN 0xffffe000

#define HW_ATL_TDM_DESCDHD_SHIFT 0

#define HW_ATL_TDM_DESCDHD_WIDTH 13




#define HW_ATL_TDM_DESCDLEN_ADR(descriptor) (0x00007c08 + (descriptor) * 0x40)

#define HW_ATL_TDM_DESCDLEN_MSK 0x00001ff8

#define HW_ATL_TDM_DESCDLEN_MSKN 0xffffe007

#define HW_ATL_TDM_DESCDLEN_SHIFT 3

#define HW_ATL_TDM_DESCDLEN_WIDTH 10

#define HW_ATL_TDM_DESCDLEN_DEFAULT 0x0




#define HW_ATL_TDM_INT_DESC_WRB_EN_ADR 0x00007b40

#define HW_ATL_TDM_INT_DESC_WRB_EN_MSK 0x00000002

#define HW_ATL_TDM_INT_DESC_WRB_EN_MSKN 0xfffffffd

#define HW_ATL_TDM_INT_DESC_WRB_EN_SHIFT 1

#define HW_ATL_TDM_INT_DESC_WRB_EN_WIDTH 1

#define HW_ATL_TDM_INT_DESC_WRB_EN_DEFAULT 0x0




#define HW_ATL_TDM_DESCDWRB_THRESH_ADR(descriptor) \
	(0x00007c18 + (descriptor) * 0x40)

#define HW_ATL_TDM_DESCDWRB_THRESH_MSK 0x00007f00

#define HW_ATL_TDM_DESCDWRB_THRESH_MSKN 0xffff80ff

#define HW_ATL_TDM_DESCDWRB_THRESH_SHIFT 8

#define HW_ATL_TDM_DESCDWRB_THRESH_WIDTH 7

#define HW_ATL_TDM_DESCDWRB_THRESH_DEFAULT 0x0




#define HW_ATL_THM_LSO_TCP_FLAG_FIRST_ADR 0x00007820

#define HW_ATL_THM_LSO_TCP_FLAG_FIRST_MSK 0x00000fff

#define HW_ATL_THM_LSO_TCP_FLAG_FIRST_MSKN 0xfffff000

#define HW_ATL_THM_LSO_TCP_FLAG_FIRST_SHIFT 0

#define HW_ATL_THM_LSO_TCP_FLAG_FIRST_WIDTH 12

#define HW_ATL_THM_LSO_TCP_FLAG_FIRST_DEFAULT 0x0




#define HW_ATL_THM_LSO_TCP_FLAG_LAST_ADR 0x00007824

#define HW_ATL_THM_LSO_TCP_FLAG_LAST_MSK 0x00000fff

#define HW_ATL_THM_LSO_TCP_FLAG_LAST_MSKN 0xfffff000

#define HW_ATL_THM_LSO_TCP_FLAG_LAST_SHIFT 0

#define HW_ATL_THM_LSO_TCP_FLAG_LAST_WIDTH 12

#define HW_ATL_THM_LSO_TCP_FLAG_LAST_DEFAULT 0x0




#define HW_ATL_RPO_LRO_RSC_MAX_ADR 0x00005598

#define HW_ATL_RPO_LRO_RSC_MAX_MSK 0xFFFFFFFF

#define HW_ATL_RPO_LRO_RSC_MAX_MSKN 0x00000000

#define HW_ATL_RPO_LRO_RSC_MAX_SHIFT 0

#define HW_ATL_RPO_LRO_RSC_MAX_WIDTH 32

#define HW_ATL_RPO_LRO_RSC_MAX_DEFAULT 0x0




#define HW_ATL_RPO_LRO_EN_ADR 0x00005590

#define HW_ATL_RPO_LRO_EN_MSK 0xFFFFFFFF

#define HW_ATL_RPO_LRO_EN_MSKN 0x00000000

#define HW_ATL_RPO_LRO_EN_SHIFT 0

#define HW_ATL_RPO_LRO_EN_WIDTH 32

#define HW_ATL_RPO_LRO_EN_DEFAULT 0x0




#define HW_ATL_RPO_LRO_PTOPT_EN_ADR 0x00005594

#define HW_ATL_RPO_LRO_PTOPT_EN_MSK 0x00008000

#define HW_ATL_RPO_LRO_PTOPT_EN_MSKN 0xFFFF7FFF

#define HW_ATL_RPO_LRO_PTOPT_EN_SHIFT 15

#define HW_ATL_RPO_LRO_PTOPT_EN_WIDTH 1

#define HW_ATL_RPO_LRO_PTOPT_EN_DEFALT 0x1




#define HW_ATL_RPO_LRO_QSES_LMT_ADR 0x00005594

#define HW_ATL_RPO_LRO_QSES_LMT_MSK 0x00003000

#define HW_ATL_RPO_LRO_QSES_LMT_MSKN 0xFFFFCFFF

#define HW_ATL_RPO_LRO_QSES_LMT_SHIFT 12

#define HW_ATL_RPO_LRO_QSES_LMT_WIDTH 2

#define HW_ATL_RPO_LRO_QSES_LMT_DEFAULT 0x1




#define HW_ATL_RPO_LRO_TOT_DSC_LMT_ADR 0x00005594

#define HW_ATL_RPO_LRO_TOT_DSC_LMT_MSK 0x00000060

#define HW_ATL_RPO_LRO_TOT_DSC_LMT_MSKN 0xFFFFFF9F

#define HW_ATL_RPO_LRO_TOT_DSC_LMT_SHIFT 5

#define HW_ATL_RPO_LRO_TOT_DSC_LMT_WIDTH 2

#define HW_ATL_RPO_LRO_TOT_DSC_LMT_DEFALT 0x1




#define HW_ATL_RPO_LRO_PKT_MIN_ADR 0x00005594

#define HW_ATL_RPO_LRO_PKT_MIN_MSK 0x0000001F

#define HW_ATL_RPO_LRO_PKT_MIN_MSKN 0xFFFFFFE0

#define HW_ATL_RPO_LRO_PKT_MIN_SHIFT 0

#define HW_ATL_RPO_LRO_PKT_MIN_WIDTH 5

#define HW_ATL_RPO_LRO_PKT_MIN_DEFAULT 0x8


#define HW_ATL_RPO_LRO_LDES_MAX_WIDTH 2

#define HW_ATL_RPO_LRO_LDES_MAX_DEFAULT 0x0




#define HW_ATL_RPO_LRO_TB_DIV_ADR 0x00005620

#define HW_ATL_RPO_LRO_TB_DIV_MSK 0xFFF00000

#define HW_ATL_RPO_LRO_TB_DIV_MSKN 0x000FFFFF

#define HW_ATL_RPO_LRO_TB_DIV_SHIFT 20

#define HW_ATL_RPO_LRO_TB_DIV_WIDTH 12

#define HW_ATL_RPO_LRO_TB_DIV_DEFAULT 0xC35




#define HW_ATL_RPO_LRO_INA_IVAL_ADR 0x00005620

#define HW_ATL_RPO_LRO_INA_IVAL_MSK 0x000FFC00

#define HW_ATL_RPO_LRO_INA_IVAL_MSKN 0xFFF003FF

#define HW_ATL_RPO_LRO_INA_IVAL_SHIFT 10

#define HW_ATL_RPO_LRO_INA_IVAL_WIDTH 10

#define HW_ATL_RPO_LRO_INA_IVAL_DEFAULT 0xA




#define HW_ATL_RPO_LRO_MAX_IVAL_ADR 0x00005620

#define HW_ATL_RPO_LRO_MAX_IVAL_MSK 0x000003FF

#define HW_ATL_RPO_LRO_MAX_IVAL_MSKN 0xFFFFFC00

#define HW_ATL_RPO_LRO_MAX_IVAL_SHIFT 0

#define HW_ATL_RPO_LRO_MAX_IVAL_WIDTH 10

#define HW_ATL_RPO_LRO_MAX_IVAL_DEFAULT 0x19




#define HW_ATL_TDM_DCA_DCPUID_ADR(dca) (0x00008400 + (dca) * 0x4)

#define HW_ATL_TDM_DCA_DCPUID_MSK 0x000000FF

#define HW_ATL_TDM_DCA_DCPUID_MSKN 0xFFFFFF00

#define HW_ATL_TDM_DCA_DCPUID_SHIFT 0

#define HW_ATL_TDM_DCA_DCPUID_WIDTH 8

#define HW_ATL_TDM_DCA_DCPUID_DEFAULT 0x0




#define HW_ATL_TDM_DCA_DDESC_EN_ADR(dca) (0x00008400 + (dca) * 0x4)

#define HW_ATL_TDM_DCA_DDESC_EN_MSK 0x80000000

#define HW_ATL_TDM_DCA_DDESC_EN_MSKN 0x7FFFFFFF

#define HW_ATL_TDM_DCA_DDESC_EN_SHIFT 31

#define HW_ATL_TDM_DCA_DDESC_EN_WIDTH 1

#define HW_ATL_TDM_DCA_DDESC_EN_DEFAULT 0x0




#define HW_ATL_TDM_DESC_DEN_ADR(descriptor) (0x00007C08 + (descriptor) * 0x40)

#define HW_ATL_TDM_DESC_DEN_MSK 0x80000000

#define HW_ATL_TDM_DESC_DEN_MSKN 0x7FFFFFFF

#define HW_ATL_TDM_DESC_DEN_SHIFT 31

#define HW_ATL_TDM_DESC_DEN_WIDTH 1

#define HW_ATL_TDM_DESC_DEN_DEFAULT 0x0




#define HW_ATL_TDM_DESC_DHD_ADR(descriptor) (0x00007C0C + (descriptor) * 0x40)

#define HW_ATL_TDM_DESC_DHD_MSK 0x00001FFF

#define HW_ATL_TDM_DESC_DHD_MSKN 0xFFFFE000

#define HW_ATL_TDM_DESC_DHD_SHIFT 0

#define HW_ATL_TDM_DESC_DHD_WIDTH 13




#define HW_ATL_TDM_DESC_DLEN_ADR(descriptor) (0x00007C08 + (descriptor) * 0x40)

#define HW_ATL_TDM_DESC_DLEN_MSK 0x00001FF8

#define HW_ATL_TDM_DESC_DLEN_MSKN 0xFFFFE007

#define HW_ATL_TDM_DESC_DLEN_SHIFT 3

#define HW_ATL_TDM_DESC_DLEN_WIDTH 10

#define HW_ATL_TDM_DESC_DLEN_DEFAULT 0x0




#define HW_ATL_TDM_DESC_DWRB_THRESH_ADR(descriptor) \
	(0x00007C18 + (descriptor) * 0x40)

#define HW_ATL_TDM_DESC_DWRB_THRESH_MSK 0x00007F00

#define HW_ATL_TDM_DESC_DWRB_THRESH_MSKN 0xFFFF80FF

#define HW_ATL_TDM_DESC_DWRB_THRESH_SHIFT 8

#define HW_ATL_TDM_DESC_DWRB_THRESH_WIDTH 7

#define HW_ATL_TDM_DESC_DWRB_THRESH_DEFAULT 0x0




#define HW_ATL_TDM_INT_MOD_EN_ADR 0x00007B40

#define HW_ATL_TDM_INT_MOD_EN_MSK 0x00000010

#define HW_ATL_TDM_INT_MOD_EN_MSKN 0xFFFFFFEF

#define HW_ATL_TDM_INT_MOD_EN_SHIFT 4

#define HW_ATL_TDM_INT_MOD_EN_WIDTH 1

#define HW_ATL_TDM_INT_MOD_EN_DEFAULT 0x0



#define HW_ATL_THM_LSO_TCP_FLAG_MID_ADR 0x00007820

#define HW_ATL_THM_LSO_TCP_FLAG_MID_MSK 0x0fff0000

#define HW_ATL_THM_LSO_TCP_FLAG_MID_MSKN 0xf000ffff

#define HW_ATL_THM_LSO_TCP_FLAG_MID_SHIFT 16

#define HW_ATL_THM_LSO_TCP_FLAG_MID_WIDTH 12

#define HW_ATL_THM_LSO_TCP_FLAG_MID_DEFAULT 0x0




#define HW_ATL_TPB_TX_TC_MODE_ADDR 0x00007900

#define HW_ATL_TPB_TX_TC_MODE_MSK 0x00000100

#define HW_ATL_TPB_TX_TC_MODE_MSKN 0xFFFFFEFF

#define HW_ATL_TPB_TX_TC_MODE_SHIFT 8

#define HW_ATL_TPB_TX_TC_MODE_WIDTH 1

#define HW_ATL_TPB_TX_TC_MODE_DEFAULT 0x0




#define HW_ATL_TPS_TX_DESC_RATE_MODE_ADR 0x00007900

#define HW_ATL_TPS_TX_DESC_RATE_MODE_MSK 0x00000080

#define HW_ATL_TPS_TX_DESC_RATE_MODE_MSKN 0xFFFFFF7F

#define HW_ATL_TPS_TX_DESC_RATE_MODE_SHIFT 7

#define HW_ATL_TPS_TX_DESC_RATE_MODE_WIDTH 1

#define HW_ATL_TPS_TX_DESC_RATE_MODE_DEFAULT 0x0




#define HW_ATL_TPB_TX_BUF_EN_ADR 0x00007900

#define HW_ATL_TPB_TX_BUF_EN_MSK 0x00000001

#define HW_ATL_TPB_TX_BUF_EN_MSKN 0xfffffffe

#define HW_ATL_TPB_TX_BUF_EN_SHIFT 0

#define HW_ATL_TPB_TX_BUF_EN_WIDTH 1

#define HW_ATL_TPB_TX_BUF_EN_DEFAULT 0x0




#define HW_ATL_TPB_TXBHI_THRESH_ADR(buffer) (0x00007914 + (buffer) * 0x10)

#define HW_ATL_TPB_TXBHI_THRESH_MSK 0x1fff0000

#define HW_ATL_TPB_TXBHI_THRESH_MSKN 0xe000ffff

#define HW_ATL_TPB_TXBHI_THRESH_SHIFT 16

#define HW_ATL_TPB_TXBHI_THRESH_WIDTH 13

#define HW_ATL_TPB_TXBHI_THRESH_DEFAULT 0x0




#define HW_ATL_TPB_TXBLO_THRESH_ADR(buffer) (0x00007914 + (buffer) * 0x10)

#define HW_ATL_TPB_TXBLO_THRESH_MSK 0x00001fff

#define HW_ATL_TPB_TXBLO_THRESH_MSKN 0xffffe000

#define HW_ATL_TPB_TXBLO_THRESH_SHIFT 0

#define HW_ATL_TPB_TXBLO_THRESH_WIDTH 13

#define HW_ATL_TPB_TXBLO_THRESH_DEFAULT 0x0




#define HW_ATL_TPB_DMA_SYS_LBK_ADR 0x00007000

#define HW_ATL_TPB_DMA_SYS_LBK_MSK 0x00000040

#define HW_ATL_TPB_DMA_SYS_LBK_MSKN 0xffffffbf

#define HW_ATL_TPB_DMA_SYS_LBK_SHIFT 6

#define HW_ATL_TPB_DMA_SYS_LBK_WIDTH 1

#define HW_ATL_TPB_DMA_SYS_LBK_DEFAULT 0x0




#define HW_ATL_TPB_DMA_NET_LBK_ADR 0x00007000

#define HW_ATL_TPB_DMA_NET_LBK_MSK 0x00000010

#define HW_ATL_TPB_DMA_NET_LBK_MSKN 0xffffffef

#define HW_ATL_TPB_DMA_NET_LBK_SHIFT 4

#define HW_ATL_TPB_DMA_NET_LBK_WIDTH 1

#define HW_ATL_TPB_DMA_NET_LBK_DEFAULT 0x0




#define HW_ATL_TPB_TXBBUF_SIZE_ADR(buffer) (0x00007910 + (buffer) * 0x10)

#define HW_ATL_TPB_TXBBUF_SIZE_MSK 0x000000ff

#define HW_ATL_TPB_TXBBUF_SIZE_MSKN 0xffffff00

#define HW_ATL_TPB_TXBBUF_SIZE_SHIFT 0

#define HW_ATL_TPB_TXBBUF_SIZE_WIDTH 8

#define HW_ATL_TPB_TXBBUF_SIZE_DEFAULT 0x0




#define HW_ATL_TPB_TX_SCP_INS_EN_ADR 0x00007900

#define HW_ATL_TPB_TX_SCP_INS_EN_MSK 0x00000004

#define HW_ATL_TPB_TX_SCP_INS_EN_MSKN 0xfffffffb

#define HW_ATL_TPB_TX_SCP_INS_EN_SHIFT 2

#define HW_ATL_TPB_TX_SCP_INS_EN_WIDTH 1

#define HW_ATL_TPB_TX_SCP_INS_EN_DEFAULT 0x0




#define HW_ATL_TPB_TX_CLK_GATE_EN_ADR 0x00007900

#define HW_ATL_TPB_TX_CLK_GATE_EN_MSK 0x00000010

#define HW_ATL_TPB_TX_CLK_GATE_EN_MSKN 0xffffffef

#define HW_ATL_TPB_TX_CLK_GATE_EN_SHIFT 4

#define HW_ATL_TPB_TX_CLK_GATE_EN_WIDTH 1

#define HW_ATL_TPB_TX_CLK_GATE_EN_DEFAULT 0x1




#define HW_ATL_TPO_IPV4CHK_EN_ADR 0x00007800

#define HW_ATL_TPO_IPV4CHK_EN_MSK 0x00000002

#define HW_ATL_TPO_IPV4CHK_EN_MSKN 0xfffffffd

#define HW_ATL_TPO_IPV4CHK_EN_SHIFT 1

#define HW_ATL_TPO_IPV4CHK_EN_WIDTH 1

#define HW_ATL_TPO_IPV4CHK_EN_DEFAULT 0x0




#define HW_ATL_TPOL4CHK_EN_ADR 0x00007800

#define HW_ATL_TPOL4CHK_EN_MSK 0x00000001

#define HW_ATL_TPOL4CHK_EN_MSKN 0xfffffffe

#define HW_ATL_TPOL4CHK_EN_SHIFT 0

#define HW_ATL_TPOL4CHK_EN_WIDTH 1

#define HW_ATL_TPOL4CHK_EN_DEFAULT 0x0




#define HW_ATL_TPO_PKT_SYS_LBK_ADR 0x00007000

#define HW_ATL_TPO_PKT_SYS_LBK_MSK 0x00000080

#define HW_ATL_TPO_PKT_SYS_LBK_MSKN 0xffffff7f

#define HW_ATL_TPO_PKT_SYS_LBK_SHIFT 7

#define HW_ATL_TPO_PKT_SYS_LBK_WIDTH 1

#define HW_ATL_TPO_PKT_SYS_LBK_DEFAULT 0x0




#define HW_ATL_TPS_DATA_TC_ARB_MODE_ADR 0x00007100

#define HW_ATL_TPS_DATA_TC_ARB_MODE_MSK 0x00000001

#define HW_ATL_TPS_DATA_TC_ARB_MODE_MSKN 0xfffffffe

#define HW_ATL_TPS_DATA_TC_ARB_MODE_SHIFT 0

#define HW_ATL_TPS_DATA_TC_ARB_MODE_WIDTH 1

#define HW_ATL_TPS_DATA_TC_ARB_MODE_DEFAULT 0x0




#define HW_ATL_TPS_DESC_RATE_EN_ADR(desc) (0x00007408 + (desc) * 0x10)

#define HW_ATL_TPS_DESC_RATE_EN_MSK 0x80000000

#define HW_ATL_TPS_DESC_RATE_EN_MSKN 0x7FFFFFFF

#define HW_ATL_TPS_DESC_RATE_EN_SHIFT 31

#define HW_ATL_TPS_DESC_RATE_EN_WIDTH 1

#define HW_ATL_TPS_DESC_RATE_EN_DEFAULT 0x0



#define HW_ATL_TPS_DESC_RATE_X_ADR(desc) (0x00007408 + (desc) * 0x10)

#define HW_ATL_TPS_DESC_RATE_X_MSK 0x03FF0000

#define HW_ATL_TPS_DESC_RATE_X_MSKN 0xFC00FFFF

#define HW_ATL_TPS_DESC_RATE_X_SHIFT 16

#define HW_ATL_TPS_DESC_RATE_X_WIDTH 10

#define HW_ATL_TPS_DESC_RATE_X_DEFAULT 0x0



#define HW_ATL_TPS_DESC_RATE_Y_ADR(desc) (0x00007408 + (desc) * 0x10)

#define HW_ATL_TPS_DESC_RATE_Y_MSK 0x00003FFF

#define HW_ATL_TPS_DESC_RATE_Y_MSKN 0xFFFFC000

#define HW_ATL_TPS_DESC_RATE_Y_SHIFT 0

#define HW_ATL_TPS_DESC_RATE_Y_WIDTH 14

#define HW_ATL_TPS_DESC_RATE_Y_DEFAULT 0x0




#define HW_ATL_TPS_DESC_RATE_TA_RST_ADR 0x00007310

#define HW_ATL_TPS_DESC_RATE_TA_RST_MSK 0x80000000

#define HW_ATL_TPS_DESC_RATE_TA_RST_MSKN 0x7fffffff

#define HW_ATL_TPS_DESC_RATE_TA_RST_SHIFT 31

#define HW_ATL_TPS_DESC_RATE_TA_RST_WIDTH 1

#define HW_ATL_TPS_DESC_RATE_TA_RST_DEFAULT 0x0




#define HW_ATL_TPS_DESC_RATE_LIM_ADR 0x00007310

#define HW_ATL_TPS_DESC_RATE_LIM_MSK 0x000007ff

#define HW_ATL_TPS_DESC_RATE_LIM_MSKN 0xfffff800

#define HW_ATL_TPS_DESC_RATE_LIM_SHIFT 0

#define HW_ATL_TPS_DESC_RATE_LIM_WIDTH 11

#define HW_ATL_TPS_DESC_RATE_LIM_DEFAULT 0x0




#define HW_ATL_TPS_DESC_TC_ARB_MODE_ADR 0x00007200

#define HW_ATL_TPS_DESC_TC_ARB_MODE_MSK 0x00000003

#define HW_ATL_TPS_DESC_TC_ARB_MODE_MSKN 0xfffffffc

#define HW_ATL_TPS_DESC_TC_ARB_MODE_SHIFT 0

#define HW_ATL_TPS_DESC_TC_ARB_MODE_WIDTH 2

#define HW_ATL_TPS_DESC_TC_ARB_MODE_DEFAULT 0x0




#define HW_ATL_TPS_DESC_TCTCREDIT_MAX_ADR(tc) (0x00007210 + (tc) * 0x4)

#define HW_ATL_TPS_DESC_TCTCREDIT_MAX_MSK 0x0fff0000

#define HW_ATL_TPS_DESC_TCTCREDIT_MAX_MSKN 0xf000ffff

#define HW_ATL_TPS_DESC_TCTCREDIT_MAX_SHIFT 16

#define HW_ATL_TPS_DESC_TCTCREDIT_MAX_WIDTH 12

#define HW_ATL_TPS_DESC_TCTCREDIT_MAX_DEFAULT 0x0




#define HW_ATL_TPS_DESC_TCTWEIGHT_ADR(tc) (0x00007210 + (tc) * 0x4)

#define HW_ATL_TPS_DESC_TCTWEIGHT_MSK 0x000001ff

#define HW_ATL_TPS_DESC_TCTWEIGHT_MSKN 0xfffffe00

#define HW_ATL_TPS_DESC_TCTWEIGHT_SHIFT 0

#define HW_ATL_TPS_DESC_TCTWEIGHT_WIDTH 9

#define HW_ATL_TPS_DESC_TCTWEIGHT_DEFAULT 0x0




#define HW_ATL_TPS_DESC_VM_ARB_MODE_ADR 0x00007300

#define HW_ATL_TPS_DESC_VM_ARB_MODE_MSK 0x00000001

#define HW_ATL_TPS_DESC_VM_ARB_MODE_MSKN 0xfffffffe

#define HW_ATL_TPS_DESC_VM_ARB_MODE_SHIFT 0

#define HW_ATL_TPS_DESC_VM_ARB_MODE_WIDTH 1

#define HW_ATL_TPS_DESC_VM_ARB_MODE_DEFAULT 0x0




#define HW_ATL_TPS_DATA_TCTCREDIT_MAX_ADR(tc) (0x00007110 + (tc) * 0x4)

#define HW_ATL_TPS_DATA_TCTCREDIT_MAX_MSK 0x0fff0000

#define HW_ATL_TPS_DATA_TCTCREDIT_MAX_MSKN 0xf000ffff

#define HW_ATL_TPS_DATA_TCTCREDIT_MAX_SHIFT 16

#define HW_ATL_TPS_DATA_TCTCREDIT_MAX_WIDTH 12

#define HW_ATL_TPS_DATA_TCTCREDIT_MAX_DEFAULT 0x0




#define HW_ATL_TPS_DATA_TCTWEIGHT_ADR(tc) (0x00007110 + (tc) * 0x4)

#define HW_ATL_TPS_DATA_TCTWEIGHT_MSK 0x000001ff

#define HW_ATL_TPS_DATA_TCTWEIGHT_MSKN 0xfffffe00

#define HW_ATL_TPS_DATA_TCTWEIGHT_SHIFT 0

#define HW_ATL_TPS_DATA_TCTWEIGHT_WIDTH 9

#define HW_ATL_TPS_DATA_TCTWEIGHT_DEFAULT 0x0




#define HW_ATL_TX_REG_RES_DSBL_ADR 0x00007000

#define HW_ATL_TX_REG_RES_DSBL_MSK 0x20000000

#define HW_ATL_TX_REG_RES_DSBL_MSKN 0xdfffffff

#define HW_ATL_TX_REG_RES_DSBL_SHIFT 29

#define HW_ATL_TX_REG_RES_DSBL_WIDTH 1

#define HW_ATL_TX_REG_RES_DSBL_DEFAULT 0x1




#define HW_ATL_MSM_REG_ACCESS_BUSY_ADR 0x00004400

#define HW_ATL_MSM_REG_ACCESS_BUSY_MSK 0x00001000

#define HW_ATL_MSM_REG_ACCESS_BUSY_MSKN 0xffffefff

#define HW_ATL_MSM_REG_ACCESS_BUSY_SHIFT 12

#define HW_ATL_MSM_REG_ACCESS_BUSY_WIDTH 1




#define HW_ATL_MSM_REG_ADDR_ADR 0x00004400

#define HW_ATL_MSM_REG_ADDR_MSK 0x000000ff

#define HW_ATL_MSM_REG_ADDR_MSKN 0xffffff00

#define HW_ATL_MSM_REG_ADDR_SHIFT 0

#define HW_ATL_MSM_REG_ADDR_WIDTH 8

#define HW_ATL_MSM_REG_ADDR_DEFAULT 0x0




#define HW_ATL_MSM_REG_RD_STROBE_ADR 0x00004400

#define HW_ATL_MSM_REG_RD_STROBE_MSK 0x00000200

#define HW_ATL_MSM_REG_RD_STROBE_MSKN 0xfffffdff

#define HW_ATL_MSM_REG_RD_STROBE_SHIFT 9

#define HW_ATL_MSM_REG_RD_STROBE_WIDTH 1

#define HW_ATL_MSM_REG_RD_STROBE_DEFAULT 0x0




#define HW_ATL_MSM_REG_RD_DATA_ADR 0x00004408

#define HW_ATL_MSM_REG_RD_DATA_MSK 0xffffffff

#define HW_ATL_MSM_REG_RD_DATA_MSKN 0x00000000

#define HW_ATL_MSM_REG_RD_DATA_SHIFT 0

#define HW_ATL_MSM_REG_RD_DATA_WIDTH 32




#define HW_ATL_MSM_REG_WR_DATA_ADR 0x00004404

#define HW_ATL_MSM_REG_WR_DATA_MSK 0xffffffff

#define HW_ATL_MSM_REG_WR_DATA_MSKN 0x00000000

#define HW_ATL_MSM_REG_WR_DATA_SHIFT 0

#define HW_ATL_MSM_REG_WR_DATA_WIDTH 32

#define HW_ATL_MSM_REG_WR_DATA_DEFAULT 0x0




#define HW_ATL_MSM_REG_WR_STROBE_ADR 0x00004400

#define HW_ATL_MSM_REG_WR_STROBE_MSK 0x00000100

#define HW_ATL_MSM_REG_WR_STROBE_MSKN 0xfffffeff

#define HW_ATL_MSM_REG_WR_STROBE_SHIFT 8

#define HW_ATL_MSM_REG_WR_STROBE_WIDTH 1

#define HW_ATL_MSM_REG_WR_STROBE_DEFAULT 0x0


#define HW_ATL_PCS_PTP_CLOCK_READ_ENABLE_ADR 0x00004628

#define HW_ATL_PCS_PTP_CLOCK_READ_ENABLE_MSK 0x00000010

#define HW_ATL_PCS_PTP_CLOCK_READ_ENABLE_MSKN 0xFFFFFFEF

#define HW_ATL_PCS_PTP_CLOCK_READ_ENABLE_SHIFT 4

#define HW_ATL_PCS_PTP_CLOCK_READ_ENABLE_WIDTH 1

#define HW_ATL_PCS_PTP_CLOCK_READ_ENABLE_DEFAULT 0x0


#define HW_ATL_PCS_PTP_TS_VAL_ADDR(index) (0x00004900 + (index) * 0x4)




#define HW_ATL_GLB_SOFT_RES_ADR 0x00000000

#define HW_ATL_GLB_SOFT_RES_MSK 0x00008000

#define HW_ATL_GLB_SOFT_RES_MSKN 0xffff7fff

#define HW_ATL_GLB_SOFT_RES_SHIFT 15

#define HW_ATL_GLB_SOFT_RES_WIDTH 1

#define HW_ATL_GLB_SOFT_RES_DEFAULT 0x0




#define HW_ATL_GLB_REG_RES_DIS_ADR 0x00000000

#define HW_ATL_GLB_REG_RES_DIS_MSK 0x00004000

#define HW_ATL_GLB_REG_RES_DIS_MSKN 0xffffbfff

#define HW_ATL_GLB_REG_RES_DIS_SHIFT 14

#define HW_ATL_GLB_REG_RES_DIS_WIDTH 1

#define HW_ATL_GLB_REG_RES_DIS_DEFAULT 0x1


#define HW_ATL_TX_DMA_DEBUG_CTL_ADR 0x00008920u


#define HW_ATL_TX_DMA_DESC_BASE_ADDRMSW_ADR(descriptor) \
			(0x00007c04u + (descriptor) * 0x40)


#define HW_ATL_TX_DMA_TOTAL_REQ_LIMIT_ADR 0x00007b20u



#define HW_ATL_TX_INTR_MODERATION_CTL_ADR(queue) (0x00008980u + (queue) * 0x4)




#define HW_ATL_PCI_REG_RES_DSBL_ADR 0x00001000

#define HW_ATL_PCI_REG_RES_DSBL_MSK 0x20000000

#define HW_ATL_PCI_REG_RES_DSBL_MSKN 0xdfffffff

#define HW_ATL_PCI_REG_RES_DSBL_SHIFT 29

#define HW_ATL_PCI_REG_RES_DSBL_WIDTH 1

#define HW_ATL_PCI_REG_RES_DSBL_DEFAULT 0x1


#define HW_ATL_PCI_REG_CONTROL6_ADR 0x1014u


#define HW_ATL_GLB_CPU_SCRATCH_SCP_ADR(scratch_scp) \
	(0x00000300u + (scratch_scp) * 0x4)


#define HW_ATL_MCP_UP_FORCE_INTERRUPT_ADR 0x00000404

#define HW_ATL_MCP_UP_FORCE_INTERRUPT_MSK 0x00000002

#define HW_ATL_MCP_UP_FORCE_INTERRUPT_MSKN 0xFFFFFFFD

#define HW_ATL_MCP_UP_FORCE_INTERRUPT_SHIFT 1

#define HW_ATL_MCP_UP_FORCE_INTERRUPT_WIDTH 1

#define HW_ATL_MCP_UP_FORCE_INTERRUPT_DEFAULT 0x0


#define HW_ATL_GLB_MDIO_IFACE_ADDR_BEGIN   0x00000280u

#define HW_ATL_GLB_MDIO_IFACE_N_ADR(number) \
	(HW_ATL_GLB_MDIO_IFACE_ADDR_BEGIN + (((number) - 1) * 0x4))




#define HW_ATL_MDIO_BUSY_ADR 0x00000284

#define HW_ATL_MDIO_BUSY_MSK 0x80000000

#define HW_ATL_MDIO_BUSY_MSKN 0x7FFFFFFF

#define HW_ATL_MDIO_BUSY_SHIFT 31

#define HW_ATL_MDIO_BUSY_WIDTH 1




#define HW_ATL_MDIO_EXECUTE_OPERATION_ADR 0x00000284

#define HW_ATL_MDIO_EXECUTE_OPERATION_MSK 0x00008000

#define HW_ATL_MDIO_EXECUTE_OPERATION_MSKN 0xFFFF7FFF

#define HW_ATL_MDIO_EXECUTE_OPERATION_SHIFT 15

#define HW_ATL_MDIO_EXECUTE_OPERATION_WIDTH 1

#define HW_ATL_MDIO_EXECUTE_OPERATION_DEFAULT 0x0




#define HW_ATL_MDIO_OP_MODE_ADR 0x00000284

#define HW_ATL_MDIO_OP_MODE_MSK 0x00003000

#define HW_ATL_MDIO_OP_MODE_MSKN 0xFFFFCFFF

#define HW_ATL_MDIO_OP_MODE_SHIFT 12

#define HW_ATL_MDIO_OP_MODE_WIDTH 2

#define HW_ATL_MDIO_OP_MODE_DEFAULT 0x0




#define HW_ATL_MDIO_PHY_ADDRESS_ADR 0x00000284

#define HW_ATL_MDIO_PHY_ADDRESS_MSK 0x000003FF

#define HW_ATL_MDIO_PHY_ADDRESS_MSKN 0xFFFFFC00

#define HW_ATL_MDIO_PHY_ADDRESS_SHIFT 0

#define HW_ATL_MDIO_PHY_ADDRESS_WIDTH 10

#define HW_ATL_MDIO_PHY_ADDRESS_DEFAULT 0x0




#define HW_ATL_MDIO_WRITE_DATA_ADR 0x00000288

#define HW_ATL_MDIO_WRITE_DATA_MSK 0x0000FFFF

#define HW_ATL_MDIO_WRITE_DATA_MSKN 0xFFFF0000

#define HW_ATL_MDIO_WRITE_DATA_SHIFT 0

#define HW_ATL_MDIO_WRITE_DATA_WIDTH 16

#define HW_ATL_MDIO_WRITE_DATA_DEFAULT 0x0




#define HW_ATL_MDIO_ADDRESS_ADR 0x0000028C

#define HW_ATL_MDIO_ADDRESS_MSK 0x0000FFFF

#define HW_ATL_MDIO_ADDRESS_MSKN 0xFFFF0000

#define HW_ATL_MDIO_ADDRESS_SHIFT 0

#define HW_ATL_MDIO_ADDRESS_WIDTH 16

#define HW_ATL_MDIO_ADDRESS_DEFAULT 0x0

#define HW_ATL_MIF_RESET_TIMEOUT_ADR 0x00000348

#define HW_ATL_FW_SM_MDIO       0x0U
#define HW_ATL_FW_SM_RAM        0x2U
#define HW_ATL_FW_SM_RESET1     0x3U
#define HW_ATL_FW_SM_RESET2     0x4U

#endif 
