
#include <linux/bug.h>

void check(void)
{
	 
	BUILD_BUG_ON(!IS_ENABLED(CONFIG_64BIT));
	BUILD_BUG_ON(!IS_MODULE(CONFIG_CXL_BUS));
	BUILD_BUG_ON(!IS_MODULE(CONFIG_CXL_ACPI));
	BUILD_BUG_ON(!IS_MODULE(CONFIG_CXL_PMEM));
	BUILD_BUG_ON(!IS_ENABLED(CONFIG_CXL_REGION_INVALIDATION_TEST));
	BUILD_BUG_ON(!IS_ENABLED(CONFIG_NVDIMM_SECURITY_TEST));
	BUILD_BUG_ON(!IS_ENABLED(CONFIG_DEBUG_FS));
}
