{
  "module_name": "Makefile",
  "hash_id": "add731c1744725f1863af9fd391de70e731c67123bd486ebe7a3155519c4894f",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/amd/display/dc/dcn303/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: MIT\n#\n# Copyright (C) 2021 Advanced Micro Devices, Inc. All the rights reserved\n#\n#  Authors: AMD\n#\n# Makefile for dcn303.\n\nDCN3_03 = dcn303_init.o dcn303_hwseq.o dcn303_resource.o\n\nAMD_DAL_DCN3_03 = $(addprefix $(AMDDALPATH)/dc/dcn303/,$(DCN3_03))\n\nAMD_DISPLAY_FILES += $(AMD_DAL_DCN3_03)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}