{
  "module_name": "Makefile",
  "hash_id": "ab330e3e9089c078f9a09fb30f5903403a4545a1765eede72399678c995ff5e2",
  "original_prompt": "Ingested from linux-6.6.14/drivers/usb/gadget/udc/bdc/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_USB_BDC_UDC)\t+= bdc.o\nbdc-y\t:= bdc_core.o bdc_cmd.o bdc_ep.o bdc_udc.o\n\nifneq ($(CONFIG_USB_GADGET_VERBOSE),)\n\tbdc-y\t\t\t+= bdc_dbg.o\nendif\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}