{
  "module_name": "Makefile",
  "hash_id": "761befe50f3ae7730e6cf7503ac2a35569d270555f344f67ddb695da0c026c25",
  "original_prompt": "Ingested from linux-6.6.14/drivers/dma/lgm/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_INTEL_LDMA)\t+= lgm-dma.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}