{
  "module_name": "Kbuild",
  "hash_id": "cfa80ca955d18e402b0f0197cac07a060bea19876445a9bdd1fffb434adde391",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/nouveau/nvkm/subdev/clk/Kbuild",
  "human_readable_source": "# SPDX-License-Identifier: MIT\nnvkm-y += nvkm/subdev/clk/base.o\nnvkm-y += nvkm/subdev/clk/nv04.o\nnvkm-y += nvkm/subdev/clk/nv40.o\nnvkm-y += nvkm/subdev/clk/nv50.o\nnvkm-y += nvkm/subdev/clk/g84.o\nnvkm-y += nvkm/subdev/clk/gt215.o\nnvkm-y += nvkm/subdev/clk/mcp77.o\nnvkm-y += nvkm/subdev/clk/gf100.o\nnvkm-y += nvkm/subdev/clk/gk104.o\nnvkm-y += nvkm/subdev/clk/gk20a.o\nnvkm-y += nvkm/subdev/clk/gm20b.o\n\nnvkm-y += nvkm/subdev/clk/pllnv04.o\nnvkm-y += nvkm/subdev/clk/pllgt215.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}