{
  "module_name": "Makefile",
  "hash_id": "b74a309ef0229d764ab33c2339befb077d11a91cb2b6f938defb4e2b6b1eaeb4",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/realtek/rtl818x/rtl8180/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nrtl818x_pci-objs\t:= dev.o rtl8225.o sa2400.o max2820.o grf5101.o rtl8225se.o\n\nobj-$(CONFIG_RTL8180)\t+= rtl818x_pci.o\n\nccflags-y += -I $(srctree)/$(src)/..\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}