{
  "module_name": "Makefile",
  "hash_id": "893483963d698a913e6aebcad26ee643a939e72949f29c692f2a6c102a51085b",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/team/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the network team driver\n#\n\nobj-$(CONFIG_NET_TEAM) += team.o\nobj-$(CONFIG_NET_TEAM_MODE_BROADCAST) += team_mode_broadcast.o\nobj-$(CONFIG_NET_TEAM_MODE_ROUNDROBIN) += team_mode_roundrobin.o\nobj-$(CONFIG_NET_TEAM_MODE_RANDOM) += team_mode_random.o\nobj-$(CONFIG_NET_TEAM_MODE_ACTIVEBACKUP) += team_mode_activebackup.o\nobj-$(CONFIG_NET_TEAM_MODE_LOADBALANCE) += team_mode_loadbalance.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}