{
  "module_name": "Makefile",
  "hash_id": "bb0aad53d09ad7fc8fc0147359ded3572029f66dc28931b08f284400fd137a72",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/kmod/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n# Makefile for kmod loading selftests\n\n# No binaries, but make sure arg-less \"make\" doesn't trigger \"run_tests\"\nall:\n\nTEST_PROGS := kmod.sh\n\ninclude ../lib.mk\n\n# Nothing to clean up.\nclean:\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}