{
  "module_name": "Makefile",
  "hash_id": "2cfec543f8e380ab61d3e9d4ce06b9cfc1e5c74b0ad26c70afe76ae04a53fb06",
  "original_prompt": "Ingested from linux-6.6.14/net/x25/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the Linux X.25 Packet layer.\n#\n\nobj-$(CONFIG_X25) += x25.o\n\nx25-y\t\t\t:= af_x25.o x25_dev.o x25_facilities.o x25_in.o \\\n\t\t\t   x25_link.o x25_out.o x25_route.o x25_subr.o \\\n\t\t\t   x25_timer.o x25_proc.o x25_forward.o\nx25-$(CONFIG_SYSCTL)\t+= sysctl_net_x25.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}