{
  "module_name": "Makefile",
  "hash_id": "768eae05e72d6dffd5129942e5e399e727b6360305e63c0ffee2084ccdf801b3",
  "original_prompt": "Ingested from linux-6.6.14/sound/pci/emu10k1/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for ALSA\n# Copyright (c) 2001 by Jaroslav Kysela <perex@perex.cz>\n#\n\nsnd-emu10k1-objs := emu10k1.o emu10k1_main.o \\\n\t\t    irq.o memory.o voice.o emumpu401.o emupcm.o io.o \\\n\t\t    emumixer.o emufx.o timer.o p16v.o\nsnd-emu10k1-$(CONFIG_SND_PROC_FS) += emuproc.o\nsnd-emu10k1-synth-objs := emu10k1_synth.o emu10k1_callback.o emu10k1_patch.o\nsnd-emu10k1x-objs := emu10k1x.o\n\n# Toplevel Module Dependency\nobj-$(CONFIG_SND_EMU10K1) += snd-emu10k1.o\nobj-$(CONFIG_SND_EMU10K1_SEQ) += snd-emu10k1-synth.o\nobj-$(CONFIG_SND_EMU10K1X) += snd-emu10k1x.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}