{
  "module_name": "Makefile",
  "hash_id": "679eedaca76b682d5e2cff611a422034a8409fb563d7a1ac121cd8890c878b5c",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/test-drivers/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the test drivers.\n#\n\n# Please keep it alphabetically sorted by Kconfig name\n# (e. g. LC_ALL=C sort Makefile)\n\nobj-$(CONFIG_DVB_VIDTV) += vidtv/\n\nobj-$(CONFIG_VIDEO_VICODEC) += vicodec/\nobj-$(CONFIG_VIDEO_VIM2M) += vim2m.o\nobj-$(CONFIG_VIDEO_VIMC) += vimc/\nobj-$(CONFIG_VIDEO_VIVID) += vivid/\nobj-$(CONFIG_VIDEO_VISL) += visl/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}