{
  "module_name": "Makefile",
  "hash_id": "06c2c8070a637985f37667e6044273387b96a0b99174d2d7626cc8d754a0b08f",
  "original_prompt": "Ingested from linux-6.6.14/drivers/scsi/aacraid/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n# Adaptec aacraid\n\nobj-$(CONFIG_SCSI_AACRAID) := aacraid.o\n\naacraid-objs\t:= linit.o aachba.o commctrl.o comminit.o commsup.o \\\n\t\t   dpcsup.o rx.o sa.o rkt.o nark.o src.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}