
#ifndef __PERF_TESTS__HISTS_COMMON_H__
#define __PERF_TESTS__HISTS_COMMON_H__

struct machine;
struct machines;

#define FAKE_PID_PERF1  100
#define FAKE_PID_PERF2  200
#define FAKE_PID_BASH   300

#define FAKE_MAP_PERF    0x400000
#define FAKE_MAP_BASH    0x400000
#define FAKE_MAP_LIBC    0x500000
#define FAKE_MAP_KERNEL  0xf00000
#define FAKE_MAP_LENGTH  0x100000

#define FAKE_SYM_OFFSET1  700
#define FAKE_SYM_OFFSET2  800
#define FAKE_SYM_OFFSET3  900
#define FAKE_SYM_LENGTH   100

#define FAKE_IP_PERF_MAIN  FAKE_MAP_PERF + FAKE_SYM_OFFSET1
#define FAKE_IP_PERF_RUN_COMMAND  FAKE_MAP_PERF + FAKE_SYM_OFFSET2
#define FAKE_IP_PERF_CMD_RECORD  FAKE_MAP_PERF + FAKE_SYM_OFFSET3
#define FAKE_IP_BASH_MAIN  FAKE_MAP_BASH + FAKE_SYM_OFFSET1
#define FAKE_IP_BASH_XMALLOC  FAKE_MAP_BASH + FAKE_SYM_OFFSET2
#define FAKE_IP_BASH_XFREE  FAKE_MAP_BASH + FAKE_SYM_OFFSET3
#define FAKE_IP_LIBC_MALLOC  FAKE_MAP_LIBC + FAKE_SYM_OFFSET1
#define FAKE_IP_LIBC_FREE  FAKE_MAP_LIBC + FAKE_SYM_OFFSET2
#define FAKE_IP_LIBC_REALLOC  FAKE_MAP_LIBC + FAKE_SYM_OFFSET3
#define FAKE_IP_KERNEL_SCHEDULE  FAKE_MAP_KERNEL + FAKE_SYM_OFFSET1
#define FAKE_IP_KERNEL_PAGE_FAULT  FAKE_MAP_KERNEL + FAKE_SYM_OFFSET2
#define FAKE_IP_KERNEL_SYS_PERF_EVENT_OPEN  FAKE_MAP_KERNEL + FAKE_SYM_OFFSET3


struct machine *setup_fake_machine(struct machines *machines);

void print_hists_in(struct hists *hists);
void print_hists_out(struct hists *hists);

#endif 
