{
  "module_name": "Makefile",
  "hash_id": "75befa0fd69c5457ede9385d63c07e0aa03897e600f5fc6763285dab31ec85d1",
  "original_prompt": "Ingested from linux-6.6.14/net/kcm/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_AF_KCM) += kcm.o\n\nkcm-y := kcmsock.o kcmproc.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}