{
  "module_name": "Makefile",
  "hash_id": "9a90f4783d797ebe34022b29bad3eba1834ed4f230408e8399e298427a012ce2",
  "original_prompt": "Ingested from linux-6.6.14/drivers/staging/vc04_services/vchiq-mmal/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nbcm2835-mmal-vchiq-objs := mmal-vchiq.o\n\nobj-$(CONFIG_BCM2835_VCHIQ_MMAL) += bcm2835-mmal-vchiq.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}