{
  "module_name": "Makefile",
  "hash_id": "eb8bb9fd1ed414b08b5f96c7a1ad95d02011a100b0acac6cdba7e36a9774747a",
  "original_prompt": "Ingested from linux-6.6.14/drivers/usb/early/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for early USB devices\n#\n\nobj-$(CONFIG_EARLY_PRINTK_DBGP) += ehci-dbgp.o\nobj-$(CONFIG_EARLY_PRINTK_USB_XDBC) += xhci-dbc.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}