{
  "module_name": "Makefile",
  "hash_id": "ce75be01f3f7680ce1c17efc3246298958871118cdcd8577f38f22e87a3637dc",
  "original_prompt": "Ingested from linux-6.6.14/drivers/video/fbdev/geode/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for the Geode family framebuffer drivers\n\nobj-$(CONFIG_FB_GEODE_GX1) += gx1fb.o\nobj-$(CONFIG_FB_GEODE_GX)  += gxfb.o\nobj-$(CONFIG_FB_GEODE_LX)  += lxfb.o\n\ngx1fb-objs := gx1fb_core.o display_gx1.o video_cs5530.o\ngxfb-objs  := gxfb_core.o display_gx.o video_gx.o suspend_gx.o\nlxfb-objs  := lxfb_core.o lxfb_ops.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}