{
  "module_name": "Makefile",
  "hash_id": "d4ff2ad46a9cdf40851e0c862efd717031c9f099bc7033251630e64b6d906934",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/cec/usb/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the CEC USB device drivers.\n#\nobj-$(CONFIG_USB_PULSE8_CEC) += pulse8/\nobj-$(CONFIG_USB_RAINSHADOW_CEC) += rainshadow/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}