{
  "module_name": "Makefile",
  "hash_id": "0355fb0eb693d897a48bda6bc6efb4645408fd8faab806ced1a2e30ab45dd308",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/panfrost/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\npanfrost-y := \\\n\tpanfrost_drv.o \\\n\tpanfrost_device.o \\\n\tpanfrost_devfreq.o \\\n\tpanfrost_gem.o \\\n\tpanfrost_gem_shrinker.o \\\n\tpanfrost_gpu.o \\\n\tpanfrost_job.o \\\n\tpanfrost_mmu.o \\\n\tpanfrost_perfcnt.o \\\n\tpanfrost_dump.o\n\nobj-$(CONFIG_DRM_PANFROST) += panfrost.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}