


obj-$(CONFIG_MTD_NAND_BRCMNAND_IPROC)	+= iproc_nand.o
obj-$(CONFIG_MTD_NAND_BRCMNAND_BCMBCA)	+= bcm63138_nand.o
obj-$(CONFIG_MTD_NAND_BRCMNAND_BCM63XX)	+= bcm6368_nand.o
obj-$(CONFIG_MTD_NAND_BRCMNAND_BRCMSTB)	+= brcmstb_nand.o
obj-$(CONFIG_MTD_NAND_BRCMNAND)		+= brcmnand.o

obj-$(CONFIG_MTD_NAND_BRCMNAND_BCMA)	+= bcma_nand.o
