{
  "module_name": "Makefile",
  "hash_id": "2d502ae3b0b576c5a9ee25e9c2ff06d2a5788e4050d41d914d7caefb224d6928",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/starfive/Makefile",
  "human_readable_source": "# StarFive Platform Support\nobj-$(CONFIG_SND_SOC_JH7110_TDM) += jh7110_tdm.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}