{
  "module_name": "Makefile",
  "hash_id": "32626288dac84fb0377e3e62170b257dbf3ad20a55fb4d12de9d5c3e3dd6d144",
  "original_prompt": "Ingested from linux-6.6.14/drivers/dma/ti/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_TI_CPPI41) += cppi41.o\nobj-$(CONFIG_TI_EDMA) += edma.o\nobj-$(CONFIG_DMA_OMAP) += omap-dma.o\nobj-$(CONFIG_TI_K3_UDMA) += k3-udma.o\nobj-$(CONFIG_TI_K3_UDMA_GLUE_LAYER) += k3-udma-glue.o\nk3-psil-lib-objs := k3-psil.o \\\n\t\t    k3-psil-am654.o \\\n\t\t    k3-psil-j721e.o \\\n\t\t    k3-psil-j7200.o \\\n\t\t    k3-psil-am64.o \\\n\t\t    k3-psil-j721s2.o \\\n\t\t    k3-psil-am62.o \\\n\t\t    k3-psil-am62a.o \\\n\t\t    k3-psil-j784s4.o\nobj-$(CONFIG_TI_K3_PSIL) += k3-psil-lib.o\nobj-$(CONFIG_TI_DMA_CROSSBAR) += dma-crossbar.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}