{
  "module_name": "Makefile",
  "hash_id": "2ce8e04435d1e60128eb2a47fd456722650a07f04b36df0f4c1f3d6444014801",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/sunxi/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_SND_SUN4I_CODEC) += sun4i-codec.o\nobj-$(CONFIG_SND_SUN4I_I2S) += sun4i-i2s.o\nobj-$(CONFIG_SND_SUN4I_SPDIF) += sun4i-spdif.o\nobj-$(CONFIG_SND_SUN8I_CODEC_ANALOG) += sun8i-codec-analog.o\nobj-$(CONFIG_SND_SUN50I_CODEC_ANALOG) += sun50i-codec-analog.o\nobj-$(CONFIG_SND_SUN8I_CODEC) += sun8i-codec.o\nobj-$(CONFIG_SND_SUN8I_ADDA_PR_REGMAP) += sun8i-adda-pr-regmap.o\nobj-$(CONFIG_SND_SUN50I_DMIC) += sun50i-dmic.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}