{
  "module_name": "Makefile",
  "hash_id": "7f6b0c27e28d8ed0f1e35f3fe81245481498245e9fc718fc112e1e8985e32489",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/pci/cx18/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\ncx18-objs    := cx18-driver.o cx18-cards.o cx18-i2c.o cx18-firmware.o cx18-gpio.o \\\n\tcx18-queue.o cx18-streams.o cx18-fileops.o cx18-ioctl.o cx18-controls.o \\\n\tcx18-mailbox.o cx18-vbi.o cx18-audio.o cx18-video.o cx18-irq.o \\\n\tcx18-av-core.o cx18-av-audio.o cx18-av-firmware.o cx18-av-vbi.o cx18-scb.o \\\n\tcx18-dvb.o cx18-io.o\ncx18-alsa-objs := cx18-alsa-main.o cx18-alsa-pcm.o\n\nobj-$(CONFIG_VIDEO_CX18) += cx18.o\nobj-$(CONFIG_VIDEO_CX18_ALSA) += cx18-alsa.o\n\nccflags-y += -I $(srctree)/drivers/media/dvb-frontends\nccflags-y += -I $(srctree)/drivers/media/tuners\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}