{
  "module_name": "Makefile",
  "hash_id": "d2ca4341f4d52ee7355f945d93298d16a210fcff5fc2f34946c26c3a3e0cc44a",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/wangxun/ngbe/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Copyright (c) 2019 - 2022 Beijing WangXun Technology Co., Ltd.\n#\n# Makefile for the Wangxun(R) GbE PCI Express ethernet driver\n#\n\nobj-$(CONFIG_NGBE) += ngbe.o\n\nngbe-objs := ngbe_main.o ngbe_hw.o ngbe_mdio.o ngbe_ethtool.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}