#ifndef __MESON_DW_HDMI_H
#define __MESON_DW_HDMI_H
#define HDMITX_TOP_SW_RESET                     (0x000)
#define HDMITX_TOP_CLK_CNTL                     (0x001)
#define HDMITX_TOP_HPD_FILTER                   (0x002)
#define HDMITX_TOP_INTR_MASKN                   (0x003)
#define HDMITX_TOP_INTR_STAT                    (0x004)
#define HDMITX_TOP_INTR_STAT_CLR                (0x005)
#define HDMITX_TOP_INTR_CORE		BIT(0)
#define HDMITX_TOP_INTR_HPD_RISE	BIT(1)
#define HDMITX_TOP_INTR_HPD_FALL	BIT(2)
#define HDMITX_TOP_INTR_RXSENSE_RISE	BIT(6)
#define HDMITX_TOP_INTR_RXSENSE_FALL	BIT(7)
#define HDMITX_TOP_BIST_CNTL                    (0x006)
#define HDMITX_TOP_SHIFT_PTTN_012               (0x007)
#define HDMITX_TOP_SHIFT_PTTN_345               (0x008)
#define HDMITX_TOP_SHIFT_PTTN_67                (0x009)
#define HDMITX_TOP_TMDS_CLK_PTTN_01             (0x00A)
#define HDMITX_TOP_TMDS_CLK_PTTN_23             (0x00B)
#define HDMITX_TOP_TMDS_CLK_PTTN_CNTL           (0x00C)
#define HDMITX_TOP_REVOCMEM_STAT                (0x00D)
#define HDMITX_TOP_STAT0                        (0x00E)
#endif  
