{
  "module_name": "Makefile",
  "hash_id": "a7a0bd23bc5485df608ced9c20df05b11553469a8a21fffe19b634921e3867c2",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/fungible/funeth/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: (GPL-2.0-only OR BSD-3-Clause)\n\nccflags-y += -I$(srctree)/$(src)/../funcore -I$(srctree)/$(src)\n\nobj-$(CONFIG_FUN_ETH) += funeth.o\n\nfuneth-y := funeth_main.o funeth_rx.o funeth_tx.o funeth_devlink.o \\\n\t    funeth_ethtool.o\n\nfuneth-$(CONFIG_TLS_DEVICE) += funeth_ktls.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}