{
  "module_name": "Makefile",
  "hash_id": "7250e98de9d17825bdc82a4a86acf9d909c396121cda3cdb36f0718f83fc4675",
  "original_prompt": "Ingested from linux-6.6.14/drivers/ntb/hw/intel/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_NTB_INTEL) += ntb_hw_intel.o\nntb_hw_intel-y := ntb_hw_gen1.o ntb_hw_gen3.o ntb_hw_gen4.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}