{
  "module_name": "Makefile",
  "hash_id": "892ec651dc748c56f8b1f871ec62baa48a2660ce22911ee5d0cc6389acd9e34d",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/calxeda/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_NET_CALXEDA_XGMAC) += xgmac.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}