{
  "module_name": "Makefile",
  "hash_id": "285841d56c54638db511bff0f0bbc2958b1b0866674b54b99729f756887332ab",
  "original_prompt": "Ingested from linux-6.6.14/tools/power/x86/x86_energy_perf_policy/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nCC\t\t= $(CROSS_COMPILE)gcc\nBUILD_OUTPUT    := $(CURDIR)\nPREFIX\t\t:= /usr\nDESTDIR\t\t:=\n\nifeq (\"$(origin O)\", \"command line\")\n\tBUILD_OUTPUT := $(O)\nendif\n\nx86_energy_perf_policy : x86_energy_perf_policy.c\noverride CFLAGS +=\t-O2 -Wall -I../../../include\noverride CFLAGS +=\t-DMSRHEADER='\"../../../../arch/x86/include/asm/msr-index.h\"'\noverride CFLAGS +=\t-D_FORTIFY_SOURCE=2\n\n%: %.c\n\t@mkdir -p $(BUILD_OUTPUT)\n\t$(CC) $(CFLAGS) $< -o $(BUILD_OUTPUT)/$@ $(LDFLAGS)\n\n.PHONY : clean\nclean :\n\t@rm -f $(BUILD_OUTPUT)/x86_energy_perf_policy\n\ninstall : x86_energy_perf_policy\n\tinstall -d  $(DESTDIR)$(PREFIX)/bin\n\tinstall $(BUILD_OUTPUT)/x86_energy_perf_policy $(DESTDIR)$(PREFIX)/bin/x86_energy_perf_policy\n\tinstall -d  $(DESTDIR)$(PREFIX)/share/man/man8\n\tinstall -m 644 x86_energy_perf_policy.8 $(DESTDIR)$(PREFIX)/share/man/man8\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}