{
  "module_name": "Makefile",
  "hash_id": "59547b073072a41e91bfa4314e75e0c952c5a3f6419c386d9b838f3e2a39d6e7",
  "original_prompt": "Ingested from linux-6.6.14/drivers/reset/starfive/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_RESET_STARFIVE_JH71X0)\t\t+= reset-starfive-jh71x0.o\n\nobj-$(CONFIG_RESET_STARFIVE_JH7100)\t\t+= reset-starfive-jh7100.o\nobj-$(CONFIG_RESET_STARFIVE_JH7110)\t\t+= reset-starfive-jh7110.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}