#ifndef __LAN966X_IFH_H__
#define __LAN966X_IFH_H__
#define IFH_LEN                      7
#define IFH_LEN_BYTES                (IFH_LEN * sizeof(u32))
#define IFH_POS_TIMESTAMP            192
#define IFH_POS_BYPASS               191
#define IFH_POS_MASQ                 190
#define IFH_POS_MASQ_PORT            186
#define IFH_POS_LEN                  178
#define IFH_POS_WRDMODE              176
#define IFH_POS_RTAG48               175
#define IFH_POS_HAS_RED_TAG          174
#define IFH_POS_CUTTHRU              173
#define IFH_POS_REW_CMD              163
#define IFH_POS_REW_OAM              162
#define IFH_POS_PDU_TYPE             158
#define IFH_POS_FCS_UPD              157
#define IFH_POS_DSCP                 151
#define IFH_POS_DP                   150
#define IFH_POS_RTE_INB_UPDATE       149
#define IFH_POS_POP_CNT              147
#define IFH_POS_ETYPE_OFS            145
#define IFH_POS_SRCPORT              141
#define IFH_POS_SEQ_NUM              120
#define IFH_POS_TCI                  103
#define IFH_POS_QOS_CLASS            100
#define IFH_POS_CPUQ                 92
#define IFH_POS_LEARN_FLAGS          90
#define IFH_POS_SFLOW_ID             86
#define IFH_POS_ACL_HIT              85
#define IFH_POS_ACL_IDX              79
#define IFH_POS_ISDX                 71
#define IFH_POS_DSTS                 62
#define IFH_POS_FLOOD                60
#define IFH_POS_SEQ_OP               58
#define IFH_POS_IPV                  55
#define IFH_POS_AFI                  54
#define IFH_POS_AGED                 52
#define IFH_POS_RTP_ID               42
#define IFH_POS_RTP_SUBID            41
#define IFH_POS_PN_DATA_STATUS       33
#define IFH_POS_PN_TRANSF_STATUS_ZERO 32
#define IFH_POS_PN_CC                16
#define IFH_WID_TIMESTAMP            32
#define IFH_WID_BYPASS               1
#define IFH_WID_MASQ                 1
#define IFH_WID_MASQ_PORT            4
#define IFH_WID_LEN                  14
#define IFH_WID_WRDMODE              2
#define IFH_WID_RTAG48               1
#define IFH_WID_HAS_RED_TAG          1
#define IFH_WID_CUTTHRU              1
#define IFH_WID_REW_CMD              10
#define IFH_WID_REW_OAM              1
#define IFH_WID_PDU_TYPE             4
#define IFH_WID_FCS_UPD              1
#define IFH_WID_DSCP                 6
#define IFH_WID_DP                   1
#define IFH_WID_RTE_INB_UPDATE       1
#define IFH_WID_POP_CNT              2
#define IFH_WID_ETYPE_OFS            2
#define IFH_WID_SRCPORT              4
#define IFH_WID_SEQ_NUM              16
#define IFH_WID_TCI                  17
#define IFH_WID_QOS_CLASS            3
#define IFH_WID_CPUQ                 8
#define IFH_WID_LEARN_FLAGS          2
#define IFH_WID_SFLOW_ID             4
#define IFH_WID_ACL_HIT              1
#define IFH_WID_ACL_IDX              6
#define IFH_WID_ISDX                 8
#define IFH_WID_DSTS                 9
#define IFH_WID_FLOOD                2
#define IFH_WID_SEQ_OP               2
#define IFH_WID_IPV                  3
#define IFH_WID_AFI                  1
#define IFH_WID_AGED                 2
#define IFH_WID_RTP_ID               10
#define IFH_WID_RTP_SUBID            1
#define IFH_WID_PN_DATA_STATUS       8
#define IFH_WID_PN_TRANSF_STATUS_ZERO 1
#define IFH_WID_PN_CC                16
#endif  
