{
  "module_name": "Makefile",
  "hash_id": "6a965fe516b6c916608f4935b0a0986f68dfb2f30e329a485e7accfdde656f65",
  "original_prompt": "Ingested from linux-6.6.14/arch/x86/net/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Arch-specific network modules\n#\n\nifeq ($(CONFIG_X86_32),y)\n        obj-$(CONFIG_BPF_JIT) += bpf_jit_comp32.o\nelse\n        obj-$(CONFIG_BPF_JIT) += bpf_jit_comp.o\nendif\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}