{
  "module_name": "Makefile",
  "hash_id": "d499725a75869450cc4dbe3658a8acda3086f078563715eb354ac82ffab1cc8e",
  "original_prompt": "Ingested from linux-6.6.14/fs/debugfs/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\ndebugfs-objs\t:= inode.o file.o\n\nobj-$(CONFIG_DEBUG_FS)\t+= debugfs.o\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}