{
  "module_name": "Makefile",
  "hash_id": "0d1e8542a630a33d64759382812b019fcc00fd231b258bee51195af3b161ec73",
  "original_prompt": "Ingested from linux-6.6.14/drivers/misc/genwqe/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for GenWQE driver\n#\n\nobj-$(CONFIG_GENWQE) := genwqe_card.o\ngenwqe_card-objs := card_base.o card_dev.o card_ddcb.o card_sysfs.o \\\n\tcard_debugfs.o card_utils.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}