{
  "module_name": "Makefile",
  "hash_id": "e27b2f745a677c2d29060801353d6d6e0bf7ba359ce6c2e201c16362fbf5856d",
  "original_prompt": "Ingested from linux-6.6.14/drivers/pinctrl/stm32/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Core\nobj-$(CONFIG_PINCTRL_STM32) += pinctrl-stm32.o\n\n# SoC Drivers\nobj-$(CONFIG_PINCTRL_STM32F429)\t+= pinctrl-stm32f429.o\nobj-$(CONFIG_PINCTRL_STM32F469)\t+= pinctrl-stm32f469.o\nobj-$(CONFIG_PINCTRL_STM32F746)\t+= pinctrl-stm32f746.o\nobj-$(CONFIG_PINCTRL_STM32F769)\t+= pinctrl-stm32f769.o\nobj-$(CONFIG_PINCTRL_STM32H743)\t+= pinctrl-stm32h743.o\nobj-$(CONFIG_PINCTRL_STM32MP135) += pinctrl-stm32mp135.o\nobj-$(CONFIG_PINCTRL_STM32MP157) += pinctrl-stm32mp157.o\nobj-$(CONFIG_PINCTRL_STM32MP257) += pinctrl-stm32mp257.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}