{
  "module_name": "Makefile",
  "hash_id": "6d7861c9570ad0021bf49edb1426acb7e4a2769085c1d2a34cc49468102291b5",
  "original_prompt": "Ingested from linux-6.6.14/drivers/pmdomain/rockchip/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_ROCKCHIP_PM_DOMAINS)\t+= pm-domains.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}