{
  "module_name": "Makefile",
  "hash_id": "6592cfe159ad09140012d154624b6c46fc48db1f1505cbd3213b69b9f5a560da",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/atmel/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_ATMEL)             += atmel.o\nobj-$(CONFIG_PCI_ATMEL)         += atmel_pci.o \nobj-$(CONFIG_PCMCIA_ATMEL)      += atmel_cs.o\n\nobj-$(CONFIG_AT76C50X_USB)      += at76c50x-usb.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}