{
  "module_name": "Makefile",
  "hash_id": "365de0b7d4cfc566cf5b9942e78053393f922da1546474a15d916433fd5aedf9",
  "original_prompt": "Ingested from linux-6.6.14/drivers/firmware/smccc/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\nobj-$(CONFIG_HAVE_ARM_SMCCC_DISCOVERY)\t+= smccc.o kvm_guest.o\nobj-$(CONFIG_ARM_SMCCC_SOC_ID)\t+= soc_id.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}