{
  "module_name": "Makefile",
  "hash_id": "5e7bab43e1e10f018ebcdc02244aa35a37f55786813116231e8196368a6a4b99",
  "original_prompt": "Ingested from linux-6.6.14/drivers/nfc/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for nfc devices\n#\n\nobj-$(CONFIG_NFC_FDP)\t\t+= fdp/\nobj-$(CONFIG_NFC_PN544)\t\t+= pn544/\nobj-$(CONFIG_NFC_MICROREAD)\t+= microread/\nobj-$(CONFIG_NFC_PN533)\t\t+= pn533/\nobj-$(CONFIG_NFC_MEI_PHY)\t+= mei_phy.o\nobj-$(CONFIG_NFC_SIM)\t\t+= nfcsim.o\nobj-$(CONFIG_NFC_PORT100)\t+= port100.o\nobj-$(CONFIG_NFC_MRVL)\t\t+= nfcmrvl/\nobj-$(CONFIG_NFC_TRF7970A)\t+= trf7970a.o\nobj-$(CONFIG_NFC_ST21NFCA)  \t+= st21nfca/\nobj-$(CONFIG_NFC_ST_NCI)\t+= st-nci/\nobj-$(CONFIG_NFC_NXP_NCI)\t+= nxp-nci/\nobj-$(CONFIG_NFC_S3FWRN5)\t+= s3fwrn5/\nobj-$(CONFIG_NFC_ST95HF)\t+= st95hf/\nobj-$(CONFIG_NFC_VIRTUAL_NCI)\t+= virtual_ncidev.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}