{
  "module_name": "Makefile",
  "hash_id": "71c1ca5dc5094068faa23c6c3263f4e92c5f3187f01acc7ad4a7d5961bb54cfc",
  "original_prompt": "Ingested from linux-6.6.14/drivers/scsi/pm8001/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Kernel configuration file for the PM8001 SAS/SATA 8x6G based HBA driver\n#\n# Copyright (C) 2008-2009  USI Co., Ltd.\n\n\nobj-$(CONFIG_SCSI_PM8001) += pm80xx.o\n\nCFLAGS_pm80xx_tracepoints.o := -I$(src)\n\npm80xx-y += pm8001_init.o \\\n\t\tpm8001_sas.o  \\\n\t\tpm8001_ctl.o  \\\n\t\tpm8001_hwi.o  \\\n\t\tpm80xx_hwi.o  \\\n\t\tpm80xx_tracepoints.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}