{
  "module_name": "Makefile",
  "hash_id": "ef081a2c5dd30b751e01fea027df566fd5712468c4ca55599d521d538e1f3d1d",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/platform/cadence/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\nobj-$(CONFIG_VIDEO_CADENCE_CSI2RX)\t+= cdns-csi2rx.o\nobj-$(CONFIG_VIDEO_CADENCE_CSI2TX)\t+= cdns-csi2tx.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}