{
  "module_name": "Makefile",
  "hash_id": "b93e0fc4f75fe9d13048c1c330c849d44c9128b561eaf0c48d7ac654384406a3",
  "original_prompt": "Ingested from openssh-9.6p1/regress/unittests/bitmap/Makefile",
  "human_readable_source": "#\t$OpenBSD: Makefile,v 1.4 2017/12/21 00:41:22 djm Exp $\n\nPROG=test_bitmap\nSRCS=tests.c\n\n# From usr.sbin/ssh\nSRCS+=bitmap.c atomicio.c\n\nREGRESS_TARGETS=run-regress-${PROG}\n\nrun-regress-${PROG}: ${PROG}\n\tenv ${TEST_ENV} ./${PROG}\n\n.include <bsd.regress.mk>\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}