{
  "module_name": "Makefile",
  "hash_id": "02d92c0a306857004026ee6d9d805f705cb15131cd6a85f4fe6c562ee543b0fb",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/drivers/net/team/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for net selftests\n\nTEST_PROGS := dev_addr_lists.sh\n\nTEST_FILES := \\\n\tlag_lib.sh \\\n\tnet_forwarding_lib.sh\n\ninclude ../../../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}