{
  "module_name": "Makefile",
  "hash_id": "83bea8aa67d13257d9df052a97dc984fbf614bc60c2e87e34bdf6ca334269bb3",
  "original_prompt": "Ingested from linux-6.6.14/drivers/soc/rockchip/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Rockchip Soc drivers\n#\nobj-$(CONFIG_ROCKCHIP_GRF) += grf.o\nobj-$(CONFIG_ROCKCHIP_IODOMAIN) += io-domain.o\nobj-$(CONFIG_ROCKCHIP_DTPM) += dtpm.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}