{
  "module_name": "Makefile",
  "hash_id": "8a5ff43aee9f1d230a30a54634f294b6678932a1b3581ba97241dc2062a7f2f2",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/broadcom/brcm80211/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: ISC\n#\n# Makefile fragment for Broadcom 802.11 Networking Device Driver\n#\n# Copyright (c) 2010 Broadcom Corporation\n#\n\n# common flags\nsubdir-ccflags-$(CONFIG_BRCMDBG)\t+= -DDEBUG\n\nobj-$(CONFIG_BRCMUTIL)\t+= brcmutil/\nobj-$(CONFIG_BRCMFMAC)\t+= brcmfmac/\nobj-$(CONFIG_BRCMSMAC)\t+= brcmsmac/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}