{
  "module_name": "Makefile",
  "hash_id": "1597a04058a2c0609557fbc6eaea910668171589e911a21ef0faf527c64e0973",
  "original_prompt": "Ingested from openssh-9.6p1/regress/unittests/sshbuf/Makefile",
  "human_readable_source": "#\t$OpenBSD: Makefile,v 1.10 2021/01/09 12:24:31 dtucker Exp $\n\n#\t$OpenBSD: Makefile,v 1.8 2020/01/26 00:09:50 djm Exp $\n\nPROG=test_sshbuf\nSRCS=tests.c\nSRCS+=test_sshbuf.c\nSRCS+=test_sshbuf_getput_basic.c\nSRCS+=test_sshbuf_getput_crypto.c\nSRCS+=test_sshbuf_misc.c\nSRCS+=test_sshbuf_fuzz.c\nSRCS+=test_sshbuf_getput_fuzz.c\nSRCS+=test_sshbuf_fixed.c\n\n# From usr.bin/ssh\nSRCS+=sshbuf-getput-basic.c sshbuf-getput-crypto.c sshbuf-misc.c sshbuf.c\nSRCS+=sshbuf-io.c atomicio.c misc.c xmalloc.c log.c fatal.c ssherr.c cleanup.c\nSRCS+=match.c addr.c addrmatch.c\n\nrun-regress-${PROG}: ${PROG}\n\tenv ${TEST_ENV} ./${PROG} ${UNITTEST_ARGS}\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}