#ifndef __DAL_TYPES_H__
#define __DAL_TYPES_H__
#include "signal_types.h"
#include "dc_types.h"
struct dal_logger;
struct dc_bios;
enum dce_version {
	DCE_VERSION_UNKNOWN = (-1),
	DCE_VERSION_6_0,
	DCE_VERSION_6_1,
	DCE_VERSION_6_4,
	DCE_VERSION_8_0,
	DCE_VERSION_8_1,
	DCE_VERSION_8_3,
	DCE_VERSION_10_0,
	DCE_VERSION_11_0,
	DCE_VERSION_11_2,
	DCE_VERSION_11_22,
	DCE_VERSION_12_0,
	DCE_VERSION_12_1,
	DCE_VERSION_MAX,
	DCN_VERSION_1_0,
	DCN_VERSION_1_01,
	DCN_VERSION_2_0,
	DCN_VERSION_2_01,
	DCN_VERSION_2_1,
	DCN_VERSION_3_0,
	DCN_VERSION_3_01,
	DCN_VERSION_3_02,
	DCN_VERSION_3_03,
	DCN_VERSION_3_1,
	DCN_VERSION_3_14,
	DCN_VERSION_3_15,
	DCN_VERSION_3_16,
	DCN_VERSION_3_2,
	DCN_VERSION_3_21,
	DCN_VERSION_MAX
};
#endif  
