{
  "module_name": "Makefile",
  "hash_id": "58baa71a7cf7657bdadc05fd7173e4b1208d1db065000b9a930286db8fda891c",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/mediatek/mt8195/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\n# platform driver\nsnd-soc-mt8195-afe-objs := \\\n\tmt8195-audsys-clk.o \\\n\tmt8195-afe-clk.o \\\n\tmt8195-afe-pcm.o \\\n\tmt8195-dai-adda.o \\\n\tmt8195-dai-etdm.o \\\n\tmt8195-dai-pcm.o\n\nobj-$(CONFIG_SND_SOC_MT8195) += snd-soc-mt8195-afe.o\n\n# machine driver\nobj-$(CONFIG_SND_SOC_MT8195_MT6359) += mt8195-mt6359.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}