{
  "module_name": "Makefile",
  "hash_id": "852e6ae45bd86f71c1fc5ca54306689ae7dfb2f82de154e17452949f5f872ec7",
  "original_prompt": "Ingested from linux-6.6.14/drivers/idle/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_INTEL_IDLE)\t\t\t+= intel_idle.o\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}