{
  "module_name": "Makefile",
  "hash_id": "6f2cd1c7b14e396accc5dceabca9ae7b854c5f7aa5196deaa667791195263370",
  "original_prompt": "Ingested from linux-6.6.14/sound/i2c/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for ALSA\n# Copyright (c) 2001 by Jaroslav Kysela <perex@perex.cz>\n#\n\nsnd-i2c-objs := i2c.o\nsnd-cs8427-objs := cs8427.o\nsnd-tea6330t-objs := tea6330t.o\n\nobj-$(CONFIG_SND) += other/\n\n# Toplevel Module Dependency\nobj-$(CONFIG_SND_INTERWAVE_STB) += snd-tea6330t.o snd-i2c.o\nobj-$(CONFIG_SND_ICE1712) += snd-cs8427.o snd-i2c.o\nobj-$(CONFIG_SND_ICE1724) += snd-i2c.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}