{
  "module_name": "Makefile",
  "hash_id": "b5714e977a374470511c278401bb05c96b07c41a4002c0075848e14fdaf764ea",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/platform/nxp/imx8-isi/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n\nimx8-isi-y := imx8-isi-core.o imx8-isi-crossbar.o imx8-isi-gasket.o \\\n\timx8-isi-hw.o imx8-isi-pipe.o imx8-isi-video.o\nimx8-isi-$(CONFIG_DEBUG_FS) += imx8-isi-debug.o\nimx8-isi-$(CONFIG_VIDEO_IMX8_ISI_M2M) += imx8-isi-m2m.o\n\nobj-$(CONFIG_VIDEO_IMX8_ISI) += imx8-isi.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}