{
  "module_name": "Makefile",
  "hash_id": "f119c11572829b8e62591e8b85781657ddf9e985d97cbc230b570a760393b774",
  "original_prompt": "Ingested from linux-6.6.14/drivers/pmdomain/samsung/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_EXYNOS_PM_DOMAINS)\t\t+= exynos-pm-domains.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}