{
  "module_name": "Makefile",
  "hash_id": "8288921d4d2f25a8e59f0887e8ed4d2d16c19a042b37c42f23ac3ecbe2c4f680",
  "original_prompt": "Ingested from linux-6.6.14/drivers/vfio/fsl-mc/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: (GPL-2.0+ OR BSD-3-Clause)\n\nvfio-fsl-mc-y := vfio_fsl_mc.o vfio_fsl_mc_intr.o\nobj-$(CONFIG_VFIO_FSL_MC) += vfio-fsl-mc.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}