{
  "module_name": "Makefile",
  "hash_id": "3dbfed4ee7eff3a0a1a58f6a0518499253d2b969fcb7707720a56daae0405623",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/pcs/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for Linux PCS drivers\n\npcs_xpcs-$(CONFIG_PCS_XPCS)\t:= pcs-xpcs.o pcs-xpcs-nxp.o pcs-xpcs-wx.o\n\nobj-$(CONFIG_PCS_XPCS)\t\t+= pcs_xpcs.o\nobj-$(CONFIG_PCS_LYNX)\t\t+= pcs-lynx.o\nobj-$(CONFIG_PCS_MTK_LYNXI)\t+= pcs-mtk-lynxi.o\nobj-$(CONFIG_PCS_RZN1_MIIC)\t+= pcs-rzn1-miic.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}