{
  "module_name": "Makefile",
  "hash_id": "b6d812f50ba27f4be65c9d08dc9b10bd2fd536a509250d21efc50cbeba4675a5",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/platform/samsung/exynos-gsc/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nexynos-gsc-objs := gsc-core.o gsc-m2m.o gsc-regs.o\n\nobj-$(CONFIG_VIDEO_SAMSUNG_EXYNOS_GSC)\t+= exynos-gsc.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}