{
  "module_name": "Makefile",
  "hash_id": "1573dfc95374ffbcc3646a9c3068bc32e459ce47cd8aa14293470efacf07de01",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/qcom/qdsp6/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nsnd-q6dsp-common-objs := q6dsp-common.o q6dsp-lpass-ports.o q6dsp-lpass-clocks.o\nsnd-q6apm-objs := q6apm.o audioreach.o topology.o\n\nobj-$(CONFIG_SND_SOC_QDSP6_COMMON) += snd-q6dsp-common.o\nobj-$(CONFIG_SND_SOC_QDSP6_CORE) += q6core.o\nobj-$(CONFIG_SND_SOC_QDSP6_AFE) += q6afe.o\nobj-$(CONFIG_SND_SOC_QDSP6_AFE_DAI) += q6afe-dai.o\nobj-$(CONFIG_SND_SOC_QDSP6_AFE_CLOCKS) += q6afe-clocks.o\nobj-$(CONFIG_SND_SOC_QDSP6_ADM) += q6adm.o\nobj-$(CONFIG_SND_SOC_QDSP6_ROUTING) += q6routing.o\nobj-$(CONFIG_SND_SOC_QDSP6_ASM) += q6asm.o\nobj-$(CONFIG_SND_SOC_QDSP6_ASM_DAI) += q6asm-dai.o\n\nobj-$(CONFIG_SND_SOC_QDSP6_APM) += snd-q6apm.o\nobj-$(CONFIG_SND_SOC_QDSP6_APM_DAI) += q6apm-dai.o\nobj-$(CONFIG_SND_SOC_QDSP6_APM_LPASS_DAI) += q6apm-lpass-dais.o\nobj-$(CONFIG_SND_SOC_QDSP6_PRM) += q6prm.o\nobj-$(CONFIG_SND_SOC_QDSP6_PRM_LPASS_CLOCKS) += q6prm-clocks.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}