#ifndef _DT_BINDINGS_PHY_QMP
#define _DT_BINDINGS_PHY_QMP
#define QMP_USB43DP_USB3_PIPE_CLK	0
#define QMP_USB43DP_DP_LINK_CLK		1
#define QMP_USB43DP_DP_VCO_DIV_CLK	2
#define QMP_USB43DP_USB3_PHY		0
#define QMP_USB43DP_DP_PHY		1
#endif  
