{
  "module_name": "Makefile",
  "hash_id": "ae925ae7d5202efb01809d0f86c30c32e6dda07104164296a41ecd101e136f22",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/damon/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for damon selftests\n\nTEST_GEN_FILES += huge_count_read_write\n\nTEST_FILES = _chk_dependency.sh _debugfs_common.sh\nTEST_PROGS = debugfs_attrs.sh debugfs_schemes.sh debugfs_target_ids.sh\nTEST_PROGS += debugfs_empty_targets.sh debugfs_huge_count_read_write.sh\nTEST_PROGS += debugfs_duplicate_context_creation.sh\nTEST_PROGS += debugfs_rm_non_contexts.sh\nTEST_PROGS += sysfs.sh sysfs_update_removed_scheme_dir.sh\nTEST_PROGS += reclaim.sh lru_sort.sh\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}