{
  "module_name": "Makefile",
  "hash_id": "1c33d2d18883c39f721f4dd4f618a1adf063b2a9ec768a3238acb51955b8eec3",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/seccomp/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nCFLAGS += -Wl,-no-as-needed -Wall $(KHDR_INCLUDES)\nLDFLAGS += -lpthread\nLDLIBS += -lcap\n\nTEST_GEN_PROGS := seccomp_bpf seccomp_benchmark\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}