try:
    exec
except NameError:
    print("SKIP")
    raise SystemExit
def test_syntax(code):
    try:
        exec(code)
        print("no SyntaxError")
    except IndentationError:
        print("IndentationError")
    except SyntaxError:
        print("SyntaxError")
test_syntax("a \\a\n")
test_syntax("def f():\n  a\n a\n")
test_syntax("'abc")
test_syntax("!")
test_syntax("$")
test_syntax("`")
test_syntax(" a\n")
test_syntax("123z")
test_syntax('1 or 2 or')
test_syntax('{1:')
test_syntax("1 = 2")
test_syntax("'' = 1")
test_syntax("{} = 1")
test_syntax("(i for i in a) = 1")
test_syntax("f() = 1")
test_syntax("f**2 = 1")
test_syntax("f[0]**2 = 1")
test_syntax("x = *x")
test_syntax("*a, *b = c")
test_syntax("a, b += c")
test_syntax("(a, b) += c")
test_syntax("[a, b] += c")
test_syntax("def f(a=1, b): pass")
test_syntax("del f()")
test_syntax("del f[0]**2")
test_syntax("del (a for a in a)")
test_syntax("break")
test_syntax("continue")
test_syntax("yield")
test_syntax("nonlocal a")
test_syntax("await 1")
test_syntax("try:\n a\nexcept:\n pass\nexcept:\n pass")
test_syntax("f(1=2)")
test_syntax("f(a=1, 2)")
test_syntax("{1:2, 3}")
test_syntax("{1, 2:3}")
test_syntax("'abc' b'def'")
test_syntax("def f(a, a): pass")
test_syntax("def f():\n def g():\n  nonlocal a")
test_syntax('def f(x):\n global x')
test_syntax('def f(x):\n nonlocal x')
test_syntax('def f():\n nonlocal x\n global x')
test_syntax('def f(x, *a, *):\n pass')
test_syntax('lambda x, *a, *: 1')
test_syntax('def f(x, *a, **kw, r):\n pass')
test_syntax('lambda x, *a, **kw, r: 1')
