{
  "module_name": "Makefile",
  "hash_id": "84c335ec3e77712886287ea4e6655f7e7dd16192fa9a3ebef26c66f97e89806b",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/xen-netback/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_XEN_NETDEV_BACKEND) := xen-netback.o\n\nxen-netback-y := netback.o xenbus.o interface.o hash.o rx.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}