{
  "module_name": "Makefile",
  "hash_id": "a5579e616b8e6bbfeb5fcd62f77ee2dc3f0e6ea6d1e749357930b4038b97d1db",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/nci/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nCFLAGS += -Wl,-no-as-needed -Wall\nLDFLAGS += -lpthread\n\nTEST_GEN_PROGS := nci_dev\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}