{
  "module_name": "Makefile",
  "hash_id": "0d96378a21ec1418b738b81745107dafccde31f37b4112687e25806bf7bbfaed",
  "original_prompt": "Ingested from linux-6.6.14/kernel/kcsan/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nKCSAN_SANITIZE := n\nKCOV_INSTRUMENT := n\nUBSAN_SANITIZE := n\n\nCFLAGS_REMOVE_core.o = $(CC_FLAGS_FTRACE)\nCFLAGS_REMOVE_debugfs.o = $(CC_FLAGS_FTRACE)\nCFLAGS_REMOVE_report.o = $(CC_FLAGS_FTRACE)\n\nCFLAGS_core.o := $(call cc-option,-fno-conserve-stack) \\\n\t$(call cc-option,-mno-outline-atomics) \\\n\t-fno-stack-protector -DDISABLE_BRANCH_PROFILING\n\nobj-y := core.o debugfs.o report.o\n\nKCSAN_INSTRUMENT_BARRIERS_selftest.o := y\nobj-$(CONFIG_KCSAN_SELFTEST) += selftest.o\n\nCFLAGS_kcsan_test.o := $(CFLAGS_KCSAN) -fno-omit-frame-pointer\nCFLAGS_kcsan_test.o += $(DISABLE_STRUCTLEAK_PLUGIN)\nobj-$(CONFIG_KCSAN_KUNIT_TEST) += kcsan_test.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}