{
  "module_name": "Makefile",
  "hash_id": "58026f9e08b0a0f68d3802683c22f731170db5dedd70ced055e169c071360f7b",
  "original_prompt": "Ingested from linux-6.6.14/drivers/pmdomain/ti/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_ARCH_OMAP2PLUS)\t\t+= omap_prm.o\nobj-$(CONFIG_TI_SCI_PM_DOMAINS)\t\t+= ti_sci_pm_domains.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}