{
  "module_name": "Makefile",
  "hash_id": "d0f50d8568ac3cab6e40ddf6615dad51b312c5e432fe231a0f95aee8fecd194d",
  "original_prompt": "Ingested from openssh-9.6p1/regress/unittests/Makefile",
  "human_readable_source": "#\t$OpenBSD: Makefile,v 1.13 2023/09/24 08:14:13 claudio Exp $\n\nSUBDIR=\ttest_helper sshbuf sshkey bitmap kex hostkeys utf8 match conversion\nSUBDIR+=authopt misc sshsig\n\n.include <bsd.subdir.mk>\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}