{
  "module_name": "Makefile",
  "hash_id": "d95154ef26631a0afd0af0a21ef61dd3cbd501cb14dfaaf76e0b3cd1e0e97f18",
  "original_prompt": "Ingested from linux-6.6.14/drivers/crypto/intel/qat/qat_c3xxxvf/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nccflags-y := -I $(srctree)/$(src)/../qat_common\nobj-$(CONFIG_CRYPTO_DEV_QAT_C3XXXVF) += qat_c3xxxvf.o\nqat_c3xxxvf-objs := adf_drv.o adf_c3xxxvf_hw_data.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}