{
  "module_name": "Makefile",
  "hash_id": "0b49ddf0aeca9f297061e37a04714f3a4e27b93444e0e4168faa4b6bfe1a952e",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/natsemi/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the National Semiconductor Sonic devices.\n#\n\nobj-$(CONFIG_MACSONIC) += macsonic.o\nobj-$(CONFIG_MIPS_JAZZ_SONIC) += jazzsonic.o\nobj-$(CONFIG_NATSEMI) += natsemi.o\nobj-$(CONFIG_NS83820) += ns83820.o\nobj-$(CONFIG_XTENSA_XT2000_SONIC) += xtsonic.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}