{
  "module_name": "Makefile",
  "hash_id": "49335fb444e5ec3942b5ceb75311b03721104b2b9f4f709837610d4347539b62",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/mediatek/mt8192/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\n# platform driver\nsnd-soc-mt8192-afe-objs := \\\n\tmt8192-afe-pcm.o \\\n\tmt8192-afe-clk.o \\\n\tmt8192-afe-gpio.o \\\n\tmt8192-dai-adda.o \\\n\tmt8192-afe-control.o \\\n\tmt8192-dai-i2s.o \\\n\tmt8192-dai-pcm.o \\\n\tmt8192-dai-tdm.o\n\nobj-$(CONFIG_SND_SOC_MT8192) += snd-soc-mt8192-afe.o\nobj-$(CONFIG_SND_SOC_MT8192_MT6359_RT1015_RT5682) += \\\n\tmt8192-mt6359-rt1015-rt5682.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}