{
  "module_name": "Makefile",
  "hash_id": "d6b0a873b6365e268d0446601e09fff82fa7e8be7fa4fa6104cf9f1ef9234611",
  "original_prompt": "Ingested from linux-6.6.14/drivers/scsi/fcoe/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_FCOE) += fcoe.o\nobj-$(CONFIG_LIBFCOE) += libfcoe.o\n\nlibfcoe-objs := fcoe_ctlr.o fcoe_transport.o fcoe_sysfs.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}