{
  "module_name": "Makefile",
  "hash_id": "2ce600cc128407eca99a7da780fcb3e53d215274512e58c7dac233906b856ba2",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/pstore/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for pstore selftests.\n# Expects pstore backend is registered.\n\nall:\n\nTEST_PROGS := pstore_tests pstore_post_reboot_tests\nTEST_FILES := common_tests pstore_crash_test\nEXTRA_CLEAN := logs/* *uuid\n\ninclude ../lib.mk\n\nrun_crash:\n\t@sh pstore_crash_test || { echo \"pstore_crash_test: [FAIL]\"; exit 1; }\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}