{
  "module_name": "Makefile",
  "hash_id": "e9ee4aeebdcf6ed8d96737aae0e02d25727acbe76ba0df691152706f7c39c3fa",
  "original_prompt": "Ingested from linux-6.6.14/drivers/thermal/intel/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for various Intel thermal drivers.\n\nobj-$(CONFIG_INTEL_TCC)\t+= intel_tcc.o\nobj-$(CONFIG_INTEL_POWERCLAMP)\t+= intel_powerclamp.o\nobj-$(CONFIG_X86_PKG_TEMP_THERMAL)\t+= x86_pkg_temp_thermal.o\nobj-$(CONFIG_INTEL_SOC_DTS_IOSF_CORE)\t+= intel_soc_dts_iosf.o\nobj-$(CONFIG_INTEL_SOC_DTS_THERMAL)\t+= intel_soc_dts_thermal.o\nobj-$(CONFIG_INTEL_QUARK_DTS_THERMAL)\t+= intel_quark_dts_thermal.o\nobj-$(CONFIG_INT340X_THERMAL)  += int340x_thermal/\nobj-$(CONFIG_INTEL_BXT_PMIC_THERMAL) += intel_bxt_pmic_thermal.o\nobj-$(CONFIG_INTEL_PCH_THERMAL)\t+= intel_pch_thermal.o\nobj-$(CONFIG_INTEL_TCC_COOLING)\t+= intel_tcc_cooling.o\nobj-$(CONFIG_X86_THERMAL_VECTOR) += therm_throt.o\nobj-$(CONFIG_INTEL_HFI_THERMAL) += intel_hfi.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}