{
  "module_name": "Makefile",
  "hash_id": "806e85d9bc92215c57e2bb7379c8ad07515c910fa684bbb23bd3c4f852e40868",
  "original_prompt": "Ingested from linux-6.6.14/drivers/video/fbdev/omap2/omapfb/displays/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_FB_OMAP2_ENCODER_OPA362) += encoder-opa362.o\nobj-$(CONFIG_FB_OMAP2_ENCODER_TFP410) += encoder-tfp410.o\nobj-$(CONFIG_FB_OMAP2_ENCODER_TPD12S015) += encoder-tpd12s015.o\nobj-$(CONFIG_FB_OMAP2_CONNECTOR_DVI) += connector-dvi.o\nobj-$(CONFIG_FB_OMAP2_CONNECTOR_HDMI) += connector-hdmi.o\nobj-$(CONFIG_FB_OMAP2_CONNECTOR_ANALOG_TV) += connector-analog-tv.o\nobj-$(CONFIG_FB_OMAP2_PANEL_DPI) += panel-dpi.o\nobj-$(CONFIG_FB_OMAP2_PANEL_DSI_CM) += panel-dsi-cm.o\nobj-$(CONFIG_FB_OMAP2_PANEL_SONY_ACX565AKM) += panel-sony-acx565akm.o\nobj-$(CONFIG_FB_OMAP2_PANEL_LGPHILIPS_LB035Q02) += panel-lgphilips-lb035q02.o\nobj-$(CONFIG_FB_OMAP2_PANEL_SHARP_LS037V7DW01) += panel-sharp-ls037v7dw01.o\nobj-$(CONFIG_FB_OMAP2_PANEL_TPO_TD028TTEC1) += panel-tpo-td028ttec1.o\nobj-$(CONFIG_FB_OMAP2_PANEL_TPO_TD043MTEA1) += panel-tpo-td043mtea1.o\nobj-$(CONFIG_FB_OMAP2_PANEL_NEC_NL8048HL11) += panel-nec-nl8048hl11.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}