 
 

#ifndef _DT_BINDINGS_CLK_QCOM_LPASSCC_SC8280XP_H
#define _DT_BINDINGS_CLK_QCOM_LPASSCC_SC8280XP_H

 
#define LPASS_AUDIO_SWR_RX_CGCR				0
#define LPASS_AUDIO_SWR_WSA_CGCR			1
#define LPASS_AUDIO_SWR_WSA2_CGCR			2

 
#define LPASS_AUDIO_SWR_TX_CGCR				0

#endif
