{
  "module_name": "Makefile",
  "hash_id": "a24eec3cb1a0befbf1dd6ea3b7e1d9a328e54da7162d36ca411e217d9591bba1",
  "original_prompt": "Ingested from linux-6.6.14/sound/sparc/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for ALSA\n# Copyright (c) 2002 by David S. Miller <davem@redhat.com>\n#\n\nsnd-sun-amd7930-objs := amd7930.o\nsnd-sun-cs4231-objs := cs4231.o\nsnd-sun-dbri-objs := dbri.o\n\nobj-$(CONFIG_SND_SUN_AMD7930) += snd-sun-amd7930.o\nobj-$(CONFIG_SND_SUN_CS4231) += snd-sun-cs4231.o\nobj-$(CONFIG_SND_SUN_DBRI) += snd-sun-dbri.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}