{
  "module_name": "Makefile",
  "hash_id": "7217851ab22579d2d44508c5e8886bfa537f0863f2021e546d8e716254c8cb00",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/platform/rockchip/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-y += rga/\nobj-y += rkisp1/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}