{
  "module_name": "Makefile",
  "hash_id": "cf7cad79d83be6f5f808acd2326d417e2dec4ff7d5990a10347d0caed407e509",
  "original_prompt": "Ingested from linux-6.6.14/tools/leds/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for LEDs tools\n\nCFLAGS = -Wall -Wextra -g -I../../include/uapi\n\nall: uledmon led_hw_brightness_mon\n%: %.c\n\t$(CC) $(CFLAGS) -o $@ $^\n\nclean:\n\t$(RM) uledmon led_hw_brightness_mon\n\n.PHONY: all clean\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}