{
  "module_name": "Makefile",
  "hash_id": "cf538976e7b3343d3d986c84166060ab69bac9943099488fc543d28a9f74512d",
  "original_prompt": "Ingested from linux-6.6.14/drivers/vdpa/pds/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n# Copyright(c) 2023 Advanced Micro Devices, Inc\n\nobj-$(CONFIG_PDS_VDPA) := pds_vdpa.o\n\npds_vdpa-y := aux_drv.o \\\n\t      cmds.o \\\n\t      debugfs.o \\\n\t      vdpa_dev.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}