#ifndef _COMEDI_DRIVERS_NI_ROUTING_NI_DEVICE_ROUTES_EXTERN_H
#define _COMEDI_DRIVERS_NI_ROUTING_NI_DEVICE_ROUTES_EXTERN_H
#include "../ni_device_routes.h"
extern struct ni_device_routes ni_pxi_6030e_device_routes;
extern struct ni_device_routes ni_pci_6070e_device_routes;
extern struct ni_device_routes ni_pci_6220_device_routes;
extern struct ni_device_routes ni_pci_6221_device_routes;
extern struct ni_device_routes ni_pxi_6224_device_routes;
extern struct ni_device_routes ni_pxi_6225_device_routes;
extern struct ni_device_routes ni_pci_6229_device_routes;
extern struct ni_device_routes ni_pci_6251_device_routes;
extern struct ni_device_routes ni_pxi_6251_device_routes;
extern struct ni_device_routes ni_pxie_6251_device_routes;
extern struct ni_device_routes ni_pci_6254_device_routes;
extern struct ni_device_routes ni_pci_6259_device_routes;
extern struct ni_device_routes ni_pci_6534_device_routes;
extern struct ni_device_routes ni_pxie_6535_device_routes;
extern struct ni_device_routes ni_pci_6602_device_routes;
extern struct ni_device_routes ni_pci_6713_device_routes;
extern struct ni_device_routes ni_pci_6723_device_routes;
extern struct ni_device_routes ni_pci_6733_device_routes;
extern struct ni_device_routes ni_pxi_6733_device_routes;
extern struct ni_device_routes ni_pxie_6738_device_routes;
#endif  
