{
  "module_name": "Makefile",
  "hash_id": "5a0b3e730f2596717380374d4124d91c6a10b093d0f0d787ce44ff36702ffaab",
  "original_prompt": "Ingested from linux-6.6.14/net/bpf/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_BPF_SYSCALL)\t:= test_run.o\nifeq ($(CONFIG_BPF_JIT),y)\nobj-$(CONFIG_BPF_SYSCALL)\t+= bpf_dummy_struct_ops.o\nendif\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}