{
  "module_name": "Makefile",
  "hash_id": "8bdd8023680a60c1122d414206d1be9b194275905dbea59adc4b5beeb0e12964",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/usb/cx231xx/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\ncx231xx-y += cx231xx-video.o cx231xx-i2c.o cx231xx-cards.o cx231xx-core.o\ncx231xx-y += cx231xx-avcore.o cx231xx-417.o cx231xx-pcb-cfg.o cx231xx-vbi.o\ncx231xx-$(CONFIG_VIDEO_CX231XX_RC) += cx231xx-input.o\n\ncx231xx-alsa-objs := cx231xx-audio.o\n\nobj-$(CONFIG_VIDEO_CX231XX) += cx231xx.o\nobj-$(CONFIG_VIDEO_CX231XX_ALSA) += cx231xx-alsa.o\nobj-$(CONFIG_VIDEO_CX231XX_DVB) += cx231xx-dvb.o\n\nccflags-y += -I $(srctree)/drivers/media/tuners\nccflags-y += -I $(srctree)/drivers/media/dvb-frontends\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}