{
  "module_name": "Makefile",
  "hash_id": "a084334b85b3cea2b92d5d5df7d5ab299a9ee31d7074797a25581f31638c0520",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/pci/dm1105/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_DVB_DM1105) += dm1105.o\n\nccflags-y += -I $(srctree)/drivers/media/dvb-frontends\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}