{
  "module_name": "Makefile",
  "hash_id": "ee76db5d28d1b4cf315270ca23fbbe3a46a37041b57fccb27e20adb211d6ebbe",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/moxa/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the MOXART network device drivers.\n#\n\nobj-$(CONFIG_ARM_MOXART_ETHER) += moxart_ether.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}