{
  "module_name": "Makefile",
  "hash_id": "c8c1e1782967b59fc9c2a25ea0d7f4c56546f4c7c671133473ddbab4a0e3ad19",
  "original_prompt": "Ingested from linux-6.6.14/drivers/crypto/intel/ixp4xx/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_CRYPTO_DEV_IXP4XX) += ixp4xx_crypto.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}