{
  "module_name": "Makefile",
  "hash_id": "2615de6a1d25af76f0a6e90ec0574b81f7043a4ddf7dbb407b73029c7d7f68f4",
  "original_prompt": "Ingested from linux-6.6.14/drivers/platform/x86/hp/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for linux/drivers/platform/x86/hp\n# HP x86 Platform-Specific Drivers\n#\n\n# Hewlett Packard\nobj-$(CONFIG_HP_ACCEL)\t\t+= hp_accel.o\nobj-$(CONFIG_HP_WMI)\t\t+= hp-wmi.o\nobj-$(CONFIG_TC1100_WMI)\t+= tc1100-wmi.o\nobj-$(CONFIG_HP_BIOSCFG)\t+= hp-bioscfg/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}