{
  "module_name": "Makefile",
  "hash_id": "488cdcefa2673eb417481e26f99d2fe851de8ca1b2aec38adf1247ae803d01ce",
  "original_prompt": "Ingested from linux-6.6.14/drivers/soc/fsl/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the Linux Kernel SOC fsl specific device drivers\n#\n\nobj-$(CONFIG_FSL_DPAA)                 += qbman/\nobj-$(CONFIG_QUICC_ENGINE)\t\t+= qe/\nobj-$(CONFIG_CPM)\t\t\t+= qe/\nobj-$(CONFIG_FSL_RCPM)\t\t\t+= rcpm.o\nobj-$(CONFIG_FSL_GUTS)\t\t\t+= guts.o\nobj-$(CONFIG_FSL_MC_DPIO) \t\t+= dpio/\nobj-$(CONFIG_DPAA2_CONSOLE)\t\t+= dpaa2-console.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}