{
  "module_name": "Makefile",
  "hash_id": "d96024138c4c983ff959422f9705817af67bd2eb5c13926ea3b8aa5d6bcae781",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/platform/sunxi/sun4i-csi/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\nsun4i-csi-y += sun4i_csi.o\nsun4i-csi-y += sun4i_dma.o\nsun4i-csi-y += sun4i_v4l2.o\n\nobj-$(CONFIG_VIDEO_SUN4I_CSI)\t+= sun4i-csi.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}