{
  "module_name": "Makefile",
  "hash_id": "ccb7d63cdc234dd88ebcdf9bc6f4cbbbc488b60f44706c89942754e7f6b4ef68",
  "original_prompt": "Ingested from linux-6.6.14/drivers/infiniband/sw/siw/Makefile",
  "human_readable_source": "obj-$(CONFIG_RDMA_SIW) += siw.o\n\nsiw-y := \\\n\tsiw_cm.o \\\n\tsiw_cq.o \\\n\tsiw_main.o \\\n\tsiw_mem.o \\\n\tsiw_qp.o \\\n\tsiw_qp_tx.o \\\n\tsiw_qp_rx.o \\\n\tsiw_verbs.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}