{
  "module_name": "Makefile",
  "hash_id": "8ef81791a77988d371842869b3d7695b4263eb89cea357e7ee617663512473eb",
  "original_prompt": "Ingested from linux-6.6.14/drivers/crypto/gemini/Makefile",
  "human_readable_source": "obj-$(CONFIG_CRYPTO_DEV_SL3516) += sl3516-ce.o\nsl3516-ce-y += sl3516-ce-core.o sl3516-ce-cipher.o sl3516-ce-rng.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}