{
  "module_name": "Makefile",
  "hash_id": "32e83f355584c49906885a0b6bf195263da4ff373e37b3513a3e1f1a8d99c5e2",
  "original_prompt": "Ingested from linux-6.6.14/security/lockdown/Makefile",
  "human_readable_source": "obj-$(CONFIG_SECURITY_LOCKDOWN_LSM) += lockdown.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}