{
  "module_name": "Makefile",
  "hash_id": "c1ea4b2edab302c795924fc8373d035972c8fe0192a31ed67810c0c839d952f6",
  "original_prompt": "Ingested from linux-6.6.14/tools/bootconfig/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for bootconfig command\ninclude ../scripts/Makefile.include\n\nbindir ?= /usr/bin\n\nifeq ($(srctree),)\nsrctree := $(patsubst %/,%,$(dir $(CURDIR)))\nsrctree := $(patsubst %/,%,$(dir $(srctree)))\nendif\n\nLIBSRC = $(srctree)/lib/bootconfig.c $(srctree)/include/linux/bootconfig.h\nCFLAGS = -Wall -g -I$(CURDIR)/include\n\nALL_TARGETS := bootconfig\nALL_PROGRAMS := $(patsubst %,$(OUTPUT)%,$(ALL_TARGETS))\n\nall: $(ALL_PROGRAMS) test\n\n$(OUTPUT)bootconfig: main.c include/linux/bootconfig.h $(LIBSRC)\n\t$(CC) $(filter %.c,$^) $(CFLAGS) -o $@\n\ntest: $(ALL_PROGRAMS) test-bootconfig.sh\n\t./test-bootconfig.sh $(OUTPUT)\n\ninstall: $(ALL_PROGRAMS)\n\tinstall $(OUTPUT)bootconfig $(DESTDIR)$(bindir)\n\nclean:\n\t$(RM) -f $(OUTPUT)*.o $(ALL_PROGRAMS)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}