 

#ifndef __IRQSRCS_DCN_1_0_H__
#define __IRQSRCS_DCN_1_0_H__


#define DCN_1_0__SRCID__DC_I2C_SW_DONE	            1	
#define DCN_1_0__CTXID__DC_I2C_SW_DONE	            0

#define DCN_1_0__SRCID__DC_I2C_DDC1_HW_DONE	        1	
#define DCN_1_0__CTXID__DC_I2C_DDC1_HW_DONE	        1

#define DCN_1_0__SRCID__DC_I2C_DDC2_HW_DONE	        1	
#define DCN_1_0__CTXID__DC_I2C_DDC2_HW_DONE	        2

#define DCN_1_0__SRCID__DC_I2C_DDC3_HW_DONE	        1	
#define DCN_1_0__CTXID__DC_I2C_DDC3_HW_DONE	        3

#define DCN_1_0__SRCID__DC_I2C_DDC4_HW_DONE	        1	
#define DCN_1_0__CTXID__DC_I2C_DDC4_HW_DONE         4

#define DCN_1_0__SRCID__DC_I2C_DDC5_HW_DONE	        1	
#define DCN_1_0__CTXID__DC_I2C_DDC5_HW_DONE	        5

#define DCN_1_0__SRCID__DC_I2C_DDC6_HW_DONE	        1	
#define DCN_1_0__CTXID__DC_I2C_DDC6_HW_DONE	        6

#define DCN_1_0__SRCID__DC_I2C_DDCVGA_HW_DONE	    1	
#define DCN_1_0__CTXID__DC_I2C_DDCVGA_HW_DONE	    7

#define DCN_1_0__SRCID__DC_I2C_DDC1_READ_REQUEST	1   
#define DCN_1_0__CTXID__DC_I2C_DDC1_READ_REQUEST	8

#define DCN_1_0__SRCID__DC_I2C_DDC2_READ_REQUEST	1	
#define DCN_1_0__CTXID__DC_I2C_DDC2_READ_REQUEST	9

#define DCN_1_0__SRCID__DC_I2C_DDC3_READ_REQUEST	1	
#define DCN_1_0__CTXID__DC_I2C_DDC3_READ_REQUEST	10

#define DCN_1_0__SRCID__DC_I2C_DDC4_READ_REQUEST	1	
#define DCN_1_0__CTXID__DC_I2C_DDC4_READ_REQUEST	11

#define DCN_1_0__SRCID__DC_I2C_DDC5_READ_REQUEST	1	
#define DCN_1_0__CTXID__DC_I2C_DDC5_READ_REQUEST	12

#define DCN_1_0__SRCID__DC_I2C_DDC6_READ_REQUEST	1	
#define DCN_1_0__CTXID__DC_I2C_DDC6_READ_REQUEST	13

#define DCN_1_0__SRCID__DC_I2C_DDCVGA_READ_REQUEST	1	
#define DCN_1_0__CTXID__DC_I2C_DDCVGA_READ_REQUEST	14

#define DCN_1_0__SRCID__GENERIC_I2C_DDC_READ_REQUEST	1	
#define DCN_1_0__CTXID__GENERIC_I2C_DDC_READ_REQUEST	15

#define DCN_1_0__SRCID__DCCG_PERFCOUNTER_INT0_STATUS	2	
#define DCN_1_0__CTXID__DCCG_PERFCOUNTER_INT0_STATUS	7

#define DCN_1_0__SRCID__DCCG_PERFCOUNTER_INT1_STATUS	2	
#define DCN_1_0__CTXID__DCCG_PERFCOUNTER_INT1_STATUS	8

#define DCN_1_0__SRCID__DMU_PERFCOUNTER_INT0_STATUS	3	
#define DCN_1_0__CTXID__DMU_PERFCOUNTER_INT0_STATUS	7

#define DCN_1_0__SRCID__DMU_PERFCOUNTER_INT1_STATUS	3	
#define DCN_1_0__CTXID__DMU_PERFCOUNTER_INT1_STATUS	8

#define DCN_1_0__SRCID__DIO_PERFCOUNTER_INT0_STATUS	4	
#define DCN_1_0__CTXID__DIO_PERFCOUNTER_INT0_STATUS	7

#define DCN_1_0__SRCID__DIO_PERFCOUNTER_INT1_STATUS	4	
#define DCN_1_0__CTXID__DIO_PERFCOUNTER_INT1_STATUS	8

#define DCN_1_0__SRCID__RBBMIF_TIMEOUT_INT	        5	
#define DCN_1_0__CTXID__RBBMIF_TIMEOUT_INT	        12

#define DCN_1_0__SRCID__DMCU_INTERNAL_INT	        5	
#define DCN_1_0__CTXID__DMCU_INTERNAL_INT	        13

#define DCN_1_0__SRCID__DMCU_SCP_INT	            5	
#define DCN_1_0__CTXID__DMCU_SCP_INT	            14

#define DCN_1_0__SRCID__DMCU_ABM0_HG_READY_INT	    6	
#define DCN_1_0__CTXID__DMCU_ABM0_HG_READY_INT	    0

#define DCN_1_0__SRCID__DMCU_ABM0_LS_READY_INT	    6	
#define DCN_1_0__CTXID__DMCU_ABM0_LS_READY_INT	    1

#define DCN_1_0__SRCID__DMCU_ABM0_BL_UPDATE_INT	    6	
#define DCN_1_0__CTXID__DMCU_ABM0_BL_UPDATE_INT	    2

#define DCN_1_0__SRCID__DMCU_ABM1_HG_READY_INT	    6	
#define DCN_1_0__CTXID__DMCU_ABM1_HG_READY_INT	    3

#define DCN_1_0__SRCID__DMCU_ABM1_LS_READY_INT	    6	
#define DCN_1_0__CTXID__DMCU_ABM1_LS_READY_INT	    4

#define DCN_1_0__SRCID__DMCU_ABM1_BL_UPDATE_INT	    6	
#define DCN_1_0__CTXID__DMCU_ABM1_BL_UPDATE_INT	    5

#define DCN_1_0__SRCID__WB0_PERFCOUNTER_INT0_STATUS	6	
#define DCN_1_0__CTXID__WB0_PERFCOUNTER_INT0_STATUS	6

#define DCN_1_0__SRCID__WB0_PERFCOUNTER_INT1_STATUS	6	
#define DCN_1_0__CTXID__WB0_PERFCOUNTER_INT1_STATUS	7

#define DCN_1_0__SRCID__DPDBG_FIFO_OVERFLOW_INT	    7	
#define DCN_1_0__CTXID__DPDBG_FIFO_OVERFLOW_INT	    1

#define DCN_1_0__SRCID__DCIO_DPCS_TXA_ERROR_INT	    8	
#define DCN_1_0__CTXID__DCIO_DPCS_TXA_ERROR_INT	    0

#define DCN_1_0__SRCID__DCIO_DPCS_TXB_ERROR_INT	    8	
#define DCN_1_0__CTXID__DCIO_DPCS_TXB_ERROR_INT	    1

#define DCN_1_0__SRCID__DCIO_DPCS_TXC_ERROR_INT	    8	
#define DCN_1_0__CTXID__DCIO_DPCS_TXC_ERROR_INT	    2

#define DCN_1_0__SRCID__DCIO_DPCS_TXD_ERROR_INT	    8	
#define DCN_1_0__CTXID__DCIO_DPCS_TXD_ERROR_INT	    3

#define DCN_1_0__SRCID__DCIO_DPCS_TXE_ERROR_INT	    8	
#define DCN_1_0__CTXID__DCIO_DPCS_TXE_ERROR_INT	    4

#define DCN_1_0__SRCID__DCIO_DPCS_TXF_ERROR_INT	    8	
#define DCN_1_0__CTXID__DCIO_DPCS_TXF_ERROR_INT	    5

#define DCN_1_0__SRCID__DCIO_DPCS_TXG_ERROR_INT	    8	
#define DCN_1_0__CTXID__DCIO_DPCS_TXG_ERROR_INT	    6

#define DCN_1_0__SRCID__DCIO_DPCS_RXA_ERROR_INT	    8	
#define DCN_1_0__CTXID__DCIO_DPCS_RXA_ERROR_INT	    7

#define DCN_1_0__SRCID__DC_HPD1_INT	                9	
#define DCN_1_0__CTXID__DC_HPD1_INT	                0

#define DCN_1_0__SRCID__DC_HPD2_INT	                9	
#define DCN_1_0__CTXID__DC_HPD2_INT	                1

#define DCN_1_0__SRCID__DC_HPD3_INT	                9	
#define DCN_1_0__CTXID__DC_HPD3_INT	                2

#define DCN_1_0__SRCID__DC_HPD4_INT	                9	
#define DCN_1_0__CTXID__DC_HPD4_INT	                3

#define DCN_1_0__SRCID__DC_HPD5_INT	                9	
#define DCN_1_0__CTXID__DC_HPD5_INT	                4

#define DCN_1_0__SRCID__DC_HPD6_INT	                9	
#define DCN_1_0__CTXID__DC_HPD6_INT	                5 

#define DCN_1_0__SRCID__DC_HPD1_RX_INT	            9	
#define DCN_1_0__CTXID__DC_HPD1_RX_INT	            6

#define DCN_1_0__SRCID__DC_HPD2_RX_INT	            9	
#define DCN_1_0__CTXID__DC_HPD2_RX_INT	            7

#define DCN_1_0__SRCID__DC_HPD3_RX_INT	            9	
#define DCN_1_0__CTXID__DC_HPD3_RX_INT	            8

#define DCN_1_0__SRCID__DC_HPD4_RX_INT	            9	
#define DCN_1_0__CTXID__DC_HPD4_RX_INT	            9

#define DCN_1_0__SRCID__DC_HPD5_RX_INT	            9	
#define DCN_1_0__CTXID__DC_HPD5_RX_INT	            10

#define DCN_1_0__SRCID__DC_HPD6_RX_INT	            9	
#define DCN_1_0__CTXID__DC_HPD6_RX_INT	            11

#define DCN_1_0__SRCID__DC_DAC_A_AUTO_DET	        0xA	
#define DCN_1_0__CTXID__DC_DAC_A_AUTO_DET	        0

#define DCN_1_0__SRCID__AZ_ENDPOINT0_AUDIO_FMT_CHANGED_INT	0xA	
#define DCN_1_0__CTXID__AZ_ENDPOINT0_AUDIO_FMT_CHANGED_INT	2

#define DCN_1_0__SRCID__AZ_ENDPOINT1_AUDIO_FMT_CHANGED_INT	0xA	
#define DCN_1_0__CTXID__AZ_ENDPOINT1_AUDIO_FMT_CHANGED_INT	3

#define DCN_1_0__SRCID__AZ_ENDPOINT2_AUDIO_FMT_CHANGED_INT	0xA	
#define DCN_1_0__CTXID__AZ_ENDPOINT2_AUDIO_FMT_CHANGED_INT	4

#define DCN_1_0__SRCID__AZ_ENDPOINT3_AUDIO_FMT_CHANGED_INT	0xA	
#define DCN_1_0__CTXID__AZ_ENDPOINT3_AUDIO_FMT_CHANGED_INT	5

#define DCN_1_0__SRCID__AZ_ENDPOINT4_AUDIO_FMT_CHANGED_INT	0xA	
#define DCN_1_0__CTXID__AZ_ENDPOINT4_AUDIO_FMT_CHANGED_INT	6

#define DCN_1_0__SRCID__AZ_ENDPOINT5_AUDIO_FMT_CHANGED_INT	0xA	
#define DCN_1_0__CTXID__AZ_ENDPOINT5_AUDIO_FMT_CHANGED_INT	7

#define DCN_1_0__SRCID__AZ_ENDPOINT6_AUDIO_FMT_CHANGED_INT	0xA	
#define DCN_1_0__CTXID__AZ_ENDPOINT6_AUDIO_FMT_CHANGED_INT	8

#define DCN_1_0__SRCID__AZ_ENDPOINT7_AUDIO_FMT_CHANGED_INT	0xA	
#define DCN_1_0__CTXID__AZ_ENDPOINT7_AUDIO_FMT_CHANGED_INT	9

#define DCN_1_0__SRCID__AZ_ENDPOINT0_AUDIO_ENABLED_INT	0xB	
#define DCN_1_0__CTXID__AZ_ENDPOINT0_AUDIO_ENABLED_INT	0

#define DCN_1_0__SRCID__AZ_ENDPOINT1_AUDIO_ENABLED_INT	0xB	
#define DCN_1_0__CTXID__AZ_ENDPOINT1_AUDIO_ENABLED_INT	1

#define DCN_1_0__SRCID__AZ_ENDPOINT2_AUDIO_ENABLED_INT	0xB	
#define DCN_1_0__CTXID__AZ_ENDPOINT2_AUDIO_ENABLED_INT	2

#define DCN_1_0__SRCID__AZ_ENDPOINT3_AUDIO_ENABLED_INT	0xB	
#define DCN_1_0__CTXID__AZ_ENDPOINT3_AUDIO_ENABLED_INT	3

#define DCN_1_0__SRCID__AZ_ENDPOINT4_AUDIO_ENABLED_INT	0xB	
#define DCN_1_0__CTXID__AZ_ENDPOINT4_AUDIO_ENABLED_INT	4

#define DCN_1_0__SRCID__AZ_ENDPOINT5_AUDIO_ENABLED_INT	0xB	
#define DCN_1_0__CTXID__AZ_ENDPOINT5_AUDIO_ENABLED_INT	5

#define DCN_1_0__SRCID__AZ_ENDPOINT6_AUDIO_ENABLED_INT	0xB	
#define DCN_1_0__CTXID__AZ_ENDPOINT6_AUDIO_ENABLED_INT	6

#define DCN_1_0__SRCID__AZ_ENDPOINT7_AUDIO_ENABLED_INT	0xB	
#define DCN_1_0__CTXID__AZ_ENDPOINT7_AUDIO_ENABLED_INT	7

#define DCN_1_0__SRCID__AZ_ENDPOINT0_AUDIO_DISABLED_INT	0xC	
#define DCN_1_0__CTXID__AZ_ENDPOINT0_AUDIO_DISABLED_INT	0

#define DCN_1_0__SRCID__AZ_ENDPOINT1_AUDIO_DISABLED_INT	0xC	
#define DCN_1_0__CTXID__AZ_ENDPOINT1_AUDIO_DISABLED_INT	1

#define DCN_1_0__SRCID__AZ_ENDPOINT2_AUDIO_DISABLED_INT	0xC	
#define DCN_1_0__CTXID__AZ_ENDPOINT2_AUDIO_DISABLED_INT	2

#define DCN_1_0__SRCID__AZ_ENDPOINT3_AUDIO_DISABLED_INT	0xC	
#define DCN_1_0__CTXID__AZ_ENDPOINT3_AUDIO_DISABLED_INT	3

#define DCN_1_0__SRCID__AZ_ENDPOINT4_AUDIO_DISABLED_INT	0xC	
#define DCN_1_0__CTXID__AZ_ENDPOINT4_AUDIO_DISABLED_INT	4

#define DCN_1_0__SRCID__AZ_ENDPOINT5_AUDIO_DISABLED_INT	0xC	
#define DCN_1_0__CTXID__AZ_ENDPOINT5_AUDIO_DISABLED_INT	5

#define DCN_1_0__SRCID__AZ_ENDPOINT6_AUDIO_DISABLED_INT	0xC	
#define DCN_1_0__CTXID__AZ_ENDPOINT6_AUDIO_DISABLED_INT	6

#define DCN_1_0__SRCID__AZ_ENDPOINT7_AUDIO_DISABLED_INT	0xC	
#define DCN_1_0__CTXID__AZ_ENDPOINT7_AUDIO_DISABLED_INT	7

#define DCN_1_0__SRCID__DC_AUX1_GTC_SYNC_LOCK_DONE	0xD	    
#define DCN_1_0__CTXID__DC_AUX1_GTC_SYNC_LOCK_DONE	0

#define DCN_1_0__SRCID__DC_AUX1_GTC_SYNC_ERROR	    0xD	    
#define DCN_1_0__CTXID__DC_AUX1_GTC_SYNC_ERROR	    1

#define DCN_1_0__SRCID__DC_AUX2_GTC_SYNC_LOCK_DONE	0xD	    
#define DCN_1_0__CTXID__DC_AUX2_GTC_SYNC_LOCK_DONE	2

#define DCN_1_0__SRCID__DC_AUX2_GTC_SYNC_ERROR	    0xD	    
#define DCN_1_0__CTXID__DC_AUX2_GTC_SYNC_ERROR	    3

#define DCN_1_0__SRCID__DC_AUX3_GTC_SYNC_LOCK_DONE	0xD	    
#define DCN_1_0__CTXID__DC_AUX3_GTC_SYNC_LOCK_DONE	4

#define DCN_1_0__SRCID__DC_AUX3_GTC_SYNC_ERROR	    0xD	    
#define DCN_1_0__CTXID__DC_AUX3_GTC_SYNC_ERROR	    5

#define DCN_1_0__SRCID__DC_DIGA_VID_STRM_DISABLE	    0xE	    
#define DCN_1_0__CTXID__DC_DIGA_VID_STRM_DISABLE	    0

#define DCN_1_0__SRCID__DC_DIGB_VID_STRM_DISABLE	    0xE	    
#define DCN_1_0__CTXID__DC_DIGB_VID_STRM_DISABLE	    1

#define DCN_1_0__SRCID__DC_DIGC_VID_STRM_DISABLE	    0xE	    
#define DCN_1_0__CTXID__DC_DIGC_VID_STRM_DISABLE	    2

#define DCN_1_0__SRCID__DC_DIGD_VID_STRM_DISABLE	    0xE	    
#define DCN_1_0__CTXID__DC_DIGD_VID_STRM_DISABLE	    3

#define DCN_1_0__SRCID__DC_DIGE_VID_STRM_DISABLE	    0xE	    
#define DCN_1_0__CTXID__DC_DIGE_VID_STRM_DISABLE	    4

#define DCN_1_0__SRCID__DC_DIGF_VID_STRM_DISABLE	    0xE	    
#define DCN_1_0__CTXID__DC_DIGF_VID_STRM_DISABLE	    5

#define DCN_1_0__SRCID__DC_DIGG_VID_STRM_DISABLE	    0xE	    
#define DCN_1_0__CTXID__DC_DIGG_VID_STRM_DISABLE	    6

#define DCN_1_0__SRCID__DC_DIGH_VID_STRM_DISABLE	    0xE	    
#define DCN_1_0__CTXID__DC_DIGH_VID_STRM_DISABLE	    7

#define DCN_1_0__SRCID__DC_DIGA_FAST_TRAINING_COMPLETE_INT	0xF	    
#define DCN_1_0__CTXID__DC_DIGA_FAST_TRAINING_COMPLETE_INT	0

#define DCN_1_0__SRCID__DC_DIGB_FAST_TRAINING_COMPLETE_INT	0xF	    
#define DCN_1_0__CTXID__DC_DIGB_FAST_TRAINING_COMPLETE_INT	1

#define DCN_1_0__SRCID__DC_DIGC_FAST_TRAINING_COMPLETE_INT	0xF	    
#define DCN_1_0__CTXID__DC_DIGC_FAST_TRAINING_COMPLETE_INT	2

#define DCN_1_0__SRCID__DC_DIGD_FAST_TRAINING_COMPLETE_INT	0xF	    
#define DCN_1_0__CTXID__DC_DIGD_FAST_TRAINING_COMPLETE_INT	3

#define DCN_1_0__SRCID__DC_DIGE_FAST_TRAINING_COMPLETE_INT	0xF	    
#define DCN_1_0__CTXID__DC_DIGE_FAST_TRAINING_COMPLETE_INT	4

#define DCN_1_0__SRCID__DC_DIGF_FAST_TRAINING_COMPLETE_INT	0xF	    
#define DCN_1_0__CTXID__DC_DIGF_FAST_TRAINING_COMPLETE_INT	5

#define DCN_1_0__SRCID__DC_DIGG_FAST_TRAINING_COMPLETE_INT	0xF	    
#define DCN_1_0__CTXID__DC_DIGG_FAST_TRAINING_COMPLETE_INT	6

#define DCN_1_0__SRCID__DC_DIGH_FAST_TRAINING_COMPLETE_INT	0xF	    
#define DCN_1_0__CTXID__DC_DIGH_FAST_TRAINING_COMPLETE_INT	7

#define DCN_1_0__SRCID__DC_AUX1_SW_DONE	                0x10	
#define DCN_1_0__CTXID__DC_AUX1_SW_DONE	                0

#define DCN_1_0__SRCID__DC_AUX1_LS_DONE	                0x10	
#define DCN_1_0__CTXID__DC_AUX1_LS_DONE	                1

#define DCN_1_0__SRCID__DC_AUX2_SW_DONE	                0x10	
#define DCN_1_0__CTXID__DC_AUX2_SW_DONE	                2

#define DCN_1_0__SRCID__DC_AUX2_LS_DONE	                0x10	
#define DCN_1_0__CTXID__DC_AUX2_LS_DONE	                3

#define DCN_1_0__SRCID__DC_AUX3_SW_DONE	                0x10	
#define DCN_1_0__CTXID__DC_AUX3_SW_DONE	                4

#define DCN_1_0__SRCID__DC_AUX3_LS_DONE	                0x10	
#define DCN_1_0__CTXID__DC_AUX3_LS_DONE	                5

#define DCN_1_0__SRCID__DC_AUX4_SW_DONE	                0x10	
#define DCN_1_0__CTXID__DC_AUX4_SW_DONE	                6

#define DCN_1_0__SRCID__DC_AUX4_LS_DONE	                0x10	
#define DCN_1_0__CTXID__DC_AUX4_LS_DONE	                7

#define DCN_1_0__SRCID__DC_AUX5_SW_DONE	                0x10	
#define DCN_1_0__CTXID__DC_AUX5_SW_DONE	                8

#define DCN_1_0__SRCID__DC_AUX5_LS_DONE	                0x10	
#define DCN_1_0__CTXID__DC_AUX5_LS_DONE	                9

#define DCN_1_0__SRCID__DC_AUX6_SW_DONE	                0x10	
#define DCN_1_0__CTXID__DC_AUX6_SW_DONE	                10

#define DCN_1_0__SRCID__DC_AUX6_LS_DONE	                0x10	
#define DCN_1_0__CTXID__DC_AUX6_LS_DONE	                11

#define DCN_1_0__SRCID__VGA_CRT_INT	                    0x10	
#define DCN_1_0__CTXID__VGA_CRT_INT	                    12

#define DCN_1_0__SRCID__DCCG_PERFCOUNTER2_INT0_STATUS	0x11	
#define DCN_1_0__CTXID__DCCG_PERFCOUNTER2_INT0_STATUS	0

#define DCN_1_0__SRCID__DCCG_PERFCOUNTER2_INT1_STATUS	0x11	
#define DCN_1_0__CTXID__DCCG_PERFCOUNTER2_INT1_STATUS	1

#define DCN_1_0__SRCID__BUFMGR_CWB0_IHIF_interrupt	    0x12	
#define DCN_1_0__CTXID__BUFMGR_CWB0_IHIF_interrupt	    0

#define DCN_1_0__SRCID__BUFMGR_CWB1_IHIF_interrupt	    0x12	
#define DCN_1_0__CTXID__BUFMGR_CWB1_IHIF_interrupt	    1

#define DCN_1_0__SRCID__MCIF0_BUFMGR_SW_CONTROL_MCIF_BUFMGR_SW_INT	0x12	
#define DCN_1_0__CTXID__MCIF0_BUFMGR_SW_CONTROL_MCIF_BUFMGR_SW_INT	2

#define DCN_1_0__SRCID__MCIF1_BUFMGR_SW_CONTROL_MCIF_BUFMGR_SW_INT	0x12	
#define DCN_1_0__CTXID__MCIF1_BUFMGR_SW_CONTROL_MCIF_BUFMGR_SW_INT	3

#define DCN_1_0__SRCID__SISCL0_COEF_RAM_CONFLICT_STATUS	            0x12	
#define DCN_1_0__CTXID__SISCL0_COEF_RAM_CONFLICT_STATUS	            4

#define DCN_1_0__SRCID__SISCL0_OVERFLOW_STATUS	        0x12	
#define DCN_1_0__CTXID__SISCL0_OVERFLOW_STATUS	        5

#define DCN_1_0__SRCID__SISCL1_COEF_RAM_CONFLICT_STATUS	0x12	
#define DCN_1_0__CTXID__SISCL1_COEF_RAM_CONFLICT_STATUS	6

#define DCN_1_0__SRCID__SISCL1_OVERFLOW_STATUS	        0x12	
#define DCN_1_0__CTXID__SISCL1_OVERFLOW_STATUS	        7

#define DCN_1_0__SRCID__DC_AUX4_GTC_SYNC_LOCK_DONE	    0x13	
#define DCN_1_0__CTXID__DC_AUX4_GTC_SYNC_LOCK_DONE	    0

#define DCN_1_0__SRCID__DC_AUX4_GTC_SYNC_ERROR	        0x13	
#define DCN_1_0__CTXID__DC_AUX4_GTC_SYNC_ERROR	        1

#define DCN_1_0__SRCID__DC_AUX5_GTC_SYNC_LOCK_DONE	    0x13	
#define DCN_1_0__CTXID__DC_AUX5_GTC_SYNC_LOCK_DONE	    2

#define DCN_1_0__SRCID__DC_AUX5_GTC_SYNC_ERROR	        0x13	
#define DCN_1_0__CTXID__DC_AUX5_GTC_SYNC_ERROR	        3

#define DCN_1_0__SRCID__DC_AUX6_GTC_SYNC_LOCK_DONE	    0x13	
#define DCN_1_0__CTXID__DC_AUX6_GTC_SYNC_LOCK_DONE	    4

#define DCN_1_0__SRCID__DC_AUX6_GTC_SYNC_ERROR	        0x13	
#define DCN_1_0__CTXID__DC_AUX6_GTC_SYNC_ERROR	        5

#define DCN_1_0__SRCID__DCPG_DCFE0_POWER_UP_INT	        0x14	
#define DCN_1_0__CTXID__DCPG_DCFE0_POWER_UP_INT	        0

#define DCN_1_0__SRCID__DCPG_DCFE1_POWER_UP_INT	        0x14	
#define DCN_1_0__CTXID__DCPG_DCFE1_POWER_UP_INT	        1

#define DCN_1_0__SRCID__DCPG_DCFE2_POWER_UP_INT	        0x14	
#define DCN_1_0__CTXID__DCPG_DCFE2_POWER_UP_INT	        2

#define DCN_1_0__SRCID__DCPG_DCFE3_POWER_UP_INT	        0x14	
#define DCN_1_0__CTXID__DCPG_DCFE3_POWER_UP_INT	        3

#define DCN_1_0__SRCID__DCPG_DCFE4_POWER_UP_INT	        0x14	
#define DCN_1_0__CTXID__DCPG_DCFE4_POWER_UP_INT	        4

#define DCN_1_0__SRCID__DCPG_DCFE5_POWER_UP_INT	        0x14	
#define DCN_1_0__CTXID__DCPG_DCFE5_POWER_UP_INT	        5

#define DCN_1_0__SRCID__DCPG_DCFE6_POWER_UP_INT	        0x14	
#define DCN_1_0__CTXID__DCPG_DCFE6_POWER_UP_INT	        6

#define DCN_1_0__SRCID__DCPG_DCFE7_POWER_UP_INT	        0x14	
#define DCN_1_0__CTXID__DCPG_DCFE7_POWER_UP_INT	        7

#define DCN_1_0__SRCID__DCPG_DCFE0_POWER_DOWN_INT	    0x14	
#define DCN_1_0__CTXID__DCPG_DCFE0_POWER_DOWN_INT	    8

#define DCN_1_0__SRCID__DCPG_DCFE1_POWER_DOWN_INT	    0x14	
#define DCN_1_0__CTXID__DCPG_DCFE1_POWER_DOWN_INT	    9

#define DCN_1_0__SRCID__DCPG_DCFE2_POWER_DOWN_INT	    0x14	
#define DCN_1_0__CTXID__DCPG_DCFE2_POWER_DOWN_INT	    10

#define DCN_1_0__SRCID__DCPG_DCFE3_POWER_DOWN_INT   	0x14	
#define DCN_1_0__CTXID__DCPG_DCFE3_POWER_DOWN_INT	    11

#define DCN_1_0__SRCID__DCPG_DCFE4_POWER_DOWN_INT	    0x14	
#define DCN_1_0__CTXID__DCPG_DCFE4_POWER_DOWN_INT	    12

#define DCN_1_0__SRCID__DCPG_DCFE5_POWER_DOWN_INT	    0x14	
#define DCN_1_0__CTXID__DCPG_DCFE5_POWER_DOWN_INT	    13

#define DCN_1_0__SRCID__DCPG_DCFE6_POWER_DOWN_INT	    0x14	
#define DCN_1_0__CTXID__DCPG_DCFE6_POWER_DOWN_INT	    14

#define DCN_1_0__SRCID__DCPG_DCFE7_POWER_DOWN_INT	    0x14	
#define DCN_1_0__CTXID__DCPG_DCFE7_POWER_DOWN_INT	    15

#define DCN_1_0__SRCID__DCCG_IHC_VSYNC_otg0_latch_int	0x15	
#define DCN_1_0__CTXID__DCCG_IHC_VSYNC_otg0_latch_int	0

#define DCN_1_0__SRCID__DCCG_IHC_VSYNC_otg1_latch_int	0x15	
#define DCN_1_0__CTXID__DCCG_IHC_VSYNC_otg1_latch_int	1

#define DCN_1_0__SRCID__DCCG_IHC_VSYNC_otg2_latch_int	0x15	
#define DCN_1_0__CTXID__DCCG_IHC_VSYNC_otg2_latch_int	2

#define DCN_1_0__SRCID__DCCG_IHC_VSYNC_otg3_latch_int	0x15	
#define DCN_1_0__CTXID__DCCG_IHC_VSYNC_otg3_latch_int	3

#define DCN_1_0__SRCID__DCCG_IHC_VSYNC_otg4_latch_int	0x15	
#define DCN_1_0__CTXID__DCCG_IHC_VSYNC_otg4_latch_int	4

#define DCN_1_0__SRCID__DCCG_IHC_VSYNC_otg5_latch_int	0x15	
#define DCN_1_0__CTXID__DCCG_IHC_VSYNC_otg5_latch_int	5

#define DCN_1_0__SRCID__OPTC0_DATA_UNDERFLOW_INT	    0x15	
#define DCN_1_0__CTXID__OPTC0_DATA_UNDERFLOW_INT	    6

#define DCN_1_0__SRCID__OPTC1_DATA_UNDERFLOW_INT	    0x15	
#define DCN_1_0__CTXID__OPTC1_DATA_UNDERFLOW_INT	    7

#define DCN_1_0__SRCID__OPTC2_DATA_UNDERFLOW_INT	    0x15	
#define DCN_1_0__CTXID__OPTC2_DATA_UNDERFLOW_INT	    8

#define DCN_1_0__SRCID__OPTC3_DATA_UNDERFLOW_INT	    0x15	
#define DCN_1_0__CTXID__OPTC3_DATA_UNDERFLOW_INT	    9

#define DCN_1_0__SRCID__OPTC4_DATA_UNDERFLOW_INT	    0x15	
#define DCN_1_0__CTXID__OPTC4_DATA_UNDERFLOW_INT	    10

#define DCN_1_0__SRCID__OPTC5_DATA_UNDERFLOW_INT	    0x15	
#define DCN_1_0__CTXID__OPTC5_DATA_UNDERFLOW_INT	    11

#define DCN_1_0__SRCID__MPCC0_STALL_INTERRUPT	        0x16	
#define DCN_1_0__CTXID__MPCC0_STALL_INTERRUPT	        0

#define DCN_1_0__SRCID__MPCC1_STALL_INTERRUPT	        0x16	
#define DCN_1_0__CTXID__MPCC1_STALL_INTERRUPT	        1

#define DCN_1_0__SRCID__MPCC2_STALL_INTERRUPT	        0x16	
#define DCN_1_0__CTXID__MPCC2_STALL_INTERRUPT	        2

#define DCN_1_0__SRCID__MPCC3_STALL_INTERRUPT	        0x16	
#define DCN_1_0__CTXID__MPCC3_STALL_INTERRUPT	        3

#define DCN_1_0__SRCID__MPCC4_STALL_INTERRUPT	        0x16	
#define DCN_1_0__CTXID__MPCC4_STALL_INTERRUPT	        4

#define DCN_1_0__SRCID__MPCC5_STALL_INTERRUPT	        0x16	
#define DCN_1_0__CTXID__MPCC5_STALL_INTERRUPT	        5

#define DCN_1_0__SRCID__MPCC6_STALL_INTERRUPT	        0x16	
#define DCN_1_0__CTXID__MPCC6_STALL_INTERRUPT	        6

#define DCN_1_0__SRCID__MPCC7_STALL_INTERRUPT	        0x16	
#define DCN_1_0__CTXID__MPCC7_STALL_INTERRUPT	        7

#define DCN_1_0__SRCID__OTG1_CPU_SS_INT	                0x17	
#define DCN_1_0__CTXID__OTG1_CPU_SS_INT	                0

#define DCN_1_0__SRCID__OTG1_RANGE_TIMING_UPDATE	    0x17	
#define DCN_1_0__CTXID__OTG1_RANGE_TIMING_UPDATE	    1

#define DCN_1_0__SRCID__OTG2_CPU_SS_INT	0x17	
#define DCN_1_0__CTXID__OTG2_CPU_SS_INT	2

#define DCN_1_0__SRCID__OTG2_RANGE_TIMING_UPDATE	0x17	
#define DCN_1_0__CTXID__OTG2_RANGE_TIMING_UPDATE	3

#define DCN_1_0__SRCID__OTG3_CPU_SS_INT	0x17	
#define DCN_1_0__CTXID__OTG3_CPU_SS_INT	4

#define DCN_1_0__SRCID__OTG3_RANGE_TIMING_UPDATE	0x17	
#define DCN_1_0__CTXID__OTG3_RANGE_TIMING_UPDATE	5

#define DCN_1_0__SRCID__OTG4_CPU_SS_INT	0x17	
#define DCN_1_0__CTXID__OTG4_CPU_SS_INT	6

#define DCN_1_0__SRCID__OTG4_RANGE_TIMING_UPDATE	0x17	
#define DCN_1_0__CTXID__OTG4_RANGE_TIMING_UPDATE	7

#define DCN_1_0__SRCID__OTG5_CPU_SS_INT	0x17	
#define DCN_1_0__CTXID__OTG5_CPU_SS_INT	8

#define DCN_1_0__SRCID__OTG5_RANGE_TIMING_UPDATE	0x17	
#define DCN_1_0__CTXID__OTG5_RANGE_TIMING_UPDATE	9

#define DCN_1_0__SRCID__OTG6_CPU_SS_INT	0x17	
#define DCN_1_0__CTXID__OTG6_CPU_SS_INT	10

#define DCN_1_0__SRCID__OTG6_RANGE_TIMING_UPDATE	0x17	
#define DCN_1_0__CTXID__OTG6_RANGE_TIMING_UPDATE	11

#define DCN_1_0__SRCID__DC_D1_OTG_V_UPDATE	0x18	
#define DCN_1_0__SRCID__DC_D2_OTG_V_UPDATE	0x19	
#define DCN_1_0__SRCID__DC_D3_OTG_V_UPDATE	0x1A	
#define DCN_1_0__SRCID__DC_D4_OTG_V_UPDATE	0x1B	
#define DCN_1_0__SRCID__DC_D5_OTG_V_UPDATE	0x1C	
#define DCN_1_0__SRCID__DC_D6_OTG_V_UPDATE	0x1D	

#define DCN_1_0__SRCID__DC_D1_OTG_SNAPSHOT	0x1E	
#define DCN_1_0__CTXID__DC_D1_OTG_SNAPSHOT	0

#define DCN_1_0__SRCID__DC_D1_FORCE_CNT_W	0x1E	
#define DCN_1_0__CTXID__DC_D1_FORCE_CNT_W	1

#define DCN_1_0__SRCID__DC_D1_FORCE_VSYNC_NXT_LINE	0x1E	
#define DCN_1_0__CTXID__DC_D1_FORCE_VSYNC_NXT_LINE	2

#define DCN_1_0__SRCID__DC_D1_OTG_EXTT_TRG_A	0x1E	
#define DCN_1_0__CTXID__DC_D1_OTG_EXTT_TRG_A	3

#define DCN_1_0__SRCID__DC_D1_OTG_EXTT_TRG_B	0x1E	
#define DCN_1_0__CTXID__DC_D1_OTG_EXTT_TRG_B	4

#define DCN_1_0__SRCID__DC_D1_OTG_GSL_VSYNC_GAP	0x1E	
#define DCN_1_0__CTXID__DC_D1_OTG_GSL_VSYNC_GAP	5

#define DCN_1_0__SRCID__OTG1_VERTICAL_INTERRUPT0_CONTROL	0x1E	
#define DCN_1_0__CTXID__OTG1_VERTICAL_INTERRUPT0_CONTROL	6

#define DCN_1_0__SRCID__OTG1_VERTICAL_INTERRUPT1_CONTROL	0x1E	
#define DCN_1_0__CTXID__OTG1_VERTICAL_INTERRUPT1_CONTROL	7

#define DCN_1_0__SRCID__OTG1_VERTICAL_INTERRUPT2_CONTROL	0x1E	
#define DCN_1_0__CTXID__OTG1_VERTICAL_INTERRUPT2_CONTROL	8

#define DCN_1_0__SRCID__OTG1_EXT_TIMING_SYNC_LOSS_INTERRUPT_CONTROL	0x1E	
#define DCN_1_0__CTXID__OTG1_EXT_TIMING_SYNC_LOSS_INTERRUPT_CONTROL	9

#define DCN_1_0__SRCID__OTG1_EXT_TIMING_SYNC_INTERRUPT_CONTROL	0x1E	
#define DCN_1_0__CTXID__OTG1_EXT_TIMING_SYNC_INTERRUPT_CONTROL	10

#define DCN_1_0__SRCID__OTG1_EXT_TIMING_SYNC_SIGNAL_INTERRUPT_CONTROL	0x1E	
#define DCN_1_0__CTXID__OTG1_EXT_TIMING_SYNC_SIGNAL_INTERRUPT_CONTROL	11

#define DCN_1_0__SRCID__OTG1_SET_VTOTAL_MIN_EVENT_INT	0x1E	
#define DCN_1_0__CTXID__OTG1_SET_VTOTAL_MIN_EVENT_INT	12

#define DCN_1_0__SRCID__DC_D2_OTG_SNAPSHOT	0x1F	
#define DCN_1_0__CTXID__DC_D2_OTG_SNAPSHOT	0

#define DCN_1_0__SRCID__DC_D2_FORCE_CNT_W	0x1F	
#define DCN_1_0__CTXID__DC_D2_FORCE_CNT_W	1

#define DCN_1_0__SRCID__DC_D2_FORCE_VSYNC_NXT_LINE	0x1F	
#define DCN_1_0__CTXID__DC_D2_FORCE_VSYNC_NXT_LINE	2

#define DCN_1_0__SRCID__DC_D2_OTG_EXTT_TRG_A	0x1F	
#define DCN_1_0__CTXID__DC_D2_OTG_EXTT_TRG_A	3

#define DCN_1_0__SRCID__DC_D2_OTG_EXTT_TRG_B	0x1F	
#define DCN_1_0__CTXID__DC_D2_OTG_EXTT_TRG_B	4

#define DCN_1_0__SRCID__DC_D2_OTG_GSL_VSYNC_GAP	0x1F	
#define DCN_1_0__CTXID__DC_D2_OTG_GSL_VSYNC_GAP	5

#define DCN_1_0__SRCID__OTG2_VERTICAL_INTERRUPT0_CONTROL	0x1F	
#define DCN_1_0__CTXID__OTG2_VERTICAL_INTERRUPT0_CONTROL	6

#define DCN_1_0__SRCID__OTG2_VERTICAL_INTERRUPT1_CONTROL	0x1F	
#define DCN_1_0__CTXID__OTG2_VERTICAL_INTERRUPT1_CONTROL	7

#define DCN_1_0__SRCID__OTG2_VERTICAL_INTERRUPT2_CONTROL	0x1F	
#define DCN_1_0__CTXID__OTG2_VERTICAL_INTERRUPT2_CONTROL	8

#define DCN_1_0__SRCID__OTG2_EXT_TIMING_SYNC_LOSS_INTERRUPT_CONTROL	0x1F	
#define DCN_1_0__CTXID__OTG2_EXT_TIMING_SYNC_LOSS_INTERRUPT_CONTROL	9

#define DCN_1_0__SRCID__OTG2_EXT_TIMING_SYNC_INTERRUPT_CONTROL	0x1F	
#define DCN_1_0__CTXID__OTG2_EXT_TIMING_SYNC_INTERRUPT_CONTROL	10

#define DCN_1_0__SRCID__OTG2_EXT_TIMING_SYNC_SIGNAL_INTERRUPT_CONTROL	0x1F	
#define DCN_1_0__CTXID__OTG2_EXT_TIMING_SYNC_SIGNAL_INTERRUPT_CONTROL	11

#define DCN_1_0__SRCID__OTG2_SET_VTOTAL_MIN_EVENT_INT	0x1F	
#define DCN_1_0__CTXID__OTG2_SET_VTOTAL_MIN_EVENT_INT	12

#define DCN_1_0__SRCID__DC_D3_OTG_SNAPSHOT	0x20	
#define DCN_1_0__CTXID__DC_D3_OTG_SNAPSHOT	0

#define DCN_1_0__SRCID__DC_D3_FORCE_CNT_W	0x20	
#define DCN_1_0__CTXID__DC_D3_FORCE_CNT_W	1

#define DCN_1_0__SRCID__DC_D3_FORCE_VSYNC_NXT_LINE	0x20	
#define DCN_1_0__CTXID__DC_D3_FORCE_VSYNC_NXT_LINE	2

#define DCN_1_0__SRCID__DC_D3_OTG_EXTT_TRG_A	0x20	
#define DCN_1_0__CTXID__DC_D3_OTG_EXTT_TRG_A	3

#define DCN_1_0__SRCID__DC_D3_OTG_EXTT_TRG_B	0x20	
#define DCN_1_0__CTXID__DC_D3_OTG_EXTT_TRG_B	4

#define DCN_1_0__SRCID__DC_D3_OTG_GSL_VSYNC_GAP	0x20	
#define DCN_1_0__CTXID__DC_D3_OTG_GSL_VSYNC_GAP	5

#define DCN_1_0__SRCID__OTG3_VERTICAL_INTERRUPT0_CONTROL	0x20	
#define DCN_1_0__CTXID__OTG3_VERTICAL_INTERRUPT0_CONTROL	6

#define DCN_1_0__SRCID__OTG3_VERTICAL_INTERRUPT1_CONTROL	0x20	
#define DCN_1_0__CTXID__OTG3_VERTICAL_INTERRUPT1_CONTROL	7

#define DCN_1_0__SRCID__OTG3_VERTICAL_INTERRUPT2_CONTROL	0x20	
#define DCN_1_0__CTXID__OTG3_VERTICAL_INTERRUPT2_CONTROL	8

#define DCN_1_0__SRCID__OTG3_EXT_TIMING_SYNC_LOSS_INTERRUPT_CONTROL	0x20	
#define DCN_1_0__CTXID__OTG3_EXT_TIMING_SYNC_LOSS_INTERRUPT_CONTROL	9

#define DCN_1_0__SRCID__OTG3_EXT_TIMING_SYNC_INTERRUPT_CONTROL	0x20	
#define DCN_1_0__CTXID__OTG3_EXT_TIMING_SYNC_INTERRUPT_CONTROL	10

#define DCN_1_0__SRCID__OTG3_EXT_TIMING_SYNC_SIGNAL_INTERRUPT_CONTROL	0x20	
#define DCN_1_0__CTXID__OTG3_EXT_TIMING_SYNC_SIGNAL_INTERRUPT_CONTROL	11

#define DCN_1_0__SRCID__OTG3_SET_VTOTAL_MIN_EVENT_INT	0x20	
#define DCN_1_0__CTXID__OTG3_SET_VTOTAL_MIN_EVENT_INT	12

#define DCN_1_0__SRCID__DC_D4_OTG_SNAPSHOT	0x21	
#define DCN_1_0__CTXID__DC_D4_OTG_SNAPSHOT	0

#define DCN_1_0__SRCID__DC_D4_FORCE_CNT_W	0x21	
#define DCN_1_0__CTXID__DC_D4_FORCE_CNT_W	1

#define DCN_1_0__SRCID__DC_D4_FORCE_VSYNC_NXT_LINE	0x21	
#define DCN_1_0__CTXID__DC_D4_FORCE_VSYNC_NXT_LINE	2

#define DCN_1_0__SRCID__DC_D4_OTG_EXTT_TRG_A	0x21	
#define DCN_1_0__CTXID__DC_D4_OTG_EXTT_TRG_A	3

#define DCN_1_0__SRCID__DC_D4_OTG_EXTT_TRG_B	0x21	
#define DCN_1_0__CTXID__DC_D4_OTG_EXTT_TRG_B	4

#define DCN_1_0__SRCID__DC_D4_OTG_GSL_VSYNC_GAP	0x21	
#define DCN_1_0__CTXID__DC_D4_OTG_GSL_VSYNC_GAP	5

#define DCN_1_0__SRCID__OTG4_VERTICAL_INTERRUPT0_CONTROL	0x21	
#define DCN_1_0__CTXID__OTG4_VERTICAL_INTERRUPT0_CONTROL	6

#define DCN_1_0__SRCID__OTG4_VERTICAL_INTERRUPT1_CONTROL	0x21	
#define DCN_1_0__CTXID__OTG4_VERTICAL_INTERRUPT1_CONTROL	7

#define DCN_1_0__SRCID__OTG4_VERTICAL_INTERRUPT2_CONTROL	0x21	
#define DCN_1_0__CTXID__OTG4_VERTICAL_INTERRUPT2_CONTROL	8

#define DCN_1_0__SRCID__OTG4_EXT_TIMING_SYNC_LOSS_INTERRUPT_CONTROL	0x21	
#define DCN_1_0__CTXID__OTG4_EXT_TIMING_SYNC_LOSS_INTERRUPT_CONTROL	9

#define DCN_1_0__SRCID__OTG4_EXT_TIMING_SYNC_INTERRUPT_CONTROL	0x21	
#define DCN_1_0__CTXID__OTG4_EXT_TIMING_SYNC_INTERRUPT_CONTROL	10

#define DCN_1_0__SRCID__OTG4_EXT_TIMING_SYNC_SIGNAL_INTERRUPT_CONTROL	0x21	
#define DCN_1_0__CTXID__OTG4_EXT_TIMING_SYNC_SIGNAL_INTERRUPT_CONTROL	11

#define DCN_1_0__SRCID__OTG4_SET_VTOTAL_MIN_EVENT_INT	0x21	
#define DCN_1_0__CTXID__OTG4_SET_VTOTAL_MIN_EVENT_INT	12

#define DCN_1_0__SRCID__DC_D5_OTG_SNAPSHOT	0x22	
#define DCN_1_0__CTXID__DC_D5_OTG_SNAPSHOT	0

#define DCN_1_0__SRCID__DC_D5_FORCE_CNT_W	0x22	
#define DCN_1_0__CTXID__DC_D5_FORCE_CNT_W	1

#define DCN_1_0__SRCID__DC_D5_FORCE_VSYNC_NXT_LINE	0x22	
#define DCN_1_0__CTXID__DC_D5_FORCE_VSYNC_NXT_LINE	2

#define DCN_1_0__SRCID__DC_D5_OTG_EXTT_TRG_A	0x22	
#define DCN_1_0__CTXID__DC_D5_OTG_EXTT_TRG_A	3

#define DCN_1_0__SRCID__DC_D5_OTG_EXTT_TRG_B	0x22	
#define DCN_1_0__CTXID__DC_D5_OTG_EXTT_TRG_B	4

#define DCN_1_0__SRCID__DC_D5_OTG_GSL_VSYNC_GAP	0x22	
#define DCN_1_0__CTXID__DC_D5_OTG_GSL_VSYNC_GAP	5

#define DCN_1_0__SRCID__OTG5_VERTICAL_INTERRUPT0_CONTROL	0x22	
#define DCN_1_0__CTXID__OTG5_VERTICAL_INTERRUPT0_CONTROL	6

#define DCN_1_0__SRCID__OTG5_VERTICAL_INTERRUPT1_CONTROL	0x22	
#define DCN_1_0__CTXID__OTG5_VERTICAL_INTERRUPT1_CONTROL	7

#define DCN_1_0__SRCID__OTG5_VERTICAL_INTERRUPT2_CONTROL	0x22	
#define DCN_1_0__CTXID__OTG5_VERTICAL_INTERRUPT2_CONTROL	8

#define DCN_1_0__SRCID__OTG5_EXT_TIMING_SYNC_LOSS_INTERRUPT_CONTROL	0x22	
#define DCN_1_0__CTXID__OTG5_EXT_TIMING_SYNC_LOSS_INTERRUPT_CONTROL	9

#define DCN_1_0__SRCID__OTG5_EXT_TIMING_SYNC_INTERRUPT_CONTROL	0x22	
#define DCN_1_0__CTXID__OTG5_EXT_TIMING_SYNC_INTERRUPT_CONTROL	10

#define DCN_1_0__SRCID__OTG5_EXT_TIMING_SYNC_SIGNAL_INTERRUPT_CONTROL	0x22	
#define DCN_1_0__CTXID__OTG5_EXT_TIMING_SYNC_SIGNAL_INTERRUPT_CONTROL	11

#define DCN_1_0__SRCID__OTG5_SET_VTOTAL_MIN_EVENT_INT	0x22	
#define DCN_1_0__CTXID__OTG5_SET_VTOTAL_MIN_EVENT_INT	12

#define DCN_1_0__SRCID__DC_D1_VBLANK	0x23	
#define DCN_1_0__CTXID__DC_D1_VBLANK	0

#define DCN_1_0__SRCID__DC_D1_VLINE1	0x23	
#define DCN_1_0__CTXID__DC_D1_VLINE1	1

#define DCN_1_0__SRCID__DC_D1_VLINE2	0x23	
#define DCN_1_0__CTXID__DC_D1_VLINE2	2

#define DCN_1_0__SRCID__DC_D2_VBLANK	0x23	
#define DCN_1_0__CTXID__DC_D2_VBLANK	3

#define DCN_1_0__SRCID__DC_D2_VLINE1	0x23	
#define DCN_1_0__CTXID__DC_D2_VLINE1	4

#define DCN_1_0__SRCID__DC_D2_VLINE2	0x23	
#define DCN_1_0__CTXID__DC_D2_VLINE2	5

#define DCN_1_0__SRCID__HUBP0_IHC_VM_CONTEXT_ERROR	0x23	
#define DCN_1_0__CTXID__HUBP0_IHC_VM_CONTEXT_ERROR	6

#define DCN_1_0__SRCID__HUBP1_IHC_VM_CONTEXT_ERROR	0x23	
#define DCN_1_0__CTXID__HUBP1_IHC_VM_CONTEXT_ERROR	7

#define DCN_1_0__SRCID__HUBP2_IHC_VM_CONTEXT_ERROR	0x23	
#define DCN_1_0__CTXID__HUBP2_IHC_VM_CONTEXT_ERROR	8

#define DCN_1_0__SRCID__HUBP3_IHC_VM_CONTEXT_ERROR	0x23	
#define DCN_1_0__CTXID__HUBP3_IHC_VM_CONTEXT_ERROR	9

#define DCN_1_0__SRCID__HUBP4_IHC_VM_CONTEXT_ERROR	0x23	
#define DCN_1_0__CTXID__HUBP4_IHC_VM_CONTEXT_ERROR	10

#define DCN_1_0__SRCID__HUBP5_IHC_VM_CONTEXT_ERROR	0x23	
#define DCN_1_0__CTXID__HUBP5_IHC_VM_CONTEXT_ERROR	11

#define DCN_1_0__SRCID__HUBP6_IHC_VM_CONTEXT_ERROR	0x23	
#define DCN_1_0__CTXID__HUBP6_IHC_VM_CONTEXT_ERROR	12

#define DCN_1_0__SRCID__HUBP7_IHC_VM_CONTEXT_ERROR	0x23	
#define DCN_1_0__CTXID__HUBP7_IHC_VM_CONTEXT_ERROR	13

#define DCN_1_0__SRCID__DPP0_PERFCOUNTER_INT0_STATUS	0x24	
#define DCN_1_0__CTXID__DPP0_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__DPP0_PERFCOUNTER_INT1_STATUS	0x24	
#define DCN_1_0__CTXID__DPP0_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__DC_D3_VBLANK	0x24	
#define DCN_1_0__CTXID__DC_D3_VBLANK	9

#define DCN_1_0__SRCID__DC_D3_VLINE1	0x24	
#define DCN_1_0__CTXID__DC_D3_VLINE1	10

#define DCN_1_0__SRCID__DC_D3_VLINE2	0x24	
#define DCN_1_0__CTXID__DC_D3_VLINE2	11

#define DCN_1_0__SRCID__DC_D4_VBLANK	0x24	
#define DCN_1_0__CTXID__DC_D4_VBLANK	12

#define DCN_1_0__SRCID__DC_D4_VLINE1	0x24	
#define DCN_1_0__CTXID__DC_D4_VLINE1	13

#define DCN_1_0__SRCID__DC_D4_VLINE2	0x24	
#define DCN_1_0__CTXID__DC_D4_VLINE2	14

#define DCN_1_0__SRCID__DPP1_PERFCOUNTER_INT0_STATUS	0x25	
#define DCN_1_0__CTXID__DPP1_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__DPP1_PERFCOUNTER_INT1_STATUS	0x25	
#define DCN_1_0__CTXID__DPP1_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__DC_D5_VBLANK	0x25	
#define DCN_1_0__CTXID__DC_D5_VBLANK	9

#define DCN_1_0__SRCID__DC_D5_VLINE1	0x25	
#define DCN_1_0__CTXID__DC_D5_VLINE1	10

#define DCN_1_0__SRCID__DC_D5_VLINE2	0x25	
#define DCN_1_0__CTXID__DC_D5_VLINE2	11

#define DCN_1_0__SRCID__DC_D6_VBLANK	0x25	
#define DCN_1_0__CTXID__DC_D6_VBLANK	12

#define DCN_1_0__SRCID__DC_D6_VLINE1	0x25	
#define DCN_1_0__CTXID__DC_D6_VLINE1	13

#define DCN_1_0__SRCID__DC_D6_VLINE2	0x25	
#define DCN_1_0__CTXID__DC_D6_VLINE2	14

#define DCN_1_0__SRCID__DPP2_PERFCOUNTER_INT0_STATUS	0x26	
#define DCN_1_0__CTXID__DPP2_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__DPP2_PERFCOUNTER_INT1_STATUS	0x26	
#define DCN_1_0__CTXID__DPP2_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__DC_D7_VBLANK	0x26	
#define DCN_1_0__CTXID__DC_D7_VBLANK	9

#define DCN_1_0__SRCID__DC_D7_VLINE1	0x26	
#define DCN_1_0__CTXID__DC_D7_VLINE1	10

#define DCN_1_0__SRCID__DC_D7_VLINE2	0x26	
#define DCN_1_0__CTXID__DC_D7_VLINE2	11

#define DCN_1_0__SRCID__DC_D8_VBLANK	0x26	
#define DCN_1_0__CTXID__DC_D8_VBLANK	12

#define DCN_1_0__SRCID__DC_D8_VLINE1	0x26	
#define DCN_1_0__CTXID__DC_D8_VLINE1	13

#define DCN_1_0__SRCID__DC_D8_VLINE2	0x26	
#define DCN_1_0__CTXID__DC_D8_VLINE2	14

#define DCN_1_0__SRCID__DPP3_PERFCOUNTER_INT0_STATUS	0x27	
#define DCN_1_0__CTXID__DPP3_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__DPP3_PERFCOUNTER_INT1_STATUS	0x27	
#define DCN_1_0__CTXID__DPP3_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__DPP4_PERFCOUNTER_INT0_STATUS	0x28	
#define DCN_1_0__CTXID__DPP4_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__DPP4_PERFCOUNTER_INT1_STATUS	0x28	
#define DCN_1_0__CTXID__DPP4_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__DPP5_PERFCOUNTER_INT0_STATUS	0x29	
#define DCN_1_0__CTXID__DPP5_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__DPP5_PERFCOUNTER_INT1_STATUS	0x29	
#define DCN_1_0__CTXID__DPP5_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__DPP6_PERFCOUNTER_INT0_STATUS	0x2A	
#define DCN_1_0__CTXID__DPP6_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__DPP6_PERFCOUNTER_INT1_STATUS	0x2A	
#define DCN_1_0__CTXID__DPP6_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__DPP7_PERFCOUNTER_INT0_STATUS	0x2B	
#define DCN_1_0__CTXID__DPP7_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__DPP7_PERFCOUNTER_INT1_STATUS	0x2B	
#define DCN_1_0__CTXID__DPP7_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__HUBP0_PERFCOUNTER_INT0_STATUS	0x2C	
#define DCN_1_0__CTXID__HUBP0_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__HUBP0_PERFCOUNTER_INT1_STATUS	0x2C	
#define DCN_1_0__CTXID__HUBP0_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__HUBP1_PERFCOUNTER_INT0_STATUS	0x2D	
#define DCN_1_0__CTXID__HUBP1_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__HUBP1_PERFCOUNTER_INT1_STATUS	0x2D	
#define DCN_1_0__CTXID__HUBP1_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__HUBP2_PERFCOUNTER_INT0_STATUS	0x2E	
#define DCN_1_0__CTXID__HUBP2_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__HUBP2_PERFCOUNTER_INT1_STATUS	0x2E	
#define DCN_1_0__CTXID__HUBP2_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__HUBP3_PERFCOUNTER_INT0_STATUS	0x2F	
#define DCN_1_0__CTXID__HUBP3_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__HUBP3_PERFCOUNTER_INT1_STATUS	0x2F	
#define DCN_1_0__CTXID__HUBP3_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__HUBP4_PERFCOUNTER_INT0_STATUS	0x30	
#define DCN_1_0__CTXID__HUBP4_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__HUBP4_PERFCOUNTER_INT1_STATUS	0x30	
#define DCN_1_0__CTXID__HUBP4_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__HUBP5_PERFCOUNTER_INT0_STATUS	0x31	
#define DCN_1_0__CTXID__HUBP5_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__HUBP5_PERFCOUNTER_INT1_STATUS	0x31	
#define DCN_1_0__CTXID__HUBP5_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__HUBP6_PERFCOUNTER_INT0_STATUS	0x32	
#define DCN_1_0__CTXID__HUBP6_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__HUBP6_PERFCOUNTER_INT1_STATUS	0x32	
#define DCN_1_0__CTXID__HUBP6_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__HUBP7_PERFCOUNTER_INT0_STATUS	0x33	
#define DCN_1_0__CTXID__HUBP7_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__HUBP7_PERFCOUNTER_INT1_STATUS	0x33	
#define DCN_1_0__CTXID__HUBP7_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__WB1_PERFCOUNTER_INT0_STATUS	0x34	
#define DCN_1_0__CTXID__WB1_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__WB1_PERFCOUNTER_INT1_STATUS	0x34	
#define DCN_1_0__CTXID__WB1_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__HUBBUB_PERFCOUNTER_INT0_STATUS	0x35	
#define DCN_1_0__CTXID__HUBBUB_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__HUBBUB_PERFCOUNTER_INT1_STATUS	0x35	
#define DCN_1_0__CTXID__HUBBUB_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__MPC_PERFCOUNTER_INT0_STATUS	0x36	
#define DCN_1_0__CTXID__MPC_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__MPC_PERFCOUNTER_INT1_STATUS	0x36	
#define DCN_1_0__CTXID__MPC_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__OPP_PERFCOUNTER_INT0_STATUS	0x37	
#define DCN_1_0__CTXID__OPP_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__OPP_PERFCOUNTER_INT1_STATUS	0x37	
#define DCN_1_0__CTXID__OPP_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__DC_D6_OTG_SNAPSHOT	0x38	
#define DCN_1_0__CTXID__DC_D6_OTG_SNAPSHOT	0

#define DCN_1_0__SRCID__DC_D6_FORCE_CNT_W	0x38	
#define DCN_1_0__CTXID__DC_D6_FORCE_CNT_W	1

#define DCN_1_0__SRCID__DC_D6_FORCE_VSYNC_NXT_LINE	0x38	
#define DCN_1_0__CTXID__DC_D6_FORCE_VSYNC_NXT_LINE	2

#define DCN_1_0__SRCID__DC_D6_OTG_EXTT_TRG_A	0x38	
#define DCN_1_0__CTXID__DC_D6_OTG_EXTT_TRG_A	3

#define DCN_1_0__SRCID__DC_D6_OTG_EXTT_TRG_B	0x38	
#define DCN_1_0__CTXID__DC_D6_OTG_EXTT_TRG_B	4

#define DCN_1_0__SRCID__DC_D6_OTG_GSL_VSYNC_GAP	0x38	
#define DCN_1_0__CTXID__DC_D6_OTG_GSL_VSYNC_GAP	5

#define DCN_1_0__SRCID__OTG6_VERTICAL_INTERRUPT0_CONTROL	0x38	
#define DCN_1_0__CTXID__OTG6_VERTICAL_INTERRUPT0_CONTROL	6

#define DCN_1_0__SRCID__OTG6_VERTICAL_INTERRUPT1_CONTROL	0x38	
#define DCN_1_0__CTXID__OTG6_VERTICAL_INTERRUPT1_CONTROL	7

#define DCN_1_0__SRCID__OTG6_VERTICAL_INTERRUPT2_CONTROL	0x38	
#define DCN_1_0__CTXID__OTG6_VERTICAL_INTERRUPT2_CONTROL	8

#define DCN_1_0__SRCID__OTG6_EXT_TIMING_SYNC_LOSS_INTERRUPT_CONTROL	0x38	
#define DCN_1_0__CTXID__OTG6_EXT_TIMING_SYNC_LOSS_INTERRUPT_CONTROL	9

#define DCN_1_0__SRCID__OTG6_EXT_TIMING_SYNC_INTERRUPT_CONTROL	0x38	
#define DCN_1_0__CTXID__OTG6_EXT_TIMING_SYNC_INTERRUPT_CONTROL	10

#define DCN_1_0__SRCID__OTG6_EXT_TIMING_SYNC_SIGNAL_INTERRUPT_CONTROL	0x38	
#define DCN_1_0__CTXID__OTG6_EXT_TIMING_SYNC_SIGNAL_INTERRUPT_CONTROL	11

#define DCN_1_0__SRCID__OTG6_SET_VTOTAL_MIN_EVENT_INT	0x38	
#define DCN_1_0__CTXID__OTG6_SET_VTOTAL_MIN_EVENT_INT	12

#define DCN_1_0__SRCID__OPTC_PERFCOUNTER_INT0_STATUS	0x39	
#define DCN_1_0__CTXID__OPTC_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__OPTC_PERFCOUNTER_INT1_STATUS	0x39	
#define DCN_1_0__CTXID__OPTC_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__MMHUBBUB_PERFCOUNTER_INT0_STATUS	0x3A	
#define DCN_1_0__CTXID__MMHUBBUB_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__MMHUBBUB_PERFCOUNTER_INT1_STATUS	0x3A	
#define DCN_1_0__CTXID__MMHUBBUB_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__AZ_PERFCOUNTER_INT0_STATUS	0x3B	
#define DCN_1_0__CTXID__AZ_PERFCOUNTER_INT0_STATUS	0

#define DCN_1_0__SRCID__AZ_PERFCOUNTER_INT1_STATUS	0x3B	
#define DCN_1_0__CTXID__AZ_PERFCOUNTER_INT1_STATUS	1

#define DCN_1_0__SRCID__DC_D1_OTG_VSTARTUP	0x3C	
#define DCN_1_0__SRCID__DC_D2_OTG_VSTARTUP	0x3D	
#define DCN_1_0__SRCID__DC_D3_OTG_VSTARTUP	0x3E	
#define DCN_1_0__SRCID__DC_D4_OTG_VSTARTUP	0x3F	
#define DCN_1_0__SRCID__DC_D5_OTG_VSTARTUP	0x40	
#define DCN_1_0__SRCID__DC_D6_OTG_VSTARTUP	0x41	

#define DCN_1_0__SRCID__DC_D1_OTG_VREADY	0x42	
#define DCN_1_0__SRCID__DC_D2_OTG_VREADY	0x43	
#define DCN_1_0__SRCID__DC_D3_OTG_VREADY	0x44	
#define DCN_1_0__SRCID__DC_D4_OTG_VREADY	0x45	
#define DCN_1_0__SRCID__DC_D5_OTG_VREADY	0x46	
#define DCN_1_0__SRCID__DC_D6_OTG_VREADY	0x47	

#define DCN_1_0__SRCID__OTG0_VSYNC_NOM	0x48	
#define DCN_1_0__SRCID__OTG1_VSYNC_NOM	0x49	
#define DCN_1_0__SRCID__OTG2_VSYNC_NOM	0x4A	
#define DCN_1_0__SRCID__OTG3_VSYNC_NOM	0x4B	
#define DCN_1_0__SRCID__OTG4_VSYNC_NOM	0x4C	
#define DCN_1_0__SRCID__OTG5_VSYNC_NOM	0x4D	

#define DCN_1_0__SRCID__DCPG_DCFE8_POWER_UP_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE8_POWER_UP_INT	0

#define DCN_1_0__SRCID__DCPG_DCFE9_POWER_UP_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE9_POWER_UP_INT	1

#define DCN_1_0__SRCID__DCPG_DCFE10_POWER_UP_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE10_POWER_UP_INT	2

#define DCN_1_0__SRCID__DCPG_DCFE11_POWER_UP_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE11_POWER_UP_INT	3

#define DCN_1_0__SRCID__DCPG_DCFE12_POWER_UP_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE12_POWER_UP_INT	4

#define DCN_1_0__SRCID__DCPG_DCFE13_POWER_UP_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE13_POWER_UP_INT	5

#define DCN_1_0__SRCID__DCPG_DCFE14_POWER_UP_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE14_POWER_UP_INT	6

#define DCN_1_0__SRCID__DCPG_DCFE15_POWER_UP_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE15_POWER_UP_INT	7

#define DCN_1_0__SRCID__DCPG_DCFE8_POWER_DOWN_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE8_POWER_DOWN_INT	8

#define DCN_1_0__SRCID__DCPG_DCFE9_POWER_DOWN_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE9_POWER_DOWN_INT	9

#define DCN_1_0__SRCID__DCPG_DCFE10_POWER_DOWN_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE10_POWER_DOWN_INT	10

#define DCN_1_0__SRCID__DCPG_DCFE11_POWER_DOWN_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE11_POWER_DOWN_INT	11

#define DCN_1_0__SRCID__DCPG_DCFE12_POWER_DOWN_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE12_POWER_DOWN_INT	12

#define DCN_1_0__SRCID__DCPG_DCFE13_POWER_DOWN_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE13_POWER_DOWN_INT	13

#define DCN_1_0__SRCID__DCPG_DCFE14_POWER_DOWN_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE14_POWER_DOWN_INT	14

#define DCN_1_0__SRCID__DCPG_DCFE15_POWER_DOWN_INT	0x4E	
#define DCN_1_0__CTXID__DCPG_DCFE15_POWER_DOWN_INT	15

#define DCN_1_0__SRCID__HUBP0_FLIP_INTERRUPT	0x4F	
#define DCN_1_0__SRCID__HUBP1_FLIP_INTERRUPT	0x50	
#define DCN_1_0__SRCID__HUBP2_FLIP_INTERRUPT	0x51	
#define DCN_1_0__SRCID__HUBP3_FLIP_INTERRUPT	0x52	
#define DCN_1_0__SRCID__HUBP4_FLIP_INTERRUPT	0x53	
#define DCN_1_0__SRCID__HUBP5_FLIP_INTERRUPT	0x54	
#define DCN_1_0__SRCID__HUBP6_FLIP_INTERRUPT	0x55	
#define DCN_1_0__SRCID__HUBP7_FLIP_INTERRUPT	0x56	

#define DCN_1_0__SRCID__OTG0_IHC_V_UPDATE_NO_LOCK_INTERRUPT	0x57	
#define DCN_1_0__SRCID__OTG1_IHC_V_UPDATE_NO_LOCK_INTERRUPT	0x58	
#define DCN_1_0__SRCID__OTG2_IHC_V_UPDATE_NO_LOCK_INTERRUPT	0x59	
#define DCN_1_0__SRCID__OTG3_IHC_V_UPDATE_NO_LOCK_INTERRUPT	0x5A	
#define DCN_1_0__SRCID__OTG4_IHC_V_UPDATE_NO_LOCK_INTERRUPT	0x5B	
#define DCN_1_0__SRCID__OTG5_IHC_V_UPDATE_NO_LOCK_INTERRUPT	0x5C	

#define DCN_1_0__SRCID__HUBP0_FLIP_AWAY_INTERRUPT	0x5D	
#define DCN_1_0__SRCID__HUBP1_FLIP_AWAY_INTERRUPT	0x5E	
#define DCN_1_0__SRCID__HUBP2_FLIP_AWAY_INTERRUPT	0x5F	
#define DCN_1_0__SRCID__HUBP3_FLIP_AWAY_INTERRUPT	0x60	
#define DCN_1_0__SRCID__HUBP4_FLIP_AWAY_INTERRUPT	0x61	
#define DCN_1_0__SRCID__HUBP5_FLIP_AWAY_INTERRUPT	0x62	
#define DCN_1_0__SRCID__HUBP6_FLIP_AWAY_INTERRUPT	0x63	
#define DCN_1_0__SRCID__HUBP7_FLIP_AWAY_INTERRUPT	0x64	

#define DCN_1_0__SRCID__DMCUB_OUTBOX_HIGH_PRIORITY_READY_INT       0x68
#define DCN_1_0__CTXID__DMCUB_OUTBOX_HIGH_PRIORITY_READY_INT       6
#define DCN_1_0__SRCID__DMCUB_OUTBOX_LOW_PRIORITY_READY_INT        0x68 
#define DCN_1_0__CTXID__DMCUB_OUTBOX_LOW_PRIORITY_READY_INT        8

#endif 
