{
  "module_name": "Makefile",
  "hash_id": "ac81aaf6f547ebca9cb910ab8dea81019debd497df72f6f4bec5e593be7f7634",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/marvell/libertas/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nlibertas-y += cfg.o\nlibertas-y += cmd.o\nlibertas-y += cmdresp.o\nlibertas-y += debugfs.o\nlibertas-y += ethtool.o\nlibertas-y += main.o\nlibertas-y += rx.o\nlibertas-y += tx.o\nlibertas-y += firmware.o\nlibertas-$(CONFIG_LIBERTAS_MESH) += mesh.o\n\nusb8xxx-objs += if_usb.o\nlibertas_cs-objs += if_cs.o\nlibertas_sdio-objs += if_sdio.o\nlibertas_spi-objs += if_spi.o\n\nobj-$(CONFIG_LIBERTAS)     += libertas.o\nobj-$(CONFIG_LIBERTAS_USB) += usb8xxx.o\nobj-$(CONFIG_LIBERTAS_CS)  += libertas_cs.o\nobj-$(CONFIG_LIBERTAS_SDIO) += libertas_sdio.o\nobj-$(CONFIG_LIBERTAS_SPI) += libertas_spi.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}