{
  "module_name": "Makefile",
  "hash_id": "eae4bf85f86d9b18035f64107cf7a18adb3dca0deda3e3fe88a7540ef674b859",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/realtek/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the Realtek network device drivers.\n#\n\nobj-$(CONFIG_8139CP) += 8139cp.o\nobj-$(CONFIG_8139TOO) += 8139too.o\nobj-$(CONFIG_ATP) += atp.o\nr8169-objs += r8169_main.o r8169_firmware.o r8169_phy_config.o\nobj-$(CONFIG_R8169) += r8169.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}