{
  "module_name": "Makefile",
  "hash_id": "4eb64c44273a75cf46bcf556fd07ff5ff8dab39a91522f860068550d5b103d5c",
  "original_prompt": "Ingested from linux-6.6.14/drivers/accel/habanalabs/common/pci/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nHL_COMMON_PCI_FILES := common/pci/pci.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}