{
  "module_name": "Makefile",
  "hash_id": "2156928a70ee8cc793489bb12a1850012ddccb526520fe1501462c8189fa65aa",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/filelock/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\nTEST_GEN_PROGS := ofdlocks\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}