{
  "module_name": "Makefile",
  "hash_id": "46ed159c2a23b3206ed897206b8902eb796c142ac724db8319da5db61aa69465",
  "original_prompt": "Ingested from linux-6.6.14/drivers/acpi/apei/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_ACPI_APEI)\t\t+= apei.o\nobj-$(CONFIG_ACPI_APEI_GHES)\t+= ghes.o\nobj-$(CONFIG_ACPI_APEI_EINJ)\t+= einj.o\nobj-$(CONFIG_ACPI_APEI_ERST_DEBUG) += erst-dbg.o\n\napei-y := apei-base.o hest.o erst.o bert.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}