{
  "module_name": "Makefile",
  "hash_id": "0e050ba8ab8c6be5ba054d87b1f6676c34f8573aa589427438e8b896c2c44ab2",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/pci/cx25821/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\ncx25821-y   := cx25821-core.o cx25821-cards.o cx25821-i2c.o \\\n\t\t       cx25821-gpio.o cx25821-medusa-video.o \\\n\t\t       cx25821-video.o\n\nobj-$(CONFIG_VIDEO_CX25821) += cx25821.o\nobj-$(CONFIG_VIDEO_CX25821_ALSA) += cx25821-alsa.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}