{
  "module_name": "Makefile",
  "hash_id": "9b91755ed2f7b616dac5876fc045de73cca9b03e0a4f65cd39e37fcb73e93dc7",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/can/usb/peak_usb/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_CAN_PEAK_USB) += peak_usb.o\npeak_usb-y = pcan_usb_core.o pcan_usb.o pcan_usb_pro.o pcan_usb_fd.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}