{
  "module_name": "Makefile",
  "hash_id": "b9f56ae6c83683e2c650791af4ee9e9e168cb368595c33a904e58607599d3537",
  "original_prompt": "Ingested from linux-6.6.14/drivers/clk/mmp/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for mmp specific clk\n#\n\nobj-y += clk-apbc.o clk-apmu.o clk-frac.o clk-mix.o clk-gate.o clk.o\n\nobj-$(CONFIG_RESET_CONTROLLER) += reset.o\n\nobj-$(CONFIG_MACH_MMP_DT) += clk-of-pxa168.o clk-of-pxa910.o\nobj-$(CONFIG_COMMON_CLK_MMP2) += clk-of-mmp2.o clk-pll.o pwr-island.o\nobj-$(CONFIG_COMMON_CLK_MMP2_AUDIO) += clk-audio.o\n\nobj-y += clk-of-pxa1928.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}