 

 

#if !defined (BUFSIZ)
#include <stdio.h>
#endif  

#include "readline.h"

#if 0
extern KEYMAP_ENTRY_ARRAY vi_escape_keymap;
#endif

 
KEYMAP_ENTRY_ARRAY vi_movement_keymap = {
   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_eof_maybe },			 
  { ISFUNC, rl_emacs_editing_mode },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_abort },				 
  { ISFUNC, rl_backward_char },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_newline },			 
  { ISFUNC, rl_kill_line },			 
  { ISFUNC, rl_clear_screen },			 
  { ISFUNC, rl_newline },			 
  { ISFUNC, rl_get_next_history },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_get_previous_history },		 
  { ISFUNC, rl_quoted_insert },			 
  { ISFUNC, rl_reverse_search_history },	 
  { ISFUNC, rl_forward_search_history },	 
  { ISFUNC, rl_transpose_chars },		 
  { ISFUNC, rl_unix_line_discard },		 
  { ISFUNC, rl_quoted_insert },			 
  { ISFUNC, rl_vi_unix_word_rubout },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_yank },				 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

  { ISFUNC, (rl_command_func_t *)0x0 },		 	 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_undo },			 

   
  { ISFUNC, rl_forward_char },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_insert_comment },		 
  { ISFUNC, rl_end_of_line },			 
  { ISFUNC, rl_vi_match },			 
  { ISFUNC, rl_vi_tilde_expand },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_complete },			 
  { ISFUNC, rl_get_next_history},		 
  { ISFUNC, rl_vi_char_search },		 
  { ISFUNC, rl_get_previous_history },		 
  { ISFUNC, rl_vi_redo },			 
  { ISFUNC, rl_vi_search },			 

   
  { ISFUNC, rl_beg_of_line },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 

   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_char_search },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_complete },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_search },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

   
  { ISFUNC, rl_vi_append_eol },			 
  { ISFUNC, rl_vi_prev_word},			 
  { ISFUNC, rl_vi_change_to },			 
  { ISFUNC, rl_vi_delete_to },			 
  { ISFUNC, rl_vi_end_word },			 
  { ISFUNC, rl_vi_char_search },		 
  { ISFUNC, rl_vi_fetch_history },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_insert_beg },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_search_again },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_put },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_replace },			 
  { ISFUNC, rl_vi_subst },			 
  { ISFUNC, rl_vi_char_search },		 
  { ISFUNC, rl_revert_line },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_next_word },			 
  { ISFUNC, rl_vi_rubout },			 
  { ISFUNC, rl_vi_yank_to },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_complete },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_first_print },		 
  { ISFUNC, rl_vi_yank_arg },			 
  { ISFUNC, rl_vi_goto_mark },			 

   
  { ISFUNC, rl_vi_append_mode },		 
  { ISFUNC, rl_vi_prev_word },			 
  { ISFUNC, rl_vi_change_to },			 
  { ISFUNC, rl_vi_delete_to },			 
  { ISFUNC, rl_vi_end_word },			 
  { ISFUNC, rl_vi_char_search },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_backward_char },			 
  { ISFUNC, rl_vi_insert_mode },		 
  { ISFUNC, rl_get_next_history },		 
  { ISFUNC, rl_get_previous_history },		 
  { ISFUNC, rl_forward_char },			 
  { ISFUNC, rl_vi_set_mark },			 
  { ISFUNC, rl_vi_search_again },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_put },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_change_char },		 
  { ISFUNC, rl_vi_subst },			 
  { ISFUNC, rl_vi_char_search },		 
  { ISFUNC, rl_vi_undo },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_next_word },			 
  { ISFUNC, rl_vi_delete },			 
  { ISFUNC, rl_vi_yank_to },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_column },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_change_case },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

#if KEYMAP_SIZE > 128
   
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 }
#endif  
};

KEYMAP_ENTRY_ARRAY vi_insertion_keymap = {
   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_vi_eof_maybe },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_rubout },			 
  { ISFUNC, rl_complete },			 
  { ISFUNC, rl_newline },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_newline },			 
  { ISFUNC, rl_menu_complete},			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_backward_menu_complete },	 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_reverse_search_history },	 
  { ISFUNC, rl_forward_search_history },	 
  { ISFUNC, rl_transpose_chars },		 
  { ISFUNC, rl_unix_line_discard },		 
  { ISFUNC, rl_quoted_insert },			 
  { ISFUNC, rl_vi_unix_word_rubout },		 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_yank },				 
  { ISFUNC, rl_insert },			 

  { ISFUNC, rl_vi_movement_mode },		 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_vi_undo },			 

   
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 

   
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 

   
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 

   
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 

   
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 

   
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 

   
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_insert },			 
  { ISFUNC, rl_rubout },			 

#if KEYMAP_SIZE > 128
   
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 

   
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert }		 
#endif  
};

 
#if 0
KEYMAP_ENTRY_ARRAY vi_escape_keymap = {
   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_tab_insert},			 
  { ISFUNC, rl_emacs_editing_mode},		 
  { ISFUNC, rl_kill_line },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_emacs_editing_mode},		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

  { ISFUNC, rl_vi_movement_mode },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_vi_undo },			 

   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

   
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 
  { ISFUNC, rl_vi_arg_digit },			 

   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

   
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 

   
  { ISFUNC, rl_arrow_keys },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_arrow_keys },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_backward_kill_word },		 

#if KEYMAP_SIZE > 128
   
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 }
#endif  
};
#endif
