{
  "module_name": "Makefile",
  "hash_id": "4f06257839110d75b06d660b2d76e5ff3032d85fdfd9681b00b1a95abfa16393",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/platform/ti/omap3isp/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for OMAP3 ISP driver\n\nccflags-$(CONFIG_VIDEO_OMAP3_DEBUG) += -DDEBUG\n\nomap3-isp-objs += \\\n\tisp.o ispvideo.o \\\n\tispcsiphy.o ispccp2.o ispcsi2.o \\\n\tispccdc.o isppreview.o ispresizer.o \\\n\tispstat.o isph3a_aewb.o isph3a_af.o isphist.o\n\nobj-$(CONFIG_VIDEO_OMAP3) += omap3-isp.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}