{
  "module_name": "Makefile",
  "hash_id": "c1a38bc0fb6c255c1d3f5d8de18e5b1c82c927c6dddbbbb2af82d6737554d24a",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/qualcomm/rmnet/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the RMNET module\n#\n\nrmnet-y\t\t := rmnet_config.o\nrmnet-y\t\t += rmnet_vnd.o\nrmnet-y\t\t += rmnet_handlers.o\nrmnet-y\t\t += rmnet_map_data.o\nrmnet-y\t\t += rmnet_map_command.o\nobj-$(CONFIG_RMNET) += rmnet.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}