{
  "module_name": "Makefile",
  "hash_id": "ddd827713e9579d72c60d4403fd3772abd05709a2855e63f2f612c95b33684af",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/dwc/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n# SYNOPSYS Platform Support\nobj-$(CONFIG_SND_DESIGNWARE_I2S) += designware_i2s.o\n\ndesignware_i2s-y := dwc-i2s.o\ndesignware_i2s-$(CONFIG_SND_DESIGNWARE_PCM) += dwc-pcm.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}