{
  "module_name": "Makefile",
  "hash_id": "95329e97259eb82d7f7ff88e7b283cc6f741aa4e8cfdc7e5549da5d1974c4158",
  "original_prompt": "Ingested from linux-6.6.14/security/integrity/evm/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for building the Extended Verification Module(EVM)\n#\nobj-$(CONFIG_EVM) += evm.o\n\nevm-y := evm_main.o evm_crypto.o evm_secfs.o\nevm-$(CONFIG_FS_POSIX_ACL) += evm_posix_acl.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}