{
  "module_name": "Makefile",
  "hash_id": "a0278487e5904f00eaa4380e79df7f2df7476cad45a22975c6c3bf9c6f3e8b36",
  "original_prompt": "Ingested from linux-6.6.14/drivers/crypto/marvell/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\nobj-$(CONFIG_CRYPTO_DEV_MARVELL_CESA) += cesa/\nobj-$(CONFIG_CRYPTO_DEV_OCTEONTX_CPT) += octeontx/\nobj-$(CONFIG_CRYPTO_DEV_OCTEONTX2_CPT) += octeontx2/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}