{
  "module_name": "Makefile",
  "hash_id": "2f61fe9466dd814930b534fc086d43f7fc4b022e5f2d293ab8fcb1f7bcaa150d",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/cgroup/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nCFLAGS += -Wall -pthread\n\nall: ${HELPER_PROGS}\n\nTEST_FILES     := with_stress.sh\nTEST_PROGS     := test_stress.sh test_cpuset_prs.sh\nTEST_GEN_FILES := wait_inotify\nTEST_GEN_PROGS = test_memcontrol\nTEST_GEN_PROGS += test_kmem\nTEST_GEN_PROGS += test_core\nTEST_GEN_PROGS += test_freezer\nTEST_GEN_PROGS += test_kill\nTEST_GEN_PROGS += test_cpu\nTEST_GEN_PROGS += test_cpuset\nTEST_GEN_PROGS += test_zswap\n\nLOCAL_HDRS += $(selfdir)/clone3/clone3_selftests.h $(selfdir)/pidfd/pidfd.h\n\ninclude ../lib.mk\n\n$(OUTPUT)/test_memcontrol: cgroup_util.c\n$(OUTPUT)/test_kmem: cgroup_util.c\n$(OUTPUT)/test_core: cgroup_util.c\n$(OUTPUT)/test_freezer: cgroup_util.c\n$(OUTPUT)/test_kill: cgroup_util.c\n$(OUTPUT)/test_cpu: cgroup_util.c\n$(OUTPUT)/test_cpuset: cgroup_util.c\n$(OUTPUT)/test_zswap: cgroup_util.c\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}