{
  "module_name": "Makefile",
  "hash_id": "175711ffa08e69c3b5ac5aef1bb27b7a1fb2386f1eacdf072c66bddb68c10196",
  "original_prompt": "Ingested from linux-6.6.14/net/bluetooth/rfcomm/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the Linux Bluetooth RFCOMM layer.\n#\n\nobj-$(CONFIG_BT_RFCOMM) += rfcomm.o\n\nrfcomm-y\t\t\t:= core.o sock.o\nrfcomm-$(CONFIG_BT_RFCOMM_TTY)\t+= tty.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}