 
 

#ifndef _KS_WLAN_IOCTL_H
#define _KS_WLAN_IOCTL_H

#include <linux/wireless.h>
 

 
 
 
#define KS_WLAN_GET_FIRM_VERSION	(SIOCIWFIRSTPRIV + 3)
#define KS_WLAN_SET_WPS_ENABLE		(SIOCIWFIRSTPRIV + 4)
#define KS_WLAN_GET_WPS_ENABLE		(SIOCIWFIRSTPRIV + 5)
#define KS_WLAN_SET_WPS_PROBE_REQ	(SIOCIWFIRSTPRIV + 6)
#define KS_WLAN_GET_EEPROM_CKSUM	(SIOCIWFIRSTPRIV + 7)
#define KS_WLAN_SET_PREAMBLE		(SIOCIWFIRSTPRIV + 8)
#define KS_WLAN_GET_PREAMBLE		(SIOCIWFIRSTPRIV + 9)
#define KS_WLAN_SET_POWER_SAVE		(SIOCIWFIRSTPRIV + 10)
#define KS_WLAN_GET_POWER_SAVE		(SIOCIWFIRSTPRIV + 11)
#define KS_WLAN_SET_SCAN_TYPE		(SIOCIWFIRSTPRIV + 12)
#define KS_WLAN_GET_SCAN_TYPE		(SIOCIWFIRSTPRIV + 13)
#define KS_WLAN_SET_RX_GAIN		(SIOCIWFIRSTPRIV + 14)
#define KS_WLAN_GET_RX_GAIN		(SIOCIWFIRSTPRIV + 15)
#define KS_WLAN_HOSTT			(SIOCIWFIRSTPRIV + 16)	 

#define KS_WLAN_SET_BEACON_LOST		(SIOCIWFIRSTPRIV + 18)
#define KS_WLAN_GET_BEACON_LOST		(SIOCIWFIRSTPRIV + 19)

#define KS_WLAN_SET_TX_GAIN		(SIOCIWFIRSTPRIV + 20)
#define KS_WLAN_GET_TX_GAIN		(SIOCIWFIRSTPRIV + 21)

 
#define KS_WLAN_SET_PHY_TYPE		(SIOCIWFIRSTPRIV + 22)
#define KS_WLAN_GET_PHY_TYPE		(SIOCIWFIRSTPRIV + 23)
#define KS_WLAN_SET_CTS_MODE		(SIOCIWFIRSTPRIV + 24)
#define KS_WLAN_GET_CTS_MODE		(SIOCIWFIRSTPRIV + 25)
 
 
#define KS_WLAN_SET_SLEEP_MODE		(SIOCIWFIRSTPRIV + 28)	 
#define KS_WLAN_GET_SLEEP_MODE		(SIOCIWFIRSTPRIV + 29)	 
 
 

#ifdef __KERNEL__

#include "ks_wlan.h"
#include <linux/netdevice.h>

int ks_wlan_setup_parameter(struct ks_wlan_private *priv,
			    unsigned int commit_flag);

#endif  

#endif  
