{
  "module_name": "Makefile",
  "hash_id": "e8eb0b38a3470e9e14890db75124624741722e0dfca52734f00d742af5cf5bc1",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/realtek/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the Linux Wireless network device drivers for Realtek units\n#\n\nobj-$(CONFIG_RTL8180)\t\t+= rtl818x/\nobj-$(CONFIG_RTL8187)\t\t+= rtl818x/\nobj-$(CONFIG_RTLWIFI)\t\t+= rtlwifi/\nobj-$(CONFIG_RTL8XXXU)\t\t+= rtl8xxxu/\nobj-$(CONFIG_RTW88)\t\t+= rtw88/\nobj-$(CONFIG_RTW89)\t\t+= rtw89/\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}