{
  "module_name": "Makefile",
  "hash_id": "8091e8e18ea73f5e8f7ab1eb03e710b0f82b3d4e2788f56a50f96cfd105996cc",
  "original_prompt": "Ingested from linux-6.6.14/drivers/phy/hisilicon/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_PHY_HI6220_USB)\t\t+= phy-hi6220-usb.o\nobj-$(CONFIG_PHY_HI3660_USB)\t\t+= phy-hi3660-usb3.o\nobj-$(CONFIG_PHY_HI3670_USB)\t\t+= phy-hi3670-usb3.o\nobj-$(CONFIG_PHY_HI3670_PCIE)\t\t+= phy-hi3670-pcie.o\nobj-$(CONFIG_PHY_HISTB_COMBPHY)\t\t+= phy-histb-combphy.o\nobj-$(CONFIG_PHY_HISI_INNO_USB2)\t+= phy-hisi-inno-usb2.o\nobj-$(CONFIG_PHY_HIX5HD2_SATA)\t\t+= phy-hix5hd2-sata.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}