{
  "module_name": "Makefile",
  "hash_id": "7751d889e2f02b00f91fd867ec6cd2e0eeca7a916cb8f8012836fbb3213d0595",
  "original_prompt": "Ingested from linux-6.6.14/drivers/video/fbdev/via/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the VIA framebuffer driver (for Linux Kernel 2.6)\n#\n\nobj-$(CONFIG_FB_VIA) += viafb.o\n\nviafb-y\t:=viafbdev.o hw.o via_i2c.o dvi.o lcd.o ioctl.o accel.o \\\n\tvia_utility.o vt1636.o global.o tblDPASetting.o viamode.o \\\n\tvia-core.o via-gpio.o via_modesetting.o via_clock.o \\\n\tvia_aux.o via_aux_edid.o via_aux_vt1636.o via_aux_vt1632.o \\\n\tvia_aux_vt1631.o via_aux_vt1625.o via_aux_vt1622.o via_aux_vt1621.o \\\n\tvia_aux_sii164.o via_aux_ch7301.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}