{
  "module_name": "Makefile",
  "hash_id": "23f5da6935f0232531ca3683b00eaa32bb3d258c6ca21e1a369c02905ed1472a",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/ux500/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Ux500 Platform Support\n\nsnd-soc-ux500-plat-msp-i2s-objs := ux500_msp_dai.o ux500_msp_i2s.o\nobj-$(CONFIG_SND_SOC_UX500_PLAT_MSP_I2S) += snd-soc-ux500-plat-msp-i2s.o\n\nsnd-soc-ux500-plat-dma-objs := ux500_pcm.o\nobj-$(CONFIG_SND_SOC_UX500_PLAT_DMA) += snd-soc-ux500-plat-dma.o\n\nsnd-soc-ux500-mach-mop500-objs := mop500.o mop500_ab8500.o\nobj-$(CONFIG_SND_SOC_UX500_MACH_MOP500) += snd-soc-ux500-mach-mop500.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}