{
  "module_name": "Makefile",
  "hash_id": "6d31cd43544a1703602169a710bfc8e9d31d60bf42bbf44384460c551ed10ba8",
  "original_prompt": "Ingested from linux-6.6.14/fs/tracefs/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\ntracefs-objs\t:= inode.o\ntracefs-objs\t+= event_inode.o\n\nobj-$(CONFIG_TRACING)\t+= tracefs.o\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}