#ifndef __SND_SOC_SAMSUNG_I2S_H
#define __SND_SOC_SAMSUNG_I2S_H
#define SAMSUNG_I2S_DAI        "samsung-i2s"
#define SAMSUNG_I2S_DAI_SEC    "samsung-i2s-sec"
#define SAMSUNG_I2S_DIV_BCLK		1
#define SAMSUNG_I2S_RCLKSRC_0		0
#define SAMSUNG_I2S_RCLKSRC_1		1
#define SAMSUNG_I2S_CDCLK		2
#define SAMSUNG_I2S_OPCLK		3
#define  SAMSUNG_I2S_OPCLK_CDCLK_OUT	0	 
#define  SAMSUNG_I2S_OPCLK_CDCLK_IN	1	 
#define  SAMSUNG_I2S_OPCLK_BCLK_OUT	2	 
#define  SAMSUNG_I2S_OPCLK_PCLK		3	 
#endif  
