{
  "module_name": "Makefile",
  "hash_id": "dc8a9ae533a2fbff2e2564f477c103631ae57ec39320a46515c09ef3db3dd473",
  "original_prompt": "Ingested from linux-6.6.14/drivers/phy/amlogic/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_PHY_MESON8_HDMI_TX)\t\t+= phy-meson8-hdmi-tx.o\nobj-$(CONFIG_PHY_MESON8B_USB2)\t\t\t+= phy-meson8b-usb2.o\nobj-$(CONFIG_PHY_MESON_GXL_USB2)\t\t+= phy-meson-gxl-usb2.o\nobj-$(CONFIG_PHY_MESON_G12A_USB2)\t\t+= phy-meson-g12a-usb2.o\nobj-$(CONFIG_PHY_MESON_G12A_USB3_PCIE)\t\t+= phy-meson-g12a-usb3-pcie.o\nobj-$(CONFIG_PHY_MESON_G12A_MIPI_DPHY_ANALOG)\t+= phy-meson-g12a-mipi-dphy-analog.o\nobj-$(CONFIG_PHY_MESON_AXG_PCIE)\t\t+= phy-meson-axg-pcie.o\nobj-$(CONFIG_PHY_MESON_AXG_MIPI_PCIE_ANALOG)\t+= phy-meson-axg-mipi-pcie-analog.o\nobj-$(CONFIG_PHY_MESON_AXG_MIPI_DPHY)\t\t+= phy-meson-axg-mipi-dphy.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}