{
  "module_name": "Makefile",
  "hash_id": "e6b0e6587d5a9193e6d4a16dc113b7c31d5977dc31a025ee15c1f5916060b9f6",
  "original_prompt": "Ingested from linux-6.6.14/drivers/scsi/megaraid/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_MEGARAID_MM)\t+= megaraid_mm.o\nobj-$(CONFIG_MEGARAID_MAILBOX)\t+= megaraid_mbox.o\nobj-$(CONFIG_MEGARAID_SAS)\t+= megaraid_sas.o\nmegaraid_sas-objs := megaraid_sas_base.o megaraid_sas_fusion.o \\\n\tmegaraid_sas_fp.o megaraid_sas_debugfs.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}