{
  "module_name": "Kbuild",
  "hash_id": "77330a6643dd0c8271fe334e4ef037d3f1eec05c9161b4f6549a41186d4c19dc",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/nouveau/nvkm/engine/cipher/Kbuild",
  "human_readable_source": "# SPDX-License-Identifier: MIT\nnvkm-y += nvkm/engine/cipher/g84.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}