{
  "module_name": "Makefile",
  "hash_id": "f9cb7cb35a98a7aaab28fcb813075fb3c28e90d499bf9b4f6f59d639526842fb",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/arcnet/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for linux/drivers/net/arcnet\n#\n\nobj-$(CONFIG_ARCNET) += arcnet.o\nobj-$(CONFIG_ARCNET_1201) += rfc1201.o\nobj-$(CONFIG_ARCNET_1051) += rfc1051.o\nobj-$(CONFIG_ARCNET_RAW) += arc-rawmode.o\nobj-$(CONFIG_ARCNET_CAP) += capmode.o\nobj-$(CONFIG_ARCNET_COM90xx) += com90xx.o\nobj-$(CONFIG_ARCNET_COM90xxIO) += com90io.o\nobj-$(CONFIG_ARCNET_RIM_I) += arc-rimi.o\nobj-$(CONFIG_ARCNET_COM20020) += com20020.o\nobj-$(CONFIG_ARCNET_COM20020_ISA) += com20020-isa.o\nobj-$(CONFIG_ARCNET_COM20020_PCI) += com20020-pci.o\nobj-$(CONFIG_ARCNET_COM20020_CS) += com20020_cs.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}