#ifndef __VBOX_VERSION_H__
#define __VBOX_VERSION_H__
#define VBG_VERSION_MAJOR 6
#define VBG_VERSION_MINOR 0
#define VBG_VERSION_BUILD 0
#define VBG_SVN_REV 127566
#define VBG_VERSION_STRING "6.0.0"
#endif
