{
  "module_name": "Makefile",
  "hash_id": "ae2ce7b40ba554c529e8a4c0ff4ea16b41822ebdd024bd78373af77e36661ca8",
  "original_prompt": "Ingested from linux-6.6.14/drivers/rapidio/switches/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for RIO switches\n#\n\nobj-$(CONFIG_RAPIDIO_CPS_XX)\t+= idtcps.o\nobj-$(CONFIG_RAPIDIO_CPS_GEN2)\t+= idt_gen2.o\nobj-$(CONFIG_RAPIDIO_RXS_GEN3)\t+= idt_gen3.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}