{
  "module_name": "Makefile",
  "hash_id": "cdcbfed4ef77dc8b90ce6fb5f483d59d91868746c90554b279de29db9264b622",
  "original_prompt": "Ingested from linux-6.6.14/net/tls/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the TLS subsystem.\n#\n\nCFLAGS_trace.o := -I$(src)\n\nobj-$(CONFIG_TLS) += tls.o\n\ntls-y := tls_main.o tls_sw.o tls_proc.o trace.o tls_strp.o\n\ntls-$(CONFIG_TLS_TOE) += tls_toe.o\ntls-$(CONFIG_TLS_DEVICE) += tls_device.o tls_device_fallback.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}