{
  "module_name": "Makefile",
  "hash_id": "54c5c88fa0fa81e7127fab6a6343fad9aef6d411b58c94c4fb03d9cd8913f776",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/media_tests/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\nCFLAGS += -I../ $(KHDR_INCLUDES)\nTEST_GEN_PROGS := media_device_test media_device_open video_device_test\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}