 
 

#ifndef _STREAM2MMMIO_DEFS_H
#define _STREAM2MMMIO_DEFS_H

#include <mipi_backend_defs.h>

#define _STREAM2MMIO_REG_ALIGN                  4

#define _STREAM2MMIO_COMMAND_REG_ID             0
#define _STREAM2MMIO_ACKNOWLEDGE_REG_ID         1
#define _STREAM2MMIO_PIX_WIDTH_ID_REG_ID        2
#define _STREAM2MMIO_START_ADDR_REG_ID          3       
#define _STREAM2MMIO_END_ADDR_REG_ID            4       
#define _STREAM2MMIO_STRIDE_REG_ID              5       
#define _STREAM2MMIO_NUM_ITEMS_REG_ID           6       
#define _STREAM2MMIO_BLOCK_WHEN_NO_CMD_REG_ID   7       
#define _STREAM2MMIO_REGS_PER_SID               8

#define _STREAM2MMIO_SID_REG_OFFSET             8
#define _STREAM2MMIO_MAX_NOF_SIDS              64       

 
#define _STREAM2MMIO_CMD_TOKEN_CMD_LSB          0       
#define _STREAM2MMIO_CMD_TOKEN_CMD_MSB          1

#define _STREAM2MMIO_CMD_TOKEN_WIDTH           (_STREAM2MMIO_CMD_TOKEN_CMD_MSB + 1 - _STREAM2MMIO_CMD_TOKEN_CMD_LSB)

#define _STREAM2MMIO_CMD_TOKEN_STORE_WORDS              0       
#define _STREAM2MMIO_CMD_TOKEN_STORE_PACKETS            1       
#define _STREAM2MMIO_CMD_TOKEN_SYNC_FRAME               2       

 
 
 
 
#define _STREAM2MMIO_PACK_NUM_ITEMS_BITS        16
#define _STREAM2MMIO_PACK_ACK_EOP_BIT           _STREAM2MMIO_PACK_NUM_ITEMS_BITS
#define _STREAM2MMIO_PACK_ACK_EOF_BIT           (_STREAM2MMIO_PACK_ACK_EOP_BIT + 1)

 
#define _STREAM2MMIO_ACK_TOKEN_NUM_ITEMS_LSB    0       
#define _STREAM2MMIO_ACK_TOKEN_NUM_ITEMS_MSB   (_STREAM2MMIO_PACK_NUM_ITEMS_BITS - 1)
#define _STREAM2MMIO_ACK_TOKEN_EOP_BIT         _STREAM2MMIO_PACK_ACK_EOP_BIT
#define _STREAM2MMIO_ACK_TOKEN_EOF_BIT         _STREAM2MMIO_PACK_ACK_EOF_BIT
#define _STREAM2MMIO_ACK_TOKEN_VALID_BIT       (_STREAM2MMIO_ACK_TOKEN_EOF_BIT + 1)       
 
 
#define _STREAM2MMIO_ACK_TOKEN_WIDTH           (_STREAM2MMIO_ACK_TOKEN_VALID_BIT + 1)

 
#define _STREAM2MMIO_PACK_CMD_STORE_WORDS        0
#define _STREAM2MMIO_PACK_CMD_STORE_LONG_PACKET  1
#define _STREAM2MMIO_PACK_CMD_STORE_SHORT_PACKET 2

#endif  
