{
  "module_name": "Makefile",
  "hash_id": "0c82f8c17450ed7a97f3c33296dd748eef67ae1d09ac569da184df0b6c182a9f",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/armada/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\narmada-y\t:= armada_crtc.o armada_drv.o armada_fb.o \\\n\t\t   armada_gem.o armada_overlay.o armada_plane.o armada_trace.o\narmada-y\t+= armada_510.o\narmada-$(CONFIG_DEBUG_FS) += armada_debugfs.o\narmada-$(CONFIG_DRM_FBDEV_EMULATION) += armada_fbdev.o\n\nobj-$(CONFIG_DRM_ARMADA) := armada.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}