{
  "module_name": "Makefile",
  "hash_id": "5e68fa74377bf34d08f91c44230f1d9da04589d382341520cf2d9257cb267183",
  "original_prompt": "Ingested from linux-6.6.14/drivers/video/fbdev/riva/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the Riva framebuffer driver\n#\n\nobj-$(CONFIG_FB_RIVA)     += rivafb.o\n\nrivafb-objs               := fbdev.o riva_hw.o nv_driver.o\n\nifdef CONFIG_FB_RIVA_I2C\n\trivafb-objs       += rivafb-i2c.o\nendif\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}