{
  "module_name": "Makefile",
  "hash_id": "4ae2450a90000befd9eded5825af6fec44f3e415cae58695ed9f187c7308be52",
  "original_prompt": "Ingested from linux-6.6.14/drivers/infiniband/hw/mthca/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_INFINIBAND_MTHCA) += ib_mthca.o\n\nib_mthca-y :=\tmthca_main.o mthca_cmd.o mthca_profile.o mthca_reset.o \\\n\t\tmthca_allocator.o mthca_eq.o mthca_pd.o mthca_cq.o \\\n\t\tmthca_mr.o mthca_qp.o mthca_av.o mthca_mcg.o mthca_mad.o \\\n\t\tmthca_provider.o mthca_memfree.o mthca_uar.o mthca_srq.o \\\n\t\tmthca_catas.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}