 

#ifndef __BNXT_FW_HDR_H__
#define __BNXT_FW_HDR_H__

#define BNXT_FIRMWARE_BIN_SIGNATURE     0x1a4d4342	 
#define BNXT_UCODE_TRAILER_SIGNATURE	0x726c7254	 

enum SUPPORTED_FAMILY {
	DEVICE_5702_3_4_FAMILY,		 
	DEVICE_5705_FAMILY,		 
	DEVICE_SHASTA_FAMILY,		 
	DEVICE_5706_FAMILY,		 
	DEVICE_5714_FAMILY,		 
	DEVICE_STANFORD_FAMILY,		 
	DEVICE_STANFORD_ME_FAMILY,	 
	DEVICE_SOLEDAD_FAMILY,		 
	DEVICE_CILAI_FAMILY,		 
	DEVICE_ASPEN_FAMILY,		 
	DEVICE_ASPEN_PLUS_FAMILY,	 
	DEVICE_LOGAN_FAMILY,		 
	DEVICE_LOGAN_5762,		 
	DEVICE_LOGAN_57767,		 
	DEVICE_LOGAN_57787,		 
	DEVICE_LOGAN_5725,		 
	DEVICE_SAWTOOTH_FAMILY,		 
	DEVICE_COTOPAXI_FAMILY,		 
	DEVICE_SNAGGLETOOTH_FAMILY,	 
	DEVICE_CUMULUS_FAMILY,		 
	MAX_DEVICE_FAMILY
};

enum SUPPORTED_CODE {
	CODE_ASF1,		 
	CODE_ASF2,		 
	CODE_PASSTHRU,		 
	CODE_PT_SEC,		 
	CODE_UMP,		 
	CODE_BOOT,		 
	CODE_DASH,		 
	CODE_MCTP_PASSTHRU,	 
	CODE_PM_OFFLOAD,	 
	CODE_MDNS_SD_OFFLOAD,	 
	CODE_DISC_OFFLOAD,	 
	CODE_MUSTANG,		 
	CODE_ARP_BATCH,		 
	CODE_SMASH,		 
	CODE_APE_DIAG,		 
	CODE_APE_PATCH,		 
	CODE_TANG_PATCH,	 
	CODE_KONG_FW,		 
	CODE_KONG_PATCH,	 
	CODE_BONO_FW,		 
	CODE_BONO_PATCH,	 
	CODE_CHIMP_PATCH,	 

	MAX_CODE_TYPE,
};

enum SUPPORTED_MEDIA {
	MEDIA_COPPER,		 
	MEDIA_FIBER,		 
	MEDIA_NONE,		 
	MEDIA_COPPER_FIBER,	 
	MAX_MEDIA_TYPE,
};

struct bnxt_fw_header {
	__le32 signature;	 
	u8 flags;		 
	u8 code_type;		 
	u8 device;		 
	u8 media;		 
	u8 version[16];		 
	u8 build;
	u8 revision;
	u8 minor_ver;
	u8 major_ver;
};

 
struct bnxt_ucode_trailer {
	u8 rsa_sig[256];
	__le16 flags;
	u8 version_format;
	u8 version_length;
	u8 version[16];
	__le16 dir_type;
	__le16 trailer_length;
	__le32 sig;		 
	__le32 chksum;		 
};

#endif
