{
  "module_name": "Makefile",
  "hash_id": "f5d138fad613a04b1c424b66015c55cbf227b6339adca97127eaf2bd81fdc835",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/broadcom/bnxt/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_BNXT) += bnxt_en.o\n\nbnxt_en-y := bnxt.o bnxt_hwrm.o bnxt_sriov.o bnxt_ethtool.o bnxt_dcb.o bnxt_ulp.o bnxt_xdp.o bnxt_ptp.o bnxt_vfr.o bnxt_devlink.o bnxt_dim.o bnxt_coredump.o\nbnxt_en-$(CONFIG_BNXT_FLOWER_OFFLOAD) += bnxt_tc.o\nbnxt_en-$(CONFIG_DEBUG_FS) += bnxt_debugfs.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}