{
  "module_name": "Makefile",
  "hash_id": "9300a4da6379df7b9bc01c6f47d38c54208b63bf72a8864256063987998517dd",
  "original_prompt": "Ingested from linux-6.6.14/drivers/pmdomain/mediatek/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_MTK_SCPSYS)\t\t+= mtk-scpsys.o\nobj-$(CONFIG_MTK_SCPSYS_PM_DOMAINS) \t+= mtk-pm-domains.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}