{
  "module_name": "Makefile",
  "hash_id": "05e471da8964331b1ecd248ae78c17270e8c89514207b3dfc5d65a98efe3c7d7",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/bonding/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the Ethernet Bonding driver\n#\n\nobj-$(CONFIG_BONDING) += bonding.o\n\nbonding-objs := bond_main.o bond_3ad.o bond_alb.o bond_sysfs.o bond_sysfs_slave.o bond_debugfs.o bond_netlink.o bond_options.o\n\nproc-$(CONFIG_PROC_FS) += bond_procfs.o\nbonding-objs += $(proc-y)\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}