{
  "module_name": "Makefile",
  "hash_id": "ec8e1bf2f2504efc61e2b0730846c793010224e4525ebf2cf17cca104ef8f66a",
  "original_prompt": "Ingested from linux-6.6.14/drivers/hsi/clients/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for HSI clients\n#\n\nobj-$(CONFIG_NOKIA_MODEM)\t+= nokia-modem.o\nobj-$(CONFIG_SSI_PROTOCOL)\t+= ssi_protocol.o\nobj-$(CONFIG_CMT_SPEECH)\t+= cmt_speech.o\nobj-$(CONFIG_HSI_CHAR)\t\t+= hsi_char.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}