#ifndef __OWL_EMAC_H__
#define __OWL_EMAC_H__
#define OWL_EMAC_DRVNAME			"owl-emac"
#define OWL_EMAC_POLL_DELAY_USEC		5
#define OWL_EMAC_MDIO_POLL_TIMEOUT_USEC		1000
#define OWL_EMAC_RESET_POLL_TIMEOUT_USEC	2000
#define OWL_EMAC_TX_TIMEOUT			(2 * HZ)
#define OWL_EMAC_MTU_MIN			ETH_MIN_MTU
#define OWL_EMAC_MTU_MAX			ETH_DATA_LEN
#define OWL_EMAC_RX_FRAME_MAX_LEN		(ETH_FRAME_LEN + ETH_FCS_LEN)
#define OWL_EMAC_SKB_ALIGN			4
#define OWL_EMAC_SKB_RESERVE			18
#define OWL_EMAC_MAX_MULTICAST_ADDRS		14
#define OWL_EMAC_SETUP_FRAME_LEN		192
#define OWL_EMAC_RX_RING_SIZE			64
#define OWL_EMAC_TX_RING_SIZE			32
#define OWL_EMAC_REG_MAC_CSR0			0x0000
#define OWL_EMAC_BIT_MAC_CSR0_SWR		BIT(0)	 
#define OWL_EMAC_REG_MAC_CSR1			0x0008
#define OWL_EMAC_VAL_MAC_CSR1_TPD		0x01
#define OWL_EMAC_REG_MAC_CSR2			0x0010
#define OWL_EMAC_VAL_MAC_CSR2_RPD		0x01
#define OWL_EMAC_REG_MAC_CSR3			0x0018
#define OWL_EMAC_REG_MAC_CSR4			0x0020
#define OWL_EMAC_REG_MAC_CSR5			0x0028
#define OWL_EMAC_MSK_MAC_CSR5_TS		GENMASK(22, 20)	 
#define OWL_EMAC_OFF_MAC_CSR5_TS		20
#define OWL_EMAC_VAL_MAC_CSR5_TS_DATA		0x03	 
#define OWL_EMAC_VAL_MAC_CSR5_TS_CDES		0x07	 
#define OWL_EMAC_MSK_MAC_CSR5_RS		GENMASK(19, 17)	 
#define OWL_EMAC_OFF_MAC_CSR5_RS		17
#define OWL_EMAC_VAL_MAC_CSR5_RS_FDES		0x01	 
#define OWL_EMAC_VAL_MAC_CSR5_RS_CDES		0x05	 
#define OWL_EMAC_VAL_MAC_CSR5_RS_DATA		0x07	 
#define OWL_EMAC_BIT_MAC_CSR5_NIS		BIT(16)	 
#define OWL_EMAC_BIT_MAC_CSR5_AIS		BIT(15)	 
#define OWL_EMAC_BIT_MAC_CSR5_ERI		BIT(14)	 
#define OWL_EMAC_BIT_MAC_CSR5_GTE		BIT(11)	 
#define OWL_EMAC_BIT_MAC_CSR5_ETI		BIT(10)	 
#define OWL_EMAC_BIT_MAC_CSR5_RPS		BIT(8)	 
#define OWL_EMAC_BIT_MAC_CSR5_RU		BIT(7)	 
#define OWL_EMAC_BIT_MAC_CSR5_RI		BIT(6)	 
#define OWL_EMAC_BIT_MAC_CSR5_UNF		BIT(5)	 
#define OWL_EMAC_BIT_MAC_CSR5_LCIS		BIT(4)	 
#define OWL_EMAC_BIT_MAC_CSR5_LCIQ		BIT(3)	 
#define OWL_EMAC_BIT_MAC_CSR5_TU		BIT(2)	 
#define OWL_EMAC_BIT_MAC_CSR5_TPS		BIT(1)	 
#define OWL_EMAC_BIT_MAC_CSR5_TI		BIT(0)	 
#define OWL_EMAC_REG_MAC_CSR6			0x0030
#define OWL_EMAC_BIT_MAC_CSR6_RA		BIT(30)	 
#define OWL_EMAC_BIT_MAC_CSR6_TTM		BIT(22)	 
#define OWL_EMAC_BIT_MAC_CSR6_SF		BIT(21)	 
#define OWL_EMAC_MSK_MAC_CSR6_SPEED		GENMASK(17, 16)	 
#define OWL_EMAC_OFF_MAC_CSR6_SPEED		16
#define OWL_EMAC_VAL_MAC_CSR6_SPEED_100M	0x00
#define OWL_EMAC_VAL_MAC_CSR6_SPEED_10M		0x02
#define OWL_EMAC_BIT_MAC_CSR6_ST		BIT(13)	 
#define OWL_EMAC_BIT_MAC_CSR6_LP		BIT(10)	 
#define OWL_EMAC_BIT_MAC_CSR6_FD		BIT(9)	 
#define OWL_EMAC_BIT_MAC_CSR6_PM		BIT(7)	 
#define OWL_EMAC_BIT_MAC_CSR6_PR		BIT(6)	 
#define OWL_EMAC_BIT_MAC_CSR6_IF		BIT(4)	 
#define OWL_EMAC_BIT_MAC_CSR6_PB		BIT(3)	 
#define OWL_EMAC_BIT_MAC_CSR6_HO		BIT(2)	 
#define OWL_EMAC_BIT_MAC_CSR6_SR		BIT(1)	 
#define OWL_EMAC_BIT_MAC_CSR6_HP		BIT(0)	 
#define OWL_EMAC_MSK_MAC_CSR6_STSR	       (OWL_EMAC_BIT_MAC_CSR6_ST | \
						OWL_EMAC_BIT_MAC_CSR6_SR)
#define OWL_EMAC_REG_MAC_CSR7			0x0038
#define OWL_EMAC_BIT_MAC_CSR7_NIE		BIT(16)	 
#define OWL_EMAC_BIT_MAC_CSR7_AIE		BIT(15)	 
#define OWL_EMAC_BIT_MAC_CSR7_ERE		BIT(14)	 
#define OWL_EMAC_BIT_MAC_CSR7_GTE		BIT(11)	 
#define OWL_EMAC_BIT_MAC_CSR7_ETE		BIT(10)	 
#define OWL_EMAC_BIT_MAC_CSR7_RSE		BIT(8)	 
#define OWL_EMAC_BIT_MAC_CSR7_RUE		BIT(7)	 
#define OWL_EMAC_BIT_MAC_CSR7_RIE		BIT(6)	 
#define OWL_EMAC_BIT_MAC_CSR7_UNE		BIT(5)	 
#define OWL_EMAC_BIT_MAC_CSR7_TUE		BIT(2)	 
#define OWL_EMAC_BIT_MAC_CSR7_TSE		BIT(1)	 
#define OWL_EMAC_BIT_MAC_CSR7_TIE		BIT(0)	 
#define OWL_EMAC_BIT_MAC_CSR7_ALL_NOT_TUE      (OWL_EMAC_BIT_MAC_CSR7_ERE | \
						OWL_EMAC_BIT_MAC_CSR7_GTE | \
						OWL_EMAC_BIT_MAC_CSR7_ETE | \
						OWL_EMAC_BIT_MAC_CSR7_RSE | \
						OWL_EMAC_BIT_MAC_CSR7_RUE | \
						OWL_EMAC_BIT_MAC_CSR7_RIE | \
						OWL_EMAC_BIT_MAC_CSR7_UNE | \
						OWL_EMAC_BIT_MAC_CSR7_TSE | \
						OWL_EMAC_BIT_MAC_CSR7_TIE)
#define OWL_EMAC_REG_MAC_CSR8			0x0040
#define OWL_EMAC_REG_MAC_CSR9			0x0048
#define OWL_EMAC_REG_MAC_CSR10			0x0050
#define OWL_EMAC_BIT_MAC_CSR10_SB		BIT(31)	 
#define OWL_EMAC_MSK_MAC_CSR10_CLKDIV		GENMASK(30, 28)	 
#define OWL_EMAC_OFF_MAC_CSR10_CLKDIV		28
#define OWL_EMAC_VAL_MAC_CSR10_CLKDIV_128	0x04
#define OWL_EMAC_VAL_MAC_CSR10_OPCODE_WR	0x01	 
#define OWL_EMAC_OFF_MAC_CSR10_OPCODE		26	 
#define OWL_EMAC_VAL_MAC_CSR10_OPCODE_DCG	0x00	 
#define OWL_EMAC_VAL_MAC_CSR10_OPCODE_WR	0x01	 
#define OWL_EMAC_VAL_MAC_CSR10_OPCODE_RD	0x02	 
#define OWL_EMAC_VAL_MAC_CSR10_OPCODE_CDS	0x03	 
#define OWL_EMAC_MSK_MAC_CSR10_PHYADD		GENMASK(25, 21)	 
#define OWL_EMAC_OFF_MAC_CSR10_PHYADD		21
#define OWL_EMAC_MSK_MAC_CSR10_REGADD		GENMASK(20, 16)	 
#define OWL_EMAC_OFF_MAC_CSR10_REGADD		16
#define OWL_EMAC_MSK_MAC_CSR10_DATA		GENMASK(15, 0)	 
#define OWL_EMAC_REG_MAC_CSR11			0x0058
#define OWL_EMAC_OFF_MAC_CSR11_TT		27	 
#define OWL_EMAC_OFF_MAC_CSR11_NTP		24	 
#define OWL_EMAC_OFF_MAC_CSR11_RT		20	 
#define OWL_EMAC_OFF_MAC_CSR11_NRP		17	 
#define OWL_EMAC_REG_MAC_CSR16			0x0080
#define OWL_EMAC_REG_MAC_CSR17			0x0088
#define OWL_EMAC_REG_MAC_CSR18			0x0090
#define OWL_EMAC_OFF_MAC_CSR18_CPTL		24	 
#define OWL_EMAC_OFF_MAC_CSR18_CRTL		16	 
#define OWL_EMAC_OFF_MAC_CSR18_PQT		0	 
#define OWL_EMAC_REG_MAC_CSR19			0x0098
#define OWL_EMAC_OFF_MAC_CSR19_FPTL		16	 
#define OWL_EMAC_OFF_MAC_CSR19_FRTL		0	 
#define OWL_EMAC_REG_MAC_CSR20			0x00A0
#define OWL_EMAC_BIT_MAC_CSR20_FCE		BIT(31)	 
#define OWL_EMAC_BIT_MAC_CSR20_TUE		BIT(30)	 
#define OWL_EMAC_BIT_MAC_CSR20_TPE		BIT(29)	 
#define OWL_EMAC_BIT_MAC_CSR20_RPE		BIT(28)	 
#define OWL_EMAC_BIT_MAC_CSR20_BPE		BIT(27)	 
#define OWL_EMAC_REG_MAC_CTRL			0x00B0
#define OWL_EMAC_BIT_MAC_CTRL_RRSB		BIT(8)	 
#define OWL_EMAC_OFF_MAC_CTRL_SSDC		4	 
#define OWL_EMAC_BIT_MAC_CTRL_RCPS		BIT(1)	 
#define OWL_EMAC_BIT_MAC_CTRL_RSIS		BIT(0)	 
#define OWL_EMAC_BIT_RDES0_OWN			BIT(31)	 
#define OWL_EMAC_BIT_RDES0_FF			BIT(30)	 
#define OWL_EMAC_MSK_RDES0_FL			GENMASK(29, 16)	 
#define OWL_EMAC_OFF_RDES0_FL			16
#define OWL_EMAC_BIT_RDES0_ES			BIT(15)	 
#define OWL_EMAC_BIT_RDES0_DE			BIT(14)	 
#define OWL_EMAC_BIT_RDES0_RF			BIT(11)	 
#define OWL_EMAC_BIT_RDES0_MF			BIT(10)	 
#define OWL_EMAC_BIT_RDES0_FS			BIT(9)	 
#define OWL_EMAC_BIT_RDES0_LS			BIT(8)	 
#define OWL_EMAC_BIT_RDES0_TL			BIT(7)	 
#define OWL_EMAC_BIT_RDES0_CS			BIT(6)	 
#define OWL_EMAC_BIT_RDES0_FT			BIT(5)	 
#define OWL_EMAC_BIT_RDES0_RE			BIT(3)	 
#define OWL_EMAC_BIT_RDES0_DB			BIT(2)	 
#define OWL_EMAC_BIT_RDES0_CE			BIT(1)	 
#define OWL_EMAC_BIT_RDES0_ZERO			BIT(0)	 
#define OWL_EMAC_BIT_RDES1_RER			BIT(25)	 
#define OWL_EMAC_MSK_RDES1_RBS1			GENMASK(10, 0)  
#define OWL_EMAC_BIT_TDES0_OWN			BIT(31)	 
#define OWL_EMAC_BIT_TDES0_ES			BIT(15)	 
#define OWL_EMAC_BIT_TDES0_LO			BIT(11)	 
#define OWL_EMAC_BIT_TDES0_NC			BIT(10)	 
#define OWL_EMAC_BIT_TDES0_LC			BIT(9)	 
#define OWL_EMAC_BIT_TDES0_EC			BIT(8)	 
#define OWL_EMAC_MSK_TDES0_CC			GENMASK(6, 3)  
#define OWL_EMAC_BIT_TDES0_UF			BIT(1)	 
#define OWL_EMAC_BIT_TDES0_DE			BIT(0)	 
#define OWL_EMAC_BIT_TDES1_IC			BIT(31)	 
#define OWL_EMAC_BIT_TDES1_LS			BIT(30)	 
#define OWL_EMAC_BIT_TDES1_FS			BIT(29)	 
#define OWL_EMAC_BIT_TDES1_FT1			BIT(28)	 
#define OWL_EMAC_BIT_TDES1_SET			BIT(27)	 
#define OWL_EMAC_BIT_TDES1_AC			BIT(26)	 
#define OWL_EMAC_BIT_TDES1_TER			BIT(25)	 
#define OWL_EMAC_BIT_TDES1_DPD			BIT(23)	 
#define OWL_EMAC_BIT_TDES1_FT0			BIT(22)	 
#define OWL_EMAC_MSK_TDES1_TBS1			GENMASK(10, 0)  
static const char *const owl_emac_clk_names[] = { "eth", "rmii" };
#define OWL_EMAC_NCLKS ARRAY_SIZE(owl_emac_clk_names)
enum owl_emac_clk_map {
	OWL_EMAC_CLK_ETH = 0,
	OWL_EMAC_CLK_RMII
};
struct owl_emac_addr_list {
	u8 addrs[OWL_EMAC_MAX_MULTICAST_ADDRS][ETH_ALEN];
	int count;
};
struct owl_emac_ring_desc {
	u32 status;
	u32 control;
	u32 buf_addr;
	u32 reserved;		 
};
struct owl_emac_ring {
	struct owl_emac_ring_desc *descs;
	dma_addr_t descs_dma;
	struct sk_buff **skbs;
	dma_addr_t *skbs_dma;
	unsigned int size;
	unsigned int head;
	unsigned int tail;
};
struct owl_emac_priv {
	struct net_device *netdev;
	void __iomem *base;
	struct clk_bulk_data clks[OWL_EMAC_NCLKS];
	struct reset_control *reset;
	struct owl_emac_ring rx_ring;
	struct owl_emac_ring tx_ring;
	struct mii_bus *mii;
	struct napi_struct napi;
	phy_interface_t phy_mode;
	unsigned int link;
	int speed;
	int duplex;
	int pause;
	struct owl_emac_addr_list mcaddr_list;
	struct work_struct mac_reset_task;
	u32 msg_enable;		 
	spinlock_t lock;	 
};
#endif  
