{
  "module_name": "Makefile",
  "hash_id": "62326b3722caf13e9fe4202a555bbb7448b7979f802938c9f7e490078e96beb5",
  "original_prompt": "Ingested from linux-6.6.14/sound/pci/au88x0/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nsnd-au8810-objs := au8810.o\nsnd-au8820-objs := au8820.o\nsnd-au8830-objs := au8830.o\n\nobj-$(CONFIG_SND_AU8810) += snd-au8810.o\nobj-$(CONFIG_SND_AU8820) += snd-au8820.o\nobj-$(CONFIG_SND_AU8830) += snd-au8830.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}