#ifndef __DAL_COMMAND_TABLE_HELPER_DCE60_H__
#define __DAL_COMMAND_TABLE_HELPER_DCE60_H__
struct command_table_helper;
const struct command_table_helper *dal_cmd_tbl_helper_dce60_get_table(void);
#endif
