 

 

#include "mpi/mpi2_cnfg.h"

#ifndef MPI2_TRIGGER_PAGES_H
#define MPI2_TRIGGER_PAGES_H

#define MPI2_CONFIG_EXTPAGETYPE_DRIVER_PERSISTENT_TRIGGER    (0xE0)
#define MPI26_DRIVER_TRIGGER_PAGE0_PAGEVERSION               (0x01)
typedef struct _MPI26_CONFIG_PAGE_DRIVER_TIGGER_0 {
	MPI2_CONFIG_EXTENDED_PAGE_HEADER	Header;	 
	U16	TriggerFlags;		 
	U16	Reserved0xA;		 
	U32	Reserved0xC[61];	 
} _MPI26_CONFIG_PAGE_DRIVER_TIGGER_0, Mpi26DriverTriggerPage0_t;

 
#define  MPI26_DRIVER_TRIGGER0_FLAG_MASTER_TRIGGER_VALID       (0x0001)
#define  MPI26_DRIVER_TRIGGER0_FLAG_MPI_EVENT_TRIGGER_VALID    (0x0002)
#define  MPI26_DRIVER_TRIGGER0_FLAG_SCSI_SENSE_TRIGGER_VALID   (0x0004)
#define  MPI26_DRIVER_TRIGGER0_FLAG_LOGINFO_TRIGGER_VALID      (0x0008)

#define MPI26_DRIVER_TRIGGER_PAGE1_PAGEVERSION               (0x01)
typedef struct _MPI26_DRIVER_MASTER_TIGGER_ENTRY {
	U32	MasterTriggerFlags;
} MPI26_DRIVER_MASTER_TIGGER_ENTRY;

#define MPI26_MAX_MASTER_TRIGGERS                                   (1)
typedef struct _MPI26_CONFIG_PAGE_DRIVER_TIGGER_1 {
	MPI2_CONFIG_EXTENDED_PAGE_HEADER	Header;	 
	U16	NumMasterTrigger;	 
	U16	Reserved0xA;		 
	MPI26_DRIVER_MASTER_TIGGER_ENTRY MasterTriggers[MPI26_MAX_MASTER_TRIGGERS];	 
} MPI26_CONFIG_PAGE_DRIVER_TIGGER_1, Mpi26DriverTriggerPage1_t;

#define MPI26_DRIVER_TRIGGER_PAGE2_PAGEVERSION               (0x01)
typedef struct _MPI26_DRIVER_MPI_EVENT_TIGGER_ENTRY {
	U16	MPIEventCode;		 
	U16	MPIEventCodeSpecific;	 
} MPI26_DRIVER_MPI_EVENT_TIGGER_ENTRY;

#define MPI26_MAX_MPI_EVENT_TRIGGERS                            (20)
typedef struct _MPI26_CONFIG_PAGE_DRIVER_TIGGER_2 {
	MPI2_CONFIG_EXTENDED_PAGE_HEADER        Header;	 
	U16	NumMPIEventTrigger;      
	U16	Reserved0xA;		 
	MPI26_DRIVER_MPI_EVENT_TIGGER_ENTRY MPIEventTriggers[MPI26_MAX_MPI_EVENT_TRIGGERS];  
} MPI26_CONFIG_PAGE_DRIVER_TIGGER_2, Mpi26DriverTriggerPage2_t;

#define MPI26_DRIVER_TRIGGER_PAGE3_PAGEVERSION               (0x01)
typedef struct _MPI26_DRIVER_SCSI_SENSE_TIGGER_ENTRY {
	U8     ASCQ;		 
	U8     ASC;		 
	U8     SenseKey;	 
	U8     Reserved;	 
} MPI26_DRIVER_SCSI_SENSE_TIGGER_ENTRY;

#define MPI26_MAX_SCSI_SENSE_TRIGGERS                            (20)
typedef struct _MPI26_CONFIG_PAGE_DRIVER_TIGGER_3 {
	MPI2_CONFIG_EXTENDED_PAGE_HEADER	Header;	 
	U16	NumSCSISenseTrigger;			 
	U16	Reserved0xA;				 
	MPI26_DRIVER_SCSI_SENSE_TIGGER_ENTRY SCSISenseTriggers[MPI26_MAX_SCSI_SENSE_TRIGGERS];	 
} MPI26_CONFIG_PAGE_DRIVER_TIGGER_3, Mpi26DriverTriggerPage3_t;

#define MPI26_DRIVER_TRIGGER_PAGE4_PAGEVERSION               (0x01)
typedef struct _MPI26_DRIVER_IOCSTATUS_LOGINFO_TIGGER_ENTRY {
	U16        IOCStatus;       
	U16        Reserved;        
	U32        LogInfo;         
} MPI26_DRIVER_IOCSTATUS_LOGINFO_TIGGER_ENTRY;

#define MPI26_MAX_LOGINFO_TRIGGERS                            (20)
typedef struct _MPI26_CONFIG_PAGE_DRIVER_TIGGER_4 {
	MPI2_CONFIG_EXTENDED_PAGE_HEADER	Header;	 
	U16	NumIOCStatusLogInfoTrigger;		 
	U16	Reserved0xA;				 
	MPI26_DRIVER_IOCSTATUS_LOGINFO_TIGGER_ENTRY IOCStatusLoginfoTriggers[MPI26_MAX_LOGINFO_TRIGGERS];	 
} MPI26_CONFIG_PAGE_DRIVER_TIGGER_4, Mpi26DriverTriggerPage4_t;

#endif
