{
  "module_name": "Makefile",
  "hash_id": "7e4724bafae599d2eef5b632ad399fba01a4726fcedecd8ed898ccc51ba1e123",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/i2c/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nch7006-y := ch7006_drv.o ch7006_mode.o\nobj-$(CONFIG_DRM_I2C_CH7006) += ch7006.o\n\nsil164-y := sil164_drv.o\nobj-$(CONFIG_DRM_I2C_SIL164) += sil164.o\n\ntda998x-y := tda998x_drv.o\nobj-$(CONFIG_DRM_I2C_NXP_TDA998X) += tda998x.o\nobj-$(CONFIG_DRM_I2C_NXP_TDA9950) += tda9950.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}