{
  "module_name": "Makefile",
  "hash_id": "612ae226fe7b5730aa4f22d65832f9744f48644c2f670cb0a5edc2b35aa4cd75",
  "original_prompt": "Ingested from linux-6.6.14/drivers/crypto/hisilicon/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_CRYPTO_DEV_HISI_HPRE) += hpre/\nobj-$(CONFIG_CRYPTO_DEV_HISI_SEC) += sec/\nobj-$(CONFIG_CRYPTO_DEV_HISI_SEC2) += sec2/\nobj-$(CONFIG_CRYPTO_DEV_HISI_QM) += hisi_qm.o\nhisi_qm-objs = qm.o sgl.o debugfs.o\nobj-$(CONFIG_CRYPTO_DEV_HISI_ZIP) += zip/\nobj-$(CONFIG_CRYPTO_DEV_HISI_TRNG) += trng/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}