 

#ifndef __IRQSRCS_VCN_2_0_H__
#define __IRQSRCS_VCN_2_0_H__

#define VCN_2_0__SRCID__UVD_ENC_GENERAL_PURPOSE				119		
#define VCN_2_0__SRCID__UVD_ENC_LOW_LATENCY				120		
#define VCN_2_0__SRCID__UVD_SYSTEM_MESSAGE_INTERRUPT			124		
#define VCN_2_0__SRCID__JPEG_ENCODE					151		
#define VCN_2_0__SRCID__JPEG_DECODE					153		

#define VCN_2_6__SRCID_UVD_POISON					160
#define VCN_2_6__SRCID_DJPEG0_POISON					161
#define VCN_2_6__SRCID_EJPEG0_POISON					162

#endif
