{
  "module_name": "Makefile",
  "hash_id": "895fbb5de7b416f55275e7449f7c781b0ae8e4cb3a61172ca7f84aec16478826",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/pensando/ionic/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Copyright(c) 2017 - 2019 Pensando Systems, Inc\n\nobj-$(CONFIG_IONIC) := ionic.o\n\nionic-y := ionic_main.o ionic_bus_pci.o ionic_devlink.o ionic_dev.o \\\n\t   ionic_debugfs.o ionic_lif.o ionic_rx_filter.o ionic_ethtool.o \\\n\t   ionic_txrx.o ionic_stats.o ionic_fw.o\nionic-$(CONFIG_PTP_1588_CLOCK) += ionic_phc.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}