{
  "module_name": "Makefile",
  "hash_id": "ce6efc8c0401330592f8ace2e3ccc93dc2c3b13b375fe109d109d8a4682abc5a",
  "original_prompt": "Ingested from linux-6.6.14/drivers/clk/axis/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_MACH_ARTPEC6)\t+= clk-artpec6.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}