{
  "module_name": "Makefile",
  "hash_id": "ba7a0e4b9b3438f16db3192f938fb64107a2af042aa0dcb71a4ed43c2398e5a6",
  "original_prompt": "Ingested from linux-6.6.14/sound/mips/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for ALSA\n#\n\nsnd-sgi-o2-objs := sgio2audio.o ad1843.o\nsnd-sgi-hal2-objs := hal2.o\n\n# Toplevel Module Dependency\nobj-$(CONFIG_SND_SGI_O2) += snd-sgi-o2.o\nobj-$(CONFIG_SND_SGI_HAL2) += snd-sgi-hal2.o\nobj-$(CONFIG_SND_N64) += snd-n64.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}