{
  "module_name": "Makefile",
  "hash_id": "58e5c96d83a3c9e83f5c25513e9afe61a5a088c15643adf0d79e74ce8be412a8",
  "original_prompt": "Ingested from linux-6.6.14/drivers/accel/qaic/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for Qualcomm Cloud AI accelerators driver\n#\n\nobj-$(CONFIG_DRM_ACCEL_QAIC)\t:= qaic.o\n\nqaic-y := \\\n\tmhi_controller.o \\\n\tqaic_control.o \\\n\tqaic_data.o \\\n\tqaic_drv.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}