{
  "module_name": "Makefile",
  "hash_id": "cc1db0fa3854a15fa0d9d5d92cde3b11255f94c08a5ae970136bebc0b48bf228",
  "original_prompt": "Ingested from linux-6.6.14/drivers/soc/sunxi/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_SUNXI_MBUS) +=\tsunxi_mbus.o\nobj-$(CONFIG_SUNXI_SRAM) +=\tsunxi_sram.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}