/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-x86_64"
#define DATE "built on: Sat Jan 31 03:11:10 2026 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','/','h','o','m','e','/',
    'a','i','m','e','a','t','/','a','n','v','i','l','o','s','/','e',
    'x','t','/','t','o','o','l','c','h','a','i','n','/','b','i','n',
    '/','x','8','6','_','6','4','-','u','n','k','n','o','w','n','-',
    'l','i','n','u','x','-','m','u','s','l','-','g','c','c',' ','-',
    'p','t','h','r','e','a','d',' ','-','m','6','4',' ','-','W','a',
    ',','-','-','n','o','e','x','e','c','s','t','a','c','k',' ','-',
    'I','/','h','o','m','e','/','a','i','m','e','a','t','/','a','n',
    'v','i','l','o','s','/','b','u','i','l','d','_','a','r','t','i',
    'f','a','c','t','s','/','s','t','a','g','i','n','g','/','i','n',
    'c','l','u','d','e',' ','-','s','t','a','t','i','c',' ','-','D',
    'O','P','E','N','S','S','L','_','U','S','E','_','N','O','D','E',
    'L','E','T','E',' ','-','D','L','_','E','N','D','I','A','N',' ',
    '-','D','O','P','E','N','S','S','L','_','B','U','I','L','D','I',
    'N','G','_','O','P','E','N','S','S','L',' ','-','D','N','D','E',
    'B','U','G','\0'
};
