 

#ifndef _OPENSOLARIS_SYS_LOCK_H_
#define	_OPENSOLARIS_SYS_LOCK_H_

#include_next <sys/lock.h>

#define	LO_ALLMASK	(LO_INITIALIZED | LO_WITNESS | LO_QUIET |	\
    LO_RECURSABLE | LO_SLEEPABLE | LO_UPGRADABLE |	\
    LO_DUPOK | LO_CLASSMASK | LO_NOPROFILE)
#define	LO_EXPECTED	(LO_INITIALIZED | LO_WITNESS | LO_RECURSABLE |	\
    LO_SLEEPABLE | LO_UPGRADABLE | LO_DUPOK | (2 << LO_CLASSSHIFT))

#endif	 
