{
  "module_name": "Makefile",
  "hash_id": "7c1484c44e87cab0a4907736668a58ac2d37063fdc922f6b1b4be7e69c9e50a0",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/test-drivers/visl/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0+\nvisl-y := visl-core.o visl-video.o visl-dec.o visl-trace-points.o\n\nifeq ($(CONFIG_VISL_DEBUGFS),y)\n  visl-y += visl-debugfs.o\nendif\n\nobj-$(CONFIG_VIDEO_VISL) += visl.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}