{
  "module_name": "Makefile",
  "hash_id": "eb31b52fa0fdc4734d642e86af14bbd34a11444f0fb073ddcb58b16381f76697",
  "original_prompt": "Ingested from linux-6.6.14/arch/x86/events/intel/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_CPU_SUP_INTEL)\t\t+= core.o bts.o\nobj-$(CONFIG_CPU_SUP_INTEL)\t\t+= ds.o knc.o\nobj-$(CONFIG_CPU_SUP_INTEL)\t\t+= lbr.o p4.o p6.o pt.o\nobj-$(CONFIG_PERF_EVENTS_INTEL_UNCORE)\t+= intel-uncore.o\nintel-uncore-objs\t\t\t:= uncore.o uncore_nhmex.o uncore_snb.o uncore_snbep.o uncore_discovery.o\nobj-$(CONFIG_PERF_EVENTS_INTEL_CSTATE)\t+= intel-cstate.o\nintel-cstate-objs\t\t\t:= cstate.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}