{
  "module_name": "Makefile",
  "hash_id": "06a517a7a1d7bf13071761f85d0aa837884fc9918864fb3ffb9aa122e22b49af",
  "original_prompt": "Ingested from linux-6.6.14/fs/gfs2/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nccflags-y := -I$(src)\nobj-$(CONFIG_GFS2_FS) += gfs2.o\ngfs2-y := acl.o bmap.o dir.o xattr.o glock.o \\\n\tglops.o log.o lops.o main.o meta_io.o \\\n\taops.o dentry.o export.o file.o \\\n\tops_fstype.o inode.o quota.o \\\n\trecovery.o rgrp.o super.o sys.o trans.o util.o\n\ngfs2-$(CONFIG_GFS2_FS_LOCKING_DLM) += lock_dlm.o\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}