{
  "module_name": "Makefile",
  "hash_id": "2f1cafee97d454bcf6d812b9a4f74922a0da826c353f33e7af40fca6777b76bb",
  "original_prompt": "Ingested from linux-6.6.14/fs/lockd/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the linux lock manager stuff\n#\n\nccflags-y += -I$(src)\t\t\t# needed for trace events\n\nobj-$(CONFIG_LOCKD) += lockd.o\n\nlockd-objs-y += clntlock.o clntproc.o clntxdr.o host.o svc.o svclock.o \\\n\t        svcshare.o svcproc.o svcsubs.o mon.o trace.o xdr.o\nlockd-objs-$(CONFIG_LOCKD_V4) += clnt4xdr.o xdr4.o svc4proc.o\nlockd-objs-$(CONFIG_PROC_FS) += procfs.o\nlockd-objs\t\t      := $(lockd-objs-y)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}