{
  "module_name": "Makefile",
  "hash_id": "cae468d4fb3a00280d9187932f8e48d8590dd66a0382eabda3de7937cb803658",
  "original_prompt": "Ingested from linux-6.6.14/drivers/acpi/nfit/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_ACPI_NFIT) := nfit.o\nnfit-y := core.o\nnfit-y += intel.o\nnfit-$(CONFIG_X86_MCE) += mce.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}