{
  "module_name": "Makefile",
  "hash_id": "c7744814b3cc8578537c34bce38d24291977750706e4af35ec65e522e85b7ab6",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/usb/gspca/m5602/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_USB_M5602) += gspca_m5602.o\n\ngspca_m5602-objs := m5602_core.o \\\n\t\t    m5602_ov9650.o \\\n\t\t    m5602_ov7660.o \\\n\t\t    m5602_mt9m111.o \\\n\t\t    m5602_po1030.o \\\n\t\t    m5602_s5k83a.o \\\n\t\t    m5602_s5k4aa.o\n\nccflags-y += -I$(srctree)/drivers/media/usb/gspca\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}