#ifndef __HMEM_GLOBAL_H_INCLUDED__
#define __HMEM_GLOBAL_H_INCLUDED__
#include <type_support.h>
#define IS_HMEM_VERSION_1
#include "isp.h"
#define ISP_HIST_ALIGNMENT_LOG2		2
#define HMEM_SIZE_LOG2		(ISP_HIST_ADDRESS_BITS - ISP_HIST_ALIGNMENT_LOG2)
#define HMEM_SIZE			ISP_HIST_DEPTH
#define HMEM_UNIT_SIZE		(HMEM_SIZE / ISP_HIST_COMPONENTS)
#define HMEM_UNIT_COUNT		ISP_HIST_COMPONENTS
#define HMEM_RANGE_LOG2		ISP_HIST_WIDTH
#define HMEM_RANGE			BIT(HMEM_RANGE_LOG2)
typedef u32			hmem_data_t;
#endif  
