{
  "module_name": "Makefile",
  "hash_id": "6f3f8837b494bd6fca912895562bf12c37bef8ab56b168308c5542fabe77a864",
  "original_prompt": "Ingested from linux-6.6.14/tools/mm/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for vm tools\n#\ninclude ../scripts/Makefile.include\n\nTARGETS=page-types slabinfo page_owner_sort\n\nLIB_DIR = ../lib/api\nLIBS = $(LIB_DIR)/libapi.a\n\nCFLAGS += -Wall -Wextra -I../lib/ -pthread\nLDFLAGS += $(LIBS) -pthread\n\nall: $(TARGETS)\n\n$(TARGETS): $(LIBS)\n\n$(LIBS):\n\tmake -C $(LIB_DIR)\n\n%: %.c\n\t$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)\n\nclean:\n\t$(RM) page-types slabinfo page_owner_sort\n\tmake -C $(LIB_DIR) clean\n\nsbindir ?= /usr/sbin\n\ninstall: all\n\tinstall -d $(DESTDIR)$(sbindir)\n\tinstall -m 755 -p $(TARGETS) $(DESTDIR)$(sbindir)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}