{
  "module_name": "Makefile",
  "hash_id": "0040e42286fd28bf62e7203ac087c9c0bb57e8f5d61320d5a9928b2ec4d5a254",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/broadcom/brcm80211/brcmfmac/wcc/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: ISC\n#\n# Copyright (c) 2022 Broadcom Corporation\n\nccflags-y += \\\n\t-I $(srctree)/$(src) \\\n\t-I $(srctree)/$(src)/.. \\\n\t-I $(srctree)/$(src)/../../include\n\nobj-m += brcmfmac-wcc.o\nbrcmfmac-wcc-objs += \\\n\t\tcore.o module.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}