{
  "module_name": "Makefile",
  "hash_id": "86f235da90d7ff69efeeb3c9f984d6ad3824cc3b13d6df683a51a1014be8cfa3",
  "original_prompt": "Ingested from linux-6.6.14/drivers/scsi/qla2xxx/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nqla2xxx-y := qla_os.o qla_init.o qla_mbx.o qla_iocb.o qla_isr.o qla_gs.o \\\n\t\tqla_dbg.o qla_sup.o qla_attr.o qla_mid.o qla_dfs.o qla_bsg.o \\\n\t\tqla_nx.o qla_mr.o qla_nx2.o qla_target.o qla_tmpl.o qla_nvme.o \\\n\t\tqla_edif.o\n\nobj-$(CONFIG_SCSI_QLA_FC) += qla2xxx.o\nobj-$(CONFIG_TCM_QLA2XXX) += tcm_qla2xxx.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}