 

 

 

#define USE_TERMLIB 1
#include <build.priv.h>

MODULE_ID("$Id: make_keys.c,v 1.23 2021/08/18 20:55:25 tom Exp $")

#include <names.c>

static unsigned
unknown(void)
{
    static unsigned result = 0;

    if (result == 0) {
	unsigned n;
	for (n = 0; strnames[n] != 0; n++) {
	    ++result;
	}
	for (n = 0; strfnames[n] != 0; n++) {
	    ++result;
	}
    }
    return result;
}

static unsigned
lookup(const char *name)
{
    unsigned n;
    bool found = FALSE;
    for (n = 0; strnames[n] != 0; n++) {
	if (!strcmp(name, strnames[n])) {
	    found = TRUE;
	    break;
	}
    }
    if (!found) {
	for (n = 0; strfnames[n] != 0; n++) {
	    if (!strcmp(name, strfnames[n])) {
		found = TRUE;
		break;
	    }
	}
    }
    return found ? n : unknown();
}

static void
make_keys(FILE *ifp, FILE *ofp)
{
    char buffer[BUFSIZ];
    char from[256];
    char to[256];
    unsigned ignore = unknown();
    unsigned maxlen = 16;
    int scanned;

    while (fgets(buffer, (int) sizeof(buffer), ifp) != 0) {
	if (*buffer == '#')
	    continue;

	to[sizeof(to) - 1] = '\0';
	from[sizeof(from) - 1] = '\0';

	scanned = sscanf(buffer, "%255s %255s", to, from);
	if (scanned == 2) {
	    unsigned code = lookup(from);
	    if (code == ignore)
		continue;
	    if (strlen(from) > maxlen)
		maxlen = (unsigned) strlen(from);
	    fprintf(ofp, "\t{ %4u, %-*.*s },\t/* %s */\n",
		    code,
		    (int) maxlen, (int) maxlen,
		    to,
		    from);
	}
    }
}

static void
write_list(FILE *ofp, const char **list)
{
    while (*list != 0)
	fprintf(ofp, "%s\n", *list++);
}

int
main(int argc, char *argv[])
{
    static const char *prefix[] =
    {
	"#ifndef _INIT_KEYTRY_H",
	"#define _INIT_KEYTRY_H 1",
	"",
	"/* This file was generated by MAKE_KEYS */",
	"",
	"#include <tic.h>",
	"",
	"#if BROKEN_LINKER",
	"static",
	"#endif",
	"const struct tinfo_fkeys _nc_tinfo_fkeys[] = {",
	0
    };
    static const char *suffix[] =
    {
	"\t{ 0, 0} };",
	"",
	"#endif /* _INIT_KEYTRY_H */",
	0
    };

    write_list(stdout, prefix);
    if (argc > 1) {
	int n;
	for (n = 1; n < argc; n++) {
	    FILE *fp = fopen(argv[n], "r");
	    if (fp != 0) {
		make_keys(fp, stdout);
		fclose(fp);
	    }
	}
    } else {
	make_keys(stdin, stdout);
    }
    write_list(stdout, suffix);
    return EXIT_SUCCESS;
}
