{
  "module_name": "Makefile",
  "hash_id": "4483ca0d20b440e25c49ca188d981310e646f5415fbeb4b63111f0ad65d38f1d",
  "original_prompt": "Ingested from linux-6.6.14/sound/pci/ca0106/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nsnd-ca0106-objs := ca0106_main.o ca0106_mixer.o ca_midi.o\nsnd-ca0106-$(CONFIG_SND_PROC_FS) += ca0106_proc.o\n\nobj-$(CONFIG_SND_CA0106) += snd-ca0106.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}