{
  "module_name": "Makefile",
  "hash_id": "8c5687ca6dd5fad6958c3f01d0e9d6f5cfd5e3dd8531194a13bb3c553d54c859",
  "original_prompt": "Ingested from linux-6.6.14/tools/firewire/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nprefix = /usr\nnosy-dump-version = 0.4\n\nCC = gcc\n\nall : nosy-dump\n\nnosy-dump : CFLAGS = -Wall -O2 -g\nnosy-dump : CPPFLAGS = -DVERSION=\\\"$(nosy-dump-version)\\\" -I../../drivers/firewire\nnosy-dump : LDFLAGS = -g\nnosy-dump : LDLIBS = -lpopt\n\nnosy-dump : nosy-dump.o decode-fcp.o\n\nclean :\n\trm -rf *.o nosy-dump\n\ninstall :\n\tinstall nosy-dump $(prefix)/bin/nosy-dump\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}