{
  "module_name": "Makefile",
  "hash_id": "65aadcf62c18a1119d5ce57bc5d93ebaf68027709e2a9773167e3f47ba9197d0",
  "original_prompt": "Ingested from linux-6.6.14/drivers/slimbus/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for kernel SLIMbus framework.\n#\nobj-$(CONFIG_SLIMBUS)\t\t\t+= slimbus.o\nslimbus-y\t\t\t\t:= core.o messaging.o sched.o stream.o\n\n#Controllers\nobj-$(CONFIG_SLIM_QCOM_CTRL)\t\t+= slim-qcom-ctrl.o\nslim-qcom-ctrl-y\t\t\t:= qcom-ctrl.o\n\nobj-$(CONFIG_SLIM_QCOM_NGD_CTRL)\t+= slim-qcom-ngd-ctrl.o\nslim-qcom-ngd-ctrl-y\t\t\t:= qcom-ngd-ctrl.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}