CMSIS_MCU = RA4M1
MCU_SERIES = m4
LD_FILES = boards/RA4M1_CLICKER/ra4m1_clicker.ld


MICROPY_VFS_FAT = 1
USE_FSP_LPM = 0

CFLAGS+=-DDEFAULT_DBG_CH=0


FROZEN_MANIFEST ?= boards/RA4M1_CLICKER/manifest.py
