{
  "module_name": "Makefile",
  "hash_id": "58635301ff3df873e18ac3737410b6a0dee118df1aaad1b51bd1bdec1a9a5dae",
  "original_prompt": "Ingested from linux-6.6.14/net/key/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the key AF.\n#\n\nobj-$(CONFIG_NET_KEY) += af_key.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}