{
  "module_name": "Makefile",
  "hash_id": "0b3d83505b4be739165296aa7dc98eceba8c085348fbd894a925a72035bfba04",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/mediatek/mt76/mt7915/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: ISC\n\nobj-$(CONFIG_MT7915E) += mt7915e.o\n\nmt7915e-y := pci.o init.o dma.o eeprom.o main.o mcu.o mac.o \\\n\t     debugfs.o mmio.o\n\nmt7915e-$(CONFIG_NL80211_TESTMODE) += testmode.o\nmt7915e-$(CONFIG_MT798X_WMAC) += soc.o\nmt7915e-$(CONFIG_DEV_COREDUMP) += coredump.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}