{
  "module_name": "Makefile",
  "hash_id": "ed575fdcc7d97f32853569530df88ba6d6f9ca6b551af2b9f5c04b1cc4d9c86c",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/static_keys/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n# Makefile for static keys selftests\n\n# No binaries, but make sure arg-less \"make\" doesn't trigger \"run_tests\"\nall:\n\nTEST_PROGS := test_static_keys.sh\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}