{
  "module_name": "Makefile",
  "hash_id": "abf3c0846ecc134385a4b0fa18ce7e3781399fa9c0091df974ffc81771597aa3",
  "original_prompt": "Ingested from linux-6.6.14/sound/oss/dmasound/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the DMA sound driver\n#\n\nobj-$(CONFIG_DMASOUND_ATARI)\t+= dmasound_core.o dmasound_atari.o\nobj-$(CONFIG_DMASOUND_PAULA)\t+= dmasound_core.o dmasound_paula.o\nobj-$(CONFIG_DMASOUND_Q40)\t+= dmasound_core.o dmasound_q40.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}