{
  "module_name": "Makefile",
  "hash_id": "4971065311f248cce35c0bdff8d179940e52239af074c93bc608451a2f89b8aa",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/can/cc770/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n#  Makefile for the Bosch CC770 CAN controller drivers.\n#\n\nobj-$(CONFIG_CAN_CC770) += cc770.o\nobj-$(CONFIG_CAN_CC770_ISA) += cc770_isa.o\nobj-$(CONFIG_CAN_CC770_PLATFORM) += cc770_platform.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}