{
  "module_name": "Makefile",
  "hash_id": "49b684ce41b953d444c3409b521f2362b9834174852b48baf311c0cb55397743",
  "original_prompt": "Ingested from linux-6.6.14/drivers/nvme/common/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\nccflags-y\t\t\t+= -I$(src)\n\nobj-$(CONFIG_NVME_COMMON)\t+= nvme-common.o\n\nnvme-common-y\t\t\t+= auth.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}