{
  "module_name": "Makefile",
  "hash_id": "c498ce89c79e099c76ee8b71b4133afbc12184a7070f1473b68f25052f944495",
  "original_prompt": "Ingested from linux-6.6.14/drivers/platform/x86/amd/pmf/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for linux/drivers/platform/x86/amd/pmf\n# AMD Platform Management Framework\n#\n\nobj-$(CONFIG_AMD_PMF) += amd-pmf.o\namd-pmf-objs := core.o acpi.o sps.o \\\n\t\tauto-mode.o cnqf.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}