{
  "module_name": "Makefile",
  "hash_id": "958ed4ed058afad0ea18330b8629627262d2c32c36d01fbb932daa5a435fca15",
  "original_prompt": "Ingested from linux-6.6.14/drivers/mtd/nand/raw/gpmi-nand/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_MTD_NAND_GPMI_NAND) += gpmi-nand.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}