{
  "module_name": "Makefile",
  "hash_id": "a050859294bc71517e3d54be1f8aca5b50ffd69915feaf2abe3e137751be64f9",
  "original_prompt": "Ingested from linux-6.6.14/drivers/phy/st/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_PHY_MIPHY28LP) \t\t+= phy-miphy28lp.o\nobj-$(CONFIG_PHY_ST_SPEAR1310_MIPHY)\t+= phy-spear1310-miphy.o\nobj-$(CONFIG_PHY_ST_SPEAR1340_MIPHY)\t+= phy-spear1340-miphy.o\nobj-$(CONFIG_PHY_STIH407_USB)\t\t+= phy-stih407-usb.o\nobj-$(CONFIG_PHY_STM32_USBPHYC) \t+= phy-stm32-usbphyc.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}