{
  "module_name": "Makefile",
  "hash_id": "71dc211c759d26a7915a482a698419812c6a07d9aef45decfca8cefa727ea4b3",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/intel/igb/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Copyright(c) 1999 - 2018 Intel Corporation.\n#\n# Makefile for the Intel(R) 82575 PCI-Express ethernet driver\n#\n\nobj-$(CONFIG_IGB) += igb.o\n\nigb-objs := igb_main.o igb_ethtool.o e1000_82575.o \\\n\t    e1000_mac.o e1000_nvm.o e1000_phy.o e1000_mbx.o \\\n\t    e1000_i210.o igb_ptp.o igb_hwmon.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}