{
  "module_name": "Makefile",
  "hash_id": "3a7c5c4a330b91bc69d05d12e69fc37fbca59fa422da3b2325fcea04143f2790",
  "original_prompt": "Ingested from linux-6.6.14/drivers/scsi/qedf/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_QEDF) := qedf.o\nqedf-y = qedf_dbg.o qedf_main.o qedf_io.o qedf_fip.o \\\n\t qedf_attr.o qedf_els.o drv_scsi_fw_funcs.o drv_fcoe_fw_funcs.o\n\nqedf-$(CONFIG_DEBUG_FS) += qedf_debugfs.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}