{
  "module_name": "Makefile",
  "hash_id": "fbc001bc9e987675086a776fc6028c2f8e3fc4ef284ac44977725124096d2426",
  "original_prompt": "Ingested from linux-6.6.14/sound/pci/pcxhr/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nsnd-pcxhr-objs := pcxhr.o pcxhr_hwdep.o pcxhr_mixer.o pcxhr_core.o pcxhr_mix22.o\nobj-$(CONFIG_SND_PCXHR) += snd-pcxhr.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}