{
  "module_name": "Makefile",
  "hash_id": "7d021a21362036b145d60bd736756fbf627a5edbfc2b11e887e18b9f30575d38",
  "original_prompt": "Ingested from linux-6.6.14/drivers/video/fbdev/savage/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the S3 Savage framebuffer driver\n#\n\nobj-$(CONFIG_FB_SAVAGE)\t\t\t+= savagefb.o\n\nsavagefb-y\t\t\t\t+= savagefb_driver.o\nsavagefb-$(CONFIG_FB_SAVAGE_I2C)\t+= savagefb-i2c.o\nsavagefb-$(CONFIG_FB_SAVAGE_ACCEL)\t+= savagefb_accel.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}