{
  "module_name": "Makefile",
  "hash_id": "134019b30ebdcda36365d63ac0c052bdf2561049a56d101f360a179269836258",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/common/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-y += b2c2/ saa7146/ siano/ v4l2-tpg/ videobuf2/\n\n# Please keep it alphabetically sorted by Kconfig name\n# (e. g. LC_ALL=C sort Makefile)\nobj-$(CONFIG_CYPRESS_FIRMWARE) += cypress_firmware.o\nobj-$(CONFIG_TTPCI_EEPROM) += ttpci-eeprom.o\nobj-$(CONFIG_UVC_COMMON) += uvc.o\nobj-$(CONFIG_VIDEO_CX2341X) += cx2341x.o\nobj-$(CONFIG_VIDEO_TVEEPROM) += tveeprom.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}