{
  "module_name": "Makefile",
  "hash_id": "7aaa6d1a128d2db2c3c7d007b3eb7d4540a6936a5e1deba0cc160fbaf6641621",
  "original_prompt": "Ingested from linux-6.6.14/drivers/pmdomain/bcm/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_BCM_PMB)\t\t\t+= bcm-pmb.o\nobj-$(CONFIG_BCM2835_POWER)\t\t+= bcm2835-power.o\nobj-$(CONFIG_BCM63XX_POWER)\t\t+= bcm63xx-power.o\nobj-$(CONFIG_RASPBERRYPI_POWER)\t\t+= raspberrypi-power.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}