{
  "module_name": "Makefile",
  "hash_id": "92d6623ddb858302dd616335751a883670c82b310d2459dd3d488bb0c9859cdb",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/oki-semi/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the OKI Semiconductor device drivers.\n#\n\nobj-$(CONFIG_PCH_GBE) += pch_gbe/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}