{
  "module_name": "Makefile",
  "hash_id": "6805caadfab88c525205c7cf17e560a8ddbdd3869de41d397bb7ec7956e6819e",
  "original_prompt": "Ingested from linux-6.6.14/drivers/ntb/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_NTB) += ntb.o hw/ test/\nobj-$(CONFIG_NTB_TRANSPORT) += ntb_transport.o\n\nntb-y\t\t\t:= core.o\nntb-$(CONFIG_NTB_MSI)\t+= msi.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}