{
  "module_name": "Makefile",
  "hash_id": "cd889bd84530c1123f47916a5ae52f74c12992a3dd92d2cc1e09fe09968ed87e",
  "original_prompt": "Ingested from linux-6.6.14/tools/wmi/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nPREFIX ?= /usr\nSBINDIR ?= sbin\nINSTALL ?= install\nCFLAGS += -D__EXPORTED_HEADERS__ -I../../include/uapi -I../../include\n\nTARGET = dell-smbios-example\n\nall: $(TARGET)\n\n%: %.c\n\t$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $<\n\nclean:\n\t$(RM) $(TARGET)\n\ninstall: dell-smbios-example\n\t$(INSTALL) -D -m 755 $(TARGET) $(DESTDIR)$(PREFIX)/$(SBINDIR)/$(TARGET)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}