{
  "module_name": "Makefile",
  "hash_id": "b8b717e2a7323a615a1c4817b3f94ce11a8aa798b8fa8c96dfa73d915bb2410d",
  "original_prompt": "Ingested from linux-6.6.14/fs/notify/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_FSNOTIFY)\t\t+= fsnotify.o notification.o group.o mark.o \\\n\t\t\t\t   fdinfo.o\n\nobj-y\t\t\t+= dnotify/\nobj-y\t\t\t+= inotify/\nobj-y\t\t\t+= fanotify/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}