{
  "module_name": "Makefile",
  "hash_id": "c1f77a6bb4c5ab9d74629c2b6139bf09fb6dc120bd99d9427550ee15fbfa5989",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/platform/sunxi/sun6i-mipi-csi2/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nsun6i-mipi-csi2-y += sun6i_mipi_csi2.o\n\nobj-$(CONFIG_VIDEO_SUN6I_MIPI_CSI2) += sun6i-mipi-csi2.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}