{
  "module_name": "Makefile",
  "hash_id": "1e0a16f4c41b1115872b85746c220059d68e685e4a251047b3b09c553f158216",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/pidfd/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nCFLAGS += -g $(KHDR_INCLUDES) -pthread -Wall\n\nTEST_GEN_PROGS := pidfd_test pidfd_fdinfo_test pidfd_open_test \\\n\tpidfd_poll_test pidfd_wait pidfd_getfd_test pidfd_setns_test\n\ninclude ../lib.mk\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}