{
  "module_name": "Makefile",
  "hash_id": "de4ac4a92f767245d81b8e89cc1a84433b69cfd97aed4ef0a446da6fbef729a7",
  "original_prompt": "Ingested from linux-6.6.14/drivers/usb/typec/tcpm/qcom/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\nobj-$(CONFIG_TYPEC_QCOM_PMIC)\t\t+= qcom_pmic_tcpm.o\nqcom_pmic_tcpm-y\t\t\t+= qcom_pmic_typec.o \\\n\t\t\t\t\t   qcom_pmic_typec_port.o \\\n\t\t\t\t\t   qcom_pmic_typec_pdphy.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}