{
  "module_name": "Makefile",
  "hash_id": "d5c259f8de5cfa8f358f45a27fab9b3d5be12360da0f06926d1010f1065666dc",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/hyperv/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_HYPERV_NET) += hv_netvsc.o\n\nhv_netvsc-y := netvsc_drv.o netvsc.o rndis_filter.o netvsc_trace.o netvsc_bpf.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}