{
  "module_name": "Makefile",
  "hash_id": "2e1ffffc48be621f572126d63e3cce5c3a826525b0444b4ce12dce645afca52f",
  "original_prompt": "Ingested from linux-6.6.14/drivers/phy/ingenic/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_PHY_INGENIC_USB)\t\t+= phy-ingenic-usb.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}