{
  "module_name": "Makefile",
  "hash_id": "dd7a8316d3c9ab264baae4b78407ad0ef3b4d81fb0d921352478d17718212b04",
  "original_prompt": "Ingested from linux-6.6.14/drivers/infiniband/hw/mlx4/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_MLX4_INFINIBAND)\t+= mlx4_ib.o\n\nmlx4_ib-y :=\tah.o cq.o doorbell.o mad.o main.o mr.o qp.o srq.o mcg.o cm.o alias_GUID.o sysfs.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}