{
  "module_name": "Makefile",
  "hash_id": "36f8301d19d9417d4cbde2fc080826fd0bc57a36aefc16d955f2e50c3ea923ec",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wwan/iosm/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: (GPL-2.0-only)\n#\n# Copyright (C) 2020-21 Intel Corporation.\n#\n\niosm-y = \\\n\tiosm_ipc_task_queue.o\t\\\n\tiosm_ipc_imem.o\t\t\t\\\n\tiosm_ipc_imem_ops.o\t\t\\\n\tiosm_ipc_mmio.o\t\t\t\\\n\tiosm_ipc_port.o\t\t\t\\\n\tiosm_ipc_wwan.o\t\t\t\\\n\tiosm_ipc_uevent.o\t\t\\\n\tiosm_ipc_pm.o\t\t\t\\\n\tiosm_ipc_pcie.o\t\t\t\\\n\tiosm_ipc_irq.o\t\t\t\\\n\tiosm_ipc_chnl_cfg.o\t\t\\\n\tiosm_ipc_protocol.o\t\t\\\n\tiosm_ipc_protocol_ops.o\t\\\n\tiosm_ipc_mux.o\t\t\t\\\n\tiosm_ipc_mux_codec.o\t\t\\\n\tiosm_ipc_devlink.o\t\t\\\n\tiosm_ipc_flash.o\t\t\\\n\tiosm_ipc_coredump.o\n\niosm-$(CONFIG_WWAN_DEBUGFS) += \\\n\tiosm_ipc_debugfs.o\t\t\\\n\tiosm_ipc_trace.o\n\nobj-$(CONFIG_IOSM) := iosm.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}