{
  "module_name": "Makefile",
  "hash_id": "6e898252d8246d85447d5ae7134e4516a0bd2647a04c22bc1fa9a51912a620b7",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/tmpfs/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nCFLAGS += -Wall -O2\nCFLAGS += -D_GNU_SOURCE\n\nTEST_GEN_PROGS :=\nTEST_GEN_PROGS += bug-link-o-tmpfile\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}