{
  "module_name": "Makefile",
  "hash_id": "1cafed1d9837c8f9d7df304aa7cc669f22027be5958389e8ae79921bba5943a7",
  "original_prompt": "Ingested from linux-6.6.14/sound/firewire/digi00x/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nsnd-firewire-digi00x-objs := amdtp-dot.o digi00x-stream.o digi00x-proc.o \\\n\t\t\t     digi00x-pcm.o digi00x-hwdep.o \\\n\t\t\t     digi00x-transaction.o digi00x-midi.o digi00x.o\nobj-$(CONFIG_SND_FIREWIRE_DIGI00X) += snd-firewire-digi00x.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}