{
  "module_name": "Makefile",
  "hash_id": "40a3a644a05e2928030db22ed62114dd198493440e25536eacf0e942c86cfa66",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/platform/mediatek/mdp/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nmtk-mdp-y += mtk_mdp_core.o\nmtk-mdp-y += mtk_mdp_comp.o\nmtk-mdp-y += mtk_mdp_m2m.o\nmtk-mdp-y += mtk_mdp_regs.o\nmtk-mdp-y += mtk_mdp_vpu.o\n\nobj-$(CONFIG_VIDEO_MEDIATEK_MDP) += mtk-mdp.o\n\nccflags-y += -I$(srctree)/drivers/media/platform/mediatek/vpu\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}