{
  "module_name": "Makefile",
  "hash_id": "48b32eed3de6b39f8b277cb471671bed0922f6c66f9e406ed74ed0a4afee7d12",
  "original_prompt": "Ingested from linux-6.6.14/samples/acrn/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\n.PHONY: vm-sample\n\nvm-sample: vm-sample.o payload.o\n\t$(CC) $^ -o $@\n\npayload.o: payload.ld guest16.o\n\t$(LD) -T $< -o $@\n\nclean:\n\trm *.o vm-sample\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}