{
  "module_name": "Makefile",
  "hash_id": "ca516d4d4f048be97c36e4060bb6951c9f496024b2180331d32fc169c57990a2",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/efivarfs/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nCFLAGS = -Wall\n\nTEST_GEN_FILES := open-unlink create-read\nTEST_PROGS := efivarfs.sh\n\ninclude ../lib.mk\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}