{
  "module_name": "Makefile",
  "hash_id": "35ec32e26f54a892157f5bf8b4c9e8c4e96defee191448bfbfd8311f5f1ea0a2",
  "original_prompt": "Ingested from linux-6.6.14/drivers/pmdomain/actions/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0+\nobj-$(CONFIG_OWL_PM_DOMAINS_HELPER)\t+= owl-sps-helper.o\nobj-$(CONFIG_OWL_PM_DOMAINS)\t\t+= owl-sps.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}