#ifndef	_ATUSB_H
#define	_ATUSB_H
#define ATUSB_VENDOR_ID	0x20b7	 
#define ATUSB_PRODUCT_ID 0x1540	 
#define ATUSB_BUILD_SIZE 256	 
enum atusb_requests {
	ATUSB_ID			= 0x00,	 
	ATUSB_BUILD,
	ATUSB_RESET,
	ATUSB_RF_RESET			= 0x10,	 
	ATUSB_POLL_INT,
	ATUSB_TEST,			 
	ATUSB_TIMER,
	ATUSB_GPIO,
	ATUSB_SLP_TR,
	ATUSB_GPIO_CLEANUP,
	ATUSB_REG_WRITE			= 0x20,	 
	ATUSB_REG_READ,
	ATUSB_BUF_WRITE,
	ATUSB_BUF_READ,
	ATUSB_SRAM_WRITE,
	ATUSB_SRAM_READ,
	ATUSB_SPI_WRITE			= 0x30,	 
	ATUSB_SPI_READ1,
	ATUSB_SPI_READ2,
	ATUSB_SPI_WRITE2_SYNC,
	ATUSB_RX_MODE			= 0x40,  
	ATUSB_TX,
	ATUSB_EUI64_WRITE		= 0x50,  
	ATUSB_EUI64_READ,
};
enum {
	ATUSB_HW_TYPE_100813,	 
	ATUSB_HW_TYPE_101216,	 
	ATUSB_HW_TYPE_110131,	 
	ATUSB_HW_TYPE_RZUSB,	 
	ATUSB_HW_TYPE_HULUSB,	 
};
#define ATUSB_REQ_FROM_DEV	(USB_TYPE_VENDOR | USB_DIR_IN)
#define ATUSB_REQ_TO_DEV	(USB_TYPE_VENDOR | USB_DIR_OUT)
#endif  
