{
  "module_name": "Makefile",
  "hash_id": "410079b1d506833291631b96bb438ff409b11aca64ad90ef85046afa6c27890b",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/pci/pt3/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\nearth-pt3-objs += pt3.o pt3_i2c.o pt3_dma.o\n\nobj-$(CONFIG_DVB_PT3) += earth-pt3.o\n\nccflags-y += -I $(srctree)/drivers/media/dvb-frontends\nccflags-y += -I $(srctree)/drivers/media/tuners\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}