{
  "module_name": "Makefile",
  "hash_id": "affb126c7ac4e5eb270933b56702bbae0980da6bd56fa90313f0535126db652d",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/pci/ngene/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the nGene device driver\n#\n\nngene-objs := ngene-core.o ngene-i2c.o ngene-cards.o ngene-dvb.o\n\nobj-$(CONFIG_DVB_NGENE) += ngene.o\n\nccflags-y += -I $(srctree)/drivers/media/dvb-frontends/\nccflags-y += -I $(srctree)/drivers/media/tuners/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}