{
  "module_name": "Makefile",
  "hash_id": "eff919e726717544612fe567a3782225d52a381e06cd77c0b123e13344e8696e",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/uevent/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nall:\n\ninclude ../lib.mk\n\n.PHONY: all clean\n\nBINARIES := uevent_filtering\nCFLAGS += -Wl,-no-as-needed -Wall\n\nuevent_filtering: uevent_filtering.c ../kselftest.h ../kselftest_harness.h\n\t$(CC) $(CFLAGS) $< -o $@\n\nTEST_PROGS += $(BINARIES)\nEXTRA_CLEAN := $(BINARIES)\n\nall: $(BINARIES)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}