{
  "module_name": "Makefile",
  "hash_id": "43e05bcaf7bae731e8c9f5696d6b07ebfe3661ec07ce7f7528e5839eca3faf0e",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/chelsio/inline_crypto/chtls/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nccflags-y := -I $(srctree)/drivers/net/ethernet/chelsio/cxgb4 \\\n\t     -I $(srctree)/drivers/crypto/chelsio\n\nobj-$(CONFIG_CRYPTO_DEV_CHELSIO_TLS) += chtls.o\nchtls-objs := chtls_main.o chtls_cm.o chtls_io.o chtls_hw.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}