{
  "module_name": "Makefile",
  "hash_id": "35301005b9624320c2d830292f6d218ebb1971c652c39999f5496b54580b29c6",
  "original_prompt": "Ingested from linux-6.6.14/drivers/iio/filter/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for industrial I/O Filter drivers\n#\n\n# When adding new entries keep the list in alphabetical order\nobj-$(CONFIG_ADMV8818) += admv8818.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}