{
  "module_name": "Makefile",
  "hash_id": "bdc06892ddfdcdab6d04c13a40b670946f9ccb767b4511233f84080633fe41fc",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/sync/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nCFLAGS += -O2 -g -std=gnu89 -pthread -Wall -Wextra\nCFLAGS += $(KHDR_INCLUDES)\nLDFLAGS += -pthread\n\n.PHONY: all clean\n\ninclude ../lib.mk\n\n# lib.mk TEST_CUSTOM_PROGS var is for custom tests that need special\n# build rules. lib.mk will run and install them.\n\nTEST_CUSTOM_PROGS := $(OUTPUT)/sync_test\nall: $(TEST_CUSTOM_PROGS)\n\nOBJS = sync_test.o sync.o\n\nTESTS += sync_alloc.o\nTESTS += sync_fence.o\nTESTS += sync_merge.o\nTESTS += sync_wait.o\nTESTS += sync_stress_parallelism.o\nTESTS += sync_stress_consumer.o\nTESTS += sync_stress_merge.o\n\nOBJS := $(patsubst %,$(OUTPUT)/%,$(OBJS))\nTESTS := $(patsubst %,$(OUTPUT)/%,$(TESTS))\n\n$(TEST_CUSTOM_PROGS): $(TESTS) $(OBJS)\n\t$(CC) -o $(TEST_CUSTOM_PROGS) $(OBJS) $(TESTS) $(CFLAGS) $(LDFLAGS)\n\n$(OBJS): $(OUTPUT)/%.o: %.c\n\t$(CC) -c $^ -o $@ $(CFLAGS)\n\n$(TESTS): $(OUTPUT)/%.o: %.c\n\t$(CC) -c $^ -o $@\n\nEXTRA_CLEAN := $(TEST_CUSTOM_PROGS) $(OBJS) $(TESTS)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}