 

 
#define VERSION 1
#define REVISION 3

 
#define CLOCK 65000  
#define XPIX 1024
#define YPIX 768
#define XY_RATIO XY_RATIO_4_3
#define XBLANK 320
#define YBLANK 38
#define XOFFSET 8
#define XPULSE 144
#define YOFFSET 3
#define YPULSE 6
#define DPI 72
#define VFREQ 60  
#define TIMING_NAME "Linux XGA"
#define ESTABLISHED_TIMING2_BITS 0x08  
#define HSYNC_POL 0
#define VSYNC_POL 0

#include "edid.S"
