{
  "module_name": "Makefile",
  "hash_id": "2135cceacefc72968dd2375e8e2d6cd44fb56a937d1c237f71fb5e19f093e1dd",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/cec/platform/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the CEC platform device drivers.\n#\n\n# Please keep it in alphabetic order\nobj-$(CONFIG_CEC_CROS_EC) += cros-ec/\nobj-$(CONFIG_CEC_GPIO) += cec-gpio/\nobj-y += meson/\nobj-$(CONFIG_CEC_SAMSUNG_S5P) += s5p/\nobj-$(CONFIG_CEC_SECO) += seco/\nobj-$(CONFIG_CEC_STI) += sti/\nobj-$(CONFIG_CEC_STM32) += stm32/\nobj-$(CONFIG_CEC_TEGRA) += tegra/\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}