{
  "module_name": "Makefile",
  "hash_id": "75b71b13977299102656db8c924c3af376d6bebcfbdce5017cace2c29a27d63b",
  "original_prompt": "Ingested from linux-6.6.14/drivers/vfio/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_VFIO) += vfio.o\n\nvfio-y += vfio_main.o \\\n\t  iova_bitmap.o\nvfio-$(CONFIG_VFIO_DEVICE_CDEV) += device_cdev.o\nvfio-$(CONFIG_VFIO_GROUP) += group.o\nvfio-$(CONFIG_IOMMUFD) += iommufd.o\nvfio-$(CONFIG_VFIO_CONTAINER) += container.o\nvfio-$(CONFIG_VFIO_VIRQFD) += virqfd.o\n\nobj-$(CONFIG_VFIO_IOMMU_TYPE1) += vfio_iommu_type1.o\nobj-$(CONFIG_VFIO_IOMMU_SPAPR_TCE) += vfio_iommu_spapr_tce.o\nobj-$(CONFIG_VFIO_PCI_CORE) += pci/\nobj-$(CONFIG_VFIO_PLATFORM_BASE) += platform/\nobj-$(CONFIG_VFIO_MDEV) += mdev/\nobj-$(CONFIG_VFIO_FSL_MC) += fsl-mc/\nobj-$(CONFIG_VFIO_CDX) += cdx/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}