{
  "module_name": "Makefile",
  "hash_id": "2f0fb62c039d2b492ffb37bbb0e659bd9ac899cda4866bc36ca8b788cfd751b2",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/intel/iavf/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Copyright(c) 2013 - 2018 Intel Corporation.\n#\n# Makefile for the Intel(R) Ethernet Adaptive Virtual Function (iavf)\n# driver\n#\n#\n\nccflags-y += -I$(src)\nsubdir-ccflags-y += -I$(src)\n\nobj-$(CONFIG_IAVF) += iavf.o\n\niavf-objs := iavf_main.o iavf_ethtool.o iavf_virtchnl.o iavf_fdir.o \\\n\t     iavf_adv_rss.o \\\n\t     iavf_txrx.o iavf_common.o iavf_adminq.o iavf_client.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}