{
  "module_name": "Makefile",
  "hash_id": "15330cbb8f2b43627bcba62c1917c45235c815a5385bdbd91fd90a1b17d1fc47",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/mediatek/mt7601u/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_MT7601U)\t+= mt7601u.o\n\nmt7601u-objs\t= \\\n\tusb.o init.o main.o mcu.o trace.o dma.o core.o eeprom.o phy.o \\\n\tmac.o util.o debugfs.o tx.o\n\nCFLAGS_trace.o := -I$(src)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}