{
  "module_name": "Makefile",
  "hash_id": "7946ef848669fa9b7b860a852dc57b39c9dfe39392cfa2c0e1d0e9850fb2798c",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/can/ctucanfd/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-or-later\n#\n# Makefile for the CTU CAN-FD IP module drivers\n#\n\nobj-$(CONFIG_CAN_CTUCANFD) := ctucanfd.o\nctucanfd-y := ctucanfd_base.o\n\nobj-$(CONFIG_CAN_CTUCANFD_PCI) += ctucanfd_pci.o\nobj-$(CONFIG_CAN_CTUCANFD_PLATFORM) += ctucanfd_platform.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}