{
  "module_name": "Makefile",
  "hash_id": "f649ff660960bcf4489bb6a4af9eac240d8e679f1e4f87bffad4a000dbc4f364",
  "original_prompt": "Ingested from linux-6.6.14/fs/vboxsf/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: MIT\n\nobj-$(CONFIG_VBOXSF_FS) += vboxsf.o\n\nvboxsf-y := dir.o file.o utils.o vboxsf_wrappers.o super.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}