{
  "module_name": "Makefile",
  "hash_id": "a3b8d82b9749d3c8b210c84358c8797738067c94858ab8560da66fe04856be12",
  "original_prompt": "Ingested from linux-6.6.14/drivers/auxdisplay/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the kernel auxiliary displays device drivers.\n#\n\nobj-$(CONFIG_CHARLCD)\t\t+= charlcd.o\nobj-$(CONFIG_HD44780_COMMON)\t+= hd44780_common.o\nobj-$(CONFIG_ARM_CHARLCD)\t+= arm-charlcd.o\nobj-$(CONFIG_KS0108)\t\t+= ks0108.o\nobj-$(CONFIG_CFAG12864B)\t+= cfag12864b.o cfag12864bfb.o\nobj-$(CONFIG_IMG_ASCII_LCD)\t+= img-ascii-lcd.o\nobj-$(CONFIG_HD44780)\t\t+= hd44780.o\nobj-$(CONFIG_HT16K33)\t\t+= ht16k33.o\nobj-$(CONFIG_PARPORT_PANEL)\t+= panel.o\nobj-$(CONFIG_LCD2S)\t\t+= lcd2s.o\nobj-$(CONFIG_LINEDISP)\t\t+= line-display.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}