{
  "module_name": "Makefile",
  "hash_id": "2263913fcafb9cb72bca081dd21e4c51120e5663e8444ffdc5f367dee4387b2d",
  "original_prompt": "Ingested from linux-6.6.14/drivers/staging/emxx_udc/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_USB_EMXX)\t:= emxx_udc.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}