{
  "module_name": "Makefile",
  "hash_id": "774d18863d6e64d987b20d9d37e037c3858269924b2c1d4527969711e0017971",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/kexec/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n# Makefile for kexec tests\n\nARCH ?= $(shell uname -m 2>/dev/null || echo not)\nARCH_PROCESSED := $(shell echo $(ARCH) | sed -e s/i.86/x86/ -e s/x86_64/x86/)\n\nifeq ($(ARCH_PROCESSED),$(filter $(ARCH_PROCESSED),x86 ppc64le))\nTEST_PROGS := test_kexec_load.sh test_kexec_file_load.sh\nTEST_FILES := kexec_common_lib.sh\n\ninclude ../lib.mk\n\nendif\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}