{
  "module_name": "Makefile",
  "hash_id": "be0e701a5f41edaac42ae63737e876e71852df5006142a0ac0a7de90a8beae7f",
  "original_prompt": "Ingested from openssh-9.6p1/regress/unittests/test_helper/Makefile",
  "human_readable_source": "#\t$OpenBSD: Makefile,v 1.3 2016/07/04 18:01:44 guenther Exp $\n\nLIB=\ttest_helper\nSRCS=\ttest_helper.c fuzz.c\n\nNOPROFILE= yes\nNOPIC=\tyes\n\n# Hack to allow building with SUBDIR in ../../Makefile\nregress: all\n\ninstall:\n\t@echo -n\n\n.include <bsd.lib.mk>\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}