{
  "module_name": "Makefile",
  "hash_id": "e8e11cb5f9e8477d9fb13f90c9c1fc0e9bd8ea0ace7beb9dd8600634b8c1a115",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/amd/ps/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0+\n# Pink Sardine platform Support\nsnd-pci-ps-objs := pci-ps.o\nsnd-ps-pdm-dma-objs := ps-pdm-dma.o\nsnd-soc-ps-mach-objs := ps-mach.o\nsnd-ps-sdw-dma-objs := ps-sdw-dma.o\n\nobj-$(CONFIG_SND_SOC_AMD_PS) += snd-pci-ps.o\nobj-$(CONFIG_SND_SOC_AMD_PS) += snd-ps-pdm-dma.o\nobj-$(CONFIG_SND_SOC_AMD_PS) += snd-ps-sdw-dma.o\nobj-$(CONFIG_SND_SOC_AMD_PS_MACH)   += snd-soc-ps-mach.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}