{
  "module_name": "Makefile",
  "hash_id": "d2cfd7c977a225af630960a269eb8523f57568bf7be2db11428dafca80de02dc",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/ptrace/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nCFLAGS += -std=c99 -pthread -Wall $(KHDR_INCLUDES)\n\nTEST_GEN_PROGS := get_syscall_info peeksiginfo vmaccess get_set_sud\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}