{
  "module_name": "Makefile",
  "hash_id": "2021debe60e4016957159137c0ac9fdf2fe1ddc9fd33fc323421167771648a55",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/sfc/siena/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nsfc-siena-y\t\t+= farch.o siena.o \\\n\t\t\t   efx.o efx_common.o efx_channels.o nic.o \\\n\t\t\t   tx.o tx_common.o rx.o rx_common.o \\\n\t\t\t   selftest.o ethtool.o ethtool_common.o ptp.o \\\n\t\t\t   mcdi.o mcdi_port.o mcdi_port_common.o \\\n\t\t\t   mcdi_mon.o\nsfc-siena-$(CONFIG_SFC_SIENA_MTD)\t+= mtd.o\nsfc-siena-$(CONFIG_SFC_SIENA_SRIOV)\t+= siena_sriov.o\n\nobj-$(CONFIG_SFC_SIENA)\t+= sfc-siena.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}