 

#include <linux/init.h>
#include <linux/platform_device.h>
#include <linux/of.h>
#include <linux/pinctrl/pinctrl.h>

#include "pinctrl-sunxi.h"

static const struct sunxi_desc_pin sun5i_pins[] = {
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 0),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 1),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 2),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 3),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 4),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 5),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 6),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 7),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 8),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 9),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 10),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 11),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 12),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "uart1"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 13),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "uart1"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 14),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "uart1"),		 
		  SUNXI_FUNCTION(0x4, "uart3"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 15),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "uart1"),		 
		  SUNXI_FUNCTION(0x4, "uart3"),		 
		  SUNXI_FUNCTION(0x5, "keypad")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 16),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "uart2")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(A, 17),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "uart2"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 31)),		 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "pwm"),		 
		  SUNXI_FUNCTION_VARIANT(0x3,
					 "spdif",	 
					 PINCTRL_SUN5I_GR8),
		  SUNXI_FUNCTION_IRQ(0x6, 16)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ir0"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 17)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ir0"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 18)),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(B, 5),
		  PINCTRL_SUN5I_A10S | PINCTRL_SUN5I_GR8,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2s"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 19)),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(B, 6),
		  PINCTRL_SUN5I_A10S | PINCTRL_SUN5I_GR8,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2s"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 20)),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(B, 7),
		  PINCTRL_SUN5I_A10S | PINCTRL_SUN5I_GR8,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2s"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 21)),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(B, 8),
		  PINCTRL_SUN5I_A10S | PINCTRL_SUN5I_GR8,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2s"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 22)),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(B, 9),
		  PINCTRL_SUN5I_A10S | PINCTRL_SUN5I_GR8,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2s"),		 
		  SUNXI_FUNCTION_VARIANT(0x3,
					 "spdif",	 
					 PINCTRL_SUN5I_GR8),
		  SUNXI_FUNCTION_IRQ(0x6, 23)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi2"),		 
		  SUNXI_FUNCTION_VARIANT(0x3,
					 "spdif",	 
					 PINCTRL_SUN5I_GR8),
		  SUNXI_FUNCTION_IRQ(0x6, 24)),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(B, 11),
		  PINCTRL_SUN5I_A10S | PINCTRL_SUN5I_GR8,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi2"),		 
		  SUNXI_FUNCTION(0x3, "jtag"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 25)),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(B, 12),
		  PINCTRL_SUN5I_A10S | PINCTRL_SUN5I_GR8,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi2"),		 
		  SUNXI_FUNCTION(0x3, "jtag"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 26)),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(B, 13),
		  PINCTRL_SUN5I_A10S | PINCTRL_SUN5I_GR8,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi2"),		 
		  SUNXI_FUNCTION(0x3, "jtag"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 27)),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(B, 14),
		  PINCTRL_SUN5I_A10S | PINCTRL_SUN5I_GR8,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi2"),		 
		  SUNXI_FUNCTION(0x3, "jtag"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 28)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 15),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 16),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 17),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 18),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c2")),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(B, 19),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "uart0"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 29)),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(B, 20),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "uart0"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 30)),		 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "spi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "spi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "spi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "spi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 7),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 8),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 9),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 11),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 12),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 13),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 14),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 15),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(C, 16),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x4, "uart3")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(C, 17),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x4, "uart3")),	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(C, 18),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "uart2"),		 
		  SUNXI_FUNCTION(0x4, "uart3")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 19),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "uart2"),		 
		  SUNXI_FUNCTION(0x4, "uart3")),	 
	 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(D, 0),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0")),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(D, 1),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "uart2")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "uart2")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "uart2")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "uart2")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 7),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(D, 8),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0")),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(D, 9),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 11),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 12),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 13),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 14),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 15),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(D, 16),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0")),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(D, 17),
		  PINCTRL_SUN5I_A10S,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 18),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 19),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 20),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 21),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 22),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 23),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 24),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 25),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 26),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 27),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "emac")),		 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0"),		 
		  SUNXI_FUNCTION(0x4, "spi2"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 14)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0"),		 
		  SUNXI_FUNCTION(0x4, "spi2"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 15)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0"),		 
		  SUNXI_FUNCTION(0x4, "spi2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0"),		 
		  SUNXI_FUNCTION(0x4, "spi2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0"),		 
		  SUNXI_FUNCTION(0x4, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0"),		 
		  SUNXI_FUNCTION(0x4, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0"),		 
		  SUNXI_FUNCTION(0x4, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 7),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0"),		 
		  SUNXI_FUNCTION(0x4, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 8),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0"),		 
		  SUNXI_FUNCTION(0x4, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 9),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0"),		 
		  SUNXI_FUNCTION(0x4, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0"),		 
		  SUNXI_FUNCTION(0x4, "uart1")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 11),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0"),		 
		  SUNXI_FUNCTION(0x4, "uart1")),	 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x4, "jtag")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x4, "jtag")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x4, "uart0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x4, "jtag")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x4, "uart0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x4, "jtag")),		 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x2, "gps"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 0)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x2, "gps"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 1)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x2, "gps"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 2)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc1"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 3)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc1"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 4)),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(G, 5),
		  PINCTRL_SUN5I_A10S | PINCTRL_SUN5I_GR8,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc1"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 5)),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(G, 6),
		  PINCTRL_SUN5I_A10S | PINCTRL_SUN5I_GR8,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc1"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION(0x5, "uart2"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 6)),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(G, 7),
		  PINCTRL_SUN5I_A10S | PINCTRL_SUN5I_GR8,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc1"),		 
		  SUNXI_FUNCTION(0x5, "uart2"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 7)),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(G, 8),
		  PINCTRL_SUN5I_A10S | PINCTRL_SUN5I_GR8,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc1"),		 
		  SUNXI_FUNCTION(0x5, "uart2"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 8)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 9),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi1"),		 
		  SUNXI_FUNCTION(0x3, "uart3"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 9)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi1"),		 
		  SUNXI_FUNCTION(0x3, "uart3"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 10)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 11),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi1"),		 
		  SUNXI_FUNCTION(0x3, "uart3"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 11)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 12),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi1"),		 
		  SUNXI_FUNCTION(0x3, "uart3"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 12)),		 
	SUNXI_PIN_VARIANT(SUNXI_PINCTRL_PIN(G, 13),
		  PINCTRL_SUN5I_A10S | PINCTRL_SUN5I_GR8,
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi1"),		 
		  SUNXI_FUNCTION(0x3, "pwm"),		 
		  SUNXI_FUNCTION(0x5, "uart2"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 13)),		 
};

static const struct sunxi_pinctrl_desc sun5i_pinctrl_data = {
	.pins = sun5i_pins,
	.npins = ARRAY_SIZE(sun5i_pins),
	.irq_banks = 1,
	.disable_strict_mode = true,
};

static int sun5i_pinctrl_probe(struct platform_device *pdev)
{
	unsigned long variant = (unsigned long)of_device_get_match_data(&pdev->dev);

	return sunxi_pinctrl_init_with_variant(pdev, &sun5i_pinctrl_data,
					       variant);
}

static const struct of_device_id sun5i_pinctrl_match[] = {
	{
		.compatible = "allwinner,sun5i-a10s-pinctrl",
		.data = (void *)PINCTRL_SUN5I_A10S
	},
	{
		.compatible = "allwinner,sun5i-a13-pinctrl",
		.data = (void *)PINCTRL_SUN5I_A13
	},
	{
		.compatible = "nextthing,gr8-pinctrl",
		.data = (void *)PINCTRL_SUN5I_GR8
	},
	{ },
};

static struct platform_driver sun5i_pinctrl_driver = {
	.probe	= sun5i_pinctrl_probe,
	.driver	= {
		.name		= "sun5i-pinctrl",
		.of_match_table	= sun5i_pinctrl_match,
	},
};
builtin_platform_driver(sun5i_pinctrl_driver);
