
 

#include <linux/module.h>
#include <linux/platform_device.h>
#include <linux/of.h>
#include <linux/pinctrl/pinctrl.h>

#include "pinctrl-sunxi.h"

static const struct sunxi_desc_pin d1_pins[] = {
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 0),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "pwm3"),
		SUNXI_FUNCTION(0x3, "ir"),		 
		SUNXI_FUNCTION(0x4, "i2c2"),		 
		SUNXI_FUNCTION(0x5, "spi1"),		 
		SUNXI_FUNCTION(0x6, "uart0"),		 
		SUNXI_FUNCTION(0x7, "uart2"),		 
		SUNXI_FUNCTION(0x8, "spdif"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 0, 0)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 1),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "pwm4"),
		SUNXI_FUNCTION(0x3, "i2s2_dout"),	 
		SUNXI_FUNCTION(0x4, "i2c2"),		 
		SUNXI_FUNCTION(0x5, "i2s2_din"),	 
		SUNXI_FUNCTION(0x6, "uart0"),		 
		SUNXI_FUNCTION(0x7, "uart2"),		 
		SUNXI_FUNCTION(0x8, "ir"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 0, 1)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 2),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "i2s2_dout"),	 
		SUNXI_FUNCTION(0x4, "i2c0"),		 
		SUNXI_FUNCTION(0x5, "i2s2_din"),	 
		SUNXI_FUNCTION(0x6, "lcd0"),		 
		SUNXI_FUNCTION(0x7, "uart4"),		 
		SUNXI_FUNCTION(0x8, "can0"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 0, 2)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 3),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "i2s2_dout"),	 
		SUNXI_FUNCTION(0x4, "i2c0"),		 
		SUNXI_FUNCTION(0x5, "i2s2_din"),	 
		SUNXI_FUNCTION(0x6, "lcd0"),		 
		SUNXI_FUNCTION(0x7, "uart4"),		 
		SUNXI_FUNCTION(0x8, "can0"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 0, 3)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 4),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "i2s2_dout"),	 
		SUNXI_FUNCTION(0x4, "i2c1"),		 
		SUNXI_FUNCTION(0x5, "i2s2_din"),	 
		SUNXI_FUNCTION(0x6, "lcd0"),		 
		SUNXI_FUNCTION(0x7, "uart5"),		 
		SUNXI_FUNCTION(0x8, "can1"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 0, 4)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 5),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "i2s2"),		 
		SUNXI_FUNCTION(0x4, "i2c1"),		 
		SUNXI_FUNCTION(0x5, "pwm0"),
		SUNXI_FUNCTION(0x6, "lcd0"),		 
		SUNXI_FUNCTION(0x7, "uart5"),		 
		SUNXI_FUNCTION(0x8, "can1"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 0, 5)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 6),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "i2s2"),		 
		SUNXI_FUNCTION(0x4, "i2c3"),		 
		SUNXI_FUNCTION(0x5, "pwm1"),
		SUNXI_FUNCTION(0x6, "lcd0"),		 
		SUNXI_FUNCTION(0x7, "uart3"),		 
		SUNXI_FUNCTION(0x8, "bist0"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 0, 6)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 7),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "i2s2"),		 
		SUNXI_FUNCTION(0x4, "i2c3"),		 
		SUNXI_FUNCTION(0x5, "ir"),		 
		SUNXI_FUNCTION(0x6, "lcd0"),		 
		SUNXI_FUNCTION(0x7, "uart3"),		 
		SUNXI_FUNCTION(0x8, "bist1"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 0, 7)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 8),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "dmic"),		 
		SUNXI_FUNCTION(0x3, "pwm5"),
		SUNXI_FUNCTION(0x4, "i2c2"),		 
		SUNXI_FUNCTION(0x5, "spi1"),		 
		SUNXI_FUNCTION(0x6, "uart0"),		 
		SUNXI_FUNCTION(0x7, "uart1"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 0, 8)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 9),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "dmic"),		 
		SUNXI_FUNCTION(0x3, "pwm6"),
		SUNXI_FUNCTION(0x4, "i2c2"),		 
		SUNXI_FUNCTION(0x5, "spi1"),		 
		SUNXI_FUNCTION(0x6, "uart0"),		 
		SUNXI_FUNCTION(0x7, "uart1"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 0, 9)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 10),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "dmic"),		 
		SUNXI_FUNCTION(0x3, "pwm7"),
		SUNXI_FUNCTION(0x4, "i2c0"),		 
		SUNXI_FUNCTION(0x5, "spi1"),		 
		SUNXI_FUNCTION(0x6, "clk"),		 
		SUNXI_FUNCTION(0x7, "uart1"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 0, 10)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 11),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "dmic"),		 
		SUNXI_FUNCTION(0x3, "pwm2"),
		SUNXI_FUNCTION(0x4, "i2c0"),		 
		SUNXI_FUNCTION(0x5, "spi1"),		 
		SUNXI_FUNCTION(0x6, "clk"),		 
		SUNXI_FUNCTION(0x7, "uart1"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 0, 11)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 12),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "dmic"),		 
		SUNXI_FUNCTION(0x3, "pwm0"),
		SUNXI_FUNCTION(0x4, "spdif"),		 
		SUNXI_FUNCTION(0x5, "spi1"),		 
		SUNXI_FUNCTION(0x6, "clk"),		 
		SUNXI_FUNCTION(0x7, "ir"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 0, 12)),
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 0),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "uart2"),		 
		SUNXI_FUNCTION(0x3, "i2c2"),		 
		SUNXI_FUNCTION(0x4, "ledc"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 1, 0)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 1),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "uart2"),		 
		SUNXI_FUNCTION(0x3, "i2c2"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 1, 1)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 2),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "spi0"),		 
		SUNXI_FUNCTION(0x3, "mmc2"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 1, 2)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 3),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "spi0"),		 
		SUNXI_FUNCTION(0x3, "mmc2"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 1, 3)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 4),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "spi0"),		 
		SUNXI_FUNCTION(0x3, "mmc2"),		 
		SUNXI_FUNCTION(0x4, "boot"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 1, 4)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 5),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "spi0"),		 
		SUNXI_FUNCTION(0x3, "mmc2"),		 
		SUNXI_FUNCTION(0x4, "boot"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 1, 5)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 6),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "spi0"),		 
		SUNXI_FUNCTION(0x3, "mmc2"),		 
		SUNXI_FUNCTION(0x4, "uart3"),		 
		SUNXI_FUNCTION(0x5, "i2c3"),		 
		SUNXI_FUNCTION(0x6, "pll"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 1, 6)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 7),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "spi0"),		 
		SUNXI_FUNCTION(0x3, "mmc2"),		 
		SUNXI_FUNCTION(0x4, "uart3"),		 
		SUNXI_FUNCTION(0x5, "i2c3"),		 
		SUNXI_FUNCTION(0x6, "tcon"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 1, 7)),
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 0),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds0"),		 
		SUNXI_FUNCTION(0x4, "dsi"),		 
		SUNXI_FUNCTION(0x5, "i2c0"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 0)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 1),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds0"),		 
		SUNXI_FUNCTION(0x4, "dsi"),		 
		SUNXI_FUNCTION(0x5, "uart2"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 1)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 2),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds0"),		 
		SUNXI_FUNCTION(0x4, "dsi"),		 
		SUNXI_FUNCTION(0x5, "uart2"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 2)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 3),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds0"),		 
		SUNXI_FUNCTION(0x4, "dsi"),		 
		SUNXI_FUNCTION(0x5, "uart2"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 3)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 4),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds0"),		 
		SUNXI_FUNCTION(0x4, "dsi"),		 
		SUNXI_FUNCTION(0x5, "uart2"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 4)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 5),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds0"),		 
		SUNXI_FUNCTION(0x4, "dsi"),		 
		SUNXI_FUNCTION(0x5, "uart5"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 5)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 6),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds0"),		 
		SUNXI_FUNCTION(0x4, "dsi"),		 
		SUNXI_FUNCTION(0x5, "uart5"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 6)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 7),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds0"),		 
		SUNXI_FUNCTION(0x4, "dsi"),		 
		SUNXI_FUNCTION(0x5, "uart4"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 7)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 8),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds0"),		 
		SUNXI_FUNCTION(0x4, "dsi"),		 
		SUNXI_FUNCTION(0x5, "uart4"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 8)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 9),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds0"),		 
		SUNXI_FUNCTION(0x4, "dsi"),		 
		SUNXI_FUNCTION(0x5, "pwm6"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 9)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 10),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds1"),		 
		SUNXI_FUNCTION(0x4, "spi1"),		 
		SUNXI_FUNCTION(0x5, "uart3"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 10)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 11),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds1"),		 
		SUNXI_FUNCTION(0x4, "spi1"),		 
		SUNXI_FUNCTION(0x5, "uart3"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 11)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 12),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds1"),		 
		SUNXI_FUNCTION(0x4, "spi1"),		 
		SUNXI_FUNCTION(0x5, "i2c0"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 12)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 13),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds1"),		 
		SUNXI_FUNCTION(0x4, "spi1"),		 
		SUNXI_FUNCTION(0x5, "uart3"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 13)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 14),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds1"),		 
		SUNXI_FUNCTION(0x4, "spi1"),		 
		SUNXI_FUNCTION(0x5, "uart3"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 14)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 15),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds1"),		 
		SUNXI_FUNCTION(0x4, "spi1"),		 
		SUNXI_FUNCTION(0x5, "ir"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 15)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 16),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds1"),		 
		SUNXI_FUNCTION(0x4, "dmic"),		 
		SUNXI_FUNCTION(0x5, "pwm0"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 16)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 17),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds1"),		 
		SUNXI_FUNCTION(0x4, "dmic"),		 
		SUNXI_FUNCTION(0x5, "pwm1"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 17)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 18),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds1"),		 
		SUNXI_FUNCTION(0x4, "dmic"),		 
		SUNXI_FUNCTION(0x5, "pwm2"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 18)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 19),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "lvds1"),		 
		SUNXI_FUNCTION(0x4, "dmic"),		 
		SUNXI_FUNCTION(0x5, "pwm3"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 19)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 20),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "i2c2"),		 
		SUNXI_FUNCTION(0x4, "dmic"),		 
		SUNXI_FUNCTION(0x5, "pwm4"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 20)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 21),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "lcd0"),		 
		SUNXI_FUNCTION(0x3, "i2c2"),		 
		SUNXI_FUNCTION(0x4, "uart1"),		 
		SUNXI_FUNCTION(0x5, "pwm5"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 21)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 22),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "spdif"),		 
		SUNXI_FUNCTION(0x3, "ir"),		 
		SUNXI_FUNCTION(0x4, "uart1"),		 
		SUNXI_FUNCTION(0x5, "pwm7"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 2, 22)),
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 0),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "ncsi0"),		 
		SUNXI_FUNCTION(0x3, "uart2"),		 
		SUNXI_FUNCTION(0x4, "i2c1"),		 
		SUNXI_FUNCTION(0x5, "lcd0"),		 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 0)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 1),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "ncsi0"),		 
		SUNXI_FUNCTION(0x3, "uart2"),		 
		SUNXI_FUNCTION(0x4, "i2c1"),		 
		SUNXI_FUNCTION(0x5, "lcd0"),		 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 1)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 2),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "ncsi0"),		 
		SUNXI_FUNCTION(0x3, "uart2"),		 
		SUNXI_FUNCTION(0x4, "i2c0"),		 
		SUNXI_FUNCTION(0x5, "clk"),		 
		SUNXI_FUNCTION(0x6, "uart0"),		 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 2)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 3),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "ncsi0"),		 
		SUNXI_FUNCTION(0x3, "uart2"),		 
		SUNXI_FUNCTION(0x4, "i2c0"),		 
		SUNXI_FUNCTION(0x5, "clk"),		 
		SUNXI_FUNCTION(0x6, "uart0"),		 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 3)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 4),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "ncsi0"),		 
		SUNXI_FUNCTION(0x3, "uart4"),		 
		SUNXI_FUNCTION(0x4, "i2c2"),		 
		SUNXI_FUNCTION(0x5, "clk"),		 
		SUNXI_FUNCTION(0x6, "d_jtag"),		 
		SUNXI_FUNCTION(0x7, "r_jtag"),		 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 4)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 5),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "ncsi0"),		 
		SUNXI_FUNCTION(0x3, "uart4"),		 
		SUNXI_FUNCTION(0x4, "i2c2"),		 
		SUNXI_FUNCTION(0x5, "ledc"),
		SUNXI_FUNCTION(0x6, "d_jtag"),		 
		SUNXI_FUNCTION(0x7, "r_jtag"),		 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 5)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 6),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "ncsi0"),		 
		SUNXI_FUNCTION(0x3, "uart5"),		 
		SUNXI_FUNCTION(0x4, "i2c3"),		 
		SUNXI_FUNCTION(0x5, "spdif"),		 
		SUNXI_FUNCTION(0x6, "d_jtag"),		 
		SUNXI_FUNCTION(0x7, "r_jtag"),		 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 6)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 7),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "ncsi0"),		 
		SUNXI_FUNCTION(0x3, "uart5"),		 
		SUNXI_FUNCTION(0x4, "i2c3"),		 
		SUNXI_FUNCTION(0x5, "spdif"),		 
		SUNXI_FUNCTION(0x6, "d_jtag"),		 
		SUNXI_FUNCTION(0x7, "r_jtag"),		 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 7)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 8),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "ncsi0"),		 
		SUNXI_FUNCTION(0x3, "uart1"),		 
		SUNXI_FUNCTION(0x4, "pwm2"),
		SUNXI_FUNCTION(0x5, "uart3"),		 
		SUNXI_FUNCTION(0x6, "jtag"),		 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 8)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 9),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "ncsi0"),		 
		SUNXI_FUNCTION(0x3, "uart1"),		 
		SUNXI_FUNCTION(0x4, "pwm3"),
		SUNXI_FUNCTION(0x5, "uart3"),		 
		SUNXI_FUNCTION(0x6, "jtag"),		 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 9)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 10),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "ncsi0"),		 
		SUNXI_FUNCTION(0x3, "uart1"),		 
		SUNXI_FUNCTION(0x4, "pwm4"),
		SUNXI_FUNCTION(0x5, "ir"),		 
		SUNXI_FUNCTION(0x6, "jtag"),		 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 10)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 11),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "ncsi0"),		 
		SUNXI_FUNCTION(0x3, "uart1"),		 
		SUNXI_FUNCTION(0x4, "i2s0_dout"),	 
		SUNXI_FUNCTION(0x5, "i2s0_din"),	 
		SUNXI_FUNCTION(0x6, "jtag"),		 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 11)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 12),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "i2c2"),		 
		SUNXI_FUNCTION(0x3, "ncsi0"),		 
		SUNXI_FUNCTION(0x4, "i2s0_dout"),	 
		SUNXI_FUNCTION(0x5, "i2s0_din"),	 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 12)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 13),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "i2c2"),		 
		SUNXI_FUNCTION(0x3, "pwm5"),
		SUNXI_FUNCTION(0x4, "i2s0_dout"),	 
		SUNXI_FUNCTION(0x5, "i2s0_din"),	 
		SUNXI_FUNCTION(0x6, "dmic"),		 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 13)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 14),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "i2c1"),		 
		SUNXI_FUNCTION(0x3, "d_jtag"),		 
		SUNXI_FUNCTION(0x4, "i2s0_dout"),	 
		SUNXI_FUNCTION(0x5, "i2s0_din"),	 
		SUNXI_FUNCTION(0x6, "dmic"),		 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 14)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 15),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "i2c1"),		 
		SUNXI_FUNCTION(0x3, "d_jtag"),		 
		SUNXI_FUNCTION(0x4, "pwm6"),
		SUNXI_FUNCTION(0x5, "i2s0"),		 
		SUNXI_FUNCTION(0x6, "dmic"),		 
		SUNXI_FUNCTION(0x8, "emac"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 15)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 16),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "i2c3"),		 
		SUNXI_FUNCTION(0x3, "d_jtag"),		 
		SUNXI_FUNCTION(0x4, "pwm7"),
		SUNXI_FUNCTION(0x5, "i2s0"),		 
		SUNXI_FUNCTION(0x6, "dmic"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 16)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 17),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "i2c3"),		 
		SUNXI_FUNCTION(0x3, "d_jtag"),		 
		SUNXI_FUNCTION(0x4, "ir"),		 
		SUNXI_FUNCTION(0x5, "i2s0"),		 
		SUNXI_FUNCTION(0x6, "dmic"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 3, 17)),
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 0),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "mmc0"),		 
		SUNXI_FUNCTION(0x3, "jtag"),		 
		SUNXI_FUNCTION(0x4, "r_jtag"),		 
		SUNXI_FUNCTION(0x5, "i2s2_dout"),	 
		SUNXI_FUNCTION(0x6, "i2s2_din"),	 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 4, 0)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 1),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "mmc0"),		 
		SUNXI_FUNCTION(0x3, "jtag"),		 
		SUNXI_FUNCTION(0x4, "r_jtag"),		 
		SUNXI_FUNCTION(0x5, "i2s2_dout"),	 
		SUNXI_FUNCTION(0x6, "i2s2_din"),	 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 4, 1)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 2),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "mmc0"),		 
		SUNXI_FUNCTION(0x3, "uart0"),		 
		SUNXI_FUNCTION(0x4, "i2c0"),		 
		SUNXI_FUNCTION(0x5, "ledc"),
		SUNXI_FUNCTION(0x6, "spdif"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 4, 2)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 3),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "mmc0"),		 
		SUNXI_FUNCTION(0x3, "jtag"),		 
		SUNXI_FUNCTION(0x4, "r_jtag"),		 
		SUNXI_FUNCTION(0x5, "i2s2"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 4, 3)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 4),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "mmc0"),		 
		SUNXI_FUNCTION(0x3, "uart0"),		 
		SUNXI_FUNCTION(0x4, "i2c0"),		 
		SUNXI_FUNCTION(0x5, "pwm6"),
		SUNXI_FUNCTION(0x6, "ir"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 4, 4)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 5),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "mmc0"),		 
		SUNXI_FUNCTION(0x3, "jtag"),		 
		SUNXI_FUNCTION(0x4, "r_jtag"),		 
		SUNXI_FUNCTION(0x5, "i2s2"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 4, 5)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 6),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x3, "spdif"),		 
		SUNXI_FUNCTION(0x4, "ir"),		 
		SUNXI_FUNCTION(0x5, "i2s2"),		 
		SUNXI_FUNCTION(0x6, "pwm5"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 4, 6)),
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 0),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "mmc1"),		 
		SUNXI_FUNCTION(0x3, "uart3"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "pwm7"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 0)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 1),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "mmc1"),		 
		SUNXI_FUNCTION(0x3, "uart3"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "pwm6"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 1)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 2),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "mmc1"),		 
		SUNXI_FUNCTION(0x3, "uart3"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "uart4"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 2)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 3),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "mmc1"),		 
		SUNXI_FUNCTION(0x3, "uart3"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "uart4"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 3)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 4),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "mmc1"),		 
		SUNXI_FUNCTION(0x3, "uart5"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "pwm5"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 4)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 5),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "mmc1"),		 
		SUNXI_FUNCTION(0x3, "uart5"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "pwm4"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 5)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 6),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "uart1"),		 
		SUNXI_FUNCTION(0x3, "i2c2"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "pwm1"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 6)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 7),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "uart1"),		 
		SUNXI_FUNCTION(0x3, "i2c2"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "spdif"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 7)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 8),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "uart1"),		 
		SUNXI_FUNCTION(0x3, "i2c1"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "uart3"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 8)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 9),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "uart1"),		 
		SUNXI_FUNCTION(0x3, "i2c1"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "uart3"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 9)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 10),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "pwm3"),
		SUNXI_FUNCTION(0x3, "i2c3"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "clk"),		 
		SUNXI_FUNCTION(0x6, "ir"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 10)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 11),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "i2s1"),		 
		SUNXI_FUNCTION(0x3, "i2c3"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "clk"),		 
		SUNXI_FUNCTION(0x6, "tcon"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 11)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 12),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "i2s1"),		 
		SUNXI_FUNCTION(0x3, "i2c0"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "clk"),		 
		SUNXI_FUNCTION(0x6, "pwm0"),
		SUNXI_FUNCTION(0x7, "uart1"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 12)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 13),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "i2s1"),		 
		SUNXI_FUNCTION(0x3, "i2c0"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "pwm2"),
		SUNXI_FUNCTION(0x6, "ledc"),
		SUNXI_FUNCTION(0x7, "uart1"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 13)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 14),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "i2s1_din"),	 
		SUNXI_FUNCTION(0x3, "i2c2"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "i2s1_dout"),	 
		SUNXI_FUNCTION(0x6, "spi0"),		 
		SUNXI_FUNCTION(0x7, "uart1"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 14)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 15),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "i2s1_dout"),	 
		SUNXI_FUNCTION(0x3, "i2c2"),		 
		SUNXI_FUNCTION(0x4, "emac"),		 
		SUNXI_FUNCTION(0x5, "i2s1_din"),	 
		SUNXI_FUNCTION(0x6, "spi0"),		 
		SUNXI_FUNCTION(0x7, "uart1"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 15)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 16),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "ir"),		 
		SUNXI_FUNCTION(0x3, "tcon"),		 
		SUNXI_FUNCTION(0x4, "pwm5"),
		SUNXI_FUNCTION(0x5, "clk"),		 
		SUNXI_FUNCTION(0x6, "spdif"),		 
		SUNXI_FUNCTION(0x7, "ledc"),
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 16)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 17),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "uart2"),		 
		SUNXI_FUNCTION(0x3, "i2c3"),		 
		SUNXI_FUNCTION(0x4, "pwm7"),
		SUNXI_FUNCTION(0x5, "clk"),		 
		SUNXI_FUNCTION(0x6, "ir"),		 
		SUNXI_FUNCTION(0x7, "uart0"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 17)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 18),
		SUNXI_FUNCTION(0x0, "gpio_in"),
		SUNXI_FUNCTION(0x1, "gpio_out"),
		SUNXI_FUNCTION(0x2, "uart2"),		 
		SUNXI_FUNCTION(0x3, "i2c3"),		 
		SUNXI_FUNCTION(0x4, "pwm6"),
		SUNXI_FUNCTION(0x5, "clk"),		 
		SUNXI_FUNCTION(0x6, "spdif"),		 
		SUNXI_FUNCTION(0x7, "uart0"),		 
		SUNXI_FUNCTION_IRQ_BANK(0xe, 5, 18)),
};

static const unsigned int d1_irq_bank_map[] = { 1, 2, 3, 4, 5, 6 };

static const struct sunxi_pinctrl_desc d1_pinctrl_data = {
	.pins			= d1_pins,
	.npins			= ARRAY_SIZE(d1_pins),
	.irq_banks		= ARRAY_SIZE(d1_irq_bank_map),
	.irq_bank_map		= d1_irq_bank_map,
	.io_bias_cfg_variant	= BIAS_VOLTAGE_PIO_POW_MODE_CTL,
};

static int d1_pinctrl_probe(struct platform_device *pdev)
{
	unsigned long variant = (unsigned long)of_device_get_match_data(&pdev->dev);

	return sunxi_pinctrl_init_with_variant(pdev, &d1_pinctrl_data, variant);
}

static const struct of_device_id d1_pinctrl_match[] = {
	{
		.compatible = "allwinner,sun20i-d1-pinctrl",
		.data = (void *)PINCTRL_SUN20I_D1
	},
	{}
};

static struct platform_driver d1_pinctrl_driver = {
	.probe	= d1_pinctrl_probe,
	.driver	= {
		.name		= "sun20i-d1-pinctrl",
		.of_match_table	= d1_pinctrl_match,
	},
};
builtin_platform_driver(d1_pinctrl_driver);
