{
  "module_name": "Makefile",
  "hash_id": "609ad09f430f27dc88ae075dce07639d5d51d4ecd8b1f3c91eb734cc147b5f07",
  "original_prompt": "Ingested from linux-6.6.14/drivers/i3c/master/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_CDNS_I3C_MASTER)\t\t+= i3c-master-cdns.o\nobj-$(CONFIG_DW_I3C_MASTER)\t\t+= dw-i3c-master.o\nobj-$(CONFIG_AST2600_I3C_MASTER)\t+= ast2600-i3c-master.o\nobj-$(CONFIG_SVC_I3C_MASTER)\t\t+= svc-i3c-master.o\nobj-$(CONFIG_MIPI_I3C_HCI)\t\t+= mipi-i3c-hci/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}