{
  "module_name": "Makefile",
  "hash_id": "c9d5d26ade8a9e50adbb5b90803318aaca4a907df11a8a7c7dba0dcb0e95f8ad",
  "original_prompt": "Ingested from linux-6.6.14/drivers/xen/xenfs/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_XENFS) += xenfs.o\n\nxenfs-y\t\t\t  = super.o\nxenfs-$(CONFIG_XEN_DOM0) += xenstored.o\nxenfs-$(CONFIG_XEN_SYMS) += xensyms.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}