{
  "module_name": "Makefile",
  "hash_id": "57d67f681912662d98896a01587a0eadc43c8d13df168bd4785967cb083f16c7",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/intel/fm10k/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Copyright(c) 2013 - 2018 Intel Corporation.\n\n#\n# Makefile for the Intel(R) Ethernet Switch Host Interface Driver\n#\n\nobj-$(CONFIG_FM10K) += fm10k.o\n\nfm10k-y := fm10k_main.o \\\n\t   fm10k_common.o \\\n\t   fm10k_pci.o \\\n\t   fm10k_netdev.o \\\n\t   fm10k_ethtool.o \\\n\t   fm10k_pf.o \\\n\t   fm10k_vf.o \\\n\t   fm10k_mbx.o \\\n\t   fm10k_iov.o \\\n\t   fm10k_tlv.o\n\nfm10k-$(CONFIG_DEBUG_FS) += fm10k_debugfs.o\nfm10k-$(CONFIG_DCB) += fm10k_dcbnl.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}