{
  "module_name": "Makefile",
  "hash_id": "fd04746421de0539591fbd0c83f19a4b03d2eebffc7279faa45ad3a057844753",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/watchdog/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nTEST_GEN_PROGS := watchdog-test\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}