{
  "module_name": "Makefile",
  "hash_id": "affd60fda88c2cee71c97f23d3f007a8feb08a8f70981aec1c88d94a20071f4e",
  "original_prompt": "Ingested from linux-6.6.14/fs/jfs/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the Linux JFS filesystem routines.\n#\n\nobj-$(CONFIG_JFS_FS) += jfs.o\n\njfs-y    := super.o file.o inode.o namei.o jfs_mount.o jfs_umount.o \\\n\t    jfs_xtree.o jfs_imap.o jfs_debug.o jfs_dmap.o \\\n\t    jfs_unicode.o jfs_dtree.o jfs_inode.o jfs_discard.o \\\n\t    jfs_extent.o symlink.o jfs_metapage.o \\\n\t    jfs_logmgr.o jfs_txnmgr.o \\\n\t    resize.o xattr.o ioctl.o\n\njfs-$(CONFIG_JFS_POSIX_ACL) += acl.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}