{
  "module_name": "Makefile",
  "hash_id": "5764ea22e71cdb246d7a03ef7c1ab4975a317515ffd20720fcc0fc4bef4dfadb",
  "original_prompt": "Ingested from linux-6.6.14/fs/fat/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the Linux fat filesystem support.\n#\n\nobj-$(CONFIG_FAT_FS) += fat.o\nobj-$(CONFIG_VFAT_FS) += vfat.o\nobj-$(CONFIG_MSDOS_FS) += msdos.o\n\nfat-y := cache.o dir.o fatent.o file.o inode.o misc.o nfs.o\nvfat-y := namei_vfat.o\nmsdos-y := namei_msdos.o\n\nobj-$(CONFIG_FAT_KUNIT_TEST) += fat_test.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}