





































#ifndef __STDCMD_H__
#define __STDCMD_H__




#define CMD_GO_IDLE_STATE    SDHOST_CMD_0
#define CMD_SEND_IF_COND     SDHOST_CMD_8|SDHOST_RESP_LEN_48
#define CMD_SEND_CSD         SDHOST_CMD_9|SDHOST_RESP_LEN_136
#define CMD_APP_CMD          SDHOST_CMD_55|SDHOST_RESP_LEN_48
#define CMD_SD_SEND_OP_COND  SDHOST_CMD_41|SDHOST_RESP_LEN_48
#define CMD_SEND_OP_COND     SDHOST_CMD_1|SDHOST_RESP_LEN_48
#define CMD_READ_SINGLE_BLK  SDHOST_CMD_17|SDHOST_RD_CMD|SDHOST_RESP_LEN_48
#define CMD_READ_MULTI_BLK   SDHOST_CMD_18|SDHOST_RD_CMD|SDHOST_RESP_LEN_48|SDHOST_MULTI_BLK
#define CMD_WRITE_SINGLE_BLK SDHOST_CMD_24|SDHOST_WR_CMD|SDHOST_RESP_LEN_48
#define CMD_WRITE_MULTI_BLK  SDHOST_CMD_25|SDHOST_WR_CMD|SDHOST_RESP_LEN_48|SDHOST_MULTI_BLK
#define CMD_SELECT_CARD      SDHOST_CMD_7|SDHOST_RESP_LEN_48B
#define CMD_DESELECT_CARD    SDHOST_CMD_7
#define CMD_STOP_TRANS       SDHOST_CMD_12|SDHOST_RESP_LEN_48B
#define CMD_SET_BLK_CNT      SDHOST_CMD_23|SDHOST_RESP_LEN_48
#define CMD_ALL_SEND_CID     SDHOST_CMD_2|SDHOST_RESP_LEN_136
#define CMD_SEND_REL_ADDR    SDHOST_CMD_3|SDHOST_RESP_LEN_48

#endif 
