{
  "module_name": "Kbuild",
  "hash_id": "2ae6d893d1af18488c8cf90ada35c01cec4ae42624bc8bee07d3098dfaedff90",
  "original_prompt": "Ingested from linux-6.6.14/arch/x86/include/asm/Kbuild",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\n\ngenerated-y += orc_hash.h\ngenerated-y += syscalls_32.h\ngenerated-y += syscalls_64.h\ngenerated-y += syscalls_x32.h\ngenerated-y += unistd_32_ia32.h\ngenerated-y += unistd_64_x32.h\ngenerated-y += xen-hypercalls.h\n\ngeneric-y += early_ioremap.h\ngeneric-y += export.h\ngeneric-y += mcs_spinlock.h\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}