{
  "module_name": "Makefile",
  "hash_id": "53908f7eadc1bed50f00093183ebb8cebd840e299d79c0ba0aa0707588ac9951",
  "original_prompt": "Ingested from linux-6.6.14/drivers/video/fbdev/mmp/hw/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_MMP_DISP_CONTROLLER)  += mmp_ctrl.o\nobj-$(CONFIG_MMP_DISP_SPI)\t   += mmp_spi.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}