{
  "module_name": "Makefile",
  "hash_id": "42149ba456ef1a99f30aafea42ed8d660a8aa9e6ea7569088c879897af833a04",
  "original_prompt": "Ingested from linux-6.6.14/drivers/scsi/be2iscsi/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile to build the iSCSI driver for Emulex OneConnect.\n#\n#\n\nobj-$(CONFIG_BE2ISCSI) += be2iscsi.o\n\nbe2iscsi-y := be_iscsi.o be_main.o be_mgmt.o be_cmds.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}