{
  "module_name": "Makefile",
  "hash_id": "4afbc4eef16abd8a522bb946d841bd389ba7415ddc54b6ded71d237d28534e64",
  "original_prompt": "Ingested from linux-6.6.14/tools/usb/ffs-aio-example/simple/host_app/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nCC = gcc\nLIBUSB_CFLAGS = $(shell pkg-config --cflags libusb-1.0)\nLIBUSB_LIBS = $(shell pkg-config --libs libusb-1.0)\nWARNINGS = -Wall -Wextra\nCFLAGS = $(LIBUSB_CFLAGS) $(WARNINGS)\nLDFLAGS = $(LIBUSB_LIBS)\n\nall: test\n%: %.c\n\t$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)\n\nclean:\n\t$(RM) test\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}