{
  "module_name": "Makefile",
  "hash_id": "ada5668e3e4350c94d590b560a7b92dfebddfe427640f3236e6f5730c50a3e5b",
  "original_prompt": "Ingested from linux-6.6.14/drivers/dma/fsl-dpaa2-qdma/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for the NXP DPAA2 qDMA controllers\nobj-$(CONFIG_FSL_DPAA2_QDMA) += dpaa2-qdma.o dpdmai.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}