{
  "module_name": "Makefile",
  "hash_id": "71f0068c1ee777a9399e7e6ae2bea2dcbb7857d9c7be48f54fd482b7409c22c9",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/quantenna/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Copyright (c) 2015-2016 Quantenna Communications, Inc.\n# All rights reserved.\n#\n\nobj-$(CONFIG_QTNFMAC)\t+= qtnfmac/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}