{
  "module_name": "Makefile",
  "hash_id": "73bb165d19429393527491b833a7948b52a084c03f03a8bf12f2be42475021fb",
  "original_prompt": "Ingested from linux-6.6.14/drivers/crypto/intel/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\nobj-y += keembay/\nobj-y += ixp4xx/\nobj-$(CONFIG_CRYPTO_DEV_QAT) += qat/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}