{
  "module_name": "Makefile",
  "hash_id": "31cdd25be363d16c142764cfebb0c5c2bb6c27a4d2afc3e6e9aa9c8ca2034119",
  "original_prompt": "Ingested from openssh-9.6p1/regress/unittests/misc/Makefile",
  "human_readable_source": "#\t$OpenBSD: Makefile,v 1.9 2023/01/06 02:59:50 djm Exp $\n\nPROG=test_misc\nSRCS=tests.c\nSRCS+=\ttest_convtime.c\nSRCS+=\ttest_expand.c\nSRCS+=\ttest_parse.c\nSRCS+=\ttest_argv.c\nSRCS+=\ttest_strdelim.c\nSRCS+=\ttest_hpdelim.c\nSRCS+=\ttest_ptimeout.c\n\n# From usr.bin/ssh/Makefile.inc\nSRCS+=\tsshbuf.c\nSRCS+=\tsshbuf-getput-basic.c\nSRCS+=\tsshbuf-misc.c\nSRCS+=\tssherr.c\nSRCS+=\tlog.c\nSRCS+=\txmalloc.c\nSRCS+=\tmisc.c\nSRCS+=\tmatch.c\nSRCS+=\taddr.c\nSRCS+=\taddrmatch.c\n\n# From usr.bin/ssh/sshd/Makefile\nSRCS+=\tatomicio.c cleanup.c fatal.c\n\nREGRESS_TARGETS=run-regress-${PROG}\n\nrun-regress-${PROG}: ${PROG}\n\tenv ${TEST_ENV} ./${PROG}\n\n.include <bsd.regress.mk>\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}