{
  "module_name": "Makefile",
  "hash_id": "0b50d165931de3c1a2e8e010919b24aaa420e5f28d8c0703c35ed9a93173dc9a",
  "original_prompt": "Ingested from linux-6.6.14/drivers/misc/pvpanic/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0+\n#\n# Pvpanic Makefile\n#\n# Copyright (C) 2021 Oracle.\n#\nobj-$(CONFIG_PVPANIC_MMIO)\t+= pvpanic.o pvpanic-mmio.o\nobj-$(CONFIG_PVPANIC_PCI)\t+= pvpanic.o pvpanic-pci.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}