{
  "module_name": "Makefile",
  "hash_id": "f2ba1467a3f77f39a31dc60bcd7865029ba7982152ae102141ddf4eac341e397",
  "original_prompt": "Ingested from linux-6.6.14/drivers/opp/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nccflags-$(CONFIG_DEBUG_DRIVER)\t:= -DDEBUG\nobj-y\t\t\t\t+= core.o cpu.o\nobj-$(CONFIG_OF)\t\t+= of.o\nobj-$(CONFIG_DEBUG_FS)\t\t+= debugfs.o\nobj-$(CONFIG_ARM_TI_CPUFREQ)\t+= ti-opp-supply.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}