{
  "module_name": "Makefile",
  "hash_id": "4af98d17f922bade1e40bf440b3c03c5465bde4cb0a56363b92f2085ce9b5c2a",
  "original_prompt": "Ingested from linux-6.6.14/sound/virtio/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0+\n\nobj-$(CONFIG_SND_VIRTIO) += virtio_snd.o\n\nvirtio_snd-objs := \\\n\tvirtio_card.o \\\n\tvirtio_chmap.o \\\n\tvirtio_ctl_msg.o \\\n\tvirtio_jack.o \\\n\tvirtio_pcm.o \\\n\tvirtio_pcm_msg.o \\\n\tvirtio_pcm_ops.o\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}