{
  "module_name": "Makefile",
  "hash_id": "8540b7a7f93d7f00709590e4f3211a7bcb27f6598a26e036eb628b7ce0735e0a",
  "original_prompt": "Ingested from linux-6.6.14/sound/drivers/opl3/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for ALSA\n# Copyright (c) 2001 by Jaroslav Kysela <perex@perex.cz>\n#\n\nsnd-opl3-lib-objs := opl3_lib.o opl3_synth.o\nsnd-opl3-synth-y := opl3_seq.o opl3_midi.o opl3_drums.o\nifneq ($(CONFIG_SND_SEQUENCER_OSS),)\nsnd-opl3-synth-y += opl3_oss.o\nendif\n\nobj-$(CONFIG_SND_OPL3_LIB) += snd-opl3-lib.o\nobj-$(CONFIG_SND_OPL4_LIB) += snd-opl3-lib.o\nobj-$(CONFIG_SND_OPL3_LIB_SEQ) += snd-opl3-synth.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}