{
  "module_name": "Makefile",
  "hash_id": "c1793545aca148edd9084bb0f4acd23f335f02a0dc3d28cc130963d286b50ca1",
  "original_prompt": "Ingested from openssh-9.6p1/regress/unittests/match/Makefile",
  "human_readable_source": "#\t$OpenBSD: Makefile,v 1.5 2021/01/09 12:24:31 dtucker Exp $\n\nPROG=test_match\nSRCS=tests.c\n\n# From usr.bin/ssh\nSRCS+=sshbuf-getput-basic.c sshbuf-getput-crypto.c sshbuf-misc.c sshbuf.c\nSRCS+=match.c misc.c log.c uidswap.c fatal.c ssherr.c addrmatch.c xmalloc.c\nSRCS+=cleanup.c atomicio.c addr.c\n\nREGRESS_TARGETS=run-regress-${PROG}\n\nrun-regress-${PROG}: ${PROG}\n\tenv ${TEST_ENV} ./${PROG}\n\n.include <bsd.regress.mk>\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}