{
  "module_name": "Makefile",
  "hash_id": "7a010b4a72cc7a39a9c9da640d465a2db04521888be35787d69fb59ecf3b5fbf",
  "original_prompt": "Ingested from linux-6.6.14/drivers/soc/fsl/qbman/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_FSL_DPAA)                          += bman_ccsr.o qman_ccsr.o \\\n\t\t\t\t\t\t   bman_portal.o qman_portal.o \\\n\t\t\t\t\t\t   bman.o qman.o dpaa_sys.o\n\nobj-$(CONFIG_FSL_BMAN_TEST)                     += bman-test.o\nbman-test-y                                      = bman_test.o\nbman-test-$(CONFIG_FSL_BMAN_TEST_API)           += bman_test_api.o\n\nobj-$(CONFIG_FSL_QMAN_TEST)\t\t\t+= qman-test.o\nqman-test-y\t\t\t\t\t = qman_test.o\nqman-test-$(CONFIG_FSL_QMAN_TEST_API)\t\t+= qman_test_api.o\nqman-test-$(CONFIG_FSL_QMAN_TEST_STASH)\t\t+= qman_test_stash.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}