{
  "module_name": "Makefile",
  "hash_id": "a9f0772f201174233a9025be2d0a33f00a44d84e187e54a4a2ab2cd2fa6ddc7f",
  "original_prompt": "Ingested from linux-6.6.14/drivers/iio/position/Makefile",
  "human_readable_source": "#\n# Makefile for IIO linear and angular position sensors\n#\n\n# When adding new entries keep the list in alphabetical order\n\nobj-$(CONFIG_HID_SENSOR_CUSTOM_INTEL_HINGE) += hid-sensor-custom-intel-hinge.o\nobj-$(CONFIG_IQS624_POS)\t+= iqs624-pos.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}