{
  "module_name": "Makefile",
  "hash_id": "33251f8512904f478cc3c96dbafbf1a8cb138b0b5e016ea1243e37176f2319a6",
  "original_prompt": "Ingested from linux-6.6.14/drivers/staging/media/tegra-video/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\ntegra-video-objs := \\\n\t\tvideo.o \\\n\t\tvi.o \\\n\t\tvip.o \\\n\t\tcsi.o\n\ntegra-video-$(CONFIG_ARCH_TEGRA_2x_SOC)  += tegra20.o\ntegra-video-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210.o\nobj-$(CONFIG_VIDEO_TEGRA) += tegra-video.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}