{
  "module_name": "Makefile",
  "hash_id": "cac4cdb25b538c05c9b80d6e0ca7a1487e2d0e3a9c823de4d78db8a14002527c",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/cavium/liquidio/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Cavium Liquidio ethernet device driver\n#\n\nobj-$(CONFIG_LIQUIDIO_CORE) += liquidio-core.o\nliquidio-core-y := \\\n\t\tlio_ethtool.o\t\t\\\n\t\tlio_core.o\t\t\\\n\t\trequest_manager.o\t\\\n\t\tresponse_manager.o\t\\\n\t\tocteon_device.o\t\t\\\n\t\tcn66xx_device.o\t\t\\\n\t\tcn68xx_device.o\t\t\\\n\t\tcn23xx_pf_device.o\t\\\n\t\tcn23xx_vf_device.o\t\\\n\t\tocteon_mailbox.o\t\\\n\t\tocteon_mem_ops.o\t\\\n\t\tocteon_droq.o\t\t\\\n\t\tocteon_nic.o\n\nobj-$(CONFIG_LIQUIDIO) += liquidio.o\nliquidio-y := lio_main.o octeon_console.o lio_vf_rep.o\n\nobj-$(CONFIG_LIQUIDIO_VF) += liquidio_vf.o\nliquidio_vf-y := lio_vf_main.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}