{
  "module_name": "Kbuild",
  "hash_id": "7d4e33f79a448327c30af802b3a66930218cabb5f3c9dcd2e5f72a2347fd6656",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/nouveau/dispnv04/Kbuild",
  "human_readable_source": "# SPDX-License-Identifier: MIT\nnouveau-y += dispnv04/arb.o\nnouveau-y += dispnv04/crtc.o\nnouveau-y += dispnv04/cursor.o\nnouveau-y += dispnv04/dac.o\nnouveau-y += dispnv04/dfp.o\nnouveau-y += dispnv04/disp.o\nnouveau-y += dispnv04/hw.o\nnouveau-y += dispnv04/overlay.o\nnouveau-y += dispnv04/tvmodesnv17.o\nnouveau-y += dispnv04/tvnv04.o\nnouveau-y += dispnv04/tvnv17.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}