{
  "module_name": "Makefile",
  "hash_id": "56c783b0cf64a6774235e8a71f243eb6a203fef08db2c53ca154867d83053f82",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/platform/samsung/exynos4-is/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\ns5p-fimc-objs := fimc-core.o fimc-reg.o fimc-m2m.o fimc-capture.o media-dev.o\nexynos-fimc-lite-objs += fimc-lite-reg.o fimc-lite.o\ns5p-csis-objs := mipi-csis.o\nexynos4-is-common-objs := common.o\n\nexynos-fimc-is-objs := fimc-is.o fimc-isp.o fimc-is-sensor.o fimc-is-regs.o\nexynos-fimc-is-objs += fimc-is-param.o fimc-is-errno.o fimc-is-i2c.o\n\nifeq ($(CONFIG_VIDEO_EXYNOS4_ISP_DMA_CAPTURE),y)\nexynos-fimc-is-objs += fimc-isp-video.o\nendif\n\nobj-$(CONFIG_VIDEO_S5P_MIPI_CSIS)\t+= s5p-csis.o\nobj-$(CONFIG_VIDEO_EXYNOS_FIMC_LITE)\t+= exynos-fimc-lite.o\nobj-$(CONFIG_VIDEO_EXYNOS4_FIMC_IS)\t+= exynos-fimc-is.o\nobj-$(CONFIG_VIDEO_S5P_FIMC)\t\t+= s5p-fimc.o\nobj-$(CONFIG_VIDEO_EXYNOS4_IS_COMMON)\t+= exynos4-is-common.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}