{
  "module_name": "Makefile",
  "hash_id": "8955f8435d407eb31170e8c25bf78da6ffacc83603532cd8a3186940de2834a4",
  "original_prompt": "Ingested from linux-6.6.14/fs/affs/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the Linux affs filesystem routines.\n#\n\n#ccflags-y := -DDEBUG=1\n\nobj-$(CONFIG_AFFS_FS) += affs.o\n\naffs-objs := super.o namei.o inode.o file.o dir.o amigaffs.o bitmap.o symlink.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}