{
  "module_name": "Makefile",
  "hash_id": "eca4bb2b7ccf6827902b9cf98805ecebd48312d0df35fe4417258f8b43027855",
  "original_prompt": "Ingested from linux-6.6.14/drivers/dma/dw-axi-dmac/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_DW_AXI_DMAC) += dw-axi-dmac-platform.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}