{
  "module_name": "Makefile",
  "hash_id": "e59398cc1db1a0324ea7777562926218bd8e0db97756fedc5531a9a1c4b08c52",
  "original_prompt": "Ingested from linux-6.6.14/drivers/usb/image/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for USB Image drivers\n#\n\nobj-$(CONFIG_USB_MDC800)\t+= mdc800.o\nobj-$(CONFIG_USB_MICROTEK)\t+= microtek.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}