{
  "module_name": "Makefile",
  "hash_id": "1cc420b3ebe131af68b9e16918af2a4496faceeaa22d3be31732706050ecf2b7",
  "original_prompt": "Ingested from linux-6.6.14/samples/fprobe/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n\nobj-$(CONFIG_SAMPLE_FPROBE) += fprobe_example.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}