{
  "module_name": "Makefile",
  "hash_id": "06fb153f7e9672dffb89e7227ac3354293a4b0792f1566717fcbe98436873bac",
  "original_prompt": "Ingested from linux-6.6.14/arch/x86/kernel/cpu/sgx/Makefile",
  "human_readable_source": "obj-y += \\\n\tdriver.o \\\n\tencl.o \\\n\tioctl.o \\\n\tmain.o\nobj-$(CONFIG_X86_SGX_KVM)\t+= virt.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}