{
  "module_name": "Makefile",
  "hash_id": "c819b411c2d2b49eed9c6a3f88a43b4b9fe3bf44bb49ea1b9b79374a09e4312e",
  "original_prompt": "Ingested from linux-6.6.14/sound/usb/usx2y/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nsnd-usb-usx2y-objs := usbusx2y.o usX2Yhwdep.o usx2yhwdeppcm.o\nsnd-usb-us122l-objs := us122l.o\n\nobj-$(CONFIG_SND_USB_USX2Y) += snd-usb-usx2y.o\nobj-$(CONFIG_SND_USB_US122L) += snd-usb-us122l.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}