{
  "module_name": "Makefile",
  "hash_id": "c3a24a5796e059eebd7d0a3c8e1bbd7b11f47cf289cea82ade73c33ce9e08fad",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/pl111/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\npl111_drm-y +=\tpl111_display.o \\\n\t\tpl111_versatile.o \\\n\t\tpl111_drv.o\n\npl111_drm-$(CONFIG_ARCH_NOMADIK) += pl111_nomadik.o\npl111_drm-$(CONFIG_DEBUG_FS) += pl111_debugfs.o\n\nobj-$(CONFIG_DRM_PL111) += pl111_drm.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}