{
  "module_name": "Makefile",
  "hash_id": "cf1fa84d4967324f1c81fe728d7a0504dbefbc72807047026861326a03a9b9b2",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/ir/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nTEST_PROGS := ir_loopback.sh\nTEST_GEN_PROGS_EXTENDED := ir_loopback\nAPIDIR := ../../../include/uapi\nCFLAGS += -Wall -O2 -I$(APIDIR)\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}