#include <sys/cdefs.h>
__FBSDID("$FreeBSD$");
#include <sys/types.h>
#include <sys/param.h>
#include <sys/conf.h>
#include <sys/kernel.h>
#include <sys/lock.h>
#include <sys/malloc.h>
#include <sys/mutex.h>
#include <sys/errno.h>
#include <sys/cmn_err.h>
#include <sys/zfs_ioctl_compat.h>
#ifdef ZFS_LEGACY_SUPPORT
enum zfs_ioc_legacy {
	ZFS_IOC_LEGACY_NONE =	-1,
	ZFS_IOC_LEGACY_FIRST =	0,
	ZFS_LEGACY_IOC = ZFS_IOC_LEGACY_FIRST,
	ZFS_IOC_LEGACY_POOL_CREATE = ZFS_IOC_LEGACY_FIRST,
	ZFS_IOC_LEGACY_POOL_DESTROY,
	ZFS_IOC_LEGACY_POOL_IMPORT,
	ZFS_IOC_LEGACY_POOL_EXPORT,
	ZFS_IOC_LEGACY_POOL_CONFIGS,
	ZFS_IOC_LEGACY_POOL_STATS,
	ZFS_IOC_LEGACY_POOL_TRYIMPORT,
	ZFS_IOC_LEGACY_POOL_SCAN,
	ZFS_IOC_LEGACY_POOL_FREEZE,
	ZFS_IOC_LEGACY_POOL_UPGRADE,
	ZFS_IOC_LEGACY_POOL_GET_HISTORY,
	ZFS_IOC_LEGACY_VDEV_ADD,
	ZFS_IOC_LEGACY_VDEV_REMOVE,
	ZFS_IOC_LEGACY_VDEV_SET_STATE,
	ZFS_IOC_LEGACY_VDEV_ATTACH,
	ZFS_IOC_LEGACY_VDEV_DETACH,
	ZFS_IOC_LEGACY_VDEV_SETPATH,
	ZFS_IOC_LEGACY_VDEV_SETFRU,
	ZFS_IOC_LEGACY_OBJSET_STATS,
	ZFS_IOC_LEGACY_OBJSET_ZPLPROPS,
	ZFS_IOC_LEGACY_DATASET_LIST_NEXT,
	ZFS_IOC_LEGACY_SNAPSHOT_LIST_NEXT,
	ZFS_IOC_LEGACY_SET_PROP,
	ZFS_IOC_LEGACY_CREATE,
	ZFS_IOC_LEGACY_DESTROY,
	ZFS_IOC_LEGACY_ROLLBACK,
	ZFS_IOC_LEGACY_RENAME,
	ZFS_IOC_LEGACY_RECV,
	ZFS_IOC_LEGACY_SEND,
	ZFS_IOC_LEGACY_INJECT_FAULT,
	ZFS_IOC_LEGACY_CLEAR_FAULT,
	ZFS_IOC_LEGACY_INJECT_LIST_NEXT,
	ZFS_IOC_LEGACY_ERROR_LOG,
	ZFS_IOC_LEGACY_CLEAR,
	ZFS_IOC_LEGACY_PROMOTE,
	ZFS_IOC_LEGACY_DESTROY_SNAPS,
	ZFS_IOC_LEGACY_SNAPSHOT,
	ZFS_IOC_LEGACY_DSOBJ_TO_DSNAME,
	ZFS_IOC_LEGACY_OBJ_TO_PATH,
	ZFS_IOC_LEGACY_POOL_SET_PROPS,
	ZFS_IOC_LEGACY_POOL_GET_PROPS,
	ZFS_IOC_LEGACY_SET_FSACL,
	ZFS_IOC_LEGACY_GET_FSACL,
	ZFS_IOC_LEGACY_SHARE,
	ZFS_IOC_LEGACY_INHERIT_PROP,
	ZFS_IOC_LEGACY_SMB_ACL,
	ZFS_IOC_LEGACY_USERSPACE_ONE,
	ZFS_IOC_LEGACY_USERSPACE_MANY,
	ZFS_IOC_LEGACY_USERSPACE_UPGRADE,
	ZFS_IOC_LEGACY_HOLD,
	ZFS_IOC_LEGACY_RELEASE,
	ZFS_IOC_LEGACY_GET_HOLDS,
	ZFS_IOC_LEGACY_OBJSET_RECVD_PROPS,
	ZFS_IOC_LEGACY_VDEV_SPLIT,
	ZFS_IOC_LEGACY_NEXT_OBJ,
	ZFS_IOC_LEGACY_DIFF,
	ZFS_IOC_LEGACY_TMP_SNAPSHOT,
	ZFS_IOC_LEGACY_OBJ_TO_STATS,
	ZFS_IOC_LEGACY_JAIL,
	ZFS_IOC_LEGACY_UNJAIL,
	ZFS_IOC_LEGACY_POOL_REGUID,
	ZFS_IOC_LEGACY_SPACE_WRITTEN,
	ZFS_IOC_LEGACY_SPACE_SNAPS,
	ZFS_IOC_LEGACY_SEND_PROGRESS,
	ZFS_IOC_LEGACY_POOL_REOPEN,
	ZFS_IOC_LEGACY_LOG_HISTORY,
	ZFS_IOC_LEGACY_SEND_NEW,
	ZFS_IOC_LEGACY_SEND_SPACE,
	ZFS_IOC_LEGACY_CLONE,
	ZFS_IOC_LEGACY_BOOKMARK,
	ZFS_IOC_LEGACY_GET_BOOKMARKS,
	ZFS_IOC_LEGACY_DESTROY_BOOKMARKS,
	ZFS_IOC_LEGACY_NEXTBOOT,
	ZFS_IOC_LEGACY_CHANNEL_PROGRAM,
	ZFS_IOC_LEGACY_REMAP,
	ZFS_IOC_LEGACY_POOL_CHECKPOINT,
	ZFS_IOC_LEGACY_POOL_DISCARD_CHECKPOINT,
	ZFS_IOC_LEGACY_POOL_INITIALIZE,
	ZFS_IOC_LEGACY_POOL_SYNC,
	ZFS_IOC_LEGACY_LAST
};
static unsigned long zfs_ioctl_legacy_to_ozfs_[] = {
	ZFS_IOC_POOL_CREATE,			 
	ZFS_IOC_POOL_DESTROY,			 
	ZFS_IOC_POOL_IMPORT,			 
	ZFS_IOC_POOL_EXPORT,			 
	ZFS_IOC_POOL_CONFIGS,			 
	ZFS_IOC_POOL_STATS,			 
	ZFS_IOC_POOL_TRYIMPORT,			 
	ZFS_IOC_POOL_SCAN,			 
	ZFS_IOC_POOL_FREEZE,			 
	ZFS_IOC_POOL_UPGRADE,			 
	ZFS_IOC_POOL_GET_HISTORY,		 
	ZFS_IOC_VDEV_ADD,			 
	ZFS_IOC_VDEV_REMOVE,			 
	ZFS_IOC_VDEV_SET_STATE,			 
	ZFS_IOC_VDEV_ATTACH,			 
	ZFS_IOC_VDEV_DETACH,			 
	ZFS_IOC_VDEV_SETPATH,			 
	ZFS_IOC_VDEV_SETFRU,			 
	ZFS_IOC_OBJSET_STATS,			 
	ZFS_IOC_OBJSET_ZPLPROPS,		 
	ZFS_IOC_DATASET_LIST_NEXT,		 
	ZFS_IOC_SNAPSHOT_LIST_NEXT,		 
	ZFS_IOC_SET_PROP,			 
	ZFS_IOC_CREATE,				 
	ZFS_IOC_DESTROY,			 
	ZFS_IOC_ROLLBACK,			 
	ZFS_IOC_RENAME,				 
	ZFS_IOC_RECV,				 
	ZFS_IOC_SEND,				 
	ZFS_IOC_INJECT_FAULT,			 
	ZFS_IOC_CLEAR_FAULT,			 
	ZFS_IOC_INJECT_LIST_NEXT,		 
	ZFS_IOC_ERROR_LOG,			 
	ZFS_IOC_CLEAR,				 
	ZFS_IOC_PROMOTE,			 
	ZFS_IOC_DESTROY_SNAPS,			 
	ZFS_IOC_SNAPSHOT,			 
	ZFS_IOC_DSOBJ_TO_DSNAME,		 
	ZFS_IOC_OBJ_TO_PATH,			 
	ZFS_IOC_POOL_SET_PROPS,			 
	ZFS_IOC_POOL_GET_PROPS,			 
	ZFS_IOC_SET_FSACL,			 
	ZFS_IOC_GET_FSACL,			 
	ZFS_IOC_SHARE,				 
	ZFS_IOC_INHERIT_PROP,			 
	ZFS_IOC_SMB_ACL,			 
	ZFS_IOC_USERSPACE_ONE,			 
	ZFS_IOC_USERSPACE_MANY,			 
	ZFS_IOC_USERSPACE_UPGRADE,		 
	ZFS_IOC_HOLD,				 
	ZFS_IOC_RELEASE,			 
	ZFS_IOC_GET_HOLDS,			 
	ZFS_IOC_OBJSET_RECVD_PROPS,		 
	ZFS_IOC_VDEV_SPLIT,			 
	ZFS_IOC_NEXT_OBJ,			 
	ZFS_IOC_DIFF,				 
	ZFS_IOC_TMP_SNAPSHOT,			 
	ZFS_IOC_OBJ_TO_STATS,			 
	ZFS_IOC_JAIL,			 
	ZFS_IOC_UNJAIL,			 
	ZFS_IOC_POOL_REGUID,			 
	ZFS_IOC_SPACE_WRITTEN,			 
	ZFS_IOC_SPACE_SNAPS,			 
	ZFS_IOC_SEND_PROGRESS,			 
	ZFS_IOC_POOL_REOPEN,			 
	ZFS_IOC_LOG_HISTORY,			 
	ZFS_IOC_SEND_NEW,			 
	ZFS_IOC_SEND_SPACE,			 
	ZFS_IOC_CLONE,				 
	ZFS_IOC_BOOKMARK,			 
	ZFS_IOC_GET_BOOKMARKS,			 
	ZFS_IOC_DESTROY_BOOKMARKS,		 
	ZFS_IOC_NEXTBOOT,			 
	ZFS_IOC_CHANNEL_PROGRAM,		 
	ZFS_IOC_REMAP,				 
	ZFS_IOC_POOL_CHECKPOINT,		 
	ZFS_IOC_POOL_DISCARD_CHECKPOINT,	 
	ZFS_IOC_POOL_INITIALIZE,		 
};
static unsigned long zfs_ioctl_ozfs_to_legacy_common_[] = {
	ZFS_IOC_POOL_CREATE,			 
	ZFS_IOC_POOL_DESTROY,			 
	ZFS_IOC_POOL_IMPORT,			 
	ZFS_IOC_POOL_EXPORT,			 
	ZFS_IOC_POOL_CONFIGS,			 
	ZFS_IOC_POOL_STATS,			 
	ZFS_IOC_POOL_TRYIMPORT,			 
	ZFS_IOC_POOL_SCAN,			 
	ZFS_IOC_POOL_FREEZE,			 
	ZFS_IOC_POOL_UPGRADE,			 
	ZFS_IOC_POOL_GET_HISTORY,		 
	ZFS_IOC_VDEV_ADD,			 
	ZFS_IOC_VDEV_REMOVE,			 
	ZFS_IOC_VDEV_SET_STATE,			 
	ZFS_IOC_VDEV_ATTACH,			 
	ZFS_IOC_VDEV_DETACH,			 
	ZFS_IOC_VDEV_SETPATH,			 
	ZFS_IOC_VDEV_SETFRU,			 
	ZFS_IOC_OBJSET_STATS,			 
	ZFS_IOC_OBJSET_ZPLPROPS,		 
	ZFS_IOC_DATASET_LIST_NEXT,		 
	ZFS_IOC_SNAPSHOT_LIST_NEXT,		 
	ZFS_IOC_SET_PROP,			 
	ZFS_IOC_CREATE,				 
	ZFS_IOC_DESTROY,			 
	ZFS_IOC_ROLLBACK,			 
	ZFS_IOC_RENAME,				 
	ZFS_IOC_RECV,				 
	ZFS_IOC_SEND,				 
	ZFS_IOC_INJECT_FAULT,			 
	ZFS_IOC_CLEAR_FAULT,			 
	ZFS_IOC_INJECT_LIST_NEXT,		 
	ZFS_IOC_ERROR_LOG,			 
	ZFS_IOC_CLEAR,				 
	ZFS_IOC_PROMOTE,			 
	ZFS_IOC_LEGACY_SNAPSHOT,		 
	ZFS_IOC_LEGACY_DSOBJ_TO_DSNAME,		 
	ZFS_IOC_LEGACY_OBJ_TO_PATH,		 
	ZFS_IOC_LEGACY_POOL_SET_PROPS,		 
	ZFS_IOC_LEGACY_POOL_GET_PROPS,		 
	ZFS_IOC_LEGACY_SET_FSACL,		 
	ZFS_IOC_LEGACY_GET_FSACL,		 
	ZFS_IOC_LEGACY_SHARE,			 
	ZFS_IOC_LEGACY_INHERIT_PROP,		 
	ZFS_IOC_LEGACY_SMB_ACL,			 
	ZFS_IOC_LEGACY_USERSPACE_ONE,		 
	ZFS_IOC_LEGACY_USERSPACE_MANY,		 
	ZFS_IOC_LEGACY_USERSPACE_UPGRADE,	 
	ZFS_IOC_LEGACY_HOLD,			 
	ZFS_IOC_LEGACY_RELEASE,			 
	ZFS_IOC_LEGACY_GET_HOLDS,		 
	ZFS_IOC_LEGACY_OBJSET_RECVD_PROPS,	 
	ZFS_IOC_LEGACY_VDEV_SPLIT,		 
	ZFS_IOC_LEGACY_NEXT_OBJ,		 
	ZFS_IOC_LEGACY_DIFF,			 
	ZFS_IOC_LEGACY_TMP_SNAPSHOT,		 
	ZFS_IOC_LEGACY_OBJ_TO_STATS,		 
	ZFS_IOC_LEGACY_SPACE_WRITTEN,		 
	ZFS_IOC_LEGACY_SPACE_SNAPS,		 
	ZFS_IOC_LEGACY_DESTROY_SNAPS,		 
	ZFS_IOC_LEGACY_POOL_REGUID,		 
	ZFS_IOC_LEGACY_POOL_REOPEN,		 
	ZFS_IOC_LEGACY_SEND_PROGRESS,		 
	ZFS_IOC_LEGACY_LOG_HISTORY,		 
	ZFS_IOC_LEGACY_SEND_NEW,		 
	ZFS_IOC_LEGACY_SEND_SPACE,		 
	ZFS_IOC_LEGACY_CLONE,			 
	ZFS_IOC_LEGACY_BOOKMARK,		 
	ZFS_IOC_LEGACY_GET_BOOKMARKS,		 
	ZFS_IOC_LEGACY_DESTROY_BOOKMARKS,	 
	ZFS_IOC_LEGACY_NONE,  
	ZFS_IOC_LEGACY_POOL_SYNC,		 
	ZFS_IOC_LEGACY_CHANNEL_PROGRAM,		 
	ZFS_IOC_LEGACY_NONE,  
	ZFS_IOC_LEGACY_NONE,  
	ZFS_IOC_LEGACY_NONE,  
	ZFS_IOC_LEGACY_REMAP,			 
	ZFS_IOC_LEGACY_POOL_CHECKPOINT,		 
	ZFS_IOC_LEGACY_POOL_DISCARD_CHECKPOINT,	 
	ZFS_IOC_LEGACY_POOL_INITIALIZE,		 
	ZFS_IOC_LEGACY_NONE,  
	ZFS_IOC_LEGACY_NONE,  
	ZFS_IOC_LEGACY_NONE,  
	ZFS_IOC_LEGACY_NONE,  
	ZFS_IOC_LEGACY_NONE,  
};
static unsigned long zfs_ioctl_ozfs_to_legacy_platform_[] = {
	ZFS_IOC_LEGACY_NONE,  
	ZFS_IOC_LEGACY_NONE,  
	ZFS_IOC_LEGACY_NONE,  
	ZFS_IOC_LEGACY_NEXTBOOT,
	ZFS_IOC_LEGACY_JAIL,
	ZFS_IOC_LEGACY_UNJAIL,
	ZFS_IOC_LEGACY_NONE,  
	ZFS_IOC_LEGACY_NONE,  
};
int
zfs_ioctl_legacy_to_ozfs(int request)
{
	if (request >= sizeof (zfs_ioctl_legacy_to_ozfs_)/sizeof (long))
		return (-1);
	return (zfs_ioctl_legacy_to_ozfs_[request]);
}
int
zfs_ioctl_ozfs_to_legacy(int request)
{
	if (request >= ZFS_IOC_LAST)
		return (-1);
	if (request > ZFS_IOC_PLATFORM) {
		request -= ZFS_IOC_PLATFORM + 1;
		return (zfs_ioctl_ozfs_to_legacy_platform_[request]);
	}
	if (request >= sizeof (zfs_ioctl_ozfs_to_legacy_common_)/sizeof (long))
		return (-1);
	return (zfs_ioctl_ozfs_to_legacy_common_[request]);
}
void
zfs_cmd_legacy_to_ozfs(zfs_cmd_legacy_t *src, zfs_cmd_t *dst)
{
	memcpy(dst, src, offsetof(zfs_cmd_t, zc_objset_stats));
	*&dst->zc_objset_stats = *&src->zc_objset_stats;
	memcpy(&dst->zc_begin_record, &src->zc_begin_record,
	    offsetof(zfs_cmd_t, zc_sendobj) -
	    offsetof(zfs_cmd_t, zc_begin_record));
	memcpy(&dst->zc_sendobj, &src->zc_sendobj,
	    sizeof (zfs_cmd_t) - 8 - offsetof(zfs_cmd_t, zc_sendobj));
	dst->zc_zoneid = src->zc_jailid;
}
void
zfs_cmd_ozfs_to_legacy(zfs_cmd_t *src, zfs_cmd_legacy_t *dst)
{
	memcpy(dst, src, offsetof(zfs_cmd_t, zc_objset_stats));
	*&dst->zc_objset_stats = *&src->zc_objset_stats;
	*&dst->zc_begin_record.drr_u.drr_begin = *&src->zc_begin_record;
	dst->zc_begin_record.drr_payloadlen = 0;
	dst->zc_begin_record.drr_type = 0;
	memcpy(&dst->zc_inject_record, &src->zc_inject_record,
	    offsetof(zfs_cmd_t, zc_sendobj) -
	    offsetof(zfs_cmd_t, zc_inject_record));
	dst->zc_resumable = B_FALSE;
	memcpy(&dst->zc_sendobj, &src->zc_sendobj,
	    sizeof (zfs_cmd_t) - 8 - offsetof(zfs_cmd_t, zc_sendobj));
	dst->zc_jailid = src->zc_zoneid;
}
#endif  
