{
  "module_name": "Makefile",
  "hash_id": "432038659aed6dd61a2912e94a9f0b08ad7b360052be679153ed3e0219d7af74",
  "original_prompt": "Ingested from linux-6.6.14/drivers/infiniband/hw/qedr/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_INFINIBAND_QEDR) := qedr.o\n\nqedr-y := main.o verbs.o qedr_roce_cm.o qedr_iw_cm.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}