#ifndef __iwl_fw_api_sf_h__
#define __iwl_fw_api_sf_h__
enum iwl_sf_state {
	SF_LONG_DELAY_ON = 0,  
	SF_FULL_ON,
	SF_UNINIT,
	SF_INIT_OFF,
	SF_HW_NUM_STATES
};
enum iwl_sf_scenario {
	SF_SCENARIO_SINGLE_UNICAST,
	SF_SCENARIO_AGG_UNICAST,
	SF_SCENARIO_MULTICAST,
	SF_SCENARIO_BA_RESP,
	SF_SCENARIO_TX_RESP,
	SF_NUM_SCENARIO
};
#define SF_TRANSIENT_STATES_NUMBER 2	 
#define SF_NUM_TIMEOUT_TYPES 2		 
#define SF_W_MARK_SISO 6144
#define SF_W_MARK_MIMO2 8192
#define SF_W_MARK_MIMO3 6144
#define SF_W_MARK_LEGACY 4096
#define SF_W_MARK_SCAN 4096
#define SF_SINGLE_UNICAST_IDLE_TIMER_DEF 160	 
#define SF_SINGLE_UNICAST_AGING_TIMER_DEF 400	 
#define SF_AGG_UNICAST_IDLE_TIMER_DEF 160		 
#define SF_AGG_UNICAST_AGING_TIMER_DEF 400		 
#define SF_MCAST_IDLE_TIMER_DEF 160		 
#define SF_MCAST_AGING_TIMER_DEF 400		 
#define SF_BA_IDLE_TIMER_DEF 160			 
#define SF_BA_AGING_TIMER_DEF 400			 
#define SF_TX_RE_IDLE_TIMER_DEF 160			 
#define SF_TX_RE_AGING_TIMER_DEF 400		 
#define SF_SINGLE_UNICAST_IDLE_TIMER 320	 
#define SF_SINGLE_UNICAST_AGING_TIMER 2016	 
#define SF_AGG_UNICAST_IDLE_TIMER 320		 
#define SF_AGG_UNICAST_AGING_TIMER 2016		 
#define SF_MCAST_IDLE_TIMER 2016		 
#define SF_MCAST_AGING_TIMER 10016		 
#define SF_BA_IDLE_TIMER 320			 
#define SF_BA_AGING_TIMER 2016			 
#define SF_TX_RE_IDLE_TIMER 320			 
#define SF_TX_RE_AGING_TIMER 2016		 
#define SF_LONG_DELAY_AGING_TIMER 1000000	 
#define SF_CFG_DUMMY_NOTIF_OFF	BIT(16)
struct iwl_sf_cfg_cmd {
	__le32 state;
	__le32 watermark[SF_TRANSIENT_STATES_NUMBER];
	__le32 long_delay_timeouts[SF_NUM_SCENARIO][SF_NUM_TIMEOUT_TYPES];
	__le32 full_on_timeouts[SF_NUM_SCENARIO][SF_NUM_TIMEOUT_TYPES];
} __packed;  
#endif  
