{
  "module_name": "Makefile",
  "hash_id": "7f71d24afe4bec1ebcfd292455af11767505621e88b441af61e60cb2e294cf9a",
  "original_prompt": "Ingested from linux-6.6.14/drivers/crypto/hisilicon/sec2/Makefile",
  "human_readable_source": "obj-$(CONFIG_CRYPTO_DEV_HISI_SEC2) += hisi_sec2.o\nhisi_sec2-objs = sec_main.o sec_crypto.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}