{
  "module_name": "Makefile",
  "hash_id": "2d6c1118eb0c719334d93890e6d2538fddca93fbe938da85ab1c50028bacb9ef",
  "original_prompt": "Ingested from linux-6.6.14/drivers/usb/class/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for USB Class drivers\n# (one step up from the misc category)\n#\n\nobj-$(CONFIG_USB_ACM)\t\t+= cdc-acm.o\nobj-$(CONFIG_USB_PRINTER)\t+= usblp.o\nobj-$(CONFIG_USB_WDM)\t\t+= cdc-wdm.o\nobj-$(CONFIG_USB_TMC)\t\t+= usbtmc.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}