{
  "module_name": "Makefile",
  "hash_id": "f86259db36efe04e5f99d8b639286faa46273690a8c0bf7d07c36248219c1b57",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/user/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n# Makefile for user memory selftests\n\n# No binaries, but make sure arg-less \"make\" doesn't trigger \"run_tests\"\nall:\n\nTEST_PROGS := test_user_copy.sh\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}