{
  "module_name": "Makefile",
  "hash_id": "78e3f2e2edf95e4d47d8a0636500378ef166edf98f486c6dd07cb0aeeea99139",
  "original_prompt": "Ingested from linux-6.6.14/drivers/phy/intel/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_PHY_INTEL_KEEMBAY_EMMC)\t+= phy-intel-keembay-emmc.o\nobj-$(CONFIG_PHY_INTEL_KEEMBAY_USB)\t+= phy-intel-keembay-usb.o\nobj-$(CONFIG_PHY_INTEL_LGM_COMBO)\t+= phy-intel-lgm-combo.o\nobj-$(CONFIG_PHY_INTEL_LGM_EMMC)\t+= phy-intel-lgm-emmc.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}