{
  "module_name": "Makefile",
  "hash_id": "6cd9c7d3061ec0c0b9ec2b8a0d4771a80974a24b347d30f44fc7fcd5e2055466",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/ia64/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nTEST_PROGS := aliasing-test\n\nall: $(TEST_PROGS)\n\ninclude ../lib.mk\n\nclean:\n\trm -fr $(TEST_PROGS)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}