{
  "module_name": "Makefile",
  "hash_id": "0d9beec1e648395869f0f44c5fa16b6d95c0f8f849b7f99d15eb3b06aab7050e",
  "original_prompt": "Ingested from linux-6.6.14/drivers/crypto/intel/qat/qat_c62x/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nccflags-y := -I $(srctree)/$(src)/../qat_common\nobj-$(CONFIG_CRYPTO_DEV_QAT_C62X) += qat_c62x.o\nqat_c62x-objs := adf_drv.o adf_c62x_hw_data.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}