{
  "module_name": "Makefile",
  "hash_id": "3b16a63f5ac25bb99415125f388905e07f905164005d850816033b1efbef1711",
  "original_prompt": "Ingested from linux-6.6.14/drivers/s390/virtio/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for kvm guest drivers on s390\n#\n# Copyright IBM Corp. 2008\n\nobj-$(CONFIG_S390_GUEST) += virtio_ccw.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}