{
  "module_name": "Makefile",
  "hash_id": "575a093ddbc5b71cf8eab8712e1f6ac8b75a8209402036243dd9b09ca4a2166e",
  "original_prompt": "Ingested from linux-6.6.14/drivers/block/zram/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nzram-y\t:=\tzcomp.o zram_drv.o\n\nobj-$(CONFIG_ZRAM)\t+=\tzram.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}