{
  "module_name": "Makefile",
  "hash_id": "92623e78aae5217297741d923adc799cb1ad631d48bfc61c2a309755781acb5d",
  "original_prompt": "Ingested from linux-6.6.14/drivers/platform/goldfish/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for Goldfish platform specific drivers\n#\nobj-$(CONFIG_GOLDFISH_PIPE)\t+= goldfish_pipe.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}