{
  "module_name": "Makefile",
  "hash_id": "31406baadd33e10dc68e221287c2ebcb4df68476cb0c1a1e5fd20aef46b70bba",
  "original_prompt": "Ingested from linux-6.6.14/drivers/pci/endpoint/functions/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for PCI Endpoint Functions\n#\n\nobj-$(CONFIG_PCI_EPF_TEST)\t\t+= pci-epf-test.o\nobj-$(CONFIG_PCI_EPF_NTB)\t\t+= pci-epf-ntb.o\nobj-$(CONFIG_PCI_EPF_VNTB) \t\t+= pci-epf-vntb.o\nobj-$(CONFIG_PCI_EPF_MHI)\t\t+= pci-epf-mhi.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}