{
  "module_name": "Kbuild",
  "hash_id": "a66b53debf83fa1ff91997daac0648669a6b4929cdc50b85f2272c21992a185f",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/nouveau/nvkm/engine/vp/Kbuild",
  "human_readable_source": "# SPDX-License-Identifier: MIT\nnvkm-y += nvkm/engine/vp/g84.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}