{
  "module_name": "Makefile",
  "hash_id": "60952f3eb6caa032f1212ff7a387550dd27a1f69a3eaf5ec9222288260244a03",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/netfilter/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for netfilter selftests\n\nTEST_PROGS := nft_trans_stress.sh nft_fib.sh nft_nat.sh bridge_brouter.sh \\\n\tconntrack_icmp_related.sh nft_flowtable.sh ipvs.sh \\\n\tnft_concat_range.sh nft_conntrack_helper.sh \\\n\tnft_queue.sh nft_meta.sh nf_nat_edemux.sh \\\n\tipip-conntrack-mtu.sh conntrack_tcp_unreplied.sh \\\n\tconntrack_vrf.sh nft_synproxy.sh rpath.sh nft_audit.sh \\\n\tconntrack_sctp_collision.sh xt_string.sh\n\nHOSTPKG_CONFIG := pkg-config\n\nCFLAGS += $(shell $(HOSTPKG_CONFIG) --cflags libmnl 2>/dev/null)\nLDLIBS += $(shell $(HOSTPKG_CONFIG) --libs libmnl 2>/dev/null || echo -lmnl)\n\nTEST_GEN_FILES =  nf-queue connect_close audit_logread sctp_collision\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}