{
  "module_name": "Makefile",
  "hash_id": "daf20ab067f1079d768af1ab97ad65be91957ba33d104130f0a1d6adc8f433cb",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/huawei/hinic/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_HINIC) += hinic.o\n\nhinic-y := hinic_main.o hinic_tx.o hinic_rx.o hinic_port.o hinic_hw_dev.o \\\n\t   hinic_hw_io.o hinic_hw_qp.o hinic_hw_cmdq.o hinic_hw_wq.o \\\n\t   hinic_hw_mgmt.o hinic_hw_api_cmd.o hinic_hw_eqs.o hinic_hw_if.o \\\n\t   hinic_common.o hinic_ethtool.o hinic_devlink.o hinic_hw_mbox.o \\\n\t   hinic_sriov.o hinic_debugfs.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}