{
  "module_name": "Makefile",
  "hash_id": "ea8222670fd118eac5a66de7da7d61be759cf5c30f53ba52d928d10ce2c366cb",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/mediatek/mt7986/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\n# platform driver\nsnd-soc-mt7986-afe-objs := \\\n\tmt7986-afe-pcm.o \\\n\tmt7986-dai-etdm.o\n\nobj-$(CONFIG_SND_SOC_MT7986) += snd-soc-mt7986-afe.o\nobj-$(CONFIG_SND_SOC_MT7986_WM8960) += mt7986-wm8960.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}