{
  "module_name": "Makefile",
  "hash_id": "d798f14dca8369d44447a4c93e00f3e44c026dd63e8cc0521fcc29b25ddfc123",
  "original_prompt": "Ingested from linux-6.6.14/fs/squashfs/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the linux squashfs routines.\n#\n\nobj-$(CONFIG_SQUASHFS) += squashfs.o\nsquashfs-y += block.o cache.o dir.o export.o file.o fragment.o id.o inode.o\nsquashfs-y += namei.o super.o symlink.o decompressor.o page_actor.o\nsquashfs-$(CONFIG_SQUASHFS_FILE_CACHE) += file_cache.o\nsquashfs-$(CONFIG_SQUASHFS_FILE_DIRECT) += file_direct.o\nsquashfs-$(CONFIG_SQUASHFS_DECOMP_SINGLE) += decompressor_single.o\nsquashfs-$(CONFIG_SQUASHFS_DECOMP_MULTI) += decompressor_multi.o\nsquashfs-$(CONFIG_SQUASHFS_DECOMP_MULTI_PERCPU) += decompressor_multi_percpu.o\nsquashfs-$(CONFIG_SQUASHFS_XATTR) += xattr.o xattr_id.o\nsquashfs-$(CONFIG_SQUASHFS_LZ4) += lz4_wrapper.o\nsquashfs-$(CONFIG_SQUASHFS_LZO) += lzo_wrapper.o\nsquashfs-$(CONFIG_SQUASHFS_XZ) += xz_wrapper.o\nsquashfs-$(CONFIG_SQUASHFS_ZLIB) += zlib_wrapper.o\nsquashfs-$(CONFIG_SQUASHFS_ZSTD) += zstd_wrapper.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}