{
  "module_name": "Makefile",
  "hash_id": "a01cf557d5f4548db7329d00bbdc03fd2f52a34534c0f08e2d9caec0d7886fdd",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/fjes/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n################################################################################\n#\n# FUJITSU Extended Socket Network Device driver\n# Copyright (c) 2015 FUJITSU LIMITED\n#\n################################################################################\n\n\n#\n# Makefile for the FUJITSU Extended Socket network device driver\n#\n\nobj-$(CONFIG_FUJITSU_ES) += fjes.o\n\nfjes-objs := fjes_main.o fjes_hw.o fjes_ethtool.o fjes_trace.o fjes_debugfs.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}