{
  "module_name": "Makefile",
  "hash_id": "378dfed558bfa90eda824dee2f8eea3bb881f66e543606b819b7c334bb3ab8f1",
  "original_prompt": "Ingested from linux-6.6.14/sound/aoa/soundbus/i2sbus/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_SND_AOA_SOUNDBUS_I2S) += snd-aoa-i2sbus.o\nsnd-aoa-i2sbus-objs := core.o pcm.o control.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}