{
  "module_name": "Makefile",
  "hash_id": "184fc4049e890869b7d4f0bd0ff5357b6fdeb1578a9bfa96b6da17be5853d732",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/lkdtm/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for LKDTM regression tests\n\ninclude ../lib.mk\n\n# NOTE: $(OUTPUT) won't get default value if used before lib.mk\nTEST_FILES := tests.txt\nTEST_PROGS := stack-entropy.sh\nTEST_GEN_PROGS = $(patsubst %,$(OUTPUT)/%.sh,$(shell awk '{print $$1}' tests.txt | sed -e 's/\\#//'))\nall: $(TEST_GEN_PROGS)\n\n$(OUTPUT)/%: run.sh tests.txt\n\tinstall -m 0744 run.sh $@\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}