{
  "module_name": "Makefile",
  "hash_id": "41a2ebc91a0a8e4ca8019cde81a8a9a0d1482f788be32ae0c1970c1018713baf",
  "original_prompt": "Ingested from linux-6.6.14/drivers/ntb/hw/amd/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_NTB_AMD) += ntb_hw_amd.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}