 
 

 
#define ATH11K_TESTMODE_VERSION_MAJOR 1

 
#define ATH11K_TESTMODE_VERSION_MINOR 1

#define ATH11K_TM_DATA_MAX_LEN		5000
#define ATH11K_FTM_EVENT_MAX_BUF_LENGTH 2048

enum ath11k_tm_attr {
	__ATH11K_TM_ATTR_INVALID		= 0,
	ATH11K_TM_ATTR_CMD			= 1,
	ATH11K_TM_ATTR_DATA			= 2,
	ATH11K_TM_ATTR_WMI_CMDID		= 3,
	ATH11K_TM_ATTR_VERSION_MAJOR		= 4,
	ATH11K_TM_ATTR_VERSION_MINOR		= 5,
	ATH11K_TM_ATTR_WMI_OP_VERSION		= 6,

	 
	__ATH11K_TM_ATTR_AFTER_LAST,
	ATH11K_TM_ATTR_MAX		= __ATH11K_TM_ATTR_AFTER_LAST - 1,
};

 
enum ath11k_tm_cmd {
	 
	ATH11K_TM_CMD_GET_VERSION = 0,

	 
	ATH11K_TM_CMD_WMI = 1,

	 
	ATH11K_TM_CMD_TESTMODE_START = 2,

	 
	ATH11K_TM_CMD_WMI_FTM = 3,
};
