 
 

#ifndef __WL12XX_CONF_H__
#define __WL12XX_CONF_H__

 
#define CONF_TX_PWR_COMPENSATION_LEN_2 7
#define CONF_TX_PWR_COMPENSATION_LEN_5 18

struct wl12xx_conf_rf {
	 
	u8 tx_per_channel_power_compensation_2[CONF_TX_PWR_COMPENSATION_LEN_2];

	 
	u8 tx_per_channel_power_compensation_5[CONF_TX_PWR_COMPENSATION_LEN_5];
};

struct wl12xx_priv_conf {
	struct wl12xx_conf_rf rf;
	struct conf_memory_settings mem_wl127x;
};

enum wl12xx_sg_params {
	 
	WL12XX_CONF_SG_ACL_BT_MASTER_MIN_BR = 0,
	WL12XX_CONF_SG_ACL_BT_MASTER_MAX_BR,

	 
	WL12XX_CONF_SG_ACL_BT_SLAVE_MIN_BR,
	WL12XX_CONF_SG_ACL_BT_SLAVE_MAX_BR,

	 
	WL12XX_CONF_SG_ACL_BT_MASTER_MIN_EDR,
	WL12XX_CONF_SG_ACL_BT_MASTER_MAX_EDR,

	 
	WL12XX_CONF_SG_ACL_BT_SLAVE_MIN_EDR,
	WL12XX_CONF_SG_ACL_BT_SLAVE_MAX_EDR,

	 
	WL12XX_CONF_SG_ACL_WLAN_PS_MASTER_BR,
	WL12XX_CONF_SG_ACL_WLAN_PS_SLAVE_BR,

	 
	WL12XX_CONF_SG_ACL_WLAN_PS_MASTER_EDR,
	WL12XX_CONF_SG_ACL_WLAN_PS_SLAVE_EDR,

	 
	WL12XX_CONF_SG_ACL_WLAN_ACTIVE_MASTER_MIN_BR,
	WL12XX_CONF_SG_ACL_WLAN_ACTIVE_MASTER_MAX_BR,
	WL12XX_CONF_SG_ACL_WLAN_ACTIVE_SLAVE_MIN_BR,
	WL12XX_CONF_SG_ACL_WLAN_ACTIVE_SLAVE_MAX_BR,
	WL12XX_CONF_SG_ACL_WLAN_ACTIVE_MASTER_MIN_EDR,
	WL12XX_CONF_SG_ACL_WLAN_ACTIVE_MASTER_MAX_EDR,
	WL12XX_CONF_SG_ACL_WLAN_ACTIVE_SLAVE_MIN_EDR,
	WL12XX_CONF_SG_ACL_WLAN_ACTIVE_SLAVE_MAX_EDR,

	WL12XX_CONF_SG_ACL_ACTIVE_SCAN_WLAN_BR,
	WL12XX_CONF_SG_ACL_ACTIVE_SCAN_WLAN_EDR,
	WL12XX_CONF_SG_ACL_PASSIVE_SCAN_BT_BR,
	WL12XX_CONF_SG_ACL_PASSIVE_SCAN_WLAN_BR,
	WL12XX_CONF_SG_ACL_PASSIVE_SCAN_BT_EDR,
	WL12XX_CONF_SG_ACL_PASSIVE_SCAN_WLAN_EDR,

	 
	WL12XX_CONF_SG_AUTO_SCAN_PROBE_REQ,

	 
	WL12XX_CONF_SG_ACTIVE_SCAN_DURATION_FACTOR_HV3,

	 
	WL12XX_CONF_SG_ACTIVE_SCAN_DURATION_FACTOR_A2DP,

	 
	WL12XX_CONF_SG_PASSIVE_SCAN_DUR_FACTOR_A2DP_BR,

	 
	WL12XX_CONF_SG_PASSIVE_SCAN_DUR_FACTOR_A2DP_EDR,

	 
	WL12XX_CONF_SG_PASSIVE_SCAN_DUR_FACTOR_HV3,

	 
	WL12XX_CONF_SG_CONSECUTIVE_HV3_IN_PASSIVE_SCAN,
	WL12XX_CONF_SG_BCN_HV3_COLL_THR_IN_PASSIVE_SCAN,
	WL12XX_CONF_SG_TX_RX_PROTECT_BW_IN_PASSIVE_SCAN,

	 
	WL12XX_CONF_SG_STA_FORCE_PS_IN_BT_SCO,

	 
	WL12XX_CONF_SG_ANTENNA_CONFIGURATION,

	 
	WL12XX_CONF_SG_BEACON_MISS_PERCENT,

	 
	WL12XX_CONF_SG_DHCP_TIME,

	 
	WL12XX_CONF_SG_RXT,

	 
	WL12XX_CONF_SG_TXT,

	 
	WL12XX_CONF_SG_ADAPTIVE_RXT_TXT,

	 
	WL12XX_CONF_SG_GENERAL_USAGE_BIT_MAP,

	 
	WL12XX_CONF_SG_HV3_MAX_SERVED,

	 
	WL12XX_CONF_SG_PS_POLL_TIMEOUT,

	 
	WL12XX_CONF_SG_UPSD_TIMEOUT,

	WL12XX_CONF_SG_CONSECUTIVE_CTS_THRESHOLD,
	WL12XX_CONF_SG_STA_RX_WINDOW_AFTER_DTIM,
	WL12XX_CONF_SG_STA_CONNECTION_PROTECTION_TIME,

	 
	WL12XX_CONF_AP_BEACON_MISS_TX,
	WL12XX_CONF_AP_RX_WINDOW_AFTER_BEACON,
	WL12XX_CONF_AP_BEACON_WINDOW_INTERVAL,
	WL12XX_CONF_AP_CONNECTION_PROTECTION_TIME,
	WL12XX_CONF_AP_BT_ACL_VAL_BT_SERVE_TIME,
	WL12XX_CONF_AP_BT_ACL_VAL_WL_SERVE_TIME,

	 
	WL12XX_CONF_SG_CTS_DILUTED_BAD_RX_PACKETS_TH,
	WL12XX_CONF_SG_CTS_CHOP_IN_DUAL_ANT_SCO_MASTER,

	WL12XX_CONF_SG_TEMP_PARAM_1,
	WL12XX_CONF_SG_TEMP_PARAM_2,
	WL12XX_CONF_SG_TEMP_PARAM_3,
	WL12XX_CONF_SG_TEMP_PARAM_4,
	WL12XX_CONF_SG_TEMP_PARAM_5,
	WL12XX_CONF_SG_TEMP_PARAM_6,
	WL12XX_CONF_SG_TEMP_PARAM_7,
	WL12XX_CONF_SG_TEMP_PARAM_8,
	WL12XX_CONF_SG_TEMP_PARAM_9,
	WL12XX_CONF_SG_TEMP_PARAM_10,

	WL12XX_CONF_SG_PARAMS_MAX,
	WL12XX_CONF_SG_PARAMS_ALL = 0xff
};

#endif  
