{
  "module_name": "Makefile",
  "hash_id": "97ef4a57a86d3abc3dca20385f1321b0e62957503204efd23033123fced293bd",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/ti/wl12xx/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nwl12xx-objs\t= main.o cmd.o acx.o debugfs.o scan.o event.o\n\nobj-$(CONFIG_WL12XX)\t\t+= wl12xx.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}