{
  "module_name": "Makefile",
  "hash_id": "a0a43dca86827fff67bbc5e6dab986a17ab56ecb6772fe4311ffd459c8abd7a5",
  "original_prompt": "Ingested from openssh-9.6p1/regress/unittests/conversion/Makefile",
  "human_readable_source": "#\t$OpenBSD: Makefile,v 1.4 2021/01/09 12:24:30 dtucker Exp $\n\nPROG=test_conversion\nSRCS=tests.c\n\n# From usr.bin/ssh\nSRCS+=sshbuf-getput-basic.c sshbuf-getput-crypto.c sshbuf-misc.c sshbuf.c\nSRCS+=atomicio.c misc.c xmalloc.c log.c uidswap.c cleanup.c fatal.c ssherr.c\nSRCS+=match.c addr.c addrmatch.c\n\nREGRESS_TARGETS=run-regress-${PROG}\n\nrun-regress-${PROG}: ${PROG}\n\tenv ${TEST_ENV} ./${PROG}\n\n.include <bsd.regress.mk>\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}