{
  "module_name": "Makefile",
  "hash_id": "bd5b8ba55706362dba0fcf45fe1d1fea8f900aa1064a2dd43557d5831786d667",
  "original_prompt": "Ingested from linux-6.6.14/drivers/input/joystick/iforce/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the I-Force driver\n#\n# By Johann Deneux <johann.deneux@gmail.com>\n#\n\nobj-$(CONFIG_JOYSTICK_IFORCE)\t\t+= iforce.o\niforce-y := iforce-ff.o iforce-main.o iforce-packets.o\nobj-$(CONFIG_JOYSTICK_IFORCE_232)\t+= iforce-serio.o\nobj-$(CONFIG_JOYSTICK_IFORCE_USB)\t+= iforce-usb.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}