{
  "module_name": "Makefile",
  "hash_id": "9eac06561138f905d44145fc0a0bd0b5f5ab8efa8fbba8790a6ac9591b0abe5f",
  "original_prompt": "Ingested from linux-6.6.14/fs/ocfs2/dlm/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_OCFS2_FS_O2CB) += ocfs2_dlm.o\n\nocfs2_dlm-objs := dlmdomain.o dlmdebug.o dlmthread.o dlmrecovery.o \\\n\tdlmmaster.o dlmast.o dlmconvert.o dlmlock.o dlmunlock.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}