{
  "module_name": "Makefile",
  "hash_id": "3f5bed18197d5b03325473833f3699bac43634cf0a0f69ff23c75172dd3ecc59",
  "original_prompt": "Ingested from linux-6.6.14/drivers/clk/mstar/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for mstar specific clk\n#\n\nobj-$(CONFIG_MSTAR_MSC313_CPUPLL) += clk-msc313-cpupll.o\nobj-$(CONFIG_MSTAR_MSC313_MPLL) += clk-msc313-mpll.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}