{
  "module_name": "Makefile",
  "hash_id": "c070002120b249d535ca6c81371c02a4dc3cd637c6995a622370a688b5f49914",
  "original_prompt": "Ingested from linux-6.6.14/fs/orangefs/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the ORANGEFS filesystem.\n#\n\nobj-$(CONFIG_ORANGEFS_FS) += orangefs.o\n\norangefs-objs := acl.o file.o orangefs-cache.o orangefs-utils.o xattr.o \\\n\t\t dcache.o inode.o orangefs-sysfs.o orangefs-mod.o super.o \\\n\t\t devorangefs-req.o namei.o symlink.o dir.o orangefs-bufmap.o \\\n\t\t orangefs-debugfs.o waitqueue.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}