include("$(PORT_DIR)/boards/manifest.py")
require("bundle-networking")
require("time")
require("senml")
require("logging")
require("aioble")
add_library("arduino-lib", "$(ARDUINO_LIB_DIR)")
require("msgpackrpc", library="arduino-lib")
