{
  "module_name": "Makefile",
  "hash_id": "a835d2c269498dbd54fe3ffcc3e3df0fcab75d0302d115cc17babf6a460c8a32",
  "original_prompt": "Ingested from linux-6.6.14/lib/zlib_deflate/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# This is a modified version of zlib, which does all memory\n# allocation ahead of time.\n#\n# This is the compression code, see zlib_inflate for the\n# decompression code.\n#\n\nobj-$(CONFIG_ZLIB_DEFLATE) += zlib_deflate.o\n\nzlib_deflate-objs := deflate.o deftree.o deflate_syms.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}