{
  "module_name": "Makefile",
  "hash_id": "fc77130e62bc7443ff3a0269b9470211e4df33b57a0f77bdd07ba96a163ae2f8",
  "original_prompt": "Ingested from linux-6.6.14/drivers/platform/chrome/wilco_ec/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\nwilco_ec-objs\t\t\t\t:= core.o keyboard_leds.o mailbox.o \\\n\t\t\t\t\t   properties.o sysfs.o\nobj-$(CONFIG_WILCO_EC)\t\t\t+= wilco_ec.o\nwilco_ec_debugfs-objs\t\t\t:= debugfs.o\nobj-$(CONFIG_WILCO_EC_DEBUGFS)\t\t+= wilco_ec_debugfs.o\nwilco_ec_events-objs\t\t\t:= event.o\nobj-$(CONFIG_WILCO_EC_EVENTS)\t\t+= wilco_ec_events.o\nwilco_ec_telem-objs\t\t\t:= telemetry.o\nobj-$(CONFIG_WILCO_EC_TELEMETRY)\t+= wilco_ec_telem.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}