{
  "module_name": "Makefile",
  "hash_id": "b8d5daada34688e4e9f7cf75f35d905526c43128cda237120bf48ccd6c365e9d",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/pci/cx23885/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\ncx23885-objs\t:= cx23885-cards.o cx23885-video.o cx23885-vbi.o \\\n\t\t    cx23885-core.o cx23885-i2c.o cx23885-dvb.o cx23885-417.o \\\n\t\t    cx23885-ioctl.o cx23885-ir.o cx23885-av.o cx23885-input.o \\\n\t\t    cx23888-ir.o netup-init.o cimax2.o netup-eeprom.o \\\n\t\t    cx23885-f300.o cx23885-alsa.o\n\nobj-$(CONFIG_VIDEO_CX23885) += cx23885.o\nobj-$(CONFIG_MEDIA_ALTERA_CI) += altera-ci.o\n\nccflags-y += -I $(srctree)/drivers/media/tuners\nccflags-y += -I $(srctree)/drivers/media/dvb-frontends\n\nccflags-y += $(extra-cflags-y) $(extra-cflags-m)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}