{
  "module_name": "Makefile",
  "hash_id": "cb3d30ad717a11b99a0180344c4bda5d41ec33595e411049f98bb717069c1294",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/adi/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nsnd-soc-adi-axi-i2s-objs := axi-i2s.o\nsnd-soc-adi-axi-spdif-objs := axi-spdif.o\n\nobj-$(CONFIG_SND_SOC_ADI_AXI_I2S) += snd-soc-adi-axi-i2s.o\nobj-$(CONFIG_SND_SOC_ADI_AXI_SPDIF) += snd-soc-adi-axi-spdif.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}