{
  "module_name": "Makefile",
  "hash_id": "b8300b06ba83ea96d3a32c9eac9d42a8f21cc2521238c802dcd4b797567e8b0d",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/silabs/wfx/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n\n# Necessary for CREATE_TRACE_POINTS\nCFLAGS_debug.o = -I$(src)\n\nwfx-y := \\\n\tbh.o \\\n\thwio.o \\\n\tfwio.o \\\n\thif_tx_mib.o \\\n\thif_tx.o \\\n\thif_rx.o \\\n\tqueue.o \\\n\tdata_tx.o \\\n\tdata_rx.o \\\n\tscan.o \\\n\tsta.o \\\n\tkey.o \\\n\tmain.o \\\n\tdebug.o\nwfx-$(CONFIG_SPI) += bus_spi.o\n# When CONFIG_MMC == m, append to 'wfx-y' (and not to 'wfx-m')\nwfx-$(subst m,y,$(CONFIG_MMC)) += bus_sdio.o\n\nobj-$(CONFIG_WFX) += wfx.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}