{
  "module_name": "Makefile",
  "hash_id": "fb470db8505662e2e1c44c46ea81b37ec49bec570271045bbc306ab18e127493",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/broadcom/brcm80211/brcmutil/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: ISC\n#\n# Makefile fragment for Broadcom 802.11n Networking Device Driver Utilities\n#\n# Copyright (c) 2011 Broadcom Corporation\n#\nccflags-y := -I $(srctree)/$(src)/../include\n\nobj-$(CONFIG_BRCMUTIL)\t+= brcmutil.o\nbrcmutil-objs\t= utils.o d11.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}