{
  "module_name": "Makefile",
  "hash_id": "6f0136928930e4d581bb2dd224bca16d13480abf62aee5ba9ddce2bfee470096",
  "original_prompt": "Ingested from linux-6.6.14/tools/laptop/freefall/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nPREFIX ?= /usr\nSBINDIR ?= sbin\nINSTALL ?= install\n\nTARGET = freefall\n\nall: $(TARGET)\n\n%: %.c\n\t$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $<\n\nclean:\n\t$(RM) $(TARGET)\n\ninstall: freefall\n\t$(INSTALL) -D -m 755 $(TARGET) $(DESTDIR)$(PREFIX)/$(SBINDIR)/$(TARGET)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}