#ifndef UTIL_LINUX_EXITCODES_H
#define UTIL_LINUX_EXITCODES_H



#define MKFS_EX_OK	0	
#define MKFS_EX_ERROR	8	
#define MKFS_EX_USAGE	16	


#define FSCK_EX_OK		0	
#define FSCK_EX_NONDESTRUCT	1	
#define FSCK_EX_REBOOT		2	
#define FSCK_EX_DESTRUCT	FSCK_EX_REBOOT	
#define FSCK_EX_UNCORRECTED	4	
#define FSCK_EX_ERROR		8	
#define FSCK_EX_USAGE		16	
#define FSCK_EX_LIBRARY		128	

#define EXIT_NOTSUPP 2

#endif	
