#ifndef _rsmu_0_0_2_OFFSET_HEADER
#define _rsmu_0_0_2_OFFSET_HEADER
#define	mmRSMU_UMC_INDEX_REGISTER_NBIF_VG20_GPU								0x0d91
#define	mmRSMU_UMC_INDEX_REGISTER_NBIF_VG20_GPU_BASE_IDX						0
#endif
