{
  "module_name": "Makefile",
  "hash_id": "e000439f61dff7407d7b4287ccc01d2f41f7165895e74106b337a446088b056f",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/sof/imx/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: (GPL-2.0-only OR BSD-3-Clause)\nsnd-sof-imx8-objs := imx8.o\nsnd-sof-imx8m-objs := imx8m.o\nsnd-sof-imx8ulp-objs := imx8ulp.o\n\nsnd-sof-imx-common-objs := imx-common.o\n\nobj-$(CONFIG_SND_SOC_SOF_IMX8) += snd-sof-imx8.o\nobj-$(CONFIG_SND_SOC_SOF_IMX8M) += snd-sof-imx8m.o\nobj-$(CONFIG_SND_SOC_SOF_IMX8ULP) += snd-sof-imx8ulp.o\nobj-$(CONFIG_SND_SOC_SOF_IMX_COMMON) += imx-common.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}