{
  "module_name": "Makefile",
  "hash_id": "09745a873084288667fb12249613e32d04c9d868328309a9ab9fd1ac7358c49f",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/mxsfb/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nmxsfb-y := mxsfb_drv.o mxsfb_kms.o\nobj-$(CONFIG_DRM_MXSFB)\t+= mxsfb.o\nimx-lcdif-y := lcdif_drv.o lcdif_kms.o\nobj-$(CONFIG_DRM_IMX_LCDIF) += imx-lcdif.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}