{
  "module_name": "Makefile",
  "hash_id": "fbc9a92d92a91553c55ae5aa2de306b1b15ab3da020f0865742f2a237fd9b903",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/pci/ttpci/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the kernel SAA7146 FULL TS DVB device driver\n#\n\nobj-$(CONFIG_DVB_BUDGET_CORE) += budget-core.o\nobj-$(CONFIG_DVB_BUDGET) += budget.o\nobj-$(CONFIG_DVB_BUDGET_AV) += budget-av.o\nobj-$(CONFIG_DVB_BUDGET_CI) += budget-ci.o\n\nccflags-y += -I $(srctree)/drivers/media/dvb-frontends/\nccflags-y += -I $(srctree)/drivers/media/tuners\nccflags-y += -I $(srctree)/drivers/media/common\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}