{
  "module_name": "Makefile",
  "hash_id": "dcad7693a5107df73342ba903dbe8ea02079801dc82dbe2bddc78afe6221c339",
  "original_prompt": "Ingested from linux-6.6.14/samples/kobject/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_SAMPLE_KOBJECT) += kobject-example.o kset-example.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}