{
  "module_name": "Makefile",
  "hash_id": "d00e7f1505d3a9d638a065b66495ed45dcdb31da22ffa99299d4045f023dfd1a",
  "original_prompt": "Ingested from linux-6.6.14/tools/power/acpi/tools/ec/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n# tools/power/acpi/tools/acpidump/Makefile - ACPI tool Makefile\n#\n# Copyright (c) 2015, Intel Corporation\n#   Author: Lv Zheng <lv.zheng@intel.com>\n#\n\ninclude ../../Makefile.config\n\nTOOL = ec\nTOOL_OBJS = \\\n\tec_access.o\n\ninclude ../../Makefile.rules\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}