{
  "module_name": "Makefile",
  "hash_id": "2ce731764f5ac9a36af1d388c6b4676d48b0d4af6a9075f231392f7395fcd17d",
  "original_prompt": "Ingested from linux-6.6.14/fs/nfs_common/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for Linux filesystem routines that are shared by client and server.\n#\n\nobj-$(CONFIG_NFS_ACL_SUPPORT) += nfs_acl.o\nnfs_acl-objs := nfsacl.o\n\nobj-$(CONFIG_GRACE_PERIOD) += grace.o\nobj-$(CONFIG_NFS_V4_2_SSC_HELPER) += nfs_ssc.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}