{
  "module_name": "Makefile",
  "hash_id": "4f635cec5b74e5effa2e7078baf3f615a508b0b890bd655e0b377b7301816d60",
  "original_prompt": "Ingested from linux-6.6.14/drivers/reset/tegra/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_RESET_TEGRA_BPMP) += reset-bpmp.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}