{
  "module_name": "Makefile",
  "hash_id": "86811a30fd69d4599faf722aa864772d5d47f72b569c3fd6b432aa8fb21914f5",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/net/openvswitch/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\ntop_srcdir = ../../../../..\n\nCFLAGS =  -Wall -Wl,--no-as-needed -O2 -g -I$(top_srcdir)/usr/include $(KHDR_INCLUDES)\n\nTEST_PROGS := openvswitch.sh\n\nTEST_FILES := ovs-dpctl.py\n\nEXTRA_CLEAN := test_netlink_checks\n\ninclude ../../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}