




obj-$(CONFIG_SKFP) += skfp.o

skfp-objs :=  skfddi.o    hwmtm.o    fplustm.o  smt.o      cfm.o     \
              ecm.o       pcmplc.o   pmf.o      queue.o    rmt.o     \
	      smtdef.o    smtinit.o  smttimer.o srf.o      hwt.o     \
	      drvfbi.o   ess.o









ccflags-y := -DPCI -DMEM_MAPPED_IO -Wno-strict-prototypes
