#ifndef _DT_BINDINGS_AMLOGIC_MESON_AXG_AUDIO_ARB_H
#define _DT_BINDINGS_AMLOGIC_MESON_AXG_AUDIO_ARB_H
#define AXG_ARB_TODDR_A	0
#define AXG_ARB_TODDR_B	1
#define AXG_ARB_TODDR_C	2
#define AXG_ARB_FRDDR_A	3
#define AXG_ARB_FRDDR_B	4
#define AXG_ARB_FRDDR_C	5
#define AXG_ARB_TODDR_D	6
#define AXG_ARB_FRDDR_D	7
#endif  
