{
  "module_name": "Makefile",
  "hash_id": "fc1d84078ea280214270cf7dd18c5875d5a29aedc7e8a8abbdc6724bf9b824b8",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/radio/si4713/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for radios with Silicon Labs Si4713 FM Radio Transmitters\n#\n\nobj-$(CONFIG_I2C_SI4713) += si4713.o\nobj-$(CONFIG_USB_SI4713) += radio-usb-si4713.o\nobj-$(CONFIG_PLATFORM_SI4713) += radio-platform-si4713.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}