{
  "module_name": "Makefile",
  "hash_id": "d4e4b1d8b5d1ad864dc42472829916c0b59f453f39aa1f66a4c5dcb9fea29467",
  "original_prompt": "Ingested from linux-6.6.14/drivers/hid/bpf/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for HID-BPF\n#\n\nLIBBPF_INCLUDE = $(srctree)/tools/lib\n\nobj-$(CONFIG_HID_BPF) += hid_bpf.o\nCFLAGS_hid_bpf_dispatch.o += -I$(LIBBPF_INCLUDE)\nCFLAGS_hid_bpf_jmp_table.o += -I$(LIBBPF_INCLUDE)\nhid_bpf-objs += hid_bpf_dispatch.o hid_bpf_jmp_table.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}