#ifndef __ARC_ASM_CACHECTL_H
#define __ARC_ASM_CACHECTL_H
#define CF_I_INV	0x0002
#define CF_D_FLUSH	0x0010
#define CF_D_FLUSH_INV	0x0020
#define CF_DEFAULT	(CF_I_INV | CF_D_FLUSH)
#define ICACHE	CF_I_INV
#define DCACHE	CF_D_FLUSH
#define BCACHE	(CF_I_INV | CF_D_FLUSH)
#endif
