{
  "module_name": "Makefile",
  "hash_id": "9b7f5707701fd4126f23c8929d0bb4cf7f0ddb00c18dc4567f22f402b1565a1c",
  "original_prompt": "Ingested from linux-6.6.14/drivers/infiniband/sw/rdmavt/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# rdmavt driver\n#\n#\n#\n# Called from the kernel module build system.\n#\nobj-$(CONFIG_INFINIBAND_RDMAVT) += rdmavt.o\n\nrdmavt-y := vt.o ah.o cq.o mad.o mcast.o mmap.o mr.o pd.o qp.o \\\n\trc.o srq.o trace.o\n\nCFLAGS_trace.o = -I$(src)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}