{
  "module_name": "Makefile",
  "hash_id": "50cbcb0c0775e162672e7c68e7e00c34a436c3dee469b99389ef598a93cd8342",
  "original_prompt": "Ingested from linux-6.6.14/drivers/crypto/allwinner/sun8i-ss/Makefile",
  "human_readable_source": "obj-$(CONFIG_CRYPTO_DEV_SUN8I_SS) += sun8i-ss.o\nsun8i-ss-y += sun8i-ss-core.o sun8i-ss-cipher.o\nsun8i-ss-$(CONFIG_CRYPTO_DEV_SUN8I_SS_PRNG) += sun8i-ss-prng.o\nsun8i-ss-$(CONFIG_CRYPTO_DEV_SUN8I_SS_HASH) += sun8i-ss-hash.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}