{
  "module_name": "Kbuild",
  "hash_id": "7f798a9dee418ae8169e28cfcfd4646cfdbf265e74907ce99191c1029a5cc1c0",
  "original_prompt": "Ingested from linux-6.6.14/include/uapi/asm-generic/Kbuild",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Headers that are mandatory in usr/include/asm/\n# (This file is not included when SRCARCH=um since UML does not support UAPI.)\n\nmandatory-y += auxvec.h\nmandatory-y += bitsperlong.h\nmandatory-y += bpf_perf_event.h\nmandatory-y += byteorder.h\nmandatory-y += errno.h\nmandatory-y += fcntl.h\nmandatory-y += ioctl.h\nmandatory-y += ioctls.h\nmandatory-y += ipcbuf.h\nmandatory-y += mman.h\nmandatory-y += msgbuf.h\nmandatory-y += param.h\nmandatory-y += poll.h\nmandatory-y += posix_types.h\nmandatory-y += ptrace.h\nmandatory-y += resource.h\nmandatory-y += sembuf.h\nmandatory-y += setup.h\nmandatory-y += shmbuf.h\nmandatory-y += sigcontext.h\nmandatory-y += siginfo.h\nmandatory-y += signal.h\nmandatory-y += socket.h\nmandatory-y += sockios.h\nmandatory-y += stat.h\nmandatory-y += statfs.h\nmandatory-y += swab.h\nmandatory-y += termbits.h\nmandatory-y += termios.h\nmandatory-y += types.h\nmandatory-y += unistd.h\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}