{
  "module_name": "Makefile",
  "hash_id": "f417fefa19380cd9060cecf85f8410e125bc8f5a8551bb928271457bae9d6f00",
  "original_prompt": "Ingested from linux-6.6.14/lib/zlib_dfltcc/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# This is a modified version of zlib, which does all memory\n# allocation ahead of time.\n#\n# This is the code for s390 zlib hardware support.\n#\n\nobj-$(CONFIG_ZLIB_DFLTCC) += zlib_dfltcc.o\n\nzlib_dfltcc-objs := dfltcc.o dfltcc_deflate.o dfltcc_inflate.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}