{
  "module_name": "Makefile",
  "hash_id": "27611c61c1bd5ba59a22c73380e12fd35e74ccf364e16947cdb9f5e60f7a425a",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/cec/platform/tegra/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_CEC_TEGRA)\t+= tegra_cec.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}