{
  "module_name": "Makefile",
  "hash_id": "d00b8617240ce7bda095637f02d58871f423212e0d796b6decd6adbe4bab301a",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/filesystems/fat/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\nTEST_PROGS := run_fat_tests.sh\nTEST_GEN_PROGS_EXTENDED := rename_exchange\nCFLAGS += -O2 -g -Wall $(KHDR_INCLUDES)\n\ninclude ../../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}