{
  "module_name": "Makefile",
  "hash_id": "8efac5e2f8a913e5ece10bcf32ff5e3aef34ae4cd10f10686c3e1bc1bca62e7d",
  "original_prompt": "Ingested from linux-6.6.14/net/openvswitch/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for Open vSwitch.\n#\n\nobj-$(CONFIG_OPENVSWITCH) += openvswitch.o\n\nopenvswitch-y := \\\n\tactions.o \\\n\tdatapath.o \\\n\tdp_notify.o \\\n\tflow.o \\\n\tflow_netlink.o \\\n\tflow_table.o \\\n\tmeter.o \\\n\topenvswitch_trace.o \\\n\tvport.o \\\n\tvport-internal_dev.o \\\n\tvport-netdev.o\n\nifneq ($(CONFIG_NF_CONNTRACK),)\nopenvswitch-y += conntrack.o\nendif\n\nobj-$(CONFIG_OPENVSWITCH_VXLAN)+= vport-vxlan.o\nobj-$(CONFIG_OPENVSWITCH_GENEVE)+= vport-geneve.o\nobj-$(CONFIG_OPENVSWITCH_GRE)\t+= vport-gre.o\n\nCFLAGS_openvswitch_trace.o = -I$(src)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}