{
  "module_name": "Makefile",
  "hash_id": "93c46ecbed8dc20ab4b85ddcf91fd26c1d64669f190a72cf549b8670b0c9c6d0",
  "original_prompt": "Ingested from linux-6.6.14/drivers/mtd/spi-nor/controllers/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_SPI_HISI_SFC)\t+= hisi-sfc.o\nobj-$(CONFIG_SPI_NXP_SPIFI)\t+= nxp-spifi.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}