{
  "module_name": "Makefile",
  "hash_id": "6c039d93b89160708256126b2609e845158c1779f5a3d42843d95674d993509f",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/bridge/imx/Makefile",
  "human_readable_source": "obj-$(CONFIG_DRM_IMX_LDB_HELPER) += imx-ldb-helper.o\nobj-$(CONFIG_DRM_IMX8QM_LDB) += imx8qm-ldb.o\nobj-$(CONFIG_DRM_IMX8QXP_LDB) += imx8qxp-ldb.o\nobj-$(CONFIG_DRM_IMX8QXP_PIXEL_COMBINER) += imx8qxp-pixel-combiner.o\nobj-$(CONFIG_DRM_IMX8QXP_PIXEL_LINK) += imx8qxp-pixel-link.o\nobj-$(CONFIG_DRM_IMX8QXP_PIXEL_LINK_TO_DPI) += imx8qxp-pxl2dpi.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}