{
  "module_name": "Makefile",
  "hash_id": "46717dbb06d40f4a05114fd3f490f2480f2a818aa784e37600a85c537cf6ce93",
  "original_prompt": "Ingested from linux-6.6.14/drivers/nubus/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the nubus specific drivers.\n#\n\nobj-y := nubus.o bus.o\n\nobj-$(CONFIG_PROC_FS) += proc.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}