{
  "module_name": "Makefile",
  "hash_id": "8300cc78c90d25ea86d747c4ca2e2ec76f4f50d359cda5112a21b262b2796857",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/ti/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_WLCORE)\t\t\t+= wlcore/\nobj-$(CONFIG_WL12XX)\t\t\t+= wl12xx/\nobj-$(CONFIG_WL1251)\t\t\t+= wl1251/\nobj-$(CONFIG_WL18XX)\t\t\t+= wl18xx/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}