{
  "module_name": "Makefile",
  "hash_id": "9338ebbd22994d929243c431803b81fe62ba6881d11819e62c2cee4a9d10156c",
  "original_prompt": "Ingested from linux-6.6.14/tools/arch/x86/intel_sdsi/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for Intel Software Defined Silicon provisioning tool\n\nintel_sdsi: intel_sdsi.c\n\nCFLAGS = -Wextra\n\nBINDIR ?= /usr/sbin\n\noverride CFLAGS += -O2 -Wall\n\n%: %.c\n\t$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)\n\n.PHONY : clean\nclean :\n\t@rm -f intel_sdsi\n\ninstall : intel_sdsi\n\tinstall -d  $(DESTDIR)$(BINDIR)\n\tinstall -m 755 -p intel_sdsi $(DESTDIR)$(BINDIR)/intel_sdsi\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}