{
  "module_name": "Makefile",
  "hash_id": "178a076325abd1acdb40419a58ba384568c9db64496b3c7bfd869413bf90111a",
  "original_prompt": "Ingested from linux-6.6.14/drivers/virt/nitro_enclaves/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.\n\n# Enclave lifetime management support for Nitro Enclaves (NE).\n\nobj-$(CONFIG_NITRO_ENCLAVES) += nitro_enclaves.o\n\nnitro_enclaves-y := ne_pci_dev.o ne_misc_dev.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}