{
  "module_name": "Makefile",
  "hash_id": "39485f9ccd5394702c9c1cbbe2e25815fbd212fdb4ac5d2d746c9141d0ec2167",
  "original_prompt": "Ingested from linux-6.6.14/drivers/ntb/hw/idt/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_NTB_IDT) += ntb_hw_idt.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}