#ifndef _SMU7_DYN_DEFAULTS_H
#define _SMU7_DYN_DEFAULTS_H
#define SMU7_VOTINGRIGHTSCLIENTS_DFLT0              0x3FFFC102
#define SMU7_VOTINGRIGHTSCLIENTS_DFLT1              0x000400
#define SMU7_VOTINGRIGHTSCLIENTS_DFLT2              0xC00080
#define SMU7_VOTINGRIGHTSCLIENTS_DFLT3              0xC00200
#define SMU7_VOTINGRIGHTSCLIENTS_DFLT4              0xC01680
#define SMU7_VOTINGRIGHTSCLIENTS_DFLT5              0xC00033
#define SMU7_VOTINGRIGHTSCLIENTS_DFLT6              0xC00033
#define SMU7_VOTINGRIGHTSCLIENTS_DFLT7              0x3FFFC000
#define SMU7_THERMALPROTECTCOUNTER_DFLT            0x200
#define SMU7_STATICSCREENTHRESHOLDUNIT_DFLT        0
#define SMU7_STATICSCREENTHRESHOLD_DFLT            0x00C8
#define SMU7_GFXIDLECLOCKSTOPTHRESHOLD_DFLT        0x200
#define SMU7_REFERENCEDIVIDER_DFLT                  4
#define SMU7_ULVVOLTAGECHANGEDELAY_DFLT             1687
#define SMU7_CGULVPARAMETER_DFLT                    0x00040035
#define SMU7_CGULVCONTROL_DFLT                      0x00007450
#define SMU7_TARGETACTIVITY_DFLT                     50
#define SMU7_MCLK_TARGETACTIVITY_DFLT                10
#define SMU7_SCLK_TARGETACTIVITY_DFLT                30
#endif
