{
  "module_name": "Makefile",
  "hash_id": "3b0f1c29e5a1b25bb4e3a5fee8c13b391252f37d74747d6841db0a15a1410d70",
  "original_prompt": "Ingested from linux-6.6.14/fs/efivarfs/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the efivarfs filesystem\n#\n\nobj-$(CONFIG_EFIVAR_FS)\t\t+= efivarfs.o\n\nefivarfs-objs\t\t\t:= inode.o file.o super.o vars.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}