{
  "module_name": "Makefile",
  "hash_id": "aa5ea1023d0527febd859f2b86055e02d9a1b2c2cb4f7bb3a6e4fa334159d602",
  "original_prompt": "Ingested from linux-6.6.14/drivers/iio/multiplexer/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for industrial I/O multiplexer drivers\n#\n\n# When adding new entries keep the list in alphabetical order\nobj-$(CONFIG_IIO_MUX) += iio-mux.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}