{
  "module_name": "Makefile",
  "hash_id": "d869b213d8fa004b93da70314ba02e2a40a635326de3f88b4f854c2946ff25ec",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/nvdimm/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nKDIR ?= ../../../\n\ndefault:\n\t$(MAKE) -C $(KDIR) M=$$PWD\n\ninstall: default\n\t$(MAKE) -C $(KDIR) M=$$PWD modules_install\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}