{
  "module_name": "Makefile",
  "hash_id": "1292149d88dce6d67f61f30385e64bace35b154fb8cfbab4207cb11e5764e58a",
  "original_prompt": "Ingested from linux-6.6.14/drivers/firmware/xilinx/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for Xilinx firmwares\n\nobj-$(CONFIG_ZYNQMP_FIRMWARE) += zynqmp.o\nobj-$(CONFIG_ZYNQMP_FIRMWARE_DEBUG) += zynqmp-debug.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}