{
  "module_name": "Makefile",
  "hash_id": "7b4869a8de9577ed842cbcb80d03b82ceb79f36fe19de265f21ac6b1a4c95f8d",
  "original_prompt": "Ingested from linux-6.6.14/drivers/virt/acrn/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_ACRN_HSM)\t:= acrn.o\nacrn-y := hsm.o vm.o mm.o ioreq.o ioeventfd.o irqfd.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}