{
  "module_name": "Makefile",
  "hash_id": "80c1cecf8ebc0c3d7b616c738952ccd73e9a3c8c388919747b3e7148167a957c",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/dvb-core/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the kernel DVB device drivers.\n#\n\ndvb-net-$(CONFIG_DVB_NET) := dvb_net.o\ndvb-vb2-$(CONFIG_DVB_MMAP) := dvb_vb2.o\n\ndvb-core-objs := dvbdev.o dmxdev.o dvb_demux.o\t\t\t\\\n\t\t dvb_ca_en50221.o dvb_frontend.o\t\t\\\n\t\t $(dvb-net-y) dvb_ringbuffer.o $(dvb-vb2-y)\n\nobj-$(CONFIG_DVB_CORE) += dvb-core.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}