 
 

#ifndef QCOM_PHY_QMP_PCS_PCIE_V6_H_
#define QCOM_PHY_QMP_PCS_PCIE_V6_H_

 
#define QPHY_PCIE_V6_PCS_PCIE_POWER_STATE_CONFIG2	0x0c
#define QPHY_PCIE_V6_PCS_PCIE_POWER_STATE_CONFIG4	0x14
#define QPHY_PCIE_V6_PCS_PCIE_ENDPOINT_REFCLK_DRIVE	0x20
#define QPHY_PCIE_V6_PCS_PCIE_OSC_DTCT_ACTIONS		0x94

#endif
