{
  "module_name": "Makefile",
  "hash_id": "9768a98cda10a01139b0d4e97711478a7f4acdc50eee491267412f302ba4a192",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/usb/gspca/stv06xx/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_USB_STV06XX) += gspca_stv06xx.o\n\ngspca_stv06xx-objs := stv06xx.o \\\n\t\t      stv06xx_vv6410.o \\\n\t\t      stv06xx_hdcs.o \\\n\t\t      stv06xx_pb0100.o \\\n\t\t      stv06xx_st6422.o\n\nccflags-y += -I$(srctree)/drivers/media/usb/gspca\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}