{
  "module_name": "Makefile",
  "hash_id": "0be784c1e0240d7ae041c3b5417dfdd61f42793f090f7c6492ba22d75ce8ade1",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/platform/ti/omap/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the omap video device drivers.\n#\n\n# OMAP2/3 Display driver\nomap-vout-y += omap_vout.o omap_voutlib.o\nomap-vout-$(CONFIG_VIDEO_OMAP2_VOUT_VRFB) += omap_vout_vrfb.o\nobj-$(CONFIG_VIDEO_OMAP2_VOUT) += omap-vout.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}