{
  "module_name": "Makefile",
  "hash_id": "32708a5320edf4a76e0e219ffea2f31cdf8ec3c45727b4ad422a9151bacc1742",
  "original_prompt": "Ingested from linux-6.6.14/drivers/soc/pxa/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n\nobj-$(CONFIG_PXA3xx)\t\t+= mfp.o\nobj-$(CONFIG_ARCH_MMP)\t\t+= mfp.o\n\nobj-$(CONFIG_PXA_SSP)\t\t+= ssp.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}