




intel-wmi-sbl-fw-update-y				:= sbl-fw-update.o
obj-$(CONFIG_INTEL_WMI_SBL_FW_UPDATE)	+= intel-wmi-sbl-fw-update.o
intel-wmi-thunderbolt-y					:= thunderbolt.o
obj-$(CONFIG_INTEL_WMI_THUNDERBOLT)	+= intel-wmi-thunderbolt.o
