{
  "module_name": "Makefile",
  "hash_id": "612db019f2e508e6a8e528c6667ffdfbb659c3d623a8c519c7ea1cb582eb11a1",
  "original_prompt": "Ingested from linux-6.6.14/drivers/crypto/inside-secure/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_CRYPTO_DEV_SAFEXCEL) += crypto_safexcel.o\ncrypto_safexcel-objs := safexcel.o safexcel_ring.o safexcel_cipher.o safexcel_hash.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}