#ifndef _UAPI_ASM_M68K_BOOTINFO_ATARI_H
#define _UAPI_ASM_M68K_BOOTINFO_ATARI_H
#define BI_ATARI_MCH_COOKIE	0x8000	 
#define BI_ATARI_MCH_TYPE	0x8001	 
#define ATARI_MCH_ST		0
#define ATARI_MCH_STE		1
#define ATARI_MCH_TT		2
#define ATARI_MCH_FALCON	3
#define ATARI_MACH_NORMAL	0	 
#define ATARI_MACH_MEDUSA	1	 
#define ATARI_MACH_HADES	2	 
#define ATARI_MACH_AB40		3	 
#define ATARI_BOOTI_VERSION	MK_BI_VERSION(2, 1)
#endif  
