{
  "module_name": "Makefile",
  "hash_id": "303edc295102fef5994fb315e8c2c4865e149127738e3f7c4f36f97a00c9c032",
  "original_prompt": "Ingested from linux-6.6.14/tools/perf/arch/arm64/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nifndef NO_DWARF\nPERF_HAVE_DWARF_REGS := 1\nendif\nPERF_HAVE_JITDUMP := 1\nPERF_HAVE_ARCH_REGS_QUERY_REGISTER_OFFSET := 1\nHAVE_KVM_STAT_SUPPORT := 1\n\n#\n# Syscall table generation for perf\n#\n\nout    := $(OUTPUT)arch/arm64/include/generated/asm\nheader := $(out)/syscalls.c\nincpath := $(srctree)/tools\nsysdef := $(srctree)/tools/arch/arm64/include/uapi/asm/unistd.h\nsysprf := $(srctree)/tools/perf/arch/arm64/entry/syscalls/\nsystbl := $(sysprf)/mksyscalltbl\n\n# Create output directory if not already present\n_dummy := $(shell [ -d '$(out)' ] || mkdir -p '$(out)')\n\n$(header): $(sysdef) $(systbl)\n\t$(Q)$(SHELL) '$(systbl)' '$(CC)' '$(HOSTCC)' $(incpath) $(sysdef) > $@\n\nclean::\n\t$(call QUIET_CLEAN, arm64) $(RM) $(header)\n\narchheaders: $(header)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}