{
  "module_name": "Makefile",
  "hash_id": "859f1b94d979a945b01f9138a43c7ad6664f6402bff2e1afeffa9a2d5bee9fa0",
  "original_prompt": "Ingested from linux-6.6.14/sound/isa/msnd/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\nsnd-msnd-lib-objs := msnd.o msnd_midi.o msnd_pinnacle_mixer.o\nsnd-msnd-pinnacle-objs := msnd_pinnacle.o\nsnd-msnd-classic-objs := msnd_classic.o\n\n# Toplevel Module Dependency\nobj-$(CONFIG_SND_MSND_PINNACLE) += snd-msnd-pinnacle.o snd-msnd-lib.o\nobj-$(CONFIG_SND_MSND_CLASSIC) += snd-msnd-classic.o snd-msnd-lib.o\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}