{
  "module_name": "Makefile",
  "hash_id": "4ebf6d9d95c7568d4449e9715edc7f895fba113d2739a197709d0bdc5cffffdb",
  "original_prompt": "Ingested from linux-6.6.14/tools/tracing/latency/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for vm tools\n#\nVAR_CFLAGS := $(shell pkg-config --cflags libtracefs 2>/dev/null)\nVAR_LDLIBS := $(shell pkg-config --libs libtracefs 2>/dev/null)\n\nTARGETS = latency-collector\nCFLAGS = -Wall -Wextra -g -O2 $(VAR_CFLAGS)\nLDFLAGS = -lpthread $(VAR_LDLIBS)\n\nall: $(TARGETS)\n\n%: %.c\n\t$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)\n\nclean:\n\t$(RM) latency-collector\n\nprefix ?= /usr/local\nsbindir ?= ${prefix}/sbin\n\ninstall: all\n\tinstall -d $(DESTDIR)$(sbindir)\n\tinstall -m 755 -p $(TARGETS) $(DESTDIR)$(sbindir)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}