 

#include <linux/init.h>
#include <linux/platform_device.h>
#include <linux/of.h>
#include <linux/pinctrl/pinctrl.h>

#include "pinctrl-sunxi.h"

static const struct sunxi_desc_pin sun4i_a10_pins[] = {
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "spi1"),		 
		  SUNXI_FUNCTION(0x4, "uart2"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "spi1"),		 
		  SUNXI_FUNCTION(0x4, "uart2"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "spi1"),		 
		  SUNXI_FUNCTION(0x4, "uart2"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "spi1"),		 
		  SUNXI_FUNCTION(0x4, "uart2"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "spi1"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "spi3"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "spi3"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 7),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "spi3"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 8),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "spi3"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 9),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "spi3"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION_VARIANT(0x6, "i2s1",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 11),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 12),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "uart6"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 13),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "uart6"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 14),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "uart7"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION_VARIANT(0x6, "i2s1",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 15),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "uart7"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION_VARIANT(0x6, "i2s1",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 16),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "can"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION_VARIANT(0x6, "i2s1",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 17),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "emac"),		 
		  SUNXI_FUNCTION(0x3, "can"),		 
		  SUNXI_FUNCTION(0x4, "uart1"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "gmac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION_VARIANT(0x6, "i2s1",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c0"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pll_lock_dbg",
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION_VARIANT(0x2, "pwm",	 
					 PINCTRL_SUN4I_A10 |
					 PINCTRL_SUN7I_A20),
		  SUNXI_FUNCTION_VARIANT(0x3, "pwm",	 
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION_VARIANT(0x2, "ir0",	 
					 PINCTRL_SUN4I_A10 |
					 PINCTRL_SUN7I_A20),
		  SUNXI_FUNCTION_VARIANT(0x3, "pwm",	 
					 PINCTRL_SUN8I_R40),
		 
		  SUNXI_FUNCTION(0x4, "spdif")),         
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ir0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		   
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s0",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x3, "ac97")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s0",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x3, "ac97")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 7),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s0",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x3, "ac97")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 8),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s0",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x3, "ac97")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 9),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s0",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION_VARIANT(0x4, "pwm",	 
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s0",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION_VARIANT(0x4, "pwm",	 
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 11),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s0",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 12),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x2, "i2s0",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x3, "ac97"),		 
		 
		  SUNXI_FUNCTION_VARIANT(0x4, "spdif",	 
					 PINCTRL_SUN4I_A10 |
					 PINCTRL_SUN7I_A20)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 13),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi2"),		 
		 
		  SUNXI_FUNCTION(0x4, "spdif")),         
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 14),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi2"),		 
		  SUNXI_FUNCTION(0x3, "jtag")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 15),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi2"),		 
		  SUNXI_FUNCTION(0x3, "jtag")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 16),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi2"),		 
		  SUNXI_FUNCTION(0x3, "jtag")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 17),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi2"),		 
		  SUNXI_FUNCTION(0x3, "jtag")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 18),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 19),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 20),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c2"),		 
		  SUNXI_FUNCTION_VARIANT(0x4, "pwm",	 
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 21),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c2"),		 
		  SUNXI_FUNCTION_VARIANT(0x4, "pwm",	 
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 22),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "uart0"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "ir1",	 
					 PINCTRL_SUN4I_A10 |
					 PINCTRL_SUN7I_A20)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 23),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "uart0"),		 
		  SUNXI_FUNCTION(0x3, "ir1")),		 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "spi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "spi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "spi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "mmc2",	 
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 7),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 8),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 9),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 11),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 12),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "mmc2",	 
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 13),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "mmc2",	 
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 14),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "mmc2",	 
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 15),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "mmc2",	 
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 16),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 17),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 18),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 19),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "spi2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 20),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "spi2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 21),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "spi2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 22),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "spi2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 23),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x3, "spi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 24),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "mmc2",	 
					 PINCTRL_SUN8I_R40)),
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 7),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 8),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 9),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds1")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 11),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds1")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 12),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds1")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 13),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds1")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 14),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds1")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 15),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds1")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 16),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds1")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 17),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds1")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 18),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds1")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 19),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "lvds1")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 20),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 21),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "sim")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 22),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "sim")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 23),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "sim")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 24),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "sim")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 25),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "sim")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 26),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "sim")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 27),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "sim")),		 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0"),		 
		  SUNXI_FUNCTION(0x4, "sim")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 7),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 8),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 9),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 11),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts0"),		 
		  SUNXI_FUNCTION(0x3, "csi0")),		 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x4, "jtag")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x4, "jtag")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x4, "uart0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x4, "jtag")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x4, "uart0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x4, "jtag")),		 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts1"),		 
		  SUNXI_FUNCTION(0x3, "csi1"),		 
		  SUNXI_FUNCTION(0x4, "mmc1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts1"),		 
		  SUNXI_FUNCTION(0x3, "csi1"),		 
		  SUNXI_FUNCTION(0x4, "mmc1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts1"),		 
		  SUNXI_FUNCTION(0x3, "csi1"),		 
		  SUNXI_FUNCTION(0x4, "mmc1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts1"),		 
		  SUNXI_FUNCTION(0x3, "csi1"),		 
		  SUNXI_FUNCTION(0x4, "mmc1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts1"),		 
		  SUNXI_FUNCTION(0x3, "csi1"),		 
		  SUNXI_FUNCTION(0x4, "mmc1"),		 
		  SUNXI_FUNCTION(0x5, "csi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts1"),		 
		  SUNXI_FUNCTION(0x3, "csi1"),		 
		  SUNXI_FUNCTION(0x4, "mmc1"),		 
		  SUNXI_FUNCTION(0x5, "csi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts1"),		 
		  SUNXI_FUNCTION(0x3, "csi1"),		 
		  SUNXI_FUNCTION(0x4, "uart3"),		 
		  SUNXI_FUNCTION(0x5, "csi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 7),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts1"),		 
		  SUNXI_FUNCTION(0x3, "csi1"),		 
		  SUNXI_FUNCTION(0x4, "uart3"),		 
		  SUNXI_FUNCTION(0x5, "csi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 8),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts1"),		 
		  SUNXI_FUNCTION(0x3, "csi1"),		 
		  SUNXI_FUNCTION(0x4, "uart3"),		 
		  SUNXI_FUNCTION(0x5, "csi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 9),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts1"),		 
		  SUNXI_FUNCTION(0x3, "csi1"),		 
		  SUNXI_FUNCTION(0x4, "uart3"),		 
		  SUNXI_FUNCTION(0x5, "csi0"),		 
		  SUNXI_FUNCTION_VARIANT(0x6, "bist",	 
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts1"),		 
		  SUNXI_FUNCTION(0x3, "csi1"),		 
		  SUNXI_FUNCTION(0x4, "uart4"),		 
		  SUNXI_FUNCTION(0x5, "csi0"),		 
		  SUNXI_FUNCTION_VARIANT(0x6, "bist",	 
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 11),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ts1"),		 
		  SUNXI_FUNCTION(0x3, "csi1"),		 
		  SUNXI_FUNCTION(0x4, "uart4"),		 
		  SUNXI_FUNCTION(0x5, "csi0")),		 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION(0x4, "uart3"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 0),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION(0x4, "uart3"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 1),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION(0x4, "uart3"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 2),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION(0x4, "uart3"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 3),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION(0x4, "uart4"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 4),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION(0x4, "uart4"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 5),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION(0x4, "uart5"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "ms",	 
					 PINCTRL_SUN4I_A10 |
					 PINCTRL_SUN7I_A20),
		  SUNXI_FUNCTION_IRQ(0x6, 6),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 7),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION(0x4, "uart5"),		 
		  SUNXI_FUNCTION_VARIANT(0x5, "ms",	 
					 PINCTRL_SUN4I_A10 |
					 PINCTRL_SUN7I_A20),
		  SUNXI_FUNCTION_IRQ(0x6, 7),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 8),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION_VARIANT(0x5, "ms",	 
					 PINCTRL_SUN4I_A10 |
					 PINCTRL_SUN7I_A20),
		  SUNXI_FUNCTION_IRQ(0x6, 8),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 9),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION_VARIANT(0x5, "ms",	 
					 PINCTRL_SUN4I_A10 |
					 PINCTRL_SUN7I_A20),
		  SUNXI_FUNCTION_IRQ(0x6, 9),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION_VARIANT(0x5, "ms",	 
					 PINCTRL_SUN4I_A10 |
					 PINCTRL_SUN7I_A20),
		  SUNXI_FUNCTION_IRQ(0x6, 10),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 11),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION_VARIANT(0x5, "ms",	 
					 PINCTRL_SUN4I_A10 |
					 PINCTRL_SUN7I_A20),
		  SUNXI_FUNCTION_IRQ(0x6, 11),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 12),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION(0x4, "ps2"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 12),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 13),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION(0x4, "ps2"),		 
		  SUNXI_FUNCTION(0x5, "sim"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 13),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 14),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION(0x5, "sim"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 14),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 15),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION(0x5, "sim"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 15),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 16),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION(0x5, "sim"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 16),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 17),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION(0x5, "sim"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 17),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 18),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION(0x5, "sim"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 18),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 19),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION(0x5, "sim"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 19),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 20),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "can"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 20),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 21),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "can"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 21),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 22),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION(0x5, "mmc1"),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 23),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION(0x5, "mmc1"),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 24),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION(0x5, "mmc1"),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 25),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION(0x5, "mmc1"),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 26),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION(0x5, "mmc1"),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 27),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd1"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "pata",	 
					 PINCTRL_SUN4I_A10),
		  SUNXI_FUNCTION_VARIANT(0x3, "emac",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION(0x4, "keypad"),	 
		  SUNXI_FUNCTION(0x5, "mmc1"),		 
		  SUNXI_FUNCTION(0x7, "csi1")),		 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION_VARIANT(0x3, "i2c3",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION_VARIANT(0x3, "i2c3",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION_VARIANT(0x3, "i2c4",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "pwm"),		 
		  SUNXI_FUNCTION_VARIANT(0x3, "i2c4",	 
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc3")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc3")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc3")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 7),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc3")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 8),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc3")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 9),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc3")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi0"),		 
		  SUNXI_FUNCTION(0x3, "uart5"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 22)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 11),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi0"),		 
		  SUNXI_FUNCTION(0x3, "uart5"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 23)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 12),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi0"),		 
		  SUNXI_FUNCTION(0x3, "uart6"),		 
		  SUNXI_FUNCTION_VARIANT(0x4, "clk_out_a",
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION_IRQ(0x6, 24)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 13),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi0"),		 
		  SUNXI_FUNCTION(0x3, "uart6"),		 
		  SUNXI_FUNCTION_VARIANT(0x4, "clk_out_b",
					 PINCTRL_SUN7I_A20 |
					 PINCTRL_SUN8I_R40),
		  SUNXI_FUNCTION_IRQ(0x6, 25)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 14),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi0"),		 
		  SUNXI_FUNCTION(0x3, "ps2"),		 
		  SUNXI_FUNCTION(0x4, "timer4"),	 
		  SUNXI_FUNCTION_IRQ(0x6, 26)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 15),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi1"),		 
		  SUNXI_FUNCTION(0x3, "ps2"),		 
		  SUNXI_FUNCTION(0x4, "timer5"),	 
		  SUNXI_FUNCTION_IRQ(0x6, 27)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 16),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi1"),		 
		  SUNXI_FUNCTION(0x3, "uart2"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 28)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 17),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi1"),		 
		  SUNXI_FUNCTION(0x3, "uart2"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 29)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 18),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi1"),		 
		  SUNXI_FUNCTION(0x3, "uart2"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 30)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 19),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi1"),		 
		  SUNXI_FUNCTION(0x3, "uart2"),		 
		  SUNXI_FUNCTION_IRQ(0x6, 31)),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 20),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ps2"),		 
		  SUNXI_FUNCTION(0x3, "uart7"),		 
		  SUNXI_FUNCTION_VARIANT(0x4, "hdmi",	 
					 PINCTRL_SUN4I_A10 |
					 PINCTRL_SUN7I_A20),
		  SUNXI_FUNCTION_VARIANT(0x6, "pwm",	 
					 PINCTRL_SUN8I_R40)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 21),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ps2"),		 
		  SUNXI_FUNCTION(0x3, "uart7"),		 
		  SUNXI_FUNCTION_VARIANT(0x4, "hdmi",	 
					 PINCTRL_SUN4I_A10 |
					 PINCTRL_SUN7I_A20),
		  SUNXI_FUNCTION_VARIANT(0x6, "pwm",	 
					 PINCTRL_SUN8I_R40)),
};

static const struct sunxi_pinctrl_desc sun4i_a10_pinctrl_data = {
	.pins = sun4i_a10_pins,
	.npins = ARRAY_SIZE(sun4i_a10_pins),
	.irq_banks = 1,
	.irq_read_needs_mux = true,
	.disable_strict_mode = true,
};

static int sun4i_a10_pinctrl_probe(struct platform_device *pdev)
{
	unsigned long variant = (unsigned long)of_device_get_match_data(&pdev->dev);

	return sunxi_pinctrl_init_with_variant(pdev, &sun4i_a10_pinctrl_data,
					       variant);
}

static const struct of_device_id sun4i_a10_pinctrl_match[] = {
	{
		.compatible = "allwinner,sun4i-a10-pinctrl",
		.data = (void *)PINCTRL_SUN4I_A10
	},
	{
		.compatible = "allwinner,sun7i-a20-pinctrl",
		.data = (void *)PINCTRL_SUN7I_A20
	},
	{
		.compatible = "allwinner,sun8i-r40-pinctrl",
		.data = (void *)PINCTRL_SUN8I_R40
	},
	{}
};

static struct platform_driver sun4i_a10_pinctrl_driver = {
	.probe	= sun4i_a10_pinctrl_probe,
	.driver	= {
		.name		= "sun4i-pinctrl",
		.of_match_table	= sun4i_a10_pinctrl_match,
	},
};
builtin_platform_driver(sun4i_a10_pinctrl_driver);
