
 

#include <linux/module.h>
#include <linux/platform_device.h>
#include <linux/of.h>
#include <linux/pinctrl/pinctrl.h>

#include "pinctrl-sunxi.h"

static const struct sunxi_desc_pin h6_pins[] = {
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 0),
		  SUNXI_FUNCTION(0x2, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 1),
		  SUNXI_FUNCTION(0x2, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 2),
		  SUNXI_FUNCTION(0x2, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 3),
		  SUNXI_FUNCTION(0x2, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 4),
		  SUNXI_FUNCTION(0x2, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 5),
		  SUNXI_FUNCTION(0x2, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 6),
		  SUNXI_FUNCTION(0x2, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 7),
		  SUNXI_FUNCTION(0x2, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 8),
		  SUNXI_FUNCTION(0x2, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 9),
		  SUNXI_FUNCTION(0x2, "emac")),		 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 0),
		  SUNXI_FUNCTION(0x2, "ccir"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 0)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 1),
		  SUNXI_FUNCTION(0x2, "ccir"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 1)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 2),
		  SUNXI_FUNCTION(0x2, "ccir"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 2)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 3),
		  SUNXI_FUNCTION(0x2, "ccir"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 3)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 4),
		  SUNXI_FUNCTION(0x2, "ccir"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 4)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 5),
		  SUNXI_FUNCTION(0x2, "ccir"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 5)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 6),
		  SUNXI_FUNCTION(0x2, "ccir"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 6)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 7),
		  SUNXI_FUNCTION(0x2, "ccir"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 7)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 8),
		  SUNXI_FUNCTION(0x2, "ccir"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 8)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 9),
		  SUNXI_FUNCTION(0x2, "ccir"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 9)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 10),
		  SUNXI_FUNCTION(0x2, "ccir"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 10)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 11),
		  SUNXI_FUNCTION(0x2, "ccir"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 11)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 12),
		  SUNXI_FUNCTION(0x2, "i2s3"),		 
		  SUNXI_FUNCTION(0x4, "h_i2s3"),	 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 12)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 13),
		  SUNXI_FUNCTION(0x2, "i2s3"),		 
		  SUNXI_FUNCTION(0x4, "h_i2s3"),	 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 13)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 14),
		  SUNXI_FUNCTION(0x2, "i2s3"),		 
		  SUNXI_FUNCTION(0x4, "h_i2s3"),	 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 14)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 15),
		  SUNXI_FUNCTION(0x2, "i2s3"),		 
		  SUNXI_FUNCTION(0x4, "h_i2s3"),	 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 15)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 16),
		  SUNXI_FUNCTION(0x2, "i2s3"),		 
		  SUNXI_FUNCTION(0x4, "h_i2s3"),	 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 16)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 17),
		  SUNXI_FUNCTION(0x2, "i2c3"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 17)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 18),
		  SUNXI_FUNCTION(0x2, "i2c3"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 18)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 19),
		  SUNXI_FUNCTION(0x2, "pwm1"),
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 19)),
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 20),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 0, 20)),
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x4, "spi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x4, "spi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x4, "spi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2"),		 
		  SUNXI_FUNCTION(0x4, "spi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2"),		 
		  SUNXI_FUNCTION(0x4, "spi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 7),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2"),		 
		  SUNXI_FUNCTION(0x4, "spi0")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 8),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 9),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 11),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 12),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 13),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 14),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0"),		 
		  SUNXI_FUNCTION(0x3, "mmc2")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 15),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 16),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "nand0")),	 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "csi"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "csi"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "csi"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "csi"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "csi"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "csi"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "csi"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 7),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "csi"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 8),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "csi"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 9),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "csi"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "csi"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 11),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts0"),		 
		  SUNXI_FUNCTION(0x4, "csi"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 12),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts1"),		 
		  SUNXI_FUNCTION(0x4, "csi"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 13),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts1"),		 
		  SUNXI_FUNCTION(0x4, "csi"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 14),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts1"),		 
		  SUNXI_FUNCTION(0x4, "dmic"),		 
		  SUNXI_FUNCTION(0x5, "csi")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 15),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts1"),		 
		  SUNXI_FUNCTION(0x4, "dmic"),		 
		  SUNXI_FUNCTION(0x5, "csi")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 16),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts1"),		 
		  SUNXI_FUNCTION(0x4, "dmic")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 17),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts2"),		 
		  SUNXI_FUNCTION(0x4, "dmic")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 18),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts2"),		 
		  SUNXI_FUNCTION(0x4, "dmic")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 19),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts2"),		 
		  SUNXI_FUNCTION(0x4, "uart2"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 20),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts2"),		 
		  SUNXI_FUNCTION(0x4, "uart2"),		 
		  SUNXI_FUNCTION(0x5, "emac")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 21),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "lcd0"),		 
		  SUNXI_FUNCTION(0x3, "ts2"),		 
		  SUNXI_FUNCTION(0x4, "uart2")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 22),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "pwm"),		 
		  SUNXI_FUNCTION(0x3, "ts3"),		 
		  SUNXI_FUNCTION(0x4, "uart2")),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 23),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c2"),		 
		  SUNXI_FUNCTION(0x3, "ts3"),		 
		  SUNXI_FUNCTION(0x4, "uart3"),		 
		  SUNXI_FUNCTION(0x5, "jtag")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 24),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c2"),		 
		  SUNXI_FUNCTION(0x3, "ts3"),		 
		  SUNXI_FUNCTION(0x4, "uart3"),		 
		  SUNXI_FUNCTION(0x5, "jtag")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 25),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c0"),		 
		  SUNXI_FUNCTION(0x3, "ts3"),		 
		  SUNXI_FUNCTION(0x4, "uart3"),		 
		  SUNXI_FUNCTION(0x5, "jtag")),		 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 26),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2c0"),		 
		  SUNXI_FUNCTION(0x3, "ts3"),		 
		  SUNXI_FUNCTION(0x4, "uart3"),		 
		  SUNXI_FUNCTION(0x5, "jtag")),		 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x3, "jtag"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 1, 0)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x3, "jtag"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 1, 1)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x3, "uart0"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 1, 2)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x3, "jtag"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 1, 3)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x3, "uart0"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 1, 4)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc0"),		 
		  SUNXI_FUNCTION(0x3, "jtag"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 1, 5)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 1, 6)),	 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc1"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 2, 0)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc1"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 2, 1)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc1"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 2, 2)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc1"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 2, 3)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc1"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 2, 4)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "mmc1"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 2, 5)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "uart1"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 2, 6)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 7),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "uart1"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 2, 7)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 8),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "uart1"),		 
		  SUNXI_FUNCTION(0x4, "sim0"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 2, 8)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 9),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "uart1"),		 
		  SUNXI_FUNCTION(0x4, "sim0"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 2, 9)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2s2"),		 
		  SUNXI_FUNCTION(0x3, "h_i2s2"),	 
		  SUNXI_FUNCTION(0x4, "sim0"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 2, 10)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 11),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2s2"),		 
		  SUNXI_FUNCTION(0x3, "h_i2s2"),	 
		  SUNXI_FUNCTION(0x4, "sim0"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 2, 11)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 12),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2s2"),		 
		  SUNXI_FUNCTION(0x3, "h_i2s2"),	 
		  SUNXI_FUNCTION(0x4, "sim0"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 2, 12)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 13),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2s2"),		 
		  SUNXI_FUNCTION(0x3, "h_i2s2"),	 
		  SUNXI_FUNCTION(0x4, "sim0"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 2, 13)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 14),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "i2s2"),		 
		  SUNXI_FUNCTION(0x3, "h_i2s2"),	 
		  SUNXI_FUNCTION(0x4, "sim0"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 2, 14)),	 
	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 0),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "uart0"),		 
		  SUNXI_FUNCTION(0x3, "i2s0"),		 
		  SUNXI_FUNCTION(0x4, "h_i2s0"),	 
		  SUNXI_FUNCTION(0x5, "sim1"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 3, 0)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 1),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "uart0"),		 
		  SUNXI_FUNCTION(0x3, "i2s0"),		 
		  SUNXI_FUNCTION(0x4, "h_i2s0"),	 
		  SUNXI_FUNCTION(0x5, "sim1"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 3, 1)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 2),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "ir_tx"),
		  SUNXI_FUNCTION(0x3, "i2s0"),		 
		  SUNXI_FUNCTION(0x4, "h_i2s0"),	 
		  SUNXI_FUNCTION(0x5, "sim1"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 3, 2)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 3),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi1"),		 
		  SUNXI_FUNCTION(0x3, "i2s0"),		 
		  SUNXI_FUNCTION(0x4, "h_i2s0"),	 
		  SUNXI_FUNCTION(0x5, "sim1"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 3, 3)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 4),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi1"),		 
		  SUNXI_FUNCTION(0x3, "i2s0"),		 
		  SUNXI_FUNCTION(0x4, "h_i2s0"),	 
		  SUNXI_FUNCTION(0x5, "sim1"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 3, 4)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 5),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi1"),		 
		  SUNXI_FUNCTION(0x3, "spdif"),		 
		  SUNXI_FUNCTION(0x4, "i2c1"),		 
		  SUNXI_FUNCTION(0x5, "sim1"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 3, 5)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 6),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "spi1"),		 
		  SUNXI_FUNCTION(0x3, "spdif"),		 
		  SUNXI_FUNCTION(0x4, "i2c1"),		 
		  SUNXI_FUNCTION(0x5, "sim1"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 3, 6)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 7),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x3, "spdif"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 3, 7)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 8),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "hdmi"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 3, 8)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 9),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "hdmi"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 3, 9)),	 
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 10),
		  SUNXI_FUNCTION(0x0, "gpio_in"),
		  SUNXI_FUNCTION(0x1, "gpio_out"),
		  SUNXI_FUNCTION(0x2, "hdmi"),		 
		  SUNXI_FUNCTION_IRQ_BANK(0x6, 3, 10)),	 
};

static const unsigned int h6_irq_bank_map[] = { 1, 5, 6, 7 };

static const struct sunxi_pinctrl_desc h6_pinctrl_data = {
	.pins = h6_pins,
	.npins = ARRAY_SIZE(h6_pins),
	.irq_banks = 4,
	.irq_bank_map = h6_irq_bank_map,
	.irq_read_needs_mux = true,
	.io_bias_cfg_variant = BIAS_VOLTAGE_PIO_POW_MODE_SEL,
};

static int h6_pinctrl_probe(struct platform_device *pdev)
{
	return sunxi_pinctrl_init(pdev,
				  &h6_pinctrl_data);
}

static const struct of_device_id h6_pinctrl_match[] = {
	{ .compatible = "allwinner,sun50i-h6-pinctrl", },
	{}
};

static struct platform_driver h6_pinctrl_driver = {
	.probe	= h6_pinctrl_probe,
	.driver	= {
		.name		= "sun50i-h6-pinctrl",
		.of_match_table	= h6_pinctrl_match,
	},
};
builtin_platform_driver(h6_pinctrl_driver);
