{
  "module_name": "Makefile",
  "hash_id": "2423eebe818521d88180ec1b048f8bdbffa2083cd23d2bdcef819e9d7380c697",
  "original_prompt": "Ingested from linux-6.6.14/drivers/scsi/qla4xxx/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nqla4xxx-y := ql4_os.o ql4_init.o ql4_mbx.o ql4_iocb.o ql4_isr.o \\\n\t\tql4_nx.o ql4_nvram.o ql4_dbg.o ql4_attr.o ql4_bsg.o ql4_83xx.o\n\nobj-$(CONFIG_SCSI_QLA_ISCSI) += qla4xxx.o\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}