{
  "module_name": "Makefile",
  "hash_id": "fb602223195a9d2e308ebdf9f624348c389c0f8501d388155b2904b3d2f0f3b0",
  "original_prompt": "Ingested from linux-6.6.14/net/handshake/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the Generic HANDSHAKE service\n#\n# Author: Chuck Lever <chuck.lever@oracle.com>\n#\n# Copyright (c) 2023, Oracle and/or its affiliates.\n#\n\nobj-y += handshake.o\nhandshake-y := alert.o genl.o netlink.o request.o tlshd.o trace.o\n\nobj-$(CONFIG_NET_HANDSHAKE_KUNIT_TEST) += handshake-test.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}