



#ifndef ASIC_REG_ARC_FARM_KDMA_KDMA_CGM_REGS_H_
#define ASIC_REG_ARC_FARM_KDMA_KDMA_CGM_REGS_H_



#define mmARC_FARM_KDMA_KDMA_CGM_CFG 0x4E8BE00

#define mmARC_FARM_KDMA_KDMA_CGM_STS 0x4E8BE04

#define mmARC_FARM_KDMA_KDMA_CGM_CFG1 0x4E8BE08

#endif 
