{
  "module_name": "Makefile",
  "hash_id": "49e6f7456ad6bd2bff5b5d4df65929b6e9f7857f72262e991389eed9008ba093",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/mediatek/mt8173/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# MTK Platform Support\nobj-$(CONFIG_SND_SOC_MT8173) += mt8173-afe-pcm.o\n# Machine support\nobj-$(CONFIG_SND_SOC_MT8173_MAX98090) += mt8173-max98090.o\nobj-$(CONFIG_SND_SOC_MT8173_RT5650) += mt8173-rt5650.o\nobj-$(CONFIG_SND_SOC_MT8173_RT5650_RT5514) += mt8173-rt5650-rt5514.o\nobj-$(CONFIG_SND_SOC_MT8173_RT5650_RT5676) += mt8173-rt5650-rt5676.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}