{
  "module_name": "Makefile",
  "hash_id": "75da605ac7e16d5d3c0eb090e3216f96411fef4132b294035e5922e3f24d901d",
  "original_prompt": "Ingested from linux-6.6.14/fs/devpts/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the Linux /dev/pts virtual filesystem.\n#\n\nobj-$(CONFIG_UNIX98_PTYS)\t\t+= devpts.o\n\ndevpts-$(CONFIG_UNIX98_PTYS)\t\t:= inode.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}