{
  "module_name": "Makefile",
  "hash_id": "077ec6b8245da22455f9e79d6d71eba277eb610f6317d02829aa37e9f9143886",
  "original_prompt": "Ingested from linux-6.6.14/fs/hpfs/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the Linux hpfs filesystem routines.\n#\n\nobj-$(CONFIG_HPFS_FS) += hpfs.o\n\nhpfs-objs := alloc.o anode.o buffer.o dentry.o dir.o dnode.o ea.o file.o \\\n\t     inode.o map.o name.o namei.o super.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}