{
  "module_name": "Makefile",
  "hash_id": "d78b52a5d3bbfe31d6f81529e3809c4bf1444320981c6e6c7940296c1ff92fdf",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/toshiba/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the Toshiba network device drivers.\n#\n\nobj-$(CONFIG_GELIC_NET) += ps3_gelic.o\ngelic_wireless-$(CONFIG_GELIC_WIRELESS) += ps3_gelic_wireless.o\nps3_gelic-objs += ps3_gelic_net.o $(gelic_wireless-y)\nspidernet-y += spider_net.o spider_net_ethtool.o\nobj-$(CONFIG_SPIDER_NET) += spidernet.o\nobj-$(CONFIG_TC35815) += tc35815.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}