{
  "module_name": "Makefile",
  "hash_id": "6e0b5fb6ddc0e2fab1f3c7b26409304132be3e6632de958cda2522729925a408",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/lib/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n# Makefile for lib/ function selftests\n\n# No binaries, but make sure arg-less \"make\" doesn't trigger \"run_tests\"\nall:\n\nTEST_PROGS := printf.sh bitmap.sh prime_numbers.sh scanf.sh strscpy.sh\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}