{
  "module_name": "Makefile",
  "hash_id": "3faa573f840cf057da65eaa2ed010b439b114e1a8ba118f8c64a2caa3ad2f8af",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/imx/ipuv3/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\nimxdrm-objs := imx-drm-core.o ipuv3-crtc.o ipuv3-plane.o\n\nobj-$(CONFIG_DRM_IMX) += imxdrm.o\n\nobj-$(CONFIG_DRM_IMX_PARALLEL_DISPLAY) += parallel-display.o\nobj-$(CONFIG_DRM_IMX_TVE) += imx-tve.o\nobj-$(CONFIG_DRM_IMX_LDB) += imx-ldb.o\n\nobj-$(CONFIG_DRM_IMX_HDMI) += dw_hdmi-imx.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}