{
  "module_name": "Makefile",
  "hash_id": "8c3140532eefb45a226b18eedd821a1e5de5030cf5523fedac3631bd6a4ff412",
  "original_prompt": "Ingested from linux-6.6.14/drivers/base/firmware_loader/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for the Linux firmware loader\n\nobj-$(CONFIG_FW_LOADER_USER_HELPER) += fallback_table.o\nobj-$(CONFIG_FW_LOADER)\t+= firmware_class.o\nfirmware_class-objs := main.o\nfirmware_class-$(CONFIG_FW_LOADER_USER_HELPER) += fallback.o\nfirmware_class-$(CONFIG_EFI_EMBEDDED_FIRMWARE) += fallback_platform.o\nfirmware_class-$(CONFIG_FW_LOADER_SYSFS) += sysfs.o\nfirmware_class-$(CONFIG_FW_UPLOAD) += sysfs_upload.o\n\nobj-y += builtin/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}