{
  "module_name": "Makefile",
  "hash_id": "94508e7b7468dfe066f566a4eaf16136336a5a47a9706f51247d0d19e7524b81",
  "original_prompt": "Ingested from linux-6.6.14/drivers/dma/xilinx/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_XILINX_DMA) += xilinx_dma.o\nobj-$(CONFIG_XILINX_XDMA) += xdma.o\nobj-$(CONFIG_XILINX_ZYNQMP_DMA) += zynqmp_dma.o\nobj-$(CONFIG_XILINX_ZYNQMP_DPDMA) += xilinx_dpdma.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}