{
  "module_name": "Makefile",
  "hash_id": "1e801f3dd105ebb947a360bd2b4d0ad6a32d1b1e3148f62650f38c307ead4100",
  "original_prompt": "Ingested from linux-6.6.14/drivers/reset/hisilicon/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_COMMON_RESET_HI6220) += hi6220_reset.o\nobj-$(CONFIG_COMMON_RESET_HI3660) += reset-hi3660.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}