{
  "module_name": "Makefile",
  "hash_id": "2ed9e03d34e11daff2aa06355dd3393a7b28806fdc075ac3dca7ebd2ffc130b0",
  "original_prompt": "Ingested from linux-6.6.14/tools/tracing/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\ninclude ../scripts/Makefile.include\n\nall: latency rtla\n\nclean: latency_clean rtla_clean\n\ninstall: latency_install rtla_install\n\nlatency:\n\t$(call descend,latency)\n\nlatency_install:\n\t$(call descend,latency,install)\n\nlatency_clean:\n\t$(call descend,latency,clean)\n\nrtla:\n\t$(call descend,rtla)\n\nrtla_install:\n\t$(call descend,rtla,install)\n\nrtla_clean:\n\t$(call descend,rtla,clean)\n\n.PHONY: all install clean latency latency_install latency_clean \\\n\trtla rtla_install rtla_clean\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}