 

 

#if !defined (BUFSIZ)
#include <stdio.h>
#endif  

#include "readline.h"

 

KEYMAP_ENTRY_ARRAY emacs_standard_keymap = {

   
  { ISFUNC, rl_set_mark },			 
  { ISFUNC, rl_beg_of_line },			 
  { ISFUNC, rl_backward_char },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_delete },			 
  { ISFUNC, rl_end_of_line },			 
  { ISFUNC, rl_forward_char },			 
  { ISFUNC, rl_abort },				 
  { ISFUNC, rl_rubout },			 
  { ISFUNC, rl_complete },			 
  { ISFUNC, rl_newline },			 
  { ISFUNC, rl_kill_line },			 
  { ISFUNC, rl_clear_screen },			 
  { ISFUNC, rl_newline },			 
  { ISFUNC, rl_get_next_history },		 
  { ISFUNC, rl_operate_and_get_next },		 
  { ISFUNC, rl_get_previous_history },		 
  { ISFUNC, rl_quoted_insert },			 
  { ISFUNC, rl_reverse_search_history },	 
  { ISFUNC, rl_forward_search_history },	 
  { ISFUNC, rl_transpose_chars },		 
  { ISFUNC, rl_unix_line_discard },		 
  { ISFUNC, rl_quoted_insert },			 
  { ISFUNC, rl_unix_word_rubout },		 
  { ISKMAP, (rl_command_func_t *)emacs_ctlx_keymap },	 
  { ISFUNC, rl_yank },				 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISKMAP, (rl_command_func_t *)emacs_meta_keymap },  
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_char_search },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_undo_command },			 

   
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
	
	   
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 

   
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 

   
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 

   
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 

   
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 

   
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_rubout },		 

#if KEYMAP_SIZE > 128
   
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 
  { ISFUNC, rl_insert },		 

   
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert },	 
  { ISFUNC, rl_insert }		 
#endif  
};

KEYMAP_ENTRY_ARRAY emacs_meta_keymap = {

   
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_abort },			 
  { ISFUNC, rl_backward_kill_word },	 
  { ISFUNC, rl_tab_insert },		 
  { ISFUNC, rl_vi_editing_mode },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_clear_display },		 
  { ISFUNC, rl_vi_editing_mode }, 	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_revert_line },		 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_yank_nth_arg },		 
  { ISFUNC, (rl_command_func_t *)0x0 },	 

  { ISFUNC, rl_complete },		 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_backward_char_search },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 

   
  { ISFUNC, rl_set_mark },		 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_insert_comment },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_tilde_expand },		 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_insert_completions },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_digit_argument }, 	 
  { ISFUNC, rl_yank_last_arg},		 
  { ISFUNC, (rl_command_func_t *)0x0 },	 

   
  { ISFUNC, rl_digit_argument }, 	 
  { ISFUNC, rl_digit_argument }, 	 
  { ISFUNC, rl_digit_argument }, 	 
  { ISFUNC, rl_digit_argument }, 	 
  { ISFUNC, rl_digit_argument }, 	 
  { ISFUNC, rl_digit_argument }, 	 
  { ISFUNC, rl_digit_argument }, 	 
  { ISFUNC, rl_digit_argument }, 	 
  { ISFUNC, rl_digit_argument }, 	 
  { ISFUNC, rl_digit_argument }, 	 

   
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_beginning_of_history },	 
  { ISFUNC, rl_possible_completions },	 
  { ISFUNC, rl_end_of_history },	 
  { ISFUNC, rl_possible_completions },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 

   
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 
  { ISFUNC, rl_do_lowercase_version },	 

   
  { ISFUNC, (rl_command_func_t *)0x0 },		 	 
  { ISFUNC, rl_delete_horizontal_space },	 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_yank_last_arg },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

   
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_backward_word },		 
  { ISFUNC, rl_capitalize_word }, 	 
  { ISFUNC, rl_kill_word },		 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_forward_word },		 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_downcase_word },		 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_noninc_forward_search },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 	 
  { ISFUNC, rl_noninc_reverse_search },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_revert_line },		 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_transpose_words }, 	 
  { ISFUNC, rl_upcase_word },		 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_yank_pop },		 
  { ISFUNC, (rl_command_func_t *)0x0 },	 

   
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, (rl_command_func_t *)0x0 },	 
  { ISFUNC, rl_tilde_expand },		 
  { ISFUNC, rl_backward_kill_word },	 

#if KEYMAP_SIZE > 128
   
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 }
#endif  
};

KEYMAP_ENTRY_ARRAY emacs_ctlx_keymap = {

   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_abort },				 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_re_read_init_file },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_undo_command },			 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_exchange_point_and_mark },	 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_start_kbd_macro },		 
  { ISFUNC, rl_end_kbd_macro  },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

   
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 
  { ISFUNC, rl_do_lowercase_version },		 

   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_call_last_kbd_macro },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 

   
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, (rl_command_func_t *)0x0 },		 
  { ISFUNC, rl_backward_kill_line },		 

#if KEYMAP_SIZE > 128
   
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 },
  { ISFUNC, (rl_command_func_t *)0x0 }
#endif  
};
