{
  "module_name": "Makefile",
  "hash_id": "2d96584ccbf7409837cbb4aa8c6551cf6b2d5051a2f2bfd8e8f802b50e8b8cd2",
  "original_prompt": "Ingested from linux-6.6.14/drivers/firewire/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the Linux IEEE 1394 implementation\n#\n\nfirewire-core-y += core-card.o core-cdev.o core-device.o \\\n                   core-iso.o core-topology.o core-transaction.o\nfirewire-ohci-y += ohci.o\nfirewire-sbp2-y += sbp2.o\nfirewire-net-y  += net.o\n\nobj-$(CONFIG_FIREWIRE)      += firewire-core.o\nobj-$(CONFIG_FIREWIRE_OHCI) += firewire-ohci.o\nobj-$(CONFIG_FIREWIRE_SBP2) += firewire-sbp2.o\nobj-$(CONFIG_FIREWIRE_NET)  += firewire-net.o\nobj-$(CONFIG_FIREWIRE_NOSY) += nosy.o\nobj-$(CONFIG_PROVIDE_OHCI1394_DMA_INIT) += init_ohci1394_dma.o\n\nfirewire-uapi-test-objs += uapi-test.o\nobj-$(CONFIG_FIREWIRE_KUNIT_UAPI_TEST) += firewire-uapi-test.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}