{
  "module_name": "Makefile",
  "hash_id": "c61cbe474da96b48c77429ac2ee72b80259b515031a5b43c9c8283e37e3d8aae",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/powerpc/primitives/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nCFLAGS += -I$(CURDIR)\n\nTEST_GEN_PROGS := load_unaligned_zeropad\n\ntop_srcdir = ../../../../..\ninclude ../../lib.mk\n\n$(TEST_GEN_PROGS): ../harness.c\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}