{
  "module_name": "Makefile",
  "hash_id": "cd3c8f45f47b93194eb3147fabc02c6c0b1337f388e33905c00ffadf99fc1486",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/fpu/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0+\n\nLDLIBS := -lm\n\nTEST_GEN_PROGS := test_fpu\n\nTEST_PROGS := run_test_fpu.sh\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}