{
  "module_name": "Kbuild",
  "hash_id": "fddb7b0dc62df127e35208d3fc52f301262f06a09607cc2143519325dc31ab59",
  "original_prompt": "Ingested from linux-6.6.14/arch/x86/Kbuild",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_ARCH_HAS_CC_PLATFORM) += coco/\n\nobj-y += entry/\n\nobj-$(CONFIG_PERF_EVENTS) += events/\n\nobj-$(CONFIG_KVM) += kvm/\n\n# Xen paravirtualization support\nobj-$(CONFIG_XEN) += xen/\n\nobj-$(CONFIG_PVH) += platform/pvh/\n\n# Hyper-V paravirtualization support\nobj-$(subst m,y,$(CONFIG_HYPERV)) += hyperv/\n\nobj-y += realmode/\nobj-y += kernel/\nobj-y += mm/\n\nobj-y += crypto/\n\nobj-$(CONFIG_IA32_EMULATION) += ia32/\n\nobj-y += platform/\nobj-y += net/\n\nobj-$(CONFIG_KEXEC_FILE) += purgatory/\n\n# for cleaning\nsubdir- += boot tools\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}