{
  "module_name": "Makefile",
  "hash_id": "f022b25cccdacac275b3e52d2d7d036fd22254f1aa2934ff03915c99534249bb",
  "original_prompt": "Ingested from linux-6.6.14/sound/aoa/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_SND_AOA) += core/\nobj-$(CONFIG_SND_AOA_SOUNDBUS) += soundbus/\nobj-$(CONFIG_SND_AOA) += fabrics/\nobj-$(CONFIG_SND_AOA) += codecs/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}