#ifndef SMU_13_0_7_PPTABLE_H
#define SMU_13_0_7_PPTABLE_H
#pragma pack(push, 1)
#define SMU_13_0_7_TABLE_FORMAT_REVISION 15
#define SMU_13_0_7_PP_PLATFORM_CAP_POWERPLAY 0x1         
#define SMU_13_0_7_PP_PLATFORM_CAP_SBIOSPOWERSOURCE 0x2  
#define SMU_13_0_7_PP_PLATFORM_CAP_HARDWAREDC 0x4        
#define SMU_13_0_7_PP_PLATFORM_CAP_BACO 0x8              
#define SMU_13_0_7_PP_PLATFORM_CAP_MACO 0x10             
#define SMU_13_0_7_PP_PLATFORM_CAP_SHADOWPSTATE 0x20     
#define SMU_13_0_7_PP_THERMALCONTROLLER_NONE 0
#define SMU_13_0_7_PP_THERMALCONTROLLER_NAVI21 28
#define SMU_13_0_7_PP_OVERDRIVE_VERSION 0x83         
#define SMU_13_0_7_PP_POWERSAVINGCLOCK_VERSION 0x01  
enum SMU_13_0_7_ODFEATURE_CAP {
    SMU_13_0_7_ODCAP_GFXCLK_LIMITS = 0,
    SMU_13_0_7_ODCAP_UCLK_LIMITS,
    SMU_13_0_7_ODCAP_POWER_LIMIT,
    SMU_13_0_7_ODCAP_FAN_ACOUSTIC_LIMIT,
    SMU_13_0_7_ODCAP_FAN_SPEED_MIN,
    SMU_13_0_7_ODCAP_TEMPERATURE_FAN,
    SMU_13_0_7_ODCAP_TEMPERATURE_SYSTEM,
    SMU_13_0_7_ODCAP_MEMORY_TIMING_TUNE,
    SMU_13_0_7_ODCAP_FAN_ZERO_RPM_CONTROL,
    SMU_13_0_7_ODCAP_AUTO_UV_ENGINE,
    SMU_13_0_7_ODCAP_AUTO_OC_ENGINE,
    SMU_13_0_7_ODCAP_AUTO_OC_MEMORY,
    SMU_13_0_7_ODCAP_FAN_CURVE,
    SMU_13_0_7_ODCAP_AUTO_FAN_ACOUSTIC_LIMIT,
    SMU_13_0_7_ODCAP_POWER_MODE,
    SMU_13_0_7_ODCAP_PER_ZONE_GFX_VOLTAGE_OFFSET,
    SMU_13_0_7_ODCAP_COUNT,
};
enum SMU_13_0_7_ODFEATURE_ID {
    SMU_13_0_7_ODFEATURE_GFXCLK_LIMITS           = 1 << SMU_13_0_7_ODCAP_GFXCLK_LIMITS,            
    SMU_13_0_7_ODFEATURE_UCLK_LIMITS             = 1 << SMU_13_0_7_ODCAP_UCLK_LIMITS,              
    SMU_13_0_7_ODFEATURE_POWER_LIMIT             = 1 << SMU_13_0_7_ODCAP_POWER_LIMIT,              
    SMU_13_0_7_ODFEATURE_FAN_ACOUSTIC_LIMIT      = 1 << SMU_13_0_7_ODCAP_FAN_ACOUSTIC_LIMIT,       
    SMU_13_0_7_ODFEATURE_FAN_SPEED_MIN           = 1 << SMU_13_0_7_ODCAP_FAN_SPEED_MIN,            
    SMU_13_0_7_ODFEATURE_TEMPERATURE_FAN         = 1 << SMU_13_0_7_ODCAP_TEMPERATURE_FAN,          
    SMU_13_0_7_ODFEATURE_TEMPERATURE_SYSTEM      = 1 << SMU_13_0_7_ODCAP_TEMPERATURE_SYSTEM,       
    SMU_13_0_7_ODFEATURE_MEMORY_TIMING_TUNE      = 1 << SMU_13_0_7_ODCAP_MEMORY_TIMING_TUNE,       
    SMU_13_0_7_ODFEATURE_FAN_ZERO_RPM_CONTROL    = 1 << SMU_13_0_7_ODCAP_FAN_ZERO_RPM_CONTROL,     
    SMU_13_0_7_ODFEATURE_AUTO_UV_ENGINE          = 1 << SMU_13_0_7_ODCAP_AUTO_UV_ENGINE,           
    SMU_13_0_7_ODFEATURE_AUTO_OC_ENGINE          = 1 << SMU_13_0_7_ODCAP_AUTO_OC_ENGINE,           
    SMU_13_0_7_ODFEATURE_AUTO_OC_MEMORY          = 1 << SMU_13_0_7_ODCAP_AUTO_OC_MEMORY,           
    SMU_13_0_7_ODFEATURE_FAN_CURVE               = 1 << SMU_13_0_7_ODCAP_FAN_CURVE,                
    SMU_13_0_7_ODFEATURE_AUTO_FAN_ACOUSTIC_LIMIT = 1 << SMU_13_0_7_ODCAP_AUTO_FAN_ACOUSTIC_LIMIT,  
    SMU_13_0_7_ODFEATURE_POWER_MODE              = 1 << SMU_13_0_7_ODCAP_POWER_MODE,               
    SMU_13_0_7_ODFEATURE_PER_ZONE_GFX_VOLTAGE_OFFSET  = 1 << SMU_13_0_7_ODCAP_PER_ZONE_GFX_VOLTAGE_OFFSET,   
    SMU_13_0_7_ODFEATURE_COUNT                   = 16,
};
#define SMU_13_0_7_MAX_ODFEATURE 32  
enum SMU_13_0_7_ODSETTING_ID {
    SMU_13_0_7_ODSETTING_GFXCLKFMAX = 0,
    SMU_13_0_7_ODSETTING_GFXCLKFMIN,
    SMU_13_0_7_ODSETTING_UCLKFMIN,
    SMU_13_0_7_ODSETTING_UCLKFMAX,
    SMU_13_0_7_ODSETTING_POWERPERCENTAGE,
    SMU_13_0_7_ODSETTING_FANRPMMIN,
    SMU_13_0_7_ODSETTING_FANRPMACOUSTICLIMIT,
    SMU_13_0_7_ODSETTING_FANTARGETTEMPERATURE,
    SMU_13_0_7_ODSETTING_OPERATINGTEMPMAX,
    SMU_13_0_7_ODSETTING_ACTIMING,
    SMU_13_0_7_ODSETTING_FAN_ZERO_RPM_CONTROL,
    SMU_13_0_7_ODSETTING_AUTOUVENGINE,
    SMU_13_0_7_ODSETTING_AUTOOCENGINE,
    SMU_13_0_7_ODSETTING_AUTOOCMEMORY,
    SMU_13_0_7_ODSETTING_FAN_CURVE_TEMPERATURE_1,
    SMU_13_0_7_ODSETTING_FAN_CURVE_SPEED_1,
    SMU_13_0_7_ODSETTING_FAN_CURVE_TEMPERATURE_2,
    SMU_13_0_7_ODSETTING_FAN_CURVE_SPEED_2,
    SMU_13_0_7_ODSETTING_FAN_CURVE_TEMPERATURE_3,
    SMU_13_0_7_ODSETTING_FAN_CURVE_SPEED_3,
    SMU_13_0_7_ODSETTING_FAN_CURVE_TEMPERATURE_4,
    SMU_13_0_7_ODSETTING_FAN_CURVE_SPEED_4,
    SMU_13_0_7_ODSETTING_FAN_CURVE_TEMPERATURE_5,
    SMU_13_0_7_ODSETTING_FAN_CURVE_SPEED_5,
    SMU_13_0_7_ODSETTING_AUTO_FAN_ACOUSTIC_LIMIT,
    SMU_13_0_7_ODSETTING_POWER_MODE,
    SMU_13_0_7_ODSETTING_PER_ZONE_GFX_VOLTAGE_OFFSET_POINT_1,
    SMU_13_0_7_ODSETTING_PER_ZONE_GFX_VOLTAGE_OFFSET_POINT_2,
    SMU_13_0_7_ODSETTING_PER_ZONE_GFX_VOLTAGE_OFFSET_POINT_3,
    SMU_13_0_7_ODSETTING_PER_ZONE_GFX_VOLTAGE_OFFSET_POINT_4,
    SMU_13_0_7_ODSETTING_PER_ZONE_GFX_VOLTAGE_OFFSET_POINT_5,
    SMU_13_0_7_ODSETTING_PER_ZONE_GFX_VOLTAGE_OFFSET_POINT_6,
    SMU_13_0_7_ODSETTING_COUNT,
};
#define SMU_13_0_7_MAX_ODSETTING 64  
enum SMU_13_0_7_PWRMODE_SETTING {
    SMU_13_0_7_PMSETTING_POWER_LIMIT_QUIET = 0,
    SMU_13_0_7_PMSETTING_POWER_LIMIT_BALANCE,
    SMU_13_0_7_PMSETTING_POWER_LIMIT_TURBO,
    SMU_13_0_7_PMSETTING_POWER_LIMIT_RAGE,
    SMU_13_0_7_PMSETTING_ACOUSTIC_TEMP_QUIET,
    SMU_13_0_7_PMSETTING_ACOUSTIC_TEMP_BALANCE,
    SMU_13_0_7_PMSETTING_ACOUSTIC_TEMP_TURBO,
    SMU_13_0_7_PMSETTING_ACOUSTIC_TEMP_RAGE,
    SMU_13_0_7_PMSETTING_ACOUSTIC_TARGET_RPM_QUIET,
    SMU_13_0_7_PMSETTING_ACOUSTIC_TARGET_RPM_BALANCE,
    SMU_13_0_7_PMSETTING_ACOUSTIC_TARGET_RPM_TURBO,
    SMU_13_0_7_PMSETTING_ACOUSTIC_TARGET_RPM_RAGE,
    SMU_13_0_7_PMSETTING_ACOUSTIC_LIMIT_RPM_QUIET,
    SMU_13_0_7_PMSETTING_ACOUSTIC_LIMIT_RPM_BALANCE,
    SMU_13_0_7_PMSETTING_ACOUSTIC_LIMIT_RPM_TURBO,
    SMU_13_0_7_PMSETTING_ACOUSTIC_LIMIT_RPM_RAGE,
};
#define SMU_13_0_7_MAX_PMSETTING 32  
struct smu_13_0_7_overdrive_table {
    uint8_t revision;                              
    uint8_t reserve[3];                            
    uint32_t feature_count;                        
    uint32_t setting_count;                        
    uint8_t cap[SMU_13_0_7_MAX_ODFEATURE];         
    uint32_t max[SMU_13_0_7_MAX_ODSETTING];        
    uint32_t min[SMU_13_0_7_MAX_ODSETTING];        
    int16_t pm_setting[SMU_13_0_7_MAX_PMSETTING];  
};
enum SMU_13_0_7_PPCLOCK_ID {
    SMU_13_0_7_PPCLOCK_GFXCLK = 0,
    SMU_13_0_7_PPCLOCK_SOCCLK,
    SMU_13_0_7_PPCLOCK_UCLK,
    SMU_13_0_7_PPCLOCK_FCLK,
    SMU_13_0_7_PPCLOCK_DCLK_0,
    SMU_13_0_7_PPCLOCK_VCLK_0,
    SMU_13_0_7_PPCLOCK_DCLK_1,
    SMU_13_0_7_PPCLOCK_VCLK_1,
    SMU_13_0_7_PPCLOCK_DCEFCLK,
    SMU_13_0_7_PPCLOCK_DISPCLK,
    SMU_13_0_7_PPCLOCK_PIXCLK,
    SMU_13_0_7_PPCLOCK_PHYCLK,
    SMU_13_0_7_PPCLOCK_DTBCLK,
    SMU_13_0_7_PPCLOCK_COUNT,
};
#define SMU_13_0_7_MAX_PPCLOCK 16  
struct smu_13_0_7_powerplay_table {
    struct atom_common_table_header header;  
    uint8_t table_revision;                  
    uint8_t padding;
    uint16_t table_size;                     
    uint32_t golden_pp_id;                   
    uint32_t golden_revision;                
    uint16_t format_id;                      
    uint32_t platform_caps;                  
    uint8_t thermal_controller_type;  
    uint16_t small_power_limit1;
    uint16_t small_power_limit2;
    uint16_t boost_power_limit;  
    uint16_t software_shutdown_temp;
    uint32_t reserve[45];
    struct smu_13_0_7_overdrive_table overdrive_table;
    uint8_t padding1;
    PPTable_t smc_pptable;  
};
#pragma pack(pop)
#endif
