{
  "module_name": "Makefile",
  "hash_id": "a00a7a16e8505bb6985767faed4e07443a095237899f0e67df4a7f86bb30fa8e",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/drivers/dma-buf/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nCFLAGS += $(KHDR_INCLUDES)\n\nTEST_GEN_PROGS := udmabuf\n\ntop_srcdir ?=../../../../..\n\ninclude ../../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}