{
  "module_name": "Makefile",
  "hash_id": "2125a19857c0c1637c86649e6c12dceec8554c757f1385008db9bdafa8956e7e",
  "original_prompt": "Ingested from linux-6.6.14/net/netlink/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the netlink driver.\n#\n\nobj-y  \t\t\t\t:= af_netlink.o genetlink.o policy.o\n\nobj-$(CONFIG_NETLINK_DIAG)\t+= netlink_diag.o\nnetlink_diag-y\t\t\t:= diag.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}