{
  "module_name": "Makefile",
  "hash_id": "9eb9d949f41538569942f9b843502c82d5a180d430d01d8fc976b75bff1f3553",
  "original_prompt": "Ingested from linux-6.6.14/mm/kfence/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\nobj-y := core.o report.o\n\nCFLAGS_kfence_test.o := -fno-omit-frame-pointer -fno-optimize-sibling-calls\nobj-$(CONFIG_KFENCE_KUNIT_TEST) += kfence_test.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}