{
  "module_name": "Makefile",
  "hash_id": "f3026a22412538121d15e2169992315d356add041924aa96f9e332cf467b8d03",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/hisilicon/hns/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the HISILICON network device drivers.\n#\n\nobj-$(CONFIG_HNS) += hnae.o\n\nobj-$(CONFIG_HNS_DSAF) += hns_dsaf.o\nhns_dsaf-objs = hns_ae_adapt.o hns_dsaf_gmac.o hns_dsaf_mac.o hns_dsaf_misc.o \\\n\thns_dsaf_main.o hns_dsaf_ppe.o hns_dsaf_rcb.o hns_dsaf_xgmac.o\n\nobj-$(CONFIG_HNS_ENET) += hns_enet_drv.o\nhns_enet_drv-objs = hns_enet.o hns_ethtool.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}