{
  "module_name": "Makefile",
  "hash_id": "4f9b51fff1a1c82f68405614590868ef1a147118ab6b5dc61abcf93ccc049535",
  "original_prompt": "Ingested from linux-6.6.14/sound/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for the Linux sound card driver\n#\n\nobj-$(CONFIG_SOUND) += soundcore.o\nobj-$(CONFIG_DMASOUND) += oss/dmasound/\nobj-$(CONFIG_SND) += core/ i2c/ drivers/ isa/ pci/ ppc/ arm/ sh/ synth/ usb/ \\\n\tfirewire/ sparc/ spi/ parisc/ pcmcia/ mips/ soc/ atmel/ hda/ x86/ xen/ \\\n\tvirtio/\nobj-$(CONFIG_SND_AOA) += aoa/\n\n# This one must be compilable even if sound is configured out\nobj-$(CONFIG_AC97_BUS) += ac97_bus.o\nobj-$(CONFIG_AC97_BUS_NEW) += ac97/\n\nifeq ($(CONFIG_SND),y)\n  obj-y += last.o\nendif\n\nsoundcore-objs  := sound_core.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}