{
  "module_name": "Makefile",
  "hash_id": "3bd2ea99ae91b5a7e9277a96b214f60b7cf95bab08d3dcc7b51cb8b712ac718b",
  "original_prompt": "Ingested from linux-6.6.14/net/strparser/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_STREAM_PARSER) += strparser.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}