{
  "module_name": "Makefile",
  "hash_id": "a309989821bcc14f2abf63969d57f74ee57680e9b1f285bdbdcfa8da2d9f700e",
  "original_prompt": "Ingested from linux-6.6.14/drivers/infiniband/ulp/iser/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_INFINIBAND_ISER)\t+= ib_iser.o\n\nib_iser-y\t\t\t:= iser_verbs.o iser_initiator.o iser_memory.o \\\n\t\t\t\t   iscsi_iser.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}