#ifndef _NFP_NET_CTRL_H_
#define _NFP_NET_CTRL_H_
#include <linux/types.h>
#define NFP_NET_APP_CAP_SP_INDIFF	BIT_ULL(0)  
#define NFP_NET_CFG_BAR_SZ		(32 * 1024)
#define NFP_NET_RX_OFFSET		32
#define NFP_NET_LSO_MAX_HDR_SZ		255
#define NFP_NET_LSO_MAX_SEGS		64
#define NFP_NET_META_VLAN_STRIP			BIT(31)
#define NFP_NET_META_VLAN_TPID_MASK		GENMASK(19, 16)
#define NFP_NET_META_VLAN_TCI_MASK		GENMASK(15, 0)
#define NFP_NET_META_FIELD_SIZE		4
#define NFP_NET_META_HASH		1  
#define NFP_NET_META_MARK		2
#define NFP_NET_META_VLAN		4  
#define NFP_NET_META_PORTID		5
#define NFP_NET_META_CSUM		6  
#define NFP_NET_META_CONN_HANDLE	7
#define NFP_NET_META_RESYNC_INFO	8  
#define NFP_NET_META_IPSEC		9  
#define NFP_META_PORT_ID_CTRL		~0U
#define NFP_NET_META_VLAN_SIZE			4
#define NFP_NET_META_PORTID_SIZE		4
#define NFP_NET_META_CONN_HANDLE_SIZE		8
#define NFP_NET_META_IPSEC_SIZE			4
#define NFP_NET_META_IPSEC_FIELD_SIZE		12
#define NFP_NET_RSS_NONE		0
#define NFP_NET_RSS_IPV4		1
#define NFP_NET_RSS_IPV6		2
#define NFP_NET_RSS_IPV6_EX		3
#define NFP_NET_RSS_IPV4_TCP		4
#define NFP_NET_RSS_IPV6_TCP		5
#define NFP_NET_RSS_IPV6_EX_TCP		6
#define NFP_NET_RSS_IPV4_UDP		7
#define NFP_NET_RSS_IPV6_UDP		8
#define NFP_NET_RSS_IPV6_EX_UDP		9
#define NFP_NET_TXR_MAX			64
#define NFP_NET_RXR_MAX			64
#define NFP_NET_CFG_CTRL		0x0000
#define   NFP_NET_CFG_CTRL_ENABLE	  (0x1 <<  0)  
#define   NFP_NET_CFG_CTRL_PROMISC	  (0x1 <<  1)  
#define   NFP_NET_CFG_CTRL_L2BC		  (0x1 <<  2)  
#define   NFP_NET_CFG_CTRL_L2MC		  (0x1 <<  3)  
#define   NFP_NET_CFG_CTRL_RXCSUM	  (0x1 <<  4)  
#define   NFP_NET_CFG_CTRL_TXCSUM	  (0x1 <<  5)  
#define   NFP_NET_CFG_CTRL_RXVLAN	  (0x1 <<  6)  
#define   NFP_NET_CFG_CTRL_TXVLAN	  (0x1 <<  7)  
#define   NFP_NET_CFG_CTRL_SCATTER	  (0x1 <<  8)  
#define   NFP_NET_CFG_CTRL_GATHER	  (0x1 <<  9)  
#define   NFP_NET_CFG_CTRL_LSO		  (0x1 << 10)  
#define   NFP_NET_CFG_CTRL_CTAG_FILTER	  (0x1 << 11)  
#define   NFP_NET_CFG_CTRL_CMSG_DATA	  (0x1 << 12)  
#define   NFP_NET_CFG_CTRL_RXQINQ	  (0x1 << 13)  
#define   NFP_NET_CFG_CTRL_RXVLAN_V2	  (0x1 << 15)  
#define   NFP_NET_CFG_CTRL_RINGCFG	  (0x1 << 16)  
#define   NFP_NET_CFG_CTRL_RSS		  (0x1 << 17)  
#define   NFP_NET_CFG_CTRL_IRQMOD	  (0x1 << 18)  
#define   NFP_NET_CFG_CTRL_MSIXAUTO	  (0x1 << 20)  
#define   NFP_NET_CFG_CTRL_TXRWB	  (0x1 << 21)  
#define   NFP_NET_CFG_CTRL_VEPA		  (0x1 << 22)  
#define   NFP_NET_CFG_CTRL_TXVLAN_V2	  (0x1 << 23)  
#define   NFP_NET_CFG_CTRL_VXLAN	  (0x1 << 24)  
#define   NFP_NET_CFG_CTRL_NVGRE	  (0x1 << 25)  
#define   NFP_NET_CFG_CTRL_BPF		  (0x1 << 27)  
#define   NFP_NET_CFG_CTRL_LSO2		  (0x1 << 28)  
#define   NFP_NET_CFG_CTRL_RSS2		  (0x1 << 29)  
#define   NFP_NET_CFG_CTRL_CSUM_COMPLETE  (0x1 << 30)  
#define   NFP_NET_CFG_CTRL_LIVE_ADDR	  (0x1 << 31)  
#define NFP_NET_CFG_CTRL_LSO_ANY	(NFP_NET_CFG_CTRL_LSO | \
					 NFP_NET_CFG_CTRL_LSO2)
#define NFP_NET_CFG_CTRL_RSS_ANY	(NFP_NET_CFG_CTRL_RSS | \
					 NFP_NET_CFG_CTRL_RSS2)
#define NFP_NET_CFG_CTRL_RXCSUM_ANY	(NFP_NET_CFG_CTRL_RXCSUM | \
					 NFP_NET_CFG_CTRL_CSUM_COMPLETE)
#define NFP_NET_CFG_CTRL_CHAIN_META	(NFP_NET_CFG_CTRL_RSS2 | \
					 NFP_NET_CFG_CTRL_CSUM_COMPLETE)
#define NFP_NET_CFG_CTRL_RXVLAN_ANY	(NFP_NET_CFG_CTRL_RXVLAN | \
					 NFP_NET_CFG_CTRL_RXVLAN_V2)
#define NFP_NET_CFG_CTRL_TXVLAN_ANY	(NFP_NET_CFG_CTRL_TXVLAN | \
					 NFP_NET_CFG_CTRL_TXVLAN_V2)
#define NFP_NET_CFG_UPDATE		0x0004
#define   NFP_NET_CFG_UPDATE_GEN	  (0x1 <<  0)  
#define   NFP_NET_CFG_UPDATE_RING	  (0x1 <<  1)  
#define   NFP_NET_CFG_UPDATE_RSS	  (0x1 <<  2)  
#define   NFP_NET_CFG_UPDATE_TXRPRIO	  (0x1 <<  3)  
#define   NFP_NET_CFG_UPDATE_RXRPRIO	  (0x1 <<  4)  
#define   NFP_NET_CFG_UPDATE_MSIX	  (0x1 <<  5)  
#define   NFP_NET_CFG_UPDATE_RESET	  (0x1 <<  7)  
#define   NFP_NET_CFG_UPDATE_IRQMOD	  (0x1 <<  8)  
#define   NFP_NET_CFG_UPDATE_VXLAN	  (0x1 <<  9)  
#define   NFP_NET_CFG_UPDATE_BPF	  (0x1 << 10)  
#define   NFP_NET_CFG_UPDATE_MACADDR	  (0x1 << 11)  
#define   NFP_NET_CFG_UPDATE_MBOX	  (0x1 << 12)  
#define   NFP_NET_CFG_UPDATE_VF		  (0x1 << 13)  
#define   NFP_NET_CFG_UPDATE_CRYPTO	  (0x1 << 14)  
#define   NFP_NET_CFG_UPDATE_ERR	  (0x1 << 31)  
#define NFP_NET_CFG_TXRS_ENABLE		0x0008
#define NFP_NET_CFG_RXRS_ENABLE		0x0010
#define NFP_NET_CFG_MTU			0x0018
#define NFP_NET_CFG_FLBUFSZ		0x001c
#define NFP_NET_CFG_EXN			0x001f
#define NFP_NET_CFG_LSC			0x0020
#define NFP_NET_CFG_MACADDR		0x0024
#define NFP_NET_CFG_VERSION		0x0030
#define   NFP_NET_CFG_VERSION_RESERVED_MASK	(0xfe << 24)
#define   NFP_NET_CFG_VERSION_DP_NFD3		0
#define   NFP_NET_CFG_VERSION_DP_NFDK		1
#define   NFP_NET_CFG_VERSION_DP_MASK		1
#define   NFP_NET_CFG_VERSION_CLASS_MASK  (0xff << 16)
#define   NFP_NET_CFG_VERSION_CLASS(x)	  (((x) & 0xff) << 16)
#define   NFP_NET_CFG_VERSION_CLASS_GENERIC	0
#define   NFP_NET_CFG_VERSION_MAJOR_MASK  (0xff <<  8)
#define   NFP_NET_CFG_VERSION_MAJOR(x)	  (((x) & 0xff) <<  8)
#define   NFP_NET_CFG_VERSION_MINOR_MASK  (0xff <<  0)
#define   NFP_NET_CFG_VERSION_MINOR(x)	  (((x) & 0xff) <<  0)
#define NFP_NET_CFG_STS			0x0034
#define   NFP_NET_CFG_STS_LINK		  (0x1 << 0)  
#define   NFP_NET_CFG_STS_LINK_RATE_SHIFT 1
#define   NFP_NET_CFG_STS_LINK_RATE_MASK  0xF
#define   NFP_NET_CFG_STS_LINK_RATE	  \
	(NFP_NET_CFG_STS_LINK_RATE_MASK << NFP_NET_CFG_STS_LINK_RATE_SHIFT)
#define   NFP_NET_CFG_STS_LINK_RATE_UNSUPPORTED   0
#define   NFP_NET_CFG_STS_LINK_RATE_UNKNOWN	  1
#define   NFP_NET_CFG_STS_LINK_RATE_1G		  2
#define   NFP_NET_CFG_STS_LINK_RATE_10G		  3
#define   NFP_NET_CFG_STS_LINK_RATE_25G		  4
#define   NFP_NET_CFG_STS_LINK_RATE_40G		  5
#define   NFP_NET_CFG_STS_LINK_RATE_50G		  6
#define   NFP_NET_CFG_STS_LINK_RATE_100G	  7
#define NFP_NET_CFG_STS_NSP_LINK_RATE	0x0036
#define NFP_NET_CFG_CAP			0x0038
#define NFP_NET_CFG_MAX_TXRINGS		0x003c
#define NFP_NET_CFG_MAX_RXRINGS		0x0040
#define NFP_NET_CFG_MAX_MTU		0x0044
#define NFP_NET_CFG_START_TXQ		0x0048
#define NFP_NET_CFG_START_RXQ		0x004c
#define NFP_NET_CFG_RX_OFFSET		0x0050
#define NFP_NET_CFG_RX_OFFSET_DYNAMIC		0	 
#define NFP_NET_CFG_RSS_CAP		0x0054
#define   NFP_NET_CFG_RSS_CAP_HFUNC	  0xff000000
#define NFP_NET_CFG_TLV_BASE		0x0058
#define NFP_NET_CFG_VXLAN_PORT		0x0060
#define NFP_NET_CFG_VXLAN_SZ		  0x0008
#define NFP_NET_CFG_BPF_ABI		0x0080
#define NFP_NET_CFG_BPF_CAP		0x0081
#define   NFP_NET_BPF_CAP_RELO		(1 << 0)  
#define NFP_NET_CFG_BPF_MAX_LEN		0x0082
#define NFP_NET_CFG_BPF_START		0x0084
#define NFP_NET_CFG_BPF_DONE		0x0086
#define NFP_NET_CFG_BPF_STACK_SZ	0x0088
#define NFP_NET_CFG_BPF_INL_MTU		0x0089
#define NFP_NET_CFG_BPF_SIZE		0x008e
#define NFP_NET_CFG_BPF_ADDR		0x0090
#define   NFP_NET_CFG_BPF_CFG_8CTX	(1 << 0)  
#define   NFP_NET_CFG_BPF_CFG_MASK	7ULL
#define   NFP_NET_CFG_BPF_ADDR_MASK	(~NFP_NET_CFG_BPF_CFG_MASK)
#define NFP_NET_CFG_CTRL_WORD1		0x0098
#define   NFP_NET_CFG_CTRL_PKT_TYPE	  (0x1 << 0)  
#define   NFP_NET_CFG_CTRL_IPSEC	  (0x1 << 1)  
#define   NFP_NET_CFG_CTRL_MCAST_FILTER	  (0x1 << 2)  
#define   NFP_NET_CFG_CTRL_FREELIST_EN	  (0x1 << 6)  
#define NFP_NET_CFG_CAP_WORD1		0x00a4
#define NFP_NET_CFG_RESERVED		0x00b0
#define NFP_NET_CFG_RESERVED_SZ		0x0010
#define NFP_NET_CFG_RSS_BASE		0x0100
#define NFP_NET_CFG_RSS_CTRL		NFP_NET_CFG_RSS_BASE
#define   NFP_NET_CFG_RSS_MASK		  (0x7f)
#define   NFP_NET_CFG_RSS_MASK_of(_x)	  ((_x) & 0x7f)
#define   NFP_NET_CFG_RSS_IPV4		  (1 <<  8)  
#define   NFP_NET_CFG_RSS_IPV6		  (1 <<  9)  
#define   NFP_NET_CFG_RSS_IPV4_TCP	  (1 << 10)  
#define   NFP_NET_CFG_RSS_IPV4_UDP	  (1 << 11)  
#define   NFP_NET_CFG_RSS_IPV6_TCP	  (1 << 12)  
#define   NFP_NET_CFG_RSS_IPV6_UDP	  (1 << 13)  
#define   NFP_NET_CFG_RSS_HFUNC		  0xff000000
#define   NFP_NET_CFG_RSS_TOEPLITZ	  (1 << 24)  
#define   NFP_NET_CFG_RSS_XOR		  (1 << 25)  
#define   NFP_NET_CFG_RSS_CRC32		  (1 << 26)  
#define   NFP_NET_CFG_RSS_HFUNCS	  3
#define NFP_NET_CFG_RSS_KEY		(NFP_NET_CFG_RSS_BASE + 0x4)
#define NFP_NET_CFG_RSS_KEY_SZ		0x28
#define NFP_NET_CFG_RSS_ITBL		(NFP_NET_CFG_RSS_BASE + 0x4 + \
					 NFP_NET_CFG_RSS_KEY_SZ)
#define NFP_NET_CFG_RSS_ITBL_SZ		0x80
#define NFP_NET_CFG_TXR_BASE		0x0200
#define NFP_NET_CFG_TXR_ADDR(_x)	(NFP_NET_CFG_TXR_BASE + ((_x) * 0x8))
#define NFP_NET_CFG_TXR_WB_ADDR(_x)	(NFP_NET_CFG_TXR_BASE + 0x200 + \
					 ((_x) * 0x8))
#define NFP_NET_CFG_TXR_SZ(_x)		(NFP_NET_CFG_TXR_BASE + 0x400 + (_x))
#define NFP_NET_CFG_TXR_VEC(_x)		(NFP_NET_CFG_TXR_BASE + 0x440 + (_x))
#define NFP_NET_CFG_TXR_PRIO(_x)	(NFP_NET_CFG_TXR_BASE + 0x480 + (_x))
#define NFP_NET_CFG_TXR_IRQ_MOD(_x)	(NFP_NET_CFG_TXR_BASE + 0x500 + \
					 ((_x) * 0x4))
#define NFP_NET_CFG_RXR_BASE		0x0800
#define NFP_NET_CFG_RXR_ADDR(_x)	(NFP_NET_CFG_RXR_BASE + ((_x) * 0x8))
#define NFP_NET_CFG_RXR_SZ(_x)		(NFP_NET_CFG_RXR_BASE + 0x200 + (_x))
#define NFP_NET_CFG_RXR_VEC(_x)		(NFP_NET_CFG_RXR_BASE + 0x240 + (_x))
#define NFP_NET_CFG_RXR_PRIO(_x)	(NFP_NET_CFG_RXR_BASE + 0x280 + (_x))
#define NFP_NET_CFG_RXR_IRQ_MOD(_x)	(NFP_NET_CFG_RXR_BASE + 0x300 + \
					 ((_x) * 0x4))
#define NFP_NET_CFG_ICR_BASE		0x0c00
#define NFP_NET_CFG_ICR(_x)		(NFP_NET_CFG_ICR_BASE + (_x))
#define   NFP_NET_CFG_ICR_UNMASKED	0x0
#define   NFP_NET_CFG_ICR_RXTX		0x1
#define   NFP_NET_CFG_ICR_LSC		0x2
#define NFP_NET_CFG_STATS_BASE		0x0d00
#define NFP_NET_CFG_STATS_RX_DISCARDS	(NFP_NET_CFG_STATS_BASE + 0x00)
#define NFP_NET_CFG_STATS_RX_ERRORS	(NFP_NET_CFG_STATS_BASE + 0x08)
#define NFP_NET_CFG_STATS_RX_OCTETS	(NFP_NET_CFG_STATS_BASE + 0x10)
#define NFP_NET_CFG_STATS_RX_UC_OCTETS	(NFP_NET_CFG_STATS_BASE + 0x18)
#define NFP_NET_CFG_STATS_RX_MC_OCTETS	(NFP_NET_CFG_STATS_BASE + 0x20)
#define NFP_NET_CFG_STATS_RX_BC_OCTETS	(NFP_NET_CFG_STATS_BASE + 0x28)
#define NFP_NET_CFG_STATS_RX_FRAMES	(NFP_NET_CFG_STATS_BASE + 0x30)
#define NFP_NET_CFG_STATS_RX_MC_FRAMES	(NFP_NET_CFG_STATS_BASE + 0x38)
#define NFP_NET_CFG_STATS_RX_BC_FRAMES	(NFP_NET_CFG_STATS_BASE + 0x40)
#define NFP_NET_CFG_STATS_TX_DISCARDS	(NFP_NET_CFG_STATS_BASE + 0x48)
#define NFP_NET_CFG_STATS_TX_ERRORS	(NFP_NET_CFG_STATS_BASE + 0x50)
#define NFP_NET_CFG_STATS_TX_OCTETS	(NFP_NET_CFG_STATS_BASE + 0x58)
#define NFP_NET_CFG_STATS_TX_UC_OCTETS	(NFP_NET_CFG_STATS_BASE + 0x60)
#define NFP_NET_CFG_STATS_TX_MC_OCTETS	(NFP_NET_CFG_STATS_BASE + 0x68)
#define NFP_NET_CFG_STATS_TX_BC_OCTETS	(NFP_NET_CFG_STATS_BASE + 0x70)
#define NFP_NET_CFG_STATS_TX_FRAMES	(NFP_NET_CFG_STATS_BASE + 0x78)
#define NFP_NET_CFG_STATS_TX_MC_FRAMES	(NFP_NET_CFG_STATS_BASE + 0x80)
#define NFP_NET_CFG_STATS_TX_BC_FRAMES	(NFP_NET_CFG_STATS_BASE + 0x88)
#define NFP_NET_CFG_STATS_APP0_FRAMES	(NFP_NET_CFG_STATS_BASE + 0x90)
#define NFP_NET_CFG_STATS_APP0_BYTES	(NFP_NET_CFG_STATS_BASE + 0x98)
#define NFP_NET_CFG_STATS_APP1_FRAMES	(NFP_NET_CFG_STATS_BASE + 0xa0)
#define NFP_NET_CFG_STATS_APP1_BYTES	(NFP_NET_CFG_STATS_BASE + 0xa8)
#define NFP_NET_CFG_STATS_APP2_FRAMES	(NFP_NET_CFG_STATS_BASE + 0xb0)
#define NFP_NET_CFG_STATS_APP2_BYTES	(NFP_NET_CFG_STATS_BASE + 0xb8)
#define NFP_NET_CFG_STATS_APP3_FRAMES	(NFP_NET_CFG_STATS_BASE + 0xc0)
#define NFP_NET_CFG_STATS_APP3_BYTES	(NFP_NET_CFG_STATS_BASE + 0xc8)
#define NFP_NET_CFG_TXR_STATS_BASE	0x1000
#define NFP_NET_CFG_TXR_STATS(_x)	(NFP_NET_CFG_TXR_STATS_BASE + \
					 ((_x) * 0x10))
#define NFP_NET_CFG_RXR_STATS_BASE	0x1400
#define NFP_NET_CFG_RXR_STATS(_x)	(NFP_NET_CFG_RXR_STATS_BASE + \
					 ((_x) * 0x10))
#define NFP_NET_CFG_MBOX_BASE		0x1800
#define NFP_NET_CFG_MBOX_VAL_MAX_SZ	0x1F8
#define NFP_NET_CFG_MBOX_SIMPLE_CMD	0x0
#define NFP_NET_CFG_MBOX_SIMPLE_RET	0x4
#define NFP_NET_CFG_MBOX_SIMPLE_VAL	0x8
#define NFP_NET_CFG_MBOX_CMD_CTAG_FILTER_ADD 1
#define NFP_NET_CFG_MBOX_CMD_CTAG_FILTER_KILL 2
#define NFP_NET_CFG_MBOX_CMD_IPSEC 3
#define NFP_NET_CFG_MBOX_CMD_PCI_DSCP_PRIOMAP_SET	5
#define NFP_NET_CFG_MBOX_CMD_TLV_CMSG			6
#define NFP_NET_CFG_MBOX_CMD_DCB_UPDATE			7
#define NFP_NET_CFG_MBOX_CMD_MULTICAST_ADD		8
#define NFP_NET_CFG_MBOX_CMD_MULTICAST_DEL		9
#define NFP_NET_CFG_VLAN_FILTER		NFP_NET_CFG_MBOX_SIMPLE_VAL
#define  NFP_NET_CFG_VLAN_FILTER_VID	NFP_NET_CFG_VLAN_FILTER
#define  NFP_NET_CFG_VLAN_FILTER_PROTO	 (NFP_NET_CFG_VLAN_FILTER + 2)
#define NFP_NET_CFG_VLAN_FILTER_SZ	 0x0004
#define NFP_NET_CFG_MULTICAST		NFP_NET_CFG_MBOX_SIMPLE_VAL
#define NFP_NET_CFG_MULTICAST_MAC_HI	NFP_NET_CFG_MULTICAST
#define NFP_NET_CFG_MULTICAST_MAC_LO	(NFP_NET_CFG_MULTICAST + 6)
#define NFP_NET_CFG_MULTICAST_SZ	0x0006
#define NFP_NET_CFG_TLV_TYPE		0x00
#define   NFP_NET_CFG_TLV_TYPE_REQUIRED   0x8000
#define NFP_NET_CFG_TLV_LENGTH		0x02
#define   NFP_NET_CFG_TLV_LENGTH_INC	  4
#define NFP_NET_CFG_TLV_VALUE		0x04
#define NFP_NET_CFG_TLV_HEADER_REQUIRED 0x80000000
#define NFP_NET_CFG_TLV_HEADER_TYPE	0x7fff0000
#define NFP_NET_CFG_TLV_HEADER_LENGTH	0x0000ffff
#define NFP_NET_CFG_TLV_TYPE_UNKNOWN		0
#define NFP_NET_CFG_TLV_TYPE_RESERVED		1
#define NFP_NET_CFG_TLV_TYPE_END		2
#define NFP_NET_CFG_TLV_TYPE_ME_FREQ		3
#define NFP_NET_CFG_TLV_TYPE_MBOX		4
#define NFP_NET_CFG_TLV_TYPE_EXPERIMENTAL0	5
#define NFP_NET_CFG_TLV_TYPE_EXPERIMENTAL1	6
#define NFP_NET_CFG_TLV_TYPE_REPR_CAP		7
#define NFP_NET_CFG_TLV_TYPE_MBOX_CMSG_TYPES	10
#define NFP_NET_CFG_TLV_TYPE_CRYPTO_OPS		11  
#define NFP_NET_CFG_TLV_TYPE_VNIC_STATS		12
#define NFP_NET_CFG_TLV_TYPE_CRYPTO_OPS_RX_SCAN	13
struct device;
struct nfp_net_tlv_caps {
	u32 me_freq_mhz;
	unsigned int mbox_off;
	unsigned int mbox_len;
	u32 repr_cap;
	u32 mbox_cmsg_types;
	u32 crypto_ops;
	unsigned int crypto_enable_off;
	unsigned int vnic_stats_off;
	unsigned int vnic_stats_cnt;
	unsigned int tls_resync_ss:1;
};
int nfp_net_tlv_caps_parse(struct device *dev, u8 __iomem *ctrl_mem,
			   struct nfp_net_tlv_caps *caps);
#endif  
