{
  "module_name": "Makefile",
  "hash_id": "e89cbc4b76a25be8c0443e0b140518b3f2f4a087bd6baeb6294b10ea07e168c3",
  "original_prompt": "Ingested from linux-6.6.14/drivers/crypto/intel/qat/qat_c3xxx/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nccflags-y := -I $(srctree)/$(src)/../qat_common\nobj-$(CONFIG_CRYPTO_DEV_QAT_C3XXX) += qat_c3xxx.o\nqat_c3xxx-objs := adf_drv.o adf_c3xxx_hw_data.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}