#ifndef __IA_CSS_FRAME_FORMAT_H
#define __IA_CSS_FRAME_FORMAT_H
enum ia_css_frame_format {
	IA_CSS_FRAME_FORMAT_NV11 = 0,    
	IA_CSS_FRAME_FORMAT_NV12,        
	IA_CSS_FRAME_FORMAT_NV12_16,     
	IA_CSS_FRAME_FORMAT_NV12_TILEY,  
	IA_CSS_FRAME_FORMAT_NV16,        
	IA_CSS_FRAME_FORMAT_NV21,        
	IA_CSS_FRAME_FORMAT_NV61,        
	IA_CSS_FRAME_FORMAT_YV12,        
	IA_CSS_FRAME_FORMAT_YV16,        
	IA_CSS_FRAME_FORMAT_YUV420,      
	IA_CSS_FRAME_FORMAT_YUV420_16,   
	IA_CSS_FRAME_FORMAT_YUV422,      
	IA_CSS_FRAME_FORMAT_YUV422_16,   
	IA_CSS_FRAME_FORMAT_UYVY,        
	IA_CSS_FRAME_FORMAT_YUYV,        
	IA_CSS_FRAME_FORMAT_YUV444,      
	IA_CSS_FRAME_FORMAT_YUV_LINE,    
	IA_CSS_FRAME_FORMAT_RAW,	 
	IA_CSS_FRAME_FORMAT_RGB565,      
	IA_CSS_FRAME_FORMAT_PLANAR_RGB888,  
	IA_CSS_FRAME_FORMAT_RGBA888,	 
	IA_CSS_FRAME_FORMAT_QPLANE6,  
	IA_CSS_FRAME_FORMAT_BINARY_8,	 
	IA_CSS_FRAME_FORMAT_MIPI,	 
	IA_CSS_FRAME_FORMAT_RAW_PACKED,  
	IA_CSS_FRAME_FORMAT_CSI_MIPI_YUV420_8,	       
	IA_CSS_FRAME_FORMAT_CSI_MIPI_LEGACY_YUV420_8,  
	IA_CSS_FRAME_FORMAT_CSI_MIPI_YUV420_10        
};
#define IA_CSS_FRAME_FORMAT_NUM (IA_CSS_FRAME_FORMAT_CSI_MIPI_YUV420_10 + 1)
#define IA_CSS_FRAME_OUT_FORMAT_NUM	(IA_CSS_FRAME_FORMAT_RGBA888 + 1)
#endif  
