#ifndef __SH_CSS_DVS_INFO_H__
#define __SH_CSS_DVS_INFO_H__
#include <math_support.h>
#define DVS_NUM_BLOCKS_X(X)		(CEIL_MUL(CEIL_DIV((X), DVS_BLOCKDIM_X), 2))
#define DVS_NUM_BLOCKS_Y(X)		(CEIL_DIV((X), DVS_BLOCKDIM_Y_LUMA))
#define DVS_GDC_INTERP_METHOD HRT_GDC_BLI_MODE
#define DVS_INPUT_BYTES_PER_PIXEL (1)
#define DVS_NUM_BLOCKS_X_CHROMA(X)	(CEIL_DIV((X), DVS_BLOCKDIM_X))
#define DVS_NUM_BLOCKS_Y_CHROMA(X)	(CEIL_DIV((X), DVS_BLOCKDIM_Y_CHROMA))
#endif  
