{
  "module_name": "Makefile",
  "hash_id": "0fd70caab324a61f3b674ee43a55a9b9077f193d8e2b688f6ea938230c4d9ca3",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/realtek/rtlwifi/rtl8723be/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nrtl8723be-objs :=\t\t\\\n\t\tdm.o\t\t\\\n\t\tfw.o\t\t\\\n\t\thw.o\t\t\\\n\t\tled.o\t\t\\\n\t\tphy.o\t\t\\\n\t\tpwrseq.o\t\\\n\t\trf.o\t\t\\\n\t\tsw.o\t\t\\\n\t\ttable.o\t\t\\\n\t\ttrx.o\t\t\\\n\n\nobj-$(CONFIG_RTL8723BE) += rtl8723be.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}