{
  "module_name": "Makefile",
  "hash_id": "f217b5501c9679f02701349bc2dac58109f77b58c75fdebbe301af579a784458",
  "original_prompt": "Ingested from linux-6.6.14/drivers/video/fbdev/nvidia/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the nVidia framebuffer driver\n#\n\nobj-$(CONFIG_FB_NVIDIA)          += nvidiafb.o\n\nnvidiafb-y                       := nvidia.o nv_hw.o nv_setup.o \\\n\t\t\t            nv_accel.o nv_of.o\nnvidiafb-$(CONFIG_FB_NVIDIA_I2C) += nv_i2c.o\nnvidiafb-$(CONFIG_FB_NVIDIA_BACKLIGHT)  += nv_backlight.o\n\nnvidiafb-objs                    := $(nvidiafb-y)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}