{
  "module_name": "Makefile",
  "hash_id": "fddf01afd042a763457dde04170355b2b5b66167769849120a2ac204d28073ea",
  "original_prompt": "Ingested from linux-6.6.14/drivers/crypto/hisilicon/hpre/Makefile",
  "human_readable_source": "obj-$(CONFIG_CRYPTO_DEV_HISI_HPRE) += hisi_hpre.o\nhisi_hpre-objs = hpre_main.o hpre_crypto.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}