{
  "module_name": "Makefile",
  "hash_id": "7a5ffd20276c03cb5cd4b7b6fdf843a751476fe3f823c7f77b87d0706c04235c",
  "original_prompt": "Ingested from linux-6.6.14/tools/accounting/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nCC := $(CROSS_COMPILE)gcc\nCFLAGS := -I../../usr/include\n\nPROGS := getdelays procacct\n\nall: $(PROGS)\n\nclean:\n\trm -fr $(PROGS)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}