{
  "module_name": "Makefile",
  "hash_id": "4617a4329838e6ec2ce0cb9281b3783c44e72e0d0f2930fe203b3405f9f9c69d",
  "original_prompt": "Ingested from linux-6.6.14/net/ax25/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the Linux AX.25 layer.\n#\n\nobj-$(CONFIG_AX25) += ax25.o\n\nax25-y\t := ax25_addr.o ax25_dev.o ax25_iface.o ax25_in.o ax25_ip.o ax25_out.o \\\n\t    ax25_route.o ax25_std_in.o ax25_std_subr.o ax25_std_timer.o \\\n\t    ax25_subr.o ax25_timer.o ax25_uid.o af_ax25.o\nax25-$(CONFIG_AX25_DAMA_SLAVE) += ax25_ds_in.o ax25_ds_subr.o ax25_ds_timer.o\nax25-$(CONFIG_SYSCTL) += sysctl_net_ax25.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}