{
  "module_name": "Makefile",
  "hash_id": "3f8234f8c7c451848f6132d4741f03c85f3ed2ee67480a8f792f8dc2c73ec57b",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/sh/rcar/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nsnd-soc-rcar-objs\t:= core.o gen.o dma.o adg.o ssi.o ssiu.o src.o ctu.o mix.o dvc.o cmd.o debugfs.o\nobj-$(CONFIG_SND_SOC_RCAR)\t+= snd-soc-rcar.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}