{
  "module_name": "Makefile",
  "hash_id": "23b32626bcc00f0407c941142c9e08ff48a49881f8faa5aa064c3aeb0d16ff85",
  "original_prompt": "Ingested from linux-6.6.14/sound/drivers/pcsp/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nsnd-pcsp-objs := pcsp.o pcsp_lib.o pcsp_mixer.o pcsp_input.o\nobj-$(CONFIG_SND_PCSP) += snd-pcsp.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}