{
  "module_name": "Makefile",
  "hash_id": "2a5c4e5bfb058aeb7ac1676b55e4a4f3bd06a9dc0a9871eb3c660f3f8d1a8649",
  "original_prompt": "Ingested from linux-6.6.14/samples/coresight/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n\nobj-$(CONFIG_SAMPLE_CORESIGHT_SYSCFG) += coresight-cfg-sample.o\nccflags-y += -I$(srctree)/drivers/hwtracing/coresight\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}