{
  "module_name": "Makefile",
  "hash_id": "3080b3eb481e378c2e26f91a045831e3d61ed2543e1e60c208e64fec31c3da5a",
  "original_prompt": "Ingested from linux-6.6.14/sound/pci/asihpi/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nsnd-asihpi-objs := asihpi.o hpioctl.o hpimsginit.o\\\n\thpicmn.o hpifunc.o hpidebug.o hpidspcd.o\\\n\thpios.o hpi6000.o hpi6205.o hpimsgx.o\n\nobj-$(CONFIG_SND_ASIHPI) += snd-asihpi.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}