{
  "module_name": "Makefile",
  "hash_id": "ec19c913da83db36979c20b0e67226bfff3a2362f0b7d92a27a8f7640ef426ad",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/ath/carl9170/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\ncarl9170-objs := main.o usb.o cmd.o mac.o phy.o led.o fw.o tx.o rx.o\ncarl9170-$(CONFIG_CARL9170_DEBUGFS) += debug.o\n\nobj-$(CONFIG_CARL9170) += carl9170.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}