{
  "module_name": "Makefile",
  "hash_id": "62316f62f4db2d00191b148fb81689616975e4085e37dff7dda2563f126620a6",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/st/cw1200/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\ncw1200_core-y := \\\n\t\tfwio.o \\\n\t\ttxrx.o \\\n\t\tmain.o \\\n\t\tqueue.o \\\n\t\thwio.o \\\n\t\tbh.o \\\n\t\twsm.o \\\n\t\tsta.o \\\n\t\tscan.o \\\n\t\tdebug.o\ncw1200_core-$(CONFIG_PM)\t+= pm.o\n\n# CFLAGS_sta.o += -DDEBUG\n\ncw1200_wlan_sdio-y := cw1200_sdio.o\ncw1200_wlan_spi-y := cw1200_spi.o\n\nobj-$(CONFIG_CW1200) += cw1200_core.o\nobj-$(CONFIG_CW1200_WLAN_SDIO) += cw1200_wlan_sdio.o\nobj-$(CONFIG_CW1200_WLAN_SPI) += cw1200_wlan_spi.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}