{
  "module_name": "Makefile",
  "hash_id": "074dc573448eb03f82a906b63efa7f69adb1de25388b18a2cd3f064742c584a8",
  "original_prompt": "Ingested from linux-6.6.14/net/dns_resolver/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the Linux DNS Resolver.\n#\n\nobj-$(CONFIG_DNS_RESOLVER) += dns_resolver.o\n\ndns_resolver-y :=  dns_key.o dns_query.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}