{
  "module_name": "Kbuild",
  "hash_id": "1eae1786c2c960d6704478f751c70cda046b218c08d50dcad2eb4a265e2f57e1",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/nouveau/nvkm/engine/dma/Kbuild",
  "human_readable_source": "# SPDX-License-Identifier: MIT\nnvkm-y += nvkm/engine/dma/base.o\nnvkm-y += nvkm/engine/dma/nv04.o\nnvkm-y += nvkm/engine/dma/nv50.o\nnvkm-y += nvkm/engine/dma/gf100.o\nnvkm-y += nvkm/engine/dma/gf119.o\nnvkm-y += nvkm/engine/dma/gv100.o\n\nnvkm-y += nvkm/engine/dma/user.o\nnvkm-y += nvkm/engine/dma/usernv04.o\nnvkm-y += nvkm/engine/dma/usernv50.o\nnvkm-y += nvkm/engine/dma/usergf100.o\nnvkm-y += nvkm/engine/dma/usergf119.o\nnvkm-y += nvkm/engine/dma/usergv100.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}