{
  "module_name": "Makefile",
  "hash_id": "5881b6ac546db12123389116a3a030b0f62b958ce5e5707d4a81475e7ecd5861",
  "original_prompt": "Ingested from linux-6.6.14/lib/reed_solomon/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# This is a modified version of reed solomon lib,\n#\n\nobj-$(CONFIG_REED_SOLOMON) += reed_solomon.o\nobj-$(CONFIG_REED_SOLOMON_TEST) += test_rslib.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}