{
  "module_name": "Makefile",
  "hash_id": "c1434af0e70ee27dcbd8d602a4bdd1f352d5d9aa9cbc1fa9d55668674c2a01bf",
  "original_prompt": "Ingested from linux-6.6.14/fs/iomap/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-or-later\n#\n# Copyright (c) 2019 Oracle.\n# All Rights Reserved.\n#\n\nccflags-y += -I $(srctree)/$(src)\t\t# needed for trace events\n\nobj-$(CONFIG_FS_IOMAP)\t\t+= iomap.o\n\niomap-y\t\t\t\t+= trace.o \\\n\t\t\t\t   iter.o\niomap-$(CONFIG_BLOCK)\t\t+= buffered-io.o \\\n\t\t\t\t   direct-io.o \\\n\t\t\t\t   fiemap.o \\\n\t\t\t\t   seek.o\niomap-$(CONFIG_SWAP)\t\t+= swapfile.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}