{
  "module_name": "Makefile",
  "hash_id": "591013a5eb5360bc5f3dcd9b4ecfad62bd3d7c17b53ae7e9606a4b56aabaafa3",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/mellanox/mlx4/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_MLX4_CORE)\t\t+= mlx4_core.o\n\nmlx4_core-y :=\talloc.o catas.o cmd.o cq.o eq.o fw.o fw_qos.o icm.o intf.o \\\n\t\tmain.o mcg.o mr.o pd.o port.o profile.o qp.o reset.o sense.o \\\n\t\tsrq.o resource_tracker.o crdump.o\n\nobj-$(CONFIG_MLX4_EN)               += mlx4_en.o\n\nmlx4_en-y := \ten_main.o en_tx.o en_rx.o en_ethtool.o en_port.o en_cq.o \\\n\t\ten_resources.o en_netdev.o en_selftest.o en_clock.o\nmlx4_en-$(CONFIG_MLX4_EN_DCB) += en_dcb_nl.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}