{
  "module_name": "Makefile",
  "hash_id": "f6e05a8e71964f5eec24a9c5bf8d251fd3ae999ba00b96837e54dce4f91ef52c",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/platform/nvidia/tegra-vde/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\ntegra-vde-y := vde.o iommu.o dmabuf-cache.o h264.o v4l2.o\nobj-$(CONFIG_VIDEO_TEGRA_VDE)\t+= tegra-vde.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}