{
  "module_name": "Kbuild",
  "hash_id": "f01a4ad62e8f93c49607b51ee6acdad3d3499e2c9f6309a3c31c1c5111c9cfde",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/nouveau/nvkm/subdev/instmem/Kbuild",
  "human_readable_source": "# SPDX-License-Identifier: MIT\nnvkm-y += nvkm/subdev/instmem/base.o\nnvkm-y += nvkm/subdev/instmem/nv04.o\nnvkm-y += nvkm/subdev/instmem/nv40.o\nnvkm-y += nvkm/subdev/instmem/nv50.o\nnvkm-y += nvkm/subdev/instmem/gk20a.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}