{
  "module_name": "Makefile",
  "hash_id": "7038e90dc4d8e02235d131a35de3d6dc3272e84c6cde497eba4cd79bdb266a2e",
  "original_prompt": "Ingested from linux-6.6.14/security/yama/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_SECURITY_YAMA) := yama.o\n\nyama-y := yama_lsm.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}