{
  "module_name": "Makefile",
  "hash_id": "9e5b2b8a7cdeaf82c7a2f488b4121c5aa44a8f930230d1706e3ddd6bddc91e08",
  "original_prompt": "Ingested from linux-6.6.14/scripts/gdb/linux/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\nifdef building_out_of_srctree\n\nsymlinks := $(patsubst $(srctree)/$(src)/%,%,$(wildcard $(srctree)/$(src)/*.py))\n\nquiet_cmd_symlink = SYMLINK $@\n      cmd_symlink = ln -fsn $(patsubst $(obj)/%,$(abspath $(srctree))/$(src)/%,$@) $@\n\nalways-y += $(symlinks)\n$(addprefix $(obj)/, $(symlinks)): FORCE\n\t$(call if_changed,symlink)\n\nendif\n\nquiet_cmd_gen_constants_py = GEN     $@\n      cmd_gen_constants_py = \\\n\t$(CPP) -E -x c -P $(c_flags) $< > $@ ;\\\n\tsed -i '1,/<!-- end-c-headers -->/d;' $@\n\nalways-y += constants.py\n$(obj)/constants.py: $(src)/constants.py.in FORCE\n\t$(call if_changed_dep,gen_constants_py)\n\nclean-files := *.pyc *.pyo\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}