{
  "module_name": "Makefile",
  "hash_id": "bb9aeed6a30aeffb4e4cf0c86c0254fd363b63fb778d441aed1b627d5c123837",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/common/v4l2-tpg/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nv4l2-tpg-objs := v4l2-tpg-core.o v4l2-tpg-colors.o\n\nobj-$(CONFIG_VIDEO_V4L2_TPG) += v4l2-tpg.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}