




#ifndef	_RPC_CLNT_STAT_H
#define	_RPC_CLNT_STAT_H



#ifdef __cplusplus
extern "C" {
#endif

enum clnt_stat {
	RPC_SUCCESS = 0,			
	
	RPC_CANTENCODEARGS = 1,		
	RPC_CANTDECODERES = 2,		
	RPC_CANTSEND = 3,			
	RPC_CANTRECV = 4,
	
	RPC_TIMEDOUT = 5,			
	RPC_INTR = 18,			
	RPC_UDERROR = 23,			
	
	RPC_VERSMISMATCH = 6,		
	RPC_AUTHERROR = 7,		
	RPC_PROGUNAVAIL = 8,		
	RPC_PROGVERSMISMATCH = 9,	
	RPC_PROCUNAVAIL = 10,		
	RPC_CANTDECODEARGS = 11,		
	RPC_SYSTEMERROR = 12,		

	
	RPC_UNKNOWNHOST = 13,		
	RPC_UNKNOWNPROTO = 17,		
	RPC_UNKNOWNADDR = 19,		
	RPC_NOBROADCAST = 21,		

	
	RPC_RPCBFAILURE = 14,		
#define	RPC_PMAPFAILURE RPC_RPCBFAILURE
	RPC_PROGNOTREGISTERED = 15,	
	RPC_N2AXLATEFAILURE = 22,
	
	
	RPC_TLIERROR = 20,
	
	RPC_FAILED = 16,
	
	RPC_INPROGRESS = 24,
	RPC_STALERACHANDLE = 25,
	RPC_CANTCONNECT = 26,		
	RPC_XPRTFAILED = 27,		
	RPC_CANTCREATESTREAM = 28	
};

#ifdef __cplusplus
}
#endif

#endif	
