 
#ifndef MICROPY_INCLUDED_EXTMOD_MODUTIME_H
#define MICROPY_INCLUDED_EXTMOD_MODUTIME_H

#include "py/obj.h"

MP_DECLARE_CONST_FUN_OBJ_1(mp_time_mktime_obj);
MP_DECLARE_CONST_FUN_OBJ_1(mp_time_sleep_obj);
MP_DECLARE_CONST_FUN_OBJ_1(mp_time_sleep_ms_obj);
MP_DECLARE_CONST_FUN_OBJ_1(mp_time_sleep_us_obj);
MP_DECLARE_CONST_FUN_OBJ_0(mp_time_ticks_ms_obj);
MP_DECLARE_CONST_FUN_OBJ_0(mp_time_ticks_us_obj);
MP_DECLARE_CONST_FUN_OBJ_0(mp_time_ticks_cpu_obj);
MP_DECLARE_CONST_FUN_OBJ_2(mp_time_ticks_diff_obj);
MP_DECLARE_CONST_FUN_OBJ_2(mp_time_ticks_add_obj);
MP_DECLARE_CONST_FUN_OBJ_0(mp_time_time_ns_obj);

#endif 
