{
  "module_name": "Makefile",
  "hash_id": "fa69451d5c207db0279415a44cf096fb37f38516c815d8f58849ee54e07d3338",
  "original_prompt": "Ingested from linux-6.6.14/drivers/vdpa/mlx5/Makefile",
  "human_readable_source": "subdir-ccflags-y += -I$(srctree)/drivers/vdpa/mlx5/core\n\nobj-$(CONFIG_MLX5_VDPA_NET) += mlx5_vdpa.o\nmlx5_vdpa-$(CONFIG_MLX5_VDPA_NET) += net/mlx5_vnet.o core/resources.o core/mr.o net/debug.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}