
#ifndef MICROPY_INCLUDED_MIMXRT_TUSB_CONFIG_H
#define MICROPY_INCLUDED_MIMXRT_TUSB_CONFIG_H

#define CFG_TUSB_RHPORT0_MODE   (OPT_MODE_DEVICE | OPT_MODE_HIGH_SPEED)

#define CFG_TUSB_OS             (OPT_OS_NONE)

#define CFG_TUD_CDC             (1)
#define CFG_TUD_CDC_RX_BUFSIZE  (512)
#define CFG_TUD_CDC_TX_BUFSIZE  (512)

#endif 
