{
  "module_name": "Makefile",
  "hash_id": "49b5e1fb41aa1870a1cd72402bf964afd55efc469a465e2fb6fbba0f3d3221d7",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/stm/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nstm-drm-y := \\\n\tdrv.o \\\n\tltdc.o\n\nobj-$(CONFIG_DRM_STM_DSI) += dw_mipi_dsi-stm.o\n\nobj-$(CONFIG_DRM_STM) += stm-drm.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}