{
  "module_name": "Kbuild",
  "hash_id": "dbd1a7967685a60373d1ccd3e587c2f52f716550900843f4c4b594b49c50dccf",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/nouveau/nvkm/nvfw/Kbuild",
  "human_readable_source": "# SPDX-License-Identifier: MIT\nnvkm-y += nvkm/nvfw/fw.o\nnvkm-y += nvkm/nvfw/hs.o\nnvkm-y += nvkm/nvfw/ls.o\n\nnvkm-y += nvkm/nvfw/acr.o\nnvkm-y += nvkm/nvfw/flcn.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}