{
  "module_name": "Makefile",
  "hash_id": "fd2ff81ecebce8f166fd49abff3500695e38cb588704f981a8ca894327c0f558",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/ath/wil6210/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: ISC\nobj-$(CONFIG_WIL6210) += wil6210.o\n\nwil6210-y := main.o\nwil6210-y += netdev.o\nwil6210-y += cfg80211.o\nwil6210-y += pcie_bus.o\nwil6210-$(CONFIG_WIL6210_DEBUGFS) += debugfs.o\nwil6210-y += wmi.o\nwil6210-y += interrupt.o\nwil6210-y += txrx.o\nwil6210-y += txrx_edma.o\nwil6210-y += debug.o\nwil6210-y += rx_reorder.o\nwil6210-y += fw.o\nwil6210-y += pm.o\nwil6210-y += pmc.o\nwil6210-$(CONFIG_WIL6210_TRACING) += trace.o\nwil6210-y += wil_platform.o\nwil6210-y += ethtool.o\nwil6210-y += wil_crash_dump.o\nwil6210-y += p2p.o\n\n# for tracing framework to find trace.h\nCFLAGS_trace.o := -I$(src)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}