#ifndef _SYS_MNTENT_H
#define	_SYS_MNTENT_H
#define	MNTMAXSTR	128
#define	MNTTYPE_ZFS	"zfs"		 
#define	MOUNT_SUCCESS	0x00		 
#define	MOUNT_USAGE	0x01		 
#define	MOUNT_SYSERR	0x02		 
#define	MOUNT_SOFTWARE	0x04		 
#define	MOUNT_USER	0x08		 
#define	MOUNT_FILEIO	0x10		 
#define	MOUNT_FAIL	0x20		 
#define	MOUNT_SOMEOK	0x40		 
#define	MOUNT_BUSY	0x80		 
#define	MNTOPT_ASYNC	"async"		 
#define	MNTOPT_ATIME	"atime"		 
#define	MNTOPT_NOATIME	"noatime"	 
#define	MNTOPT_AUTO	"auto"		 
#define	MNTOPT_NOAUTO	"noauto"	 
#define	MNTOPT_CONTEXT	"context"	 
#define	MNTOPT_FSCONTEXT "fscontext"	 
#define	MNTOPT_DEFCONTEXT "defcontext"	 
#define	MNTOPT_ROOTCONTEXT "rootcontext"  
#define	MNTOPT_DEFAULTS	"defaults"	 
#define	MNTOPT_DEVICES	"dev"		 
#define	MNTOPT_NODEVICES "nodev"	 
#define	MNTOPT_DIRATIME	"diratime"	 
#define	MNTOPT_NODIRATIME "nodiratime"	 
#define	MNTOPT_DIRSYNC	"dirsync"	 
#define	MNTOPT_EXEC	"exec"		 
#define	MNTOPT_NOEXEC	"noexec"	 
#define	MNTOPT_GROUP	"group"		 
#define	MNTOPT_NOGROUP	"nogroup"	 
#define	MNTOPT_IVERSION	"iversion"	 
#define	MNTOPT_NOIVERSION "noiversion"	 
#define	MNTOPT_NBMAND	"mand"		 
#define	MNTOPT_NONBMAND	"nomand"	 
#define	MNTOPT_NETDEV	"_netdev"	 
#define	MNTOPT_NOFAIL	"nofail"	 
#define	MNTOPT_RELATIME	"relatime"	 
#define	MNTOPT_NORELATIME "norelatime"	 
#define	MNTOPT_STRICTATIME "strictatime"  
#define	MNTOPT_NOSTRICTATIME "nostrictatime"  
#define	MNTOPT_LAZYTIME "lazytime"	 
#ifdef __linux__
#define	MNTOPT_SETUID	"suid"		 
#define	MNTOPT_NOSETUID	"nosuid"	 
#elif defined(__FreeBSD__)
#define	MNTOPT_SETUID	"setuid"	 
#define	MNTOPT_NOSETUID	"nosetuid"	 
#else
#error "unknown OS"
#endif
#define	MNTOPT_OWNER	"owner"		 
#define	MNTOPT_NOOWNER	"noowner"	 
#define	MNTOPT_REMOUNT	"remount"	 
#define	MNTOPT_RO	"ro"		 
#define	MNTOPT_RW	"rw"		 
#define	MNTOPT_SYNC	"sync"		 
#define	MNTOPT_USER	"user"		 
#define	MNTOPT_NOUSER	"nouser"	 
#define	MNTOPT_USERS	"users"		 
#define	MNTOPT_NOUSERS	"nousers"	 
#define	MNTOPT_SUB	"sub"		 
#define	MNTOPT_NOSUB	"nosub"		 
#define	MNTOPT_QUIET	"quiet"		 
#define	MNTOPT_LOUD	"loud"		 
#define	MNTOPT_BIND	"bind"		 
#define	MNTOPT_RBIND	"rbind"		 
#define	MNTOPT_DIRXATTR	"dirxattr"	 
#define	MNTOPT_SAXATTR	"saxattr"	 
#define	MNTOPT_XATTR	"xattr"		 
#define	MNTOPT_NOXATTR	"noxattr"	 
#define	MNTOPT_COMMENT	"comment"	 
#define	MNTOPT_ZFSUTIL	"zfsutil"	 
#define	MNTOPT_ACL	"acl"		 
#define	MNTOPT_NOACL	"noacl"		 
#define	MNTOPT_POSIXACL	"posixacl"	 
#define	MNTOPT_MNTPOINT	"mntpoint"	 
#define	MNTOPT_CASESENSITIVE	"casesensitive"		 
#define	MNTOPT_CASEINSENSITIVE	"caseinsensitive"	 
#define	MNTOPT_CASEMIXED	"casemixed"		 
#endif	 
