{
  "module_name": "Makefile",
  "hash_id": "5b5791abcce02fb10fb24fae6abee0a3ce8a08cea70ee45daa141fdace6d12a6",
  "original_prompt": "Ingested from linux-6.6.14/drivers/base/power/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_PM)\t+= sysfs.o generic_ops.o common.o qos.o runtime.o wakeirq.o\nobj-$(CONFIG_PM_SLEEP)\t+= main.o wakeup.o wakeup_stats.o\nobj-$(CONFIG_PM_TRACE_RTC)\t+= trace.o\nobj-$(CONFIG_PM_GENERIC_DOMAINS)\t+=  domain.o domain_governor.o\nobj-$(CONFIG_HAVE_CLK)\t+= clock_ops.o\nobj-$(CONFIG_PM_QOS_KUNIT_TEST) += qos-test.o\n\nccflags-$(CONFIG_DEBUG_DRIVER) := -DDEBUG\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}