{
  "module_name": "Makefile",
  "hash_id": "56f058896f0914e13fb3956e693909f967df365f2c1d16f85d93c491dbb5b1df",
  "original_prompt": "Ingested from linux-6.6.14/drivers/crypto/intel/qat/qat_c62xvf/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nccflags-y := -I $(srctree)/$(src)/../qat_common\nobj-$(CONFIG_CRYPTO_DEV_QAT_C62XVF) += qat_c62xvf.o\nqat_c62xvf-objs := adf_drv.o adf_c62xvf_hw_data.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}