{
  "module_name": "Makefile",
  "hash_id": "a51077e8191633973e74645c2aa665b8bf7911f5ae5d9dc38e1b920bd4ca9c35",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/platform/amphion/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for NXP VPU driver\n\namphion-vpu-objs += vpu_drv.o \\\n\t\t\tvpu_core.o \\\n\t\t\tvpu_mbox.o \\\n\t\t\tvpu_v4l2.o \\\n\t\t\tvpu_helpers.o \\\n\t\t\tvpu_cmds.o \\\n\t\t\tvpu_msgs.o \\\n\t\t\tvpu_rpc.o \\\n\t\t\tvpu_imx8q.o \\\n\t\t\tvpu_windsor.o \\\n\t\t\tvpu_malone.o \\\n\t\t\tvpu_color.o \\\n\t\t\tvdec.o  \\\n\t\t\tvenc.o \\\n\t\t\tvpu_dbg.o\n\nobj-$(CONFIG_VIDEO_AMPHION_VPU) += amphion-vpu.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}