{
  "module_name": "Makefile",
  "hash_id": "6bd0419b9ee4e871943e84f609c3b5f17c1f877d9b70e53a7ff1a31669e73b21",
  "original_prompt": "Ingested from linux-6.6.14/drivers/iommu/arm/arm-smmu-v3/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_ARM_SMMU_V3) += arm_smmu_v3.o\narm_smmu_v3-objs-y += arm-smmu-v3.o\narm_smmu_v3-objs-$(CONFIG_ARM_SMMU_V3_SVA) += arm-smmu-v3-sva.o\narm_smmu_v3-objs := $(arm_smmu_v3-objs-y)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}