{
  "module_name": "Makefile",
  "hash_id": "fdd5d1bb00ebbbeff52d4a9f18d51759a646f09a0a190e2d92d75301852626a1",
  "original_prompt": "Ingested from linux-6.6.14/drivers/scsi/smartpqi/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_SCSI_SMARTPQI) += smartpqi.o\nsmartpqi-objs := smartpqi_init.o smartpqi_sis.o smartpqi_sas_transport.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}