{
  "module_name": "Makefile",
  "hash_id": "ec50aeedf8c32b1977106e4d72ef901c327352891f89e3840e5e57ad637e7ee2",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/marvell/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_LIBERTAS)\t\t+= libertas/\n\nobj-$(CONFIG_LIBERTAS_THINFIRM)\t+= libertas_tf/\nobj-$(CONFIG_MWIFIEX)\t+= mwifiex/\n\nobj-$(CONFIG_MWL8K)\t+= mwl8k.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}