{
  "module_name": "Makefile",
  "hash_id": "91a446c60d6fa7445537f77202330cf0b4006c49b1584caaad6ec6b014697b25",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/pci/netup_unidvb/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nnetup-unidvb-objs += netup_unidvb_core.o\nnetup-unidvb-objs += netup_unidvb_i2c.o\nnetup-unidvb-objs += netup_unidvb_ci.o\nnetup-unidvb-objs += netup_unidvb_spi.o\n\nobj-$(CONFIG_DVB_NETUP_UNIDVB) += netup-unidvb.o\n\nccflags-y += -I $(srctree)/drivers/media/dvb-frontends\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}