{
  "module_name": "Makefile",
  "hash_id": "11d147e9f058d90a78051654bca06dec7ab39f96ef4db137d6986b78b48b9284",
  "original_prompt": "Ingested from linux-6.6.14/drivers/dax/pmem/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_DEV_DAX_PMEM) += dax_pmem.o\nobj-$(CONFIG_DEV_DAX_PMEM) += dax_pmem_core.o\n\ndax_pmem-y := pmem.o\ndax_pmem_core-y := core.o\ndax_pmem_compat-y := compat.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}