{
  "module_name": "Makefile",
  "hash_id": "31a4d101c3b44cb778e075223e42682a84f577d4039dd82227f9d7f1aa71bb19",
  "original_prompt": "Ingested from linux-6.6.14/drivers/pinctrl/nomadik/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Nomadik family pin control drivers\nobj-$(CONFIG_PINCTRL_ABX500)\t+= pinctrl-abx500.o\nobj-$(CONFIG_PINCTRL_AB8500)\t+= pinctrl-ab8500.o\nobj-$(CONFIG_PINCTRL_AB8505)\t+= pinctrl-ab8505.o\nobj-$(CONFIG_PINCTRL_NOMADIK)\t+= pinctrl-nomadik.o\nobj-$(CONFIG_PINCTRL_STN8815)\t+= pinctrl-nomadik-stn8815.o\nobj-$(CONFIG_PINCTRL_DB8500)\t+= pinctrl-nomadik-db8500.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}