{
  "module_name": "Makefile",
  "hash_id": "d86fb77d58087ca73be3c6b2125fa5e845d9ad33f23fdf3175cc741cb271ed61",
  "original_prompt": "Ingested from linux-6.6.14/drivers/soc/bcm/brcmstb/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-y\t\t\t\t+= common.o biuctrl.o\nobj-$(CONFIG_BRCMSTB_PM)\t+= pm/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}