

enum linux_mptcp_mib_field {
	MPTCP_MIB_NUM = 0,
	MPTCP_MIB_MPCAPABLEPASSIVE,	
	MPTCP_MIB_MPCAPABLEACTIVE,	
	MPTCP_MIB_MPCAPABLEACTIVEACK,	
	MPTCP_MIB_MPCAPABLEPASSIVEACK,	
	MPTCP_MIB_MPCAPABLEPASSIVEFALLBACK,
	MPTCP_MIB_MPCAPABLEACTIVEFALLBACK, 
	MPTCP_MIB_TOKENFALLBACKINIT,	
	MPTCP_MIB_RETRANSSEGS,		
	MPTCP_MIB_JOINNOTOKEN,		
	MPTCP_MIB_JOINSYNRX,		
	MPTCP_MIB_JOINSYNACKRX,		
	MPTCP_MIB_JOINSYNACKMAC,	
	MPTCP_MIB_JOINACKRX,		
	MPTCP_MIB_JOINACKMAC,		
	MPTCP_MIB_DSSNOMATCH,		
	MPTCP_MIB_INFINITEMAPTX,	
	MPTCP_MIB_INFINITEMAPRX,	
	MPTCP_MIB_DSSTCPMISMATCH,	
	MPTCP_MIB_DATACSUMERR,		
	MPTCP_MIB_OFOQUEUETAIL,	
	MPTCP_MIB_OFOQUEUE,		
	MPTCP_MIB_OFOMERGE,		
	MPTCP_MIB_NODSSWINDOW,		
	MPTCP_MIB_DUPDATA,		
	MPTCP_MIB_ADDADDR,		
	MPTCP_MIB_ADDADDRTX,		
	MPTCP_MIB_ADDADDRTXDROP,	
	MPTCP_MIB_ECHOADD,		
	MPTCP_MIB_ECHOADDTX,		
	MPTCP_MIB_ECHOADDTXDROP,	
	MPTCP_MIB_PORTADD,		
	MPTCP_MIB_ADDADDRDROP,		
	MPTCP_MIB_JOINPORTSYNRX,	
	MPTCP_MIB_JOINPORTSYNACKRX,	
	MPTCP_MIB_JOINPORTACKRX,	
	MPTCP_MIB_MISMATCHPORTSYNRX,	
	MPTCP_MIB_MISMATCHPORTACKRX,	
	MPTCP_MIB_RMADDR,		
	MPTCP_MIB_RMADDRDROP,		
	MPTCP_MIB_RMADDRTX,		
	MPTCP_MIB_RMADDRTXDROP,		
	MPTCP_MIB_RMSUBFLOW,		
	MPTCP_MIB_MPPRIOTX,		
	MPTCP_MIB_MPPRIORX,		
	MPTCP_MIB_MPFAILTX,		
	MPTCP_MIB_MPFAILRX,		
	MPTCP_MIB_MPFASTCLOSETX,	
	MPTCP_MIB_MPFASTCLOSERX,	
	MPTCP_MIB_MPRSTTX,		
	MPTCP_MIB_MPRSTRX,		
	MPTCP_MIB_RCVPRUNED,		
	MPTCP_MIB_SUBFLOWSTALE,		
	MPTCP_MIB_SUBFLOWRECOVER,	
	MPTCP_MIB_SNDWNDSHARED,		
	MPTCP_MIB_RCVWNDSHARED,		
	MPTCP_MIB_RCVWNDCONFLICTUPDATE,	
	MPTCP_MIB_RCVWNDCONFLICT,	
	__MPTCP_MIB_MAX
};

#define LINUX_MIB_MPTCP_MAX	__MPTCP_MIB_MAX
struct mptcp_mib {
	unsigned long mibs[LINUX_MIB_MPTCP_MAX];
};

static inline void MPTCP_ADD_STATS(struct net *net,
				   enum linux_mptcp_mib_field field,
				   int val)
{
	if (likely(net->mib.mptcp_statistics))
		SNMP_ADD_STATS(net->mib.mptcp_statistics, field, val);
}

static inline void MPTCP_INC_STATS(struct net *net,
				   enum linux_mptcp_mib_field field)
{
	if (likely(net->mib.mptcp_statistics))
		SNMP_INC_STATS(net->mib.mptcp_statistics, field);
}

static inline void __MPTCP_INC_STATS(struct net *net,
				     enum linux_mptcp_mib_field field)
{
	if (likely(net->mib.mptcp_statistics))
		__SNMP_INC_STATS(net->mib.mptcp_statistics, field);
}

bool mptcp_mib_alloc(struct net *net);
