{
  "module_name": "Makefile",
  "hash_id": "697a23d9279d140461fd07995b6ff0a0d93f2148cc7901bf31488264f7830f9e",
  "original_prompt": "Ingested from linux-6.6.14/net/bluetooth/cmtp/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the Linux Bluetooth CMTP layer\n#\n\nobj-$(CONFIG_BT_CMTP) += cmtp.o\n\ncmtp-objs := core.o sock.o capi.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}