{
  "module_name": "Makefile",
  "hash_id": "f643fed408230868e5a2fdefc50ed483d57689c5b8e179e5a0c94a27dd49122f",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/mount_setattr/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for mount selftests.\nCFLAGS = -g $(KHDR_INCLUDES) -Wall -O2 -pthread\n\nTEST_GEN_PROGS := mount_setattr_test\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}