{
  "module_name": "Makefile",
  "hash_id": "3dae339e42f4f25f1753e758b88a75b32b9c3cadb33df26ea21e896c1124670c",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/intel/ixgbevf/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Copyright(c) 1999 - 2018 Intel Corporation.\n#\n# Makefile for the Intel(R) 82599 VF ethernet driver\n#\n\nobj-$(CONFIG_IXGBEVF) += ixgbevf.o\n\nixgbevf-objs := vf.o \\\n                mbx.o \\\n                ethtool.o \\\n                ixgbevf_main.o\nixgbevf-$(CONFIG_IXGBEVF_IPSEC) += ipsec.o\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}