{
  "module_name": "Makefile",
  "hash_id": "4ba263b4b8335e29067b2b3f92f0b3ea325098ebc177464d0e5f7ba97a7794e1",
  "original_prompt": "Ingested from linux-6.6.14/samples/hidraw/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nuserprogs-always-y += hid-example\n\nuserccflags += -I usr/include\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}