{
  "module_name": "Makefile",
  "hash_id": "2739b636d87ed6e28a6a3cbefe3bb21378d7d2d993e6547daad496c1d33b0ac0",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/dvb-frontends/drx39xyj/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\ndrx39xyj-objs := drxj.o\n\nobj-$(CONFIG_DVB_DRX39XYJ) += drx39xyj.o\n\nccflags-y += -I$(srctree)/drivers/media/tuners/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}