{
  "module_name": "Makefile",
  "hash_id": "e19a706dedb11b5a95a5677c60725e63c3d158e2c6220fdf15b5338c95983241",
  "original_prompt": "Ingested from linux-6.6.14/virt/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-y\t+= lib/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}