{
  "module_name": "Makefile",
  "hash_id": "1be3612f8abcfe3b3beefa67acf4982a00e5cbe6d11fbb05ae0fdd758acad883",
  "original_prompt": "Ingested from linux-6.6.14/drivers/mux/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for multiplexer devices.\n#\n\nmux-core-objs\t\t\t:= core.o\nmux-adg792a-objs\t\t:= adg792a.o\nmux-adgs1408-objs\t\t:= adgs1408.o\nmux-gpio-objs\t\t\t:= gpio.o\nmux-mmio-objs\t\t\t:= mmio.o\n\nobj-$(CONFIG_MULTIPLEXER)\t+= mux-core.o\nobj-$(CONFIG_MUX_ADG792A)\t+= mux-adg792a.o\nobj-$(CONFIG_MUX_ADGS1408)\t+= mux-adgs1408.o\nobj-$(CONFIG_MUX_GPIO)\t\t+= mux-gpio.o\nobj-$(CONFIG_MUX_MMIO)\t\t+= mux-mmio.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}