{
  "module_name": "Makefile",
  "hash_id": "63f6d41c3459db592e99b29a2c825ed4cb395d7e81388dd2eb14b8f2afb9d288",
  "original_prompt": "Ingested from linux-6.6.14/drivers/platform/x86/intel/pmt/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for linux/drivers/platform/x86/intel/pmt\n# Intel Platform Monitoring Technology Drivers\n#\n\nobj-$(CONFIG_INTEL_PMT_CLASS)\t\t+= pmt_class.o\npmt_class-y\t\t\t\t:= class.o\nobj-$(CONFIG_INTEL_PMT_TELEMETRY)\t+= pmt_telemetry.o\npmt_telemetry-y\t\t\t\t:= telemetry.o\nobj-$(CONFIG_INTEL_PMT_CRASHLOG)\t+= pmt_crashlog.o\npmt_crashlog-y\t\t\t\t:= crashlog.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}