{
  "module_name": "Makefile",
  "hash_id": "e55c8e402747058c931e1b218a9fe723cfe5cca5fae7c1441edb9d61f7c6703d",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/sof/xtensa/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: (GPL-2.0-only OR BSD-3-Clause)\n\nsnd-sof-xtensa-dsp-objs := core.o\n\nobj-$(CONFIG_SND_SOC_SOF_XTENSA) += snd-sof-xtensa-dsp.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}