{
  "module_name": "Makefile",
  "hash_id": "d75a63b9e2382aeff671e42a65b40fa7ba258c55ea150832a90b0b6a32e9ebe6",
  "original_prompt": "Ingested from linux-6.6.14/samples/trace_events/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n# builds the trace events example kernel modules;\n# then to use one (as root):  insmod <module_name.ko>\n\n# If you include a trace header outside of include/trace/events\n# then the file that does the #define CREATE_TRACE_POINTS must\n# have that tracer file in its main search path. This is because\n# define_trace.h will include it, and must be able to find it from\n# the include/trace directory.\n#\n# Here trace-events-sample.c does the CREATE_TRACE_POINTS.\n#\nCFLAGS_trace-events-sample.o := -I$(src)\nCFLAGS_trace_custom_sched.o := -I$(src)\n\nobj-$(CONFIG_SAMPLE_TRACE_EVENTS) += trace-events-sample.o\nobj-$(CONFIG_SAMPLE_TRACE_CUSTOM_EVENTS) += trace_custom_sched.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}