{
  "module_name": "Makefile",
  "hash_id": "fb9a037d0e0b1c3dd8fb29bac689b23606f5ad06d8b0ee6ff2133dae3a0adc35",
  "original_prompt": "Ingested from linux-6.6.14/drivers/video/fbdev/omap/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for the OMAP1 framebuffer device driver\n#\n\nobj-$(CONFIG_FB_OMAP) += omapfb.o\n\nifdef CONFIG_FB_OMAP\n# must be built-in\nobj-y += lcd_dma.o\nendif\n\nobjs-yy := omapfb_main.o lcdc.o\n\nobjs-y$(CONFIG_FB_OMAP_LCDC_EXTERNAL) += sossi.o\n\nobjs-y$(CONFIG_FB_OMAP_LCDC_HWA742) += hwa742.o\n\nlcds-y$(CONFIG_MACH_AMS_DELTA) += lcd_ams_delta.o\nlcds-y$(CONFIG_MACH_OMAP_PALMTE) += lcd_palmte.o\n\nlcds-y$(CONFIG_FB_OMAP_LCD_MIPID) += lcd_mipid.o\n\nomapfb-objs := $(objs-yy)\n\nobj-$(CONFIG_FB_OMAP) += $(lcds-yy)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}