 
 

#ifndef __FIFO_MONITOR_GLOBAL_H_INCLUDED__
#define __FIFO_MONITOR_GLOBAL_H_INCLUDED__

#define IS_FIFO_MONITOR_VERSION_2

 
#define HIVE_ISP_CSS_STREAM_SWITCH_ISP       0
#define HIVE_ISP_CSS_STREAM_SWITCH_SP        1
#define HIVE_ISP_CSS_STREAM_SWITCH_NONE      2

#endif  
