{
  "module_name": "Makefile",
  "hash_id": "ed6ef19ec8d16c69b5a6adfb8b3c38d9b406ee1ddab855e0e4f26cb043f4258a",
  "original_prompt": "Ingested from linux-6.6.14/drivers/platform/x86/intel/int3472/Makefile",
  "human_readable_source": "obj-$(CONFIG_INTEL_SKL_INT3472)\t\t+= intel_skl_int3472_discrete.o \\\n\t\t\t\t\t   intel_skl_int3472_tps68470.o\nintel_skl_int3472_discrete-y\t\t:= discrete.o clk_and_regulator.o led.o common.o\nintel_skl_int3472_tps68470-y\t\t:= tps68470.o tps68470_board_data.o common.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}