{
  "module_name": "Makefile",
  "hash_id": "2bcea3d89605c18cf53eeec13d15f7a0d0e0beafcbb59372af7128e306004083",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/sof/mediatek/mt8195/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: (GPL-2.0-only OR BSD-3-Clause)\nsnd-sof-mt8195-objs := mt8195.o mt8195-clk.o mt8195-loader.o\nobj-$(CONFIG_SND_SOC_SOF_MT8195) += snd-sof-mt8195.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}