{
  "module_name": "Makefile",
  "hash_id": "555f77b9d8607331727b53ae48678f5be63334fb7247a816bcfd619fdbce42ba",
  "original_prompt": "Ingested from linux-6.6.14/tools/perf/arch/arm/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nifndef NO_DWARF\nPERF_HAVE_DWARF_REGS := 1\nendif\nPERF_HAVE_JITDUMP := 1\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}