{
  "module_name": "Makefile",
  "hash_id": "588b021bc083f2af653645911e1acf9d4f51dea8a4913d2de69ee5184a4424a8",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/can/rcar/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n#  Makefile for the Renesas R-Car CAN & CAN FD controller drivers\n#\n\nobj-$(CONFIG_CAN_RCAR)\t\t+= rcar_can.o\nobj-$(CONFIG_CAN_RCAR_CANFD)\t+= rcar_canfd.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}