{
  "module_name": "Makefile",
  "hash_id": "acd8ec38aaf9741317c753f27a47fbef709a2497ba0d3571f54c3f589320b0fb",
  "original_prompt": "Ingested from linux-6.6.14/sound/isa/es1688/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for ALSA\n# Copyright (c) 2001 by Jaroslav Kysela <perex@perex.cz>\n#\n\nsnd-es1688-lib-objs := es1688_lib.o\nsnd-es1688-objs := es1688.o\n\n# Toplevel Module Dependency\nobj-$(CONFIG_SND_ES1688) += snd-es1688.o snd-es1688-lib.o\nobj-$(CONFIG_SND_GUSEXTREME) += snd-es1688-lib.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}