{
  "module_name": "Makefile",
  "hash_id": "c72ff407884e51468ea833cb00c81a4ed0294115d21374a148510c657bef477c",
  "original_prompt": "Ingested from linux-6.6.14/sound/firewire/fireworks/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nsnd-fireworks-objs := fireworks_transaction.o fireworks_command.o \\\n\t\t      fireworks_stream.o fireworks_proc.o fireworks_midi.o \\\n\t\t      fireworks_pcm.o fireworks_hwdep.o fireworks.o\nobj-$(CONFIG_SND_FIREWORKS) += snd-fireworks.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}