{
  "module_name": "Makefile",
  "hash_id": "af8d1695100220ca8544d3f1ce80a5b16c456b8a91040bd5e0873b544da070fd",
  "original_prompt": "Ingested from linux-6.6.14/drivers/mtd/lpddr/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# linux/drivers/mtd/lpddr/Makefile\n#\n\nobj-$(CONFIG_MTD_QINFO_PROBE)\t+= qinfo_probe.o\nobj-$(CONFIG_MTD_LPDDR)\t+= lpddr_cmds.o\nobj-$(CONFIG_MTD_LPDDR2_NVM) += lpddr2_nvm.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}