{
  "module_name": "Makefile",
  "hash_id": "eb973f0b20fa1f200d3583787cc8037a4979d876de2811e8ee6a8ac85671e141",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/platform/chips-media/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n\ncoda-vpu-objs := coda-common.o coda-bit.o coda-gdi.o coda-h264.o coda-mpeg2.o coda-mpeg4.o coda-jpeg.o\n\nobj-$(CONFIG_VIDEO_CODA) += coda-vpu.o\nobj-$(CONFIG_VIDEO_IMX_VDOA) += imx-vdoa.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}