#ifndef MICROPY_INCLUDED_PORTS_UNIX_VARIANTS_BICAMERAL_MPCONFIGVARIANT_H
#define MICROPY_INCLUDED_PORTS_UNIX_VARIANTS_BICAMERAL_MPCONFIGVARIANT_H

#define MICROPY_ENABLE_COMPILER     (0)
#define MICROPY_PY_BUILTINS_COMPILE (0)
#define MICROPY_PY_BUILTINS_EXECFILE (0)
#define MICROPY_PY_BUILTINS_EVAL_EXEC (0)
#define MICROPY_PY_MICROPYTHON_MEM_INFO (0)
#define MICROPY_PY_NETWORK          (0)
#define MICROPY_PY_SOCKET           (0)
#define MICROPY_PERSISTENT_CODE_LOAD (1)

// Enable minimal features for running .mpy
#define MICROPY_ENABLE_GC (1)
#define MICROPY_ENABLE_FINALISER (1)
#define MICROPY_STACKLESS (0)
// REPL Helper needed for main.c to link
#define MICROPY_HELPER_REPL (1)
#define MICROPY_READLINE_HISTORY_SIZE (0)

// Keyboard Interrupt
#define MICROPY_KBD_EXCEPTION (1)

// Modules
#define MICROPY_PY_OS (1)
#define MICROPY_PY_SYS (1)

#endif