{
  "module_name": "Makefile",
  "hash_id": "0a04bd4953ecd8a14655949f85a04b6f6d48c20d7e46c2e51e1bfcecacb61f95",
  "original_prompt": "Ingested from linux-6.6.14/tools/kvm/kvm_stat/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\ninclude ../../scripts/Makefile.include\ninclude ../../scripts/utilities.mak\nBINDIR=usr/bin\nMANDIR=usr/share/man\nMAN1DIR=$(MANDIR)/man1\n\nMAN1=kvm_stat.1\n\nA2X=a2x\na2x_path := $(call get-executable,$(A2X))\n\nall: man\n\nifneq ($(findstring $(MAKEFLAGS),s),s)\n  ifneq ($(V),1)\n     QUIET_A2X = @echo '  A2X     '$@;\n  endif\nendif\n\n%.1: %.txt\nifeq ($(a2x_path),)\n\t$(error \"You need to install asciidoc for man pages\")\nelse\n\t$(QUIET_A2X)$(A2X) --doctype manpage --format manpage $<\nendif\n\nclean:\n\trm -f $(MAN1)\n\nman: $(MAN1)\n\ninstall-man: man\n\tinstall -d -m 755 $(INSTALL_ROOT)/$(MAN1DIR)\n\tinstall -m 644 kvm_stat.1 $(INSTALL_ROOT)/$(MAN1DIR)\n\ninstall-tools:\n\tinstall -d -m 755 $(INSTALL_ROOT)/$(BINDIR)\n\tinstall -m 755 -p \"kvm_stat\" \"$(INSTALL_ROOT)/$(BINDIR)/$(TARGET)\"\n\ninstall: install-tools install-man\n.PHONY: all clean man install-tools install-man install\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}