{
  "module_name": "Makefile",
  "hash_id": "6cc6ba01a53b69398df68008a5cb19b7497e26bc2d7b3bff455bfe73648c7f3b",
  "original_prompt": "Ingested from linux-6.6.14/drivers/soc/mediatek/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_MTK_CMDQ) += mtk-cmdq-helper.o\nobj-$(CONFIG_MTK_DEVAPC) += mtk-devapc.o\nobj-$(CONFIG_MTK_INFRACFG) += mtk-infracfg.o\nobj-$(CONFIG_MTK_PMIC_WRAP) += mtk-pmic-wrap.o\nobj-$(CONFIG_MTK_REGULATOR_COUPLER) += mtk-regulator-coupler.o\nobj-$(CONFIG_MTK_MMSYS) += mtk-mmsys.o\nobj-$(CONFIG_MTK_MMSYS) += mtk-mutex.o\nobj-$(CONFIG_MTK_SVS) += mtk-svs.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}