{
  "module_name": "Makefile",
  "hash_id": "cb58de08c9f76c364950b311543fd87a0fd7d925130fd8b587fc0ec3338054fc",
  "original_prompt": "Ingested from linux-6.6.14/drivers/vfio/pci/pds/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Copyright (c) 2023 Advanced Micro Devices, Inc.\n\nobj-$(CONFIG_PDS_VFIO_PCI) += pds-vfio-pci.o\n\npds-vfio-pci-y := \\\n\tcmds.o\t\t\\\n\tdirty.o\t\t\\\n\tlm.o\t\t\\\n\tpci_drv.o\t\\\n\tvfio_dev.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}