{
  "module_name": "Makefile",
  "hash_id": "c98e13145ed3eaaa7408be4340dedb9bc18d06e3e779f24e5cf1f26fbb6c73ea",
  "original_prompt": "Ingested from linux-6.6.14/drivers/nfc/st-nci/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n#\n# Makefile for ST_NCI NCI based NFC driver\n#\n\nst-nci-objs = ndlc.o core.o se.o vendor_cmds.o\nobj-$(CONFIG_NFC_ST_NCI)     += st-nci.o\n\nst-nci_i2c-objs = i2c.o\nobj-$(CONFIG_NFC_ST_NCI_I2C) += st-nci_i2c.o\n\nst-nci_spi-objs = spi.o\nobj-$(CONFIG_NFC_ST_NCI_SPI) += st-nci_spi.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}