{
  "module_name": "Makefile",
  "hash_id": "bc4d927feb554db5200b8965cac2cfe9afc41971b0efd890e4e4135384fea35f",
  "original_prompt": "Ingested from linux-6.6.14/fs/sysfs/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the sysfs virtual filesystem\n#\n\nobj-y\t\t:= file.o dir.o symlink.o mount.o group.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}