{
  "module_name": "Makefile",
  "hash_id": "356bbe0060dc75c8ed8df7971bf60b2fd73093420fa9d691d84e4ad79d139abf",
  "original_prompt": "Ingested from linux-6.6.14/net/dccp/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_IP_DCCP) += dccp.o dccp_ipv4.o\n\ndccp-y := ccid.o feat.o input.o minisocks.o options.o output.o proto.o timer.o \\\n\t  qpolicy.o\n#\n# CCID algorithms to be used by dccp.ko\n#\n# CCID-2 is default (RFC 4340, p. 77) and has Ack Vectors as dependency\ndccp-y += ccids/ccid2.o ackvec.o\ndccp-$(CONFIG_IP_DCCP_CCID3)\t+= ccids/ccid3.o\ndccp-$(CONFIG_IP_DCCP_TFRC_LIB) += ccids/lib/tfrc.o\t\t\\\n\t\t\t\t   ccids/lib/tfrc_equation.o\t\\\n\t\t\t\t   ccids/lib/packet_history.o\t\\\n\t\t\t\t   ccids/lib/loss_interval.o\n\ndccp_ipv4-y := ipv4.o\n\n# build dccp_ipv6 as module whenever either IPv6 or DCCP is a module\nobj-$(subst y,$(CONFIG_IP_DCCP),$(CONFIG_IPV6)) += dccp_ipv6.o\ndccp_ipv6-y := ipv6.o\n\nobj-$(CONFIG_INET_DCCP_DIAG) += dccp_diag.o\n\ndccp-$(CONFIG_SYSCTL) += sysctl.o\n\ndccp_diag-y := diag.o\n\n# build with local directory for trace.h\nCFLAGS_proto.o := -I$(src)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}