{
  "module_name": "Makefile",
  "hash_id": "573777ba31f61e4240fc439e00ced57ec839a41ba53104ef600d2ba4e2934567",
  "original_prompt": "Ingested from linux-6.6.14/drivers/pmdomain/qcom/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_QCOM_CPR)\t\t+= cpr.o\nobj-$(CONFIG_QCOM_RPMPD)\t+= rpmpd.o\nobj-$(CONFIG_QCOM_RPMHPD)\t+= rpmhpd.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}