{
  "module_name": "Makefile",
  "hash_id": "f6282abeae3b09be564b64ec9fdef13fc4a86ff0c347f87f4622f78d187d7a6c",
  "original_prompt": "Ingested from linux-6.6.14/drivers/isdn/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for the kernel ISDN subsystem and device drivers.\n\n# Object files in subdirectories\n\nobj-$(CONFIG_BT_CMTP)\t\t\t+= capi/\nobj-$(CONFIG_MISDN)\t\t\t+= mISDN/\nobj-$(CONFIG_ISDN)\t\t\t+= hardware/\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}