{
  "module_name": "Makefile",
  "hash_id": "25e998f25008c8270ae88c1a7c7df91182709cfa0866164bf2dcaa0a8373dfc2",
  "original_prompt": "Ingested from linux-6.6.14/net/ieee802154/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_IEEE802154) += ieee802154.o\nobj-$(CONFIG_IEEE802154_SOCKET) += ieee802154_socket.o\nobj-y += 6lowpan/\n\nieee802154-y := netlink.o nl-mac.o nl-phy.o nl_policy.o core.o \\\n                header_ops.o sysfs.o nl802154.o trace.o\nieee802154_socket-y := socket.o\n\nCFLAGS_trace.o := -I$(src)\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}