{
  "module_name": "Makefile",
  "hash_id": "28308e2074e9711b3adfd51f5752884144c100dad9b76ae43eb362e7326ab333",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/wireless/mediatek/mt76/mt76x0/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_MT76x0U) += mt76x0u.o\nobj-$(CONFIG_MT76x0E) += mt76x0e.o\nobj-$(CONFIG_MT76x0_COMMON) += mt76x0-common.o\n\nmt76x0-common-y := init.o main.o eeprom.o phy.o\n\nmt76x0u-y := usb.o usb_mcu.o\nmt76x0e-y := pci.o pci_mcu.o\n\n# ccflags-y := -DDEBUG\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}