{
  "module_name": "Makefile",
  "hash_id": "9cce87c3e55abb2fdbd80d9eb1059a13c4d29f5e0c35b9522b7341e5132d6be1",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/cpufreq/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nall:\n\nTEST_PROGS := main.sh\nTEST_FILES := cpu.sh cpufreq.sh governor.sh module.sh special-tests.sh\n\ninclude ../lib.mk\n\nclean:\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}