{
  "module_name": "Makefile",
  "hash_id": "cfeca56802f6fcfe22aff0647c756cde42dcd800eda4aa858c178f6cae8207a1",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/microsoft/mana/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause\n#\n# Makefile for the Microsoft Azure Network Adapter driver\n\nobj-$(CONFIG_MICROSOFT_MANA) += mana.o\nmana-objs := gdma_main.o shm_channel.o hw_channel.o mana_en.o mana_ethtool.o mana_bpf.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}