{
  "module_name": "Makefile",
  "hash_id": "5c6a98a07da325166aa8ad09bc20fb24c91248dd896f879a5f03e982de2d6417",
  "original_prompt": "Ingested from linux-6.6.14/drivers/scsi/ibmvscsi_tgt/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_SCSI_IBMVSCSIS)\t+= ibmvscsis.o\n\nibmvscsis-y := libsrp.o ibmvscsi_tgt.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}