 
 

#ifndef __IA_CSS_ERR_H
#define __IA_CSS_ERR_H

 

 
enum ia_css_fw_warning {
	IA_CSS_FW_WARNING_NONE,
	IA_CSS_FW_WARNING_ISYS_QUEUE_FULL,  
	IA_CSS_FW_WARNING_PSYS_QUEUE_FULL,  
	IA_CSS_FW_WARNING_CIRCBUF_ALL_LOCKED,  
	IA_CSS_FW_WARNING_EXP_ID_LOCKED,  
	IA_CSS_FW_WARNING_TAG_EXP_ID_FAILED,  
	IA_CSS_FW_WARNING_FRAME_PARAM_MISMATCH,  
};

#endif  
