{
  "module_name": "Makefile",
  "hash_id": "060ed195fb85805dabc3ac1a967ec3c6d3e54376644c75eae5e49bf24afc6fed",
  "original_prompt": "Ingested from linux-6.6.14/drivers/phy/cadence/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nobj-$(CONFIG_PHY_CADENCE_TORRENT)\t+= phy-cadence-torrent.o\nobj-$(CONFIG_PHY_CADENCE_DPHY)\t+= cdns-dphy.o\nobj-$(CONFIG_PHY_CADENCE_DPHY_RX)\t+= cdns-dphy-rx.o\nobj-$(CONFIG_PHY_CADENCE_SIERRA)\t+= phy-cadence-sierra.o\nobj-$(CONFIG_PHY_CADENCE_SALVO)\t+= phy-cadence-salvo.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}