{
  "module_name": "Makefile",
  "hash_id": "767809dcea1ac90ec256c3edb65c6591269af008d413ae362df1494f8465999e",
  "original_prompt": "Ingested from linux-6.6.14/sound/atmel/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nsnd-atmel-ac97c-objs\t\t:= ac97c.o\n\nobj-$(CONFIG_SND_ATMEL_AC97C)\t+= snd-atmel-ac97c.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}