{
  "module_name": "Makefile",
  "hash_id": "4a9c21c5feb70049981d7c83c60266337281c5bcc2202e068d6771e367ad9385",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/rlimits/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-or-later\n\nCFLAGS += -Wall -O2 -g\nTEST_GEN_PROGS := rlimits-per-userns\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}