{
  "module_name": "Makefile",
  "hash_id": "d50f0ae2a4bde4b122f183d337512784047bd9d2da6b51befcda63314273d647",
  "original_prompt": "Ingested from linux-6.6.14/drivers/media/i2c/ccs/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\nccs-objs\t\t\t+= ccs-core.o ccs-reg-access.o \\\n\t\t\t\t   ccs-quirk.o ccs-limits.o ccs-data.o\nobj-$(CONFIG_VIDEO_CCS)\t\t+= ccs.o\n\nccflags-y += -I $(srctree)/drivers/media/i2c\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}