{
  "module_name": "Makefile",
  "hash_id": "294f03a08892c92577a393064a75702f2291af05e0976d29e2137b98977dc6f0",
  "original_prompt": "Ingested from linux-6.6.14/drivers/crypto/bcm/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n# File: drivers/crypto/bcm/Makefile\n#\n# Makefile for crypto acceleration files for Broadcom SPU driver\n#\n# Uncomment to enable debug tracing in the SPU driver.\n# CFLAGS_util.o := -DDEBUG\n# CFLAGS_cipher.o := -DDEBUG\n# CFLAGS_spu.o := -DDEBUG\n# CFLAGS_spu2.o := -DDEBUG\n\nobj-$(CONFIG_CRYPTO_DEV_BCM_SPU) := bcm_crypto_spu.o\n\nbcm_crypto_spu-objs :=  util.o spu.o spu2.o cipher.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}