{
  "module_name": "Makefile",
  "hash_id": "4d22292c25ca40c4b040111e60f475f5e0d0585e062735de31d3a20d9147a6e1",
  "original_prompt": "Ingested from linux-6.6.14/drivers/clk/mvebu/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_MVEBU_CLK_COMMON)\t+= common.o\nobj-$(CONFIG_MVEBU_CLK_CPU) \t+= clk-cpu.o\nobj-$(CONFIG_MVEBU_CLK_COREDIV)\t+= clk-corediv.o\nobj-$(CONFIG_ARMADA_AP_CP_HELPER) += armada_ap_cp_helper.o\n\nobj-$(CONFIG_ARMADA_370_CLK)\t+= armada-370.o\nobj-$(CONFIG_ARMADA_375_CLK)\t+= armada-375.o\nobj-$(CONFIG_ARMADA_38X_CLK)\t+= armada-38x.o\nobj-$(CONFIG_ARMADA_39X_CLK)\t+= armada-39x.o\nobj-$(CONFIG_ARMADA_37XX_CLK)\t+= armada-37xx-xtal.o\nobj-$(CONFIG_ARMADA_37XX_CLK)\t+= armada-37xx-tbg.o\nobj-$(CONFIG_ARMADA_37XX_CLK)\t+= armada-37xx-periph.o\nobj-$(CONFIG_ARMADA_XP_CLK)\t+= armada-xp.o mv98dx3236.o\nobj-$(CONFIG_ARMADA_AP806_SYSCON) += ap806-system-controller.o\nobj-$(CONFIG_ARMADA_AP_CPU_CLK) += ap-cpu-clk.o\nobj-$(CONFIG_ARMADA_CP110_SYSCON) += cp110-system-controller.o\nobj-$(CONFIG_DOVE_CLK)\t\t+= dove.o dove-divider.o\nobj-$(CONFIG_KIRKWOOD_CLK)\t+= kirkwood.o\nobj-$(CONFIG_ORION_CLK)\t\t+= orion.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}