{
  "module_name": "Makefile",
  "hash_id": "802b6203fbd007c471d90473fde451b84f9d0d3c48a36f86b0433b9022d39e32",
  "original_prompt": "Ingested from linux-6.6.14/kernel/futex/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\nobj-y += core.o syscalls.o pi.o requeue.o waitwake.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}