{
  "module_name": "Makefile",
  "hash_id": "22a4c5fed58ea05cc30bcdb641fd1b43851eb049d615c806b0d946ae29c560f5",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/intel/igbvf/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Copyright(c) 2009 - 2018 Intel Corporation.\n#\n# Makefile for the Intel(R) 82576 VF ethernet driver\n#\n\nobj-$(CONFIG_IGBVF) += igbvf.o\n\nigbvf-objs := vf.o \\\n              mbx.o \\\n              ethtool.o \\\n              netdev.o\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}