{
  "module_name": "Makefile",
  "hash_id": "4cb2f7d418561464945ab14ccc9cc6aa2c7ca56023116f5f07bd18a233e02efa",
  "original_prompt": "Ingested from linux-6.6.14/sound/aoa/core/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nobj-$(CONFIG_SND_AOA) += snd-aoa.o\nsnd-aoa-objs := core.o \\\n\t\talsa.o \\\n\t\tgpio-pmf.o \\\n\t\tgpio-feature.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}