{
  "module_name": "Kbuild",
  "hash_id": "629702732fb0ba9ec27d70596033caf92d6db6a68d403cc3e5c6cb28358bf8ac",
  "original_prompt": "Ingested from linux-6.6.14/drivers/gpu/drm/nouveau/nvkm/engine/mpeg/Kbuild",
  "human_readable_source": "# SPDX-License-Identifier: MIT\nnvkm-y += nvkm/engine/mpeg/nv31.o\nnvkm-y += nvkm/engine/mpeg/nv40.o\nnvkm-y += nvkm/engine/mpeg/nv44.o\nnvkm-y += nvkm/engine/mpeg/nv50.o\nnvkm-y += nvkm/engine/mpeg/g84.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}