{
  "module_name": "Makefile",
  "hash_id": "1916b8394aeee17fdae10ea5850778826e4012d666f4f2cbc722851947d7d0bf",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/ftrace/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nall:\n\nTEST_PROGS_EXTENDED := ftracetest\nTEST_PROGS := ftracetest-ktap\nTEST_FILES := test.d settings\nEXTRA_CLEAN := $(OUTPUT)/logs/*\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}