{
  "module_name": "Makefile",
  "hash_id": "133c7447f19b8ab3d0cf80508fd2d684c43ae0862279eb1a33ab2aa0517f848d",
  "original_prompt": "Ingested from linux-6.6.14/drivers/net/ethernet/actions/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for the Actions Semi Owl SoCs built-in ethernet macs\n#\n\nobj-$(CONFIG_OWL_EMAC) += owl-emac.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}