{
  "module_name": "Makefile",
  "hash_id": "3d25abb54a94d76d26a15810d5020309da81560191d6a1eb246cbc116274462b",
  "original_prompt": "Ingested from linux-6.6.14/fs/hostfs/Makefile",
  "human_readable_source": "#\n# Copyright (C) 2000 Jeff Dike (jdike@karaya.com)\n# Licensed under the GPL\n#\n\nhostfs-objs := hostfs_kern.o\n\nhostfs-builtin-$(CONFIG_HOSTFS) += hostfs_user.o hostfs_user_exp.o\n\nobj-y := $(hostfs-builtin-y) $(hostfs-builtin-m)\nobj-$(CONFIG_HOSTFS) += hostfs.o\n\ninclude $(srctree)/arch/um/scripts/Makefile.rules\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}