{
  "module_name": "Makefile",
  "hash_id": "efe1ac7f36249ee530b2984924fcceb784e874690ab2f84bea903bc904c07f58",
  "original_prompt": "Ingested from linux-6.6.14/sound/soc/mediatek/mt8183/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n\n# platform driver\nsnd-soc-mt8183-afe-objs := \\\n\tmt8183-afe-pcm.o \\\n\tmt8183-afe-clk.o \\\n\tmt8183-dai-i2s.o \\\n\tmt8183-dai-tdm.o \\\n\tmt8183-dai-pcm.o \\\n\tmt8183-dai-hostless.o \\\n\tmt8183-dai-adda.o\n\nobj-$(CONFIG_SND_SOC_MT8183) += snd-soc-mt8183-afe.o\nobj-$(CONFIG_SND_SOC_MT8183_MT6358_TS3A227E_MAX98357A) += mt8183-mt6358-ts3a227-max98357.o\nobj-$(CONFIG_SND_SOC_MT8183_DA7219_MAX98357A) += mt8183-da7219-max98357.o\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}