{
  "module_name": "Makefile",
  "hash_id": "12fde44fbff1d9ea8db157471f5c2dd903cff8f9315fa4a9d0d2f1c82c26a63b",
  "original_prompt": "Ingested from linux-6.6.14/drivers/nfc/fdp/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0-only\n#\n# Makefile for FDP NCI based NFC driver\n#\n\nobj-$(CONFIG_NFC_FDP)     += fdp.o\nobj-$(CONFIG_NFC_FDP_I2C) += fdp_i2c.o\n\nfdp_i2c-objs  = i2c.o\n\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}