{
  "module_name": "Makefile",
  "hash_id": "7f075503192312689a48d22f30f8b6f44c7b08e2009cd4ca6385228d6f4b5d19",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/safesetid/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\n# Makefile for SafeSetID selftest.\nCFLAGS = -Wall -O2\nLDLIBS = -lcap\n\nTEST_PROGS := safesetid-test.sh\nTEST_GEN_FILES := safesetid-test\n\ninclude ../lib.mk\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}