{
  "module_name": "Makefile",
  "hash_id": "b6721f72550fe6f083aeea15f36fc8388e2ce7a4f27307bac18a0930cba29634",
  "original_prompt": "Ingested from linux-6.6.14/tools/testing/selftests/timers/Makefile",
  "human_readable_source": "# SPDX-License-Identifier: GPL-2.0\nCFLAGS += -O3 -Wl,-no-as-needed -Wall\nLDLIBS += -lrt -lpthread -lm\n\n# these are all \"safe\" tests that don't modify\n# system time or require escalated privileges\nTEST_GEN_PROGS = posix_timers nanosleep nsleep-lat set-timer-lat mqueue-lat \\\n\t     inconsistency-check raw_skew threadtest rtcpie\n\nDESTRUCTIVE_TESTS = alarmtimer-suspend valid-adjtimex adjtick change_skew \\\n\t\t      skew_consistency clocksource-switch freq-step leap-a-day \\\n\t\t      leapcrash set-tai set-2038 set-tz\n\nTEST_GEN_PROGS_EXTENDED = $(DESTRUCTIVE_TESTS)\n\nTEST_FILES := settings\n\ninclude ../lib.mk\n\n# these tests require escalated privileges\n# and may modify the system time or trigger\n# other behavior like suspend\nrun_destructive_tests: run_tests\n\t$(call RUN_TESTS, $(DESTRUCTIVE_TESTS))\n",
  "logic_map": {},
  "failure_modes": [],
  "crash_correlation_map": {}
}